-- ============================================================
-- CMS 2.0 — V12: cms-mail-intake Stage 5 (Oracle)
--
-- Maker-checker admin actions (replay / force-link) over the
-- Stage 2 INBOUND_EMAIL schema, plus the retention-job tracking
-- column. No seed-data section — pure transactional/audit storage,
-- same as V11.
-- ============================================================

-- 1. Retention-job bookkeeping — see InboundEmail#rawPurgedAt.
ALTER TABLE INBOUND_EMAIL ADD RAW_PURGED_AT TIMESTAMP;

-- ─────────────────────────────────────────────────────────────
-- 2. MAIL_INTAKE_ADMIN_ACTION — one row per replay/force-link request, maker-checker gated.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE MAIL_INTAKE_ADMIN_ACTION (
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EMAIL_ID            NUMBER NOT NULL,
    ACTION_TYPE         VARCHAR2(20) NOT NULL,
    STATUS              VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    TARGET_COMPLAINT_ID VARCHAR2(50),
    REQUESTED_BY        VARCHAR2(100) NOT NULL,
    REQUESTED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    REQUEST_REASON      VARCHAR2(2000) NOT NULL,
    DECIDED_BY          VARCHAR2(100),
    DECIDED_AT          TIMESTAMP,
    DECISION_NOTE       VARCHAR2(2000),
    CONSTRAINT FK_ADMIN_ACTION_EMAIL FOREIGN KEY (EMAIL_ID) REFERENCES INBOUND_EMAIL (ID)
);

CREATE INDEX IDX_ADMIN_ACTION_EMAIL_ID ON MAIL_INTAKE_ADMIN_ACTION (EMAIL_ID);
CREATE INDEX IDX_ADMIN_ACTION_STATUS   ON MAIL_INTAKE_ADMIN_ACTION (STATUS, REQUESTED_AT);
