-- V15: RBIO officer summary - editable form data + clause-10 assessment columns (Oracle)
--
-- Backs GET/PUT /api/complaints/rbio/{id}/summary. The summary groups everything the complainant
-- submitted into sections, but ~30 of its fields were never captured on COMPLAINTS: they either
-- only ever existed on EMAIL_DRAFTS (and were dropped when a CRPC draft was converted) or were
-- never collected at all. COMPLAINT_RBIO_FORM_DATA gives them a home the officer can edit.
--
-- The COMPLAINT_ELIGIBILITY_ANSWERS columns are the clause-10 maintainability questions the
-- officer answers. They are deliberately NOT folded onto the existing yes/no columns:
-- ALREADY_SETTLED means the RE settled the grievance (not a court), and STAFF_OF_RE is a
-- different question from "complaint against management".
--
-- Also fixes a latent bug: COMPLAINT_ID was non-UNIQUE here while the sibling tables from V14
-- (COMPLAINT_ADDITIONAL_DETAILS, COMPLAINT_REPRESENTATIVES) are UNIQUE, yet
-- ComplaintEligibilityAnswerRepository.findByComplaintId returns Optional<>. A second row for one
-- complaint makes every read of that complaint throw IncorrectResultSizeDataAccessException.
-- The DELETE below keeps the latest ANSWERED_AT per complaint; run it before the ALTER.
--
-- MySQL equivalent: database/V15__complaint_rbio_form_data_and_eligibility_extension.sql
-- Must be applied before booting the prod profile: it runs ddl-auto=validate, so a missing
-- table or column fails startup rather than misbehaving later.
-- Not idempotent: re-running fails with ORA-00955 (name already used) / ORA-01430.

-- Dedupe before the unique constraint can be added.
DELETE FROM COMPLAINT_ELIGIBILITY_ANSWERS
 WHERE ID NOT IN (
    SELECT MAX(ID) KEEP (DENSE_RANK LAST ORDER BY ANSWERED_AT)
      FROM COMPLAINT_ELIGIBILITY_ANSWERS
     GROUP BY COMPLAINT_ID
 );

ALTER TABLE COMPLAINT_ELIGIBILITY_ANSWERS
    ADD CONSTRAINT UK_CEA_COMPLAINT UNIQUE (COMPLAINT_ID);

ALTER TABLE COMPLAINT_ELIGIBILITY_ANSWERS ADD (
    ENTITY_REGULATED_BY_RBI             VARCHAR2(10),
    NOT_DIRECTLY_ADDRESSED_TO_OMBUDSMAN VARCHAR2(10),
    NOT_REGISTERED_WITH_ENTITY          VARCHAR2(10),
    FRIVOLOUS_VEXATIOUS_THREATENING     VARCHAR2(10),
    PENDING_BEFORE_COURT                VARCHAR2(10),
    SETTLED_BEFORE_COURT                VARCHAR2(10),
    COMPLAINANT_IS_ADVOCATE             VARCHAR2(10),
    COMPLAINT_AGAINST_MANAGEMENT        VARCHAR2(10),
    FILED_WITH_CEPC_OR_RBI              VARCHAR2(10),
    DISPUTE_BETWEEN_RES                 VARCHAR2(10),
    COMPLETE_INFORMATION_UNAVAILABLE    VARCHAR2(10),
    PROPOSED_COMPLAINT_TYPE             VARCHAR2(100),
    FIRST_FILED_WITH_RE_DATE            DATE
);

CREATE TABLE COMPLAINT_RBIO_FORM_DATA (
    ID                                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    COMPLAINT_ID                      NUMBER(19)     NOT NULL UNIQUE,
    DRAFT_ID                          VARCHAR2(50),
    RECEIPT_DATE                      DATE,
    MODE_OF_RECEIPT                   VARCHAR2(50),
    COMMENTS                          VARCHAR2(4000),
    COMPLAINT_CPGRAM                  VARCHAR2(10),
    CPGRAM_NUMBER                     VARCHAR2(100),
    MODULE_NAME                       VARCHAR2(100),
    ENTITY_COUNTRY                    VARCHAR2(100),
    BRANCH_CENTER_NAME                VARCHAR2(200),
    OTHER_ENTITY_NAME                 VARCHAR2(300),
    REGISTRATION_WITH_RBI_DATE        DATE,
    COMPLAINT_REGISTRATION_DATE_VALID VARCHAR2(10),
    DATE_OF_FILING_COMPLAINT          DATE,
    LEGAL_CASE_FILED                  VARCHAR2(10),
    LEGAL_FILING_DATE                 DATE,
    PRE_ENQUIRY_RECEIVED              VARCHAR2(10),
    HIGH_PRIORITY_COMPLAINT           VARCHAR2(10),
    LOAN_DISPOSAL_AMOUNT              NUMBER(15,2),
    VERNACULAR_LANGUAGE               VARCHAR2(100),
    COMPLAINT_REGARDING_PENSION       VARCHAR2(10),
    ATM_CREDIT_DEBIT_CARD             VARCHAR2(10),
    SCHEME_FLAG                       VARCHAR2(50),
    RBO_CGPC_OLD                      VARCHAR2(100),
    GROUNDS_FLAG                      VARCHAR2(100),
    FREE_MARKED_COMPLAINT             VARCHAR2(10),
    CREATED_AT                        TIMESTAMP(6)   NOT NULL,
    UPDATED_AT                        TIMESTAMP(6)
);

CREATE INDEX IDX_CRFD_DRAFT ON COMPLAINT_RBIO_FORM_DATA (DRAFT_ID);
