-- V17: CONCILIATION_MEETINGS (Oracle)
--
-- Backs GET/PUT /api/complaints/rbio/{id}/conciliation, the RBIO Conciliation tab. Until now the
-- only conciliation state a complaint carried was COMPLAINTS.CONCILIATION_DATE and
-- CONCILIATION_OUTCOME, set by the SCHEDULE_MEETING / CONCILIATION_SUCCESS workflow actions. That
-- left the tab's own fields - who accepted the meeting, whether it ran over VC, and the minutes -
-- with nowhere to go.
--
-- A history table rather than the one-row-per-complaint shape the sibling tabs use (V15
-- COMPLAINT_RBIO_FORM_DATA, V14 COMPLAINT_ADDITIONAL_DETAILS): RBIO-US-018 allows a meeting to be
-- rescheduled repeatedly and requires the earlier attempts to survive, so COMPLAINT_ID is
-- deliberately NOT unique. The highest ID per complaint is the live meeting.
--
-- MEETING_TIME is a VARCHAR2(5) 'HH:mm' because Oracle has no TIME type and the form only ever
-- collects hours and minutes; RbioConciliationService validates the format on write.
--
-- MySQL equivalent: database/V17__conciliation_meetings.sql
-- Must be applied before booting the prod profile: it runs ddl-auto=validate, so a missing table
-- fails startup rather than misbehaving later.
-- Not idempotent: re-running fails with ORA-00955 (name already used).

CREATE TABLE CONCILIATION_MEETINGS (
    ID                      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    COMPLAINT_ID            NUMBER(19)     NOT NULL,
    -- SCHEDULED and RESCHEDULED are live and editable in place; COMPLETED and CANCELLED freeze the
    -- row so the next save opens a new meeting.
    MEETING_STATUS          VARCHAR2(30),
    MEETING_DATE            DATE,
    MEETING_TIME            VARCHAR2(5),
    ACCEPTED_BY_COMPLAINANT VARCHAR2(10),
    ACCEPTED_BY_ENTITY      VARCHAR2(10),
    CONDUCTED_THROUGH_VC    VARCHAR2(10),
    -- Minutes of the meeting, kept apart from the officer's own remarks in COMMENTS.
    MEETING_COMMENTS        VARCHAR2(4000),
    COMMENTS                VARCHAR2(4000),
    CREATED_BY              VARCHAR2(200),
    UPDATED_BY              VARCHAR2(200),
    CREATED_AT              TIMESTAMP(6)   NOT NULL,
    UPDATED_AT              TIMESTAMP(6)
);

CREATE INDEX IDX_CM_COMPLAINT ON CONCILIATION_MEETINGS (COMPLAINT_ID);
CREATE INDEX IDX_CM_STATUS ON CONCILIATION_MEETINGS (MEETING_STATUS);
