-- ============================================================
-- RBI CMS 2.0 — Complete Oracle DDL
-- Database: Oracle 21c XE / Enterprise
-- Scheme: RB-IOS 2026 (effective July 1, 2026)
-- ============================================================

-- ============================================================
-- 1. SEQUENCES
-- ============================================================
CREATE SEQUENCE BANKS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COMPLAINT_CATEGORIES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COMPLAINTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COMPLAINT_TIMELINE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COMPLAINT_ATTACHMENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE REGULATED_ENTITIES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HOLIDAYS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PINCODE_MASTER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MRE_RULE_CATEGORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MRE_RULE_DEFINITION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MRE_RULE_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MRE_DEPLOYMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE FORM_CONFIG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SUPPORTED_LOCALES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TRANSLATIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TRANSLATION_KEYS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE EXTRACTION_RULES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE REPORT_DEFINITIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE RE_RESPONSE_TRACKER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SIMULATED_EMAILS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE EMAIL_DRAFTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CITIZEN_EMAIL_VERIFICATIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE OTP_ATTEMPTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CAPTCHA_SESSIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- 2. CORE TABLES
-- ============================================================

-- BANKS
CREATE TABLE BANKS (
    ID              NUMBER(19) DEFAULT BANKS_SEQ.NEXTVAL PRIMARY KEY,
    NAME            VARCHAR2(300) NOT NULL,
    CODE            VARCHAR2(50),
    TYPE            VARCHAR2(100),
    STATUS          VARCHAR2(20) DEFAULT 'active',
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_BANK_TYPE ON BANKS(TYPE);
CREATE INDEX IDX_BANK_STATUS ON BANKS(STATUS);

-- COMPLAINT_CATEGORIES
CREATE TABLE COMPLAINT_CATEGORIES (
    ID              NUMBER(19) DEFAULT COMPLAINT_CATEGORIES_SEQ.NEXTVAL PRIMARY KEY,
    NAME            VARCHAR2(200) NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    PARENT_ID       NUMBER(19),
    STATUS          VARCHAR2(20) DEFAULT 'active',
    SORT_ORDER      NUMBER(5) DEFAULT 0,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_CATEGORY_PARENT ON COMPLAINT_CATEGORIES(PARENT_ID);
CREATE INDEX IDX_CATEGORY_STATUS ON COMPLAINT_CATEGORIES(STATUS);

-- REGULATED_ENTITIES
CREATE TABLE REGULATED_ENTITIES (
    ID              NUMBER(19) DEFAULT REGULATED_ENTITIES_SEQ.NEXTVAL PRIMARY KEY,
    NAME            VARCHAR2(500) NOT NULL,
    NAME_NORMALIZED VARCHAR2(500),
    DEPARTMENT      VARCHAR2(10) NOT NULL,
    ENTITY_TYPE     VARCHAR2(100),
    CITY            VARCHAR2(100),
    STATE           VARCHAR2(50),
    STATUS          VARCHAR2(20) DEFAULT 'active',
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_RE_DEPARTMENT ON REGULATED_ENTITIES(DEPARTMENT);
CREATE INDEX IDX_RE_NAME ON REGULATED_ENTITIES(NAME);
CREATE INDEX IDX_RE_ENTITY_TYPE ON REGULATED_ENTITIES(ENTITY_TYPE);
CREATE INDEX IDX_RE_NAME_NORM ON REGULATED_ENTITIES(NAME_NORMALIZED);

-- COMPLAINTS
CREATE TABLE COMPLAINTS (
    ID                          NUMBER(19) DEFAULT COMPLAINTS_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_NUMBER            VARCHAR2(50) NOT NULL UNIQUE,
    COMPLAINANT_NAME            VARCHAR2(200) NOT NULL,
    COMPLAINANT_EMAIL           VARCHAR2(200),
    COMPLAINANT_PHONE           VARCHAR2(20),
    COMPLAINANT_ADDRESS         VARCHAR2(500),
    BANK_ID                     NUMBER(19),
    BANK_BRANCH                 VARCHAR2(300),
    ACCOUNT_NUMBER              VARCHAR2(100),
    CATEGORY_ID                 NUMBER(19),
    SUBJECT                     VARCHAR2(500) NOT NULL,
    DESCRIPTION                 CLOB,
    RELIEF_SOUGHT               CLOB,
    STATUS                      VARCHAR2(30) DEFAULT 'pending' NOT NULL,
    PRIORITY                    VARCHAR2(20) DEFAULT 'MEDIUM',
    FILING_TYPE                 VARCHAR2(50),
    BANK_COMPLAINT_REFERENCE    VARCHAR2(200),
    BANK_COMPLAINT_DATE         TIMESTAMP,
    ASSIGNED_OFFICER            VARCHAR2(200),
    DEPARTMENT                  VARCHAR2(20),
    ASSIGNED_ROLE               VARCHAR2(50),
    ENTITY_CODE                 VARCHAR2(50),
    WORKFLOW_STAGE              VARCHAR2(50),
    -- RB-IOS 2026 Maintainability fields
    PRIOR_RE_COMPLAINT          NUMBER(1),
    RE_COMPLAINT_DATE           DATE,
    RE_COMPLAINT_REFERENCE      VARCHAR2(200),
    RE_REPLIED_AND_DISSATISFIED NUMBER(1),
    RE_LAST_COMMUNICATION_DATE  DATE,
    SAME_GRIEVANCE_PENDING      NUMBER(1) DEFAULT 0,
    -- Triage / MRE
    TRIAGE_SIGNAL               VARCHAR2(10),
    TRIAGE_FLAGS                CLOB,
    ELIGIBILITY_TIMELINE        CLOB,
    MAINTAINABILITY_DETERMINATION VARCHAR2(30),
    MAINTAINABILITY_DETERMINED_BY VARCHAR2(200),
    MAINTAINABILITY_DETERMINED_AT TIMESTAMP,
    AWARD_AMOUNT                NUMBER(15,2),
    -- Timestamps
    FILED_AT                    TIMESTAMP,
    RESOLVED_AT                 TIMESTAMP,
    CLOSED_AT                   TIMESTAMP,
    ESCALATED_AT                TIMESTAMP,
    CREATED_AT                  TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT                  TIMESTAMP DEFAULT SYSTIMESTAMP,
    -- FK
    CONSTRAINT FK_COMPLAINT_BANK FOREIGN KEY (BANK_ID) REFERENCES BANKS(ID),
    CONSTRAINT FK_COMPLAINT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES COMPLAINT_CATEGORIES(ID)
);
CREATE INDEX IDX_COMPLAINT_NUMBER ON COMPLAINTS(COMPLAINT_NUMBER);
CREATE INDEX IDX_COMPLAINT_STATUS ON COMPLAINTS(STATUS);
CREATE INDEX IDX_COMPLAINT_PRIORITY ON COMPLAINTS(PRIORITY);
CREATE INDEX IDX_COMPLAINT_EMAIL ON COMPLAINTS(COMPLAINANT_EMAIL);
CREATE INDEX IDX_COMPLAINT_CATEGORY ON COMPLAINTS(CATEGORY_ID);
CREATE INDEX IDX_COMPLAINT_BANK ON COMPLAINTS(BANK_ID);
CREATE INDEX IDX_COMPLAINT_CREATED ON COMPLAINTS(CREATED_AT);
CREATE INDEX IDX_COMPLAINT_STATUS_CREATED ON COMPLAINTS(STATUS, CREATED_AT);
CREATE INDEX IDX_COMPLAINT_RE_DATE ON COMPLAINTS(RE_COMPLAINT_DATE);
CREATE INDEX IDX_COMPLAINT_TRIAGE ON COMPLAINTS(TRIAGE_SIGNAL);
CREATE INDEX IDX_COMPLAINT_MAINTAINABILITY ON COMPLAINTS(MAINTAINABILITY_DETERMINATION);
CREATE INDEX IDX_COMPLAINT_OFFICER ON COMPLAINTS(ASSIGNED_OFFICER);
CREATE INDEX IDX_COMPLAINT_DEPT ON COMPLAINTS(DEPARTMENT);

-- COMPLAINT_TIMELINE
CREATE TABLE COMPLAINT_TIMELINE (
    ID              NUMBER(19) DEFAULT COMPLAINT_TIMELINE_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_ID    NUMBER(19) NOT NULL,
    ACTION          VARCHAR2(50) NOT NULL,
    PERFORMED_BY    VARCHAR2(200),
    REMARKS         CLOB,
    FROM_STATUS     VARCHAR2(30),
    TO_STATUS       VARCHAR2(30),
    PERFORMED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_TIMELINE_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(ID)
);
CREATE INDEX IDX_TIMELINE_COMPLAINT ON COMPLAINT_TIMELINE(COMPLAINT_ID);
CREATE INDEX IDX_TIMELINE_PERFORMED ON COMPLAINT_TIMELINE(PERFORMED_AT);

-- COMPLAINT_ATTACHMENTS
CREATE TABLE COMPLAINT_ATTACHMENTS (
    ID              NUMBER(19) DEFAULT COMPLAINT_ATTACHMENTS_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_ID    NUMBER(19) NOT NULL,
    FILE_NAME       VARCHAR2(255) NOT NULL,
    CONTENT_TYPE    VARCHAR2(100),
    FILE_SIZE       NUMBER(19),
    STORAGE_PATH    VARCHAR2(500) NOT NULL,
    UPLOADED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ATTACH_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(ID)
);
CREATE INDEX IDX_ATTACH_COMPLAINT ON COMPLAINT_ATTACHMENTS(COMPLAINT_ID);

-- HOLIDAYS (for business day calculations)
CREATE TABLE HOLIDAYS (
    ID              NUMBER(19) DEFAULT HOLIDAYS_SEQ.NEXTVAL PRIMARY KEY,
    HOLIDAY_DATE    DATE NOT NULL UNIQUE,
    NAME            VARCHAR2(200) NOT NULL,
    TYPE            VARCHAR2(50),
    YEAR            NUMBER(4) NOT NULL,
    IS_NATIONAL     NUMBER(1) DEFAULT 1
);
CREATE INDEX IDX_HOLIDAY_DATE ON HOLIDAYS(HOLIDAY_DATE);
CREATE INDEX IDX_HOLIDAY_YEAR ON HOLIDAYS(YEAR);

-- ============================================================
-- 3. INDIA POST PINCODE MASTER (Local DB lookup)
-- ============================================================
CREATE TABLE PINCODE_MASTER (
    ID              NUMBER(19) DEFAULT PINCODE_MASTER_SEQ.NEXTVAL PRIMARY KEY,
    PINCODE         VARCHAR2(6) NOT NULL,
    OFFICE_NAME     VARCHAR2(200),
    OFFICE_TYPE     VARCHAR2(20),
    DELIVERY_STATUS VARCHAR2(20),
    DIVISION_NAME   VARCHAR2(100),
    REGION_NAME     VARCHAR2(100),
    CIRCLE_NAME     VARCHAR2(100),
    TALUK           VARCHAR2(100),
    DISTRICT        VARCHAR2(100) NOT NULL,
    STATE           VARCHAR2(100) NOT NULL,
    COUNTRY         VARCHAR2(50) DEFAULT 'India'
);
CREATE INDEX IDX_PINCODE ON PINCODE_MASTER(PINCODE);
CREATE INDEX IDX_PINCODE_DISTRICT ON PINCODE_MASTER(DISTRICT);
CREATE INDEX IDX_PINCODE_STATE ON PINCODE_MASTER(STATE);
CREATE UNIQUE INDEX IDX_PINCODE_OFFICE ON PINCODE_MASTER(PINCODE, OFFICE_NAME);

-- ============================================================
-- 4. MRE RULES ENGINE TABLES
-- ============================================================

CREATE TABLE MRE_RULE_CATEGORY (
    ID              NUMBER(19) DEFAULT MRE_RULE_CATEGORY_SEQ.NEXTVAL PRIMARY KEY,
    CATEGORY_CODE   VARCHAR2(50) NOT NULL UNIQUE,
    CATEGORY_NAME   VARCHAR2(200) NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    IS_ACTIVE       NUMBER(1) DEFAULT 1 NOT NULL,
    DISPLAY_ORDER   NUMBER(5) DEFAULT 0,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_RULE_CAT_ACTIVE ON MRE_RULE_CATEGORY(IS_ACTIVE, DISPLAY_ORDER);

CREATE TABLE MRE_RULE_DEFINITION (
    ID              NUMBER(19) DEFAULT MRE_RULE_DEFINITION_SEQ.NEXTVAL PRIMARY KEY,
    RULE_CODE       VARCHAR2(50) NOT NULL UNIQUE,
    RULE_NAME       VARCHAR2(300) NOT NULL,
    CATEGORY_ID     NUMBER(19) NOT NULL,
    DRL_CONTENT     CLOB NOT NULL,
    SALIENCE        NUMBER(5) DEFAULT 10,
    VERSION         NUMBER(10) DEFAULT 1 NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    EFFECTIVE_FROM  TIMESTAMP,
    EFFECTIVE_TO    TIMESTAMP,
    CREATED_BY      VARCHAR2(100) NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_BY      VARCHAR2(100),
    UPDATED_AT      TIMESTAMP,
    APPROVED_BY     VARCHAR2(100),
    APPROVED_AT     TIMESTAMP,
    CONSTRAINT FK_RULEDEF_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES MRE_RULE_CATEGORY(ID),
    CONSTRAINT CHK_RULE_STATUS CHECK (STATUS IN ('DRAFT','PENDING_REVIEW','ACTIVE','INACTIVE','ARCHIVED'))
);
CREATE INDEX IDX_RULE_DEF_STATUS ON MRE_RULE_DEFINITION(STATUS);
CREATE INDEX IDX_RULE_DEF_CATEGORY ON MRE_RULE_DEFINITION(CATEGORY_ID, STATUS);

CREATE TABLE MRE_RULE_HISTORY (
    ID              NUMBER(19) DEFAULT MRE_RULE_HISTORY_SEQ.NEXTVAL PRIMARY KEY,
    RULE_ID         NUMBER(19) NOT NULL,
    VERSION         NUMBER(10) NOT NULL,
    DRL_CONTENT     CLOB NOT NULL,
    CHANGE_REASON   VARCHAR2(1000),
    ACTION          VARCHAR2(50) NOT NULL,
    CHANGED_BY      VARCHAR2(100) NOT NULL,
    CHANGED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_HISTORY_RULE FOREIGN KEY (RULE_ID) REFERENCES MRE_RULE_DEFINITION(ID)
);
CREATE INDEX IDX_RULE_HIST_RULE ON MRE_RULE_HISTORY(RULE_ID, VERSION);

CREATE TABLE MRE_DEPLOYMENT (
    ID              NUMBER(19) DEFAULT MRE_DEPLOYMENT_SEQ.NEXTVAL PRIMARY KEY,
    DEPLOYMENT_ID   VARCHAR2(50) NOT NULL UNIQUE,
    RULES_DEPLOYED  NUMBER(10) NOT NULL,
    STATUS          VARCHAR2(20) NOT NULL,
    DEPLOYED_BY     VARCHAR2(100) NOT NULL,
    DEPLOYED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    ERROR_MESSAGE   VARCHAR2(2000),
    CONSTRAINT CHK_DEPLOY_STATUS CHECK (STATUS IN ('SUCCESS','FAILED','ROLLED_BACK'))
);

CREATE TABLE MRE_GROUND_CONFIG (
    ID              NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GROUND_CODE     VARCHAR2(50) NOT NULL UNIQUE,
    CLAUSE_REF      VARCHAR2(20) NOT NULL,
    DESCRIPTION     VARCHAR2(500) NOT NULL,
    IS_ACTIVE       NUMBER(1) DEFAULT 1 NOT NULL,
    EVALUATION_ORDER NUMBER(5) DEFAULT 0,
    FAIL_MESSAGE    VARCHAR2(1000),
    PASS_MESSAGE    VARCHAR2(1000),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_GROUND_ACTIVE ON MRE_GROUND_CONFIG(IS_ACTIVE, EVALUATION_ORDER);

CREATE TABLE MRE_WINDOW_CONFIG (
    ID              NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATEGORY_CODE   VARCHAR2(50) NOT NULL,
    ENTITY_TYPE     VARCHAR2(50) DEFAULT 'ALL',
    WINDOW_DAYS     NUMBER(5) NOT NULL,
    FILING_DEADLINE NUMBER(5) DEFAULT 90 NOT NULL,
    WINDOW_BASIS    VARCHAR2(20) DEFAULT 'CALENDAR' NOT NULL,
    IS_ACTIVE       NUMBER(1) DEFAULT 1 NOT NULL,
    EFFECTIVE_FROM  DATE NOT NULL,
    EFFECTIVE_TO    DATE,
    CREATED_BY      VARCHAR2(100),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_WIN_BASIS CHECK (WINDOW_BASIS IN ('CALENDAR','BUSINESS'))
);
CREATE UNIQUE INDEX IDX_WINDOW_UNIQUE ON MRE_WINDOW_CONFIG(CATEGORY_CODE, ENTITY_TYPE, EFFECTIVE_FROM);

-- ============================================================
-- 5. SUPPORTING TABLES
-- ============================================================

CREATE TABLE FORM_CONFIG (
    ID              NUMBER(19) DEFAULT FORM_CONFIG_SEQ.NEXTVAL PRIMARY KEY,
    FORM_KEY        VARCHAR2(100) NOT NULL UNIQUE,
    FORM_JSON       CLOB NOT NULL,
    VERSION         NUMBER(5) DEFAULT 1,
    IS_ACTIVE       NUMBER(1) DEFAULT 1,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SUPPORTED_LOCALES (
    ID              NUMBER(19) DEFAULT SUPPORTED_LOCALES_SEQ.NEXTVAL PRIMARY KEY,
    LOCALE_CODE     VARCHAR2(10) NOT NULL UNIQUE,
    DISPLAY_NAME    VARCHAR2(100) NOT NULL,
    IS_DEFAULT      NUMBER(1) DEFAULT 0,
    IS_ACTIVE       NUMBER(1) DEFAULT 1
);

CREATE TABLE TRANSLATION_KEYS (
    ID              NUMBER(19) DEFAULT TRANSLATION_KEYS_SEQ.NEXTVAL PRIMARY KEY,
    KEY_CODE        VARCHAR2(200) NOT NULL UNIQUE,
    CONTEXT         VARCHAR2(100),
    DESCRIPTION     VARCHAR2(500)
);

CREATE TABLE TRANSLATIONS (
    ID              NUMBER(19) DEFAULT TRANSLATIONS_SEQ.NEXTVAL PRIMARY KEY,
    KEY_ID          NUMBER(19) NOT NULL,
    LOCALE_ID       NUMBER(19) NOT NULL,
    VALUE           CLOB NOT NULL,
    CONSTRAINT FK_TRANS_KEY FOREIGN KEY (KEY_ID) REFERENCES TRANSLATION_KEYS(ID),
    CONSTRAINT FK_TRANS_LOCALE FOREIGN KEY (LOCALE_ID) REFERENCES SUPPORTED_LOCALES(ID),
    CONSTRAINT UQ_TRANS_KEY_LOCALE UNIQUE (KEY_ID, LOCALE_ID)
);

CREATE TABLE EXTRACTION_RULES (
    ID              NUMBER(19) DEFAULT EXTRACTION_RULES_SEQ.NEXTVAL PRIMARY KEY,
    NAME            VARCHAR2(200) NOT NULL,
    FIELD_NAME      VARCHAR2(100) NOT NULL,
    PATTERN         VARCHAR2(1000) NOT NULL,
    PRIORITY        NUMBER(5) DEFAULT 0,
    IS_ACTIVE       NUMBER(1) DEFAULT 1,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE RE_RESPONSE_TRACKER (
    ID                  NUMBER(19) DEFAULT RE_RESPONSE_TRACKER_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_ID        NUMBER(19) NOT NULL,
    REGULATED_ENTITY_ID NUMBER(19) NOT NULL,
    FORWARDED_AT        TIMESTAMP NOT NULL,
    RESPONDED_AT        TIMESTAMP,
    WINDOW_DAYS         NUMBER(5) DEFAULT 15 NOT NULL,
    WINDOW_EXPIRES_AT   TIMESTAMP,
    BREACHED            NUMBER(1) DEFAULT 0 NOT NULL,
    EX_PARTE_ELIGIBLE   NUMBER(1) DEFAULT 0 NOT NULL,
    NOTES               VARCHAR2(500),
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_RRT_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(ID)
);
CREATE INDEX IDX_RRT_COMPLAINT ON RE_RESPONSE_TRACKER(COMPLAINT_ID);
CREATE INDEX IDX_RRT_BREACHED ON RE_RESPONSE_TRACKER(BREACHED);

CREATE TABLE SIMULATED_EMAILS (
    ID              NUMBER(19) DEFAULT SIMULATED_EMAILS_SEQ.NEXTVAL PRIMARY KEY,
    FROM_ADDRESS    VARCHAR2(200) NOT NULL,
    SUBJECT         VARCHAR2(500) NOT NULL,
    BODY            CLOB,
    STATUS          VARCHAR2(20) DEFAULT 'RECEIVED',
    RECEIVED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE EMAIL_DRAFTS (
    ID              NUMBER(19) DEFAULT EMAIL_DRAFTS_SEQ.NEXTVAL PRIMARY KEY,
    EMAIL_ID        NUMBER(19),
    EXTRACTED_DATA  CLOB,
    STATUS          VARCHAR2(30) DEFAULT 'PENDING',
    REVIEWED_BY     VARCHAR2(100),
    REVIEWED_AT     TIMESTAMP,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE CITIZEN_EMAIL_VERIFICATIONS (
    ID              NUMBER(19) DEFAULT CITIZEN_EMAIL_VERIFICATIONS_SEQ.NEXTVAL PRIMARY KEY,
    EMAIL           VARCHAR2(200) NOT NULL,
    OTP_CODE        VARCHAR2(10) NOT NULL,
    VERIFIED        NUMBER(1) DEFAULT 0,
    EXPIRES_AT      TIMESTAMP NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE OTP_ATTEMPTS (
    ID              NUMBER(19) DEFAULT OTP_ATTEMPTS_SEQ.NEXTVAL PRIMARY KEY,
    IDENTIFIER      VARCHAR2(200) NOT NULL,
    ATTEMPT_COUNT   NUMBER(5) DEFAULT 0,
    LOCKED_UNTIL    TIMESTAMP,
    LAST_ATTEMPT_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE CAPTCHA_SESSIONS (
    ID              NUMBER(19) DEFAULT CAPTCHA_SESSIONS_SEQ.NEXTVAL PRIMARY KEY,
    SESSION_ID      VARCHAR2(100) NOT NULL UNIQUE,
    ANSWER          VARCHAR2(20) NOT NULL,
    EXPIRES_AT      TIMESTAMP NOT NULL,
    USED            NUMBER(1) DEFAULT 0
);

-- SHEDLOCK (distributed scheduler)
CREATE TABLE SHEDLOCK (
    NAME       VARCHAR2(64) NOT NULL PRIMARY KEY,
    LOCK_UNTIL TIMESTAMP NOT NULL,
    LOCKED_AT  TIMESTAMP NOT NULL,
    LOCKED_BY  VARCHAR2(255) NOT NULL
);

COMMIT;
