-- V22: STORAGE_BLOBS (Oracle)
--
-- Attachment payloads used to live on the app server's filesystem, with
-- COMPLAINT_ATTACHMENTS.STORAGE_PATH holding a relative path like "CMS-001/<uuid>_name.pdf". That
-- makes the upload directory a piece of unreplicated state: a second cms-backend instance cannot
-- serve a file the first one received, and nothing backs it up with the database.
--
-- STORAGE_BLOBS moves the bytes into the schema, owned by cms-storage-service. STORAGE_PATH now
-- holds the OBJECT_ID (a UUID) instead of a path — same column, same VARCHAR2 type, so no
-- COMPLAINT_ATTACHMENTS change is needed.
--
-- TENANT_ID is deliberately nullable: the current deployment is single-tenant and populates nothing
-- here. It exists so a future multi-tenant split has a discriminator to filter on without a
-- migration on a table full of BLOBs.
--
-- MySQL equivalent: database/V22__storage_blobs.sql
-- Must be applied before booting the prod profile: it runs ddl-auto=validate, so a missing table
-- fails startup rather than misbehaving later.
-- Not idempotent: re-running fails with ORA-00955 (name already used by an existing object).

CREATE TABLE STORAGE_BLOBS (
    ID            NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    TENANT_ID     VARCHAR2(64),
    OBJECT_ID     VARCHAR2(200)  NOT NULL,
    BUCKET        VARCHAR2(200),
    FILE_NAME     VARCHAR2(500)  NOT NULL,
    CONTENT_TYPE  VARCHAR2(150),
    SIZE_BYTES    NUMBER(19)     NOT NULL,
    CHECKSUM      VARCHAR2(64),
    STORAGE_DATA  BLOB           NOT NULL,
    CREATED_AT    TIMESTAMP(6)   NOT NULL,
    CONSTRAINT PK_STORAGE_BLOBS PRIMARY KEY (ID)
);

-- Every read path (fetch, metadata, delete) looks the row up by OBJECT_ID, and the handle in
-- COMPLAINT_ATTACHMENTS.STORAGE_PATH must resolve to exactly one blob.
CREATE UNIQUE INDEX IDX_STORAGE_BLOB_OBJECT ON STORAGE_BLOBS (OBJECT_ID);

-- Supports listing a complaint's blobs from the storage service directly, bypassing cms-backend.
CREATE INDEX IDX_STORAGE_BLOB_BUCKET ON STORAGE_BLOBS (BUCKET);

-- No backfill of existing filesystem attachments. Rows whose STORAGE_PATH still holds a
-- "CMS-001/<uuid>_name.pdf" path have no matching blob and will fail to download until the files
-- are re-uploaded or migrated by a separate one-off job.
