-- ============================================================
-- RBI CMS 2.0 — Complete Oracle Seed Data
-- Database: Oracle 21c XE / Enterprise
-- Scheme: RB-IOS 2026 (effective July 1, 2026)
-- ============================================================

-- ============================================================
-- 1. BANKS (Major Indian Banks)
-- ============================================================

INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'State Bank of India', 'SBI', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Punjab National Bank', 'PNB', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Bank of Baroda', 'BOB', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Canara Bank', 'CANARA', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Union Bank of India', 'UBI', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Bank of India', 'BOI', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Indian Bank', 'IB', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Central Bank of India', 'CBI', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Indian Overseas Bank', 'IOB', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'UCO Bank', 'UCO', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Punjab & Sind Bank', 'PSB', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'HDFC Bank', 'HDFC', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'ICICI Bank', 'ICICI', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Axis Bank', 'AXIS', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Kotak Mahindra Bank', 'KOTAK', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'IndusInd Bank', 'INDUSIND', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Yes Bank', 'YES', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'IDBI Bank', 'IDBI', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Federal Bank', 'FEDERAL', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'South Indian Bank', 'SIB', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'RBL Bank', 'RBL', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Bandhan Bank', 'BANDHAN', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'IDFC First Bank', 'IDFC', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Citibank N.A.', 'CITI', 'FOREIGN', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'HSBC', 'HSBC', 'FOREIGN', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Standard Chartered Bank', 'SCB', 'FOREIGN', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Deutsche Bank', 'DB', 'FOREIGN', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Barclays Bank', 'BARCLAYS', 'FOREIGN', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'National Payments Corporation of India', 'NPCI', 'PAYMENT_SYSTEM', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Visa Inc.', 'VISA', 'CARD_NETWORK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Mastercard Inc.', 'MASTERCARD', 'CARD_NETWORK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'RuPay (NPCI)', 'RUPAY', 'CARD_NETWORK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Bajaj Finance Ltd', 'BAJAJ_FIN', 'NBFC', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Muthoot Finance', 'MUTHOOT', 'NBFC', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Manappuram Finance', 'MANAPPURAM', 'NBFC', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Paytm Payments Bank', 'PAYTM', 'PAYMENT_BANK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Airtel Payments Bank', 'AIRTEL', 'PAYMENT_BANK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'India Post Payments Bank', 'IPPB', 'PAYMENT_BANK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Jio Payments Bank', 'JIO', 'PAYMENT_BANK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Fino Payments Bank', 'FINO', 'PAYMENT_BANK', 'active');

-- ============================================================
-- 2. COMPLAINT_CATEGORIES (RB-IOS 2026 Grounds of Complaint)
-- ============================================================

INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'ATM/Debit Card', 'Issues related to ATM transactions and debit card usage', NULL, 'active', 1);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Credit Card', 'Issues related to credit card charges, billing, and services', NULL, 'active', 2);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'UPI/Mobile Banking', 'Issues related to UPI, BHIM, PhonePe, Google Pay transactions', NULL, 'active', 3);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'IMPS/NEFT/RTGS', 'Issues related to electronic fund transfers', NULL, 'active', 4);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Loan/Advance', 'Issues related to loans, EMIs, interest rates, prepayment penalties', NULL, 'active', 5);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Deposit Account', 'Issues related to savings, current, and fixed deposit accounts', NULL, 'active', 6);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Insurance', 'Issues related to mis-selling, claim rejection, policy lapses', NULL, 'active', 7);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Internet Banking', 'Issues related to net banking access, security, and transactions', NULL, 'active', 8);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'NACH/ECS/Mandate', 'Issues related to auto-debit mandates and recurring payments', NULL, 'active', 9);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Pension', 'Issues related to pension disbursement and delays', NULL, 'active', 10);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Remittance', 'Issues related to money transfer and foreign exchange', NULL, 'active', 11);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Staff Behaviour', 'Issues related to rude behaviour, non-cooperation by bank staff', NULL, 'active', 12);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'KYC/Account Opening', 'Issues related to KYC compliance, account opening/closure', NULL, 'active', 13);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Fraud/Unauthorized Transaction', 'Fraud, phishing, unauthorized debit, identity theft', NULL, 'active', 14);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Other', 'Issues not covered under above categories', NULL, 'active', 99);

-- Sub-categories for ATM/Debit Card
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Cash not dispensed', 'ATM debited but cash not dispensed', 1, 'active', 1);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Card swallowed by ATM', 'ATM retained debit card', 1, 'active', 2);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Excess debit', 'Amount debited exceeds withdrawal amount', 1, 'active', 3);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'POS transaction failure', 'POS swipe deducted but merchant shows failure', 1, 'active', 4);

-- Sub-categories for UPI
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'UPI transaction failed - amount debited', 'Money debited but not credited to beneficiary via UPI', 3, 'active', 1);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'UPI fraud', 'Unauthorized UPI collect/debit', 3, 'active', 2);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'UPI mandate issue', 'Auto-pay UPI mandate unauthorized debit', 3, 'active', 3);

-- ============================================================
-- 3. REGULATED ENTITIES (Sample across entity types)
-- ============================================================

INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'State Bank of India', 'STATE BANK OF INDIA', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Punjab National Bank', 'PUNJAB NATIONAL BANK', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'New Delhi', 'Delhi', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Bank of Baroda', 'BANK OF BARODA', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'Vadodara', 'Gujarat', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Canara Bank', 'CANARA BANK', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'Bengaluru', 'Karnataka', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Union Bank of India', 'UNION BANK OF INDIA', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'HDFC Bank', 'HDFC BANK', 'CEPC', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'ICICI Bank', 'ICICI BANK', 'CEPC', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Axis Bank', 'AXIS BANK', 'CEPC', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Kotak Mahindra Bank', 'KOTAK MAHINDRA BANK', 'CEPC', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'IndusInd Bank', 'INDUSIND BANK', 'CEPC', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Yes Bank', 'YES BANK', 'CEPC', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'IDBI Bank', 'IDBI BANK', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Federal Bank', 'FEDERAL BANK', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'Aluva', 'Kerala', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Citibank N.A.', 'CITIBANK NA', 'CEPC', 'FOREIGN_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'HSBC', 'HSBC', 'CEPC', 'FOREIGN_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Standard Chartered Bank', 'STANDARD CHARTERED BANK', 'CEPC', 'FOREIGN_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Bajaj Finance Ltd', 'BAJAJ FINANCE LTD', 'RBIO', 'NBFC', 'Pune', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Muthoot Finance', 'MUTHOOT FINANCE', 'RBIO', 'NBFC', 'Kochi', 'Kerala', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Paytm Payments Bank', 'PAYTM PAYMENTS BANK', 'CEPC', 'PAYMENT_BANK', 'Noida', 'Uttar Pradesh', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Airtel Payments Bank', 'AIRTEL PAYMENTS BANK', 'CEPC', 'PAYMENT_BANK', 'New Delhi', 'Delhi', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'India Post Payments Bank', 'INDIA POST PAYMENTS BANK', 'CEPC', 'PAYMENT_BANK', 'New Delhi', 'Delhi', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'National Payments Corporation of India', 'NATIONAL PAYMENTS CORPORATION OF INDIA', 'CEPC', 'PAYMENT_SYSTEM_OPERATOR', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'PhonePe Private Limited', 'PHONEPE PRIVATE LIMITED', 'CEPC', 'PAYMENT_AGGREGATOR', 'Bengaluru', 'Karnataka', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Google Pay (Google India Digital Services)', 'GOOGLE PAY', 'CEPC', 'PAYMENT_AGGREGATOR', 'Bengaluru', 'Karnataka', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Razorpay Software Private Limited', 'RAZORPAY SOFTWARE PRIVATE LIMITED', 'CEPC', 'PAYMENT_AGGREGATOR', 'Bengaluru', 'Karnataka', 'active');

-- ============================================================
-- 4. HOLIDAYS 2026-2027 (RBI & National Holidays)
-- ============================================================

-- 2026 Holidays
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-01-26', 'Republic Day', 'NATIONAL', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-03-10', 'Maha Shivaratri', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-03-14', 'Holi', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-03-30', 'Id-ul-Fitr', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-04-03', 'Good Friday', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-04-06', 'Ram Navami', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-04-14', 'Dr. Ambedkar Jayanti', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-05-01', 'May Day', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-05-24', 'Buddha Purnima', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-06-07', 'Id-ul-Zuha (Bakrid)', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-07-06', 'Muharram', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-08-15', 'Independence Day', 'NATIONAL', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-09-04', 'Milad-un-Nabi', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-10-02', 'Mahatma Gandhi Jayanti', 'NATIONAL', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-10-20', 'Dussehra', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-11-09', 'Diwali (Lakshmi Puja)', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-11-10', 'Diwali (Govardhan Puja)', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-11-24', 'Guru Nanak Jayanti', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-12-25', 'Christmas', 'GAZETTED', 2026, 1);

-- 2027 Holidays
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-01-26', 'Republic Day', 'NATIONAL', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-03-01', 'Maha Shivaratri', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-03-04', 'Holi', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-03-19', 'Id-ul-Fitr', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-03-26', 'Good Friday', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-04-14', 'Dr. Ambedkar Jayanti', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-05-01', 'May Day', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-05-13', 'Buddha Purnima', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-05-27', 'Id-ul-Zuha (Bakrid)', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-06-26', 'Muharram', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-08-15', 'Independence Day', 'NATIONAL', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-08-25', 'Milad-un-Nabi', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-10-02', 'Mahatma Gandhi Jayanti', 'NATIONAL', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-10-08', 'Dussehra', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-10-28', 'Diwali', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-11-14', 'Guru Nanak Jayanti', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-12-25', 'Christmas', 'GAZETTED', 2027, 1);

-- ============================================================
-- 5. SUPPORTED LOCALES
-- ============================================================

INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'en', 'English', 1, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'hi', 'Hindi', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'mr', 'Marathi', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'ta', 'Tamil', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'te', 'Telugu', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'kn', 'Kannada', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'bn', 'Bengali', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'gu', 'Gujarati', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'ml', 'Malayalam', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'pa', 'Punjabi', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'or', 'Odia', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'as', 'Assamese', 0, 1);

-- ============================================================
-- 6. FORM_CONFIG (Complaint Filing Form)
-- ============================================================

INSERT INTO FORM_CONFIG (ID, FORM_KEY, FORM_JSON, VERSION, IS_ACTIVE) VALUES (FORM_CONFIG_SEQ.NEXTVAL, 'complaint_filing_v1',
'{"formId":"complaint_filing_v1","title":"File a Complaint","sections":[{"id":"personal","title":"Personal Details","fields":[{"name":"complainantName","type":"text","label":"Full Name","required":true,"maxLength":200},{"name":"complainantEmail","type":"email","label":"Email Address","required":true},{"name":"complainantPhone","type":"tel","label":"Mobile Number","required":true,"pattern":"^[6-9]\\d{9}$"},{"name":"complainantAddress","type":"textarea","label":"Address","required":false}]},{"id":"entity","title":"Regulated Entity Details","fields":[{"name":"entityType","type":"select","label":"Entity Type","required":true,"options":["Bank","NBFC","Payment System"]},{"name":"bankId","type":"autocomplete","label":"Entity Name","required":true},{"name":"bankBranch","type":"text","label":"Branch","required":false},{"name":"accountNumber","type":"text","label":"Account/Card Number","required":false}]},{"id":"complaint","title":"Complaint Details","fields":[{"name":"categoryId","type":"select","label":"Nature of Complaint","required":true},{"name":"subject","type":"text","label":"Subject","required":true,"maxLength":500},{"name":"description","type":"richtext","label":"Description","required":true},{"name":"reliefSought","type":"textarea","label":"Relief Sought","required":true}]},{"id":"prior_re","title":"Prior Complaint to Entity","fields":[{"name":"priorReComplaint","type":"radio","label":"Did you first complain to the entity?","required":true,"options":["Yes","No"]},{"name":"reComplaintDate","type":"date","label":"Date of complaint to entity","required":false,"showIf":"priorReComplaint==Yes"},{"name":"reComplaintReference","type":"text","label":"Reference number","required":false},{"name":"reRepliedAndDissatisfied","type":"radio","label":"Did entity reply and you are dissatisfied?","required":false,"options":["Yes","No"]},{"name":"reLastCommunicationDate","type":"date","label":"Date of last communication","required":false}]}]}',
1, 1);

-- ============================================================
-- 7. SAMPLE COMPLAINTS (for testing MRE assessment)
-- ============================================================

-- Complaint 1: MAINTAINABLE - All conditions met
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, COMPLAINANT_ADDRESS, BANK_ID, BANK_BRANCH, ACCOUNT_NUMBER, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ASSIGNED_OFFICER, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, RE_LAST_COMMUNICATION_DATE, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/MUM/000001', 'Rajesh Kumar', 'rajesh.kumar@gmail.com', '9876543210', '42, MG Road, Andheri West, Mumbai 400058', 1, 'Andheri West Branch', '30129876543', 1, 'ATM cash not dispensed - Rs 10000 debited',
'I attempted to withdraw Rs 10,000 from SBI ATM at Andheri West on 01-May-2026. The machine showed transaction successful but no cash was dispensed. Amount has been debited from my account. I have the ATM slip.',
'Immediate reversal of Rs 10,000 and compensation for mental harassment', 'in_progress', 'HIGH', 'ONLINE', 'RBIO', 'RBIO_OFFICER', 'officer.rbio1', 'SBI', 'ASSESSMENT',
1, DATE '2026-05-02', 'SBI/CMP/2026/45678', 1, DATE '2026-05-20', 0, 'GREEN', TIMESTAMP '2026-06-02 10:30:00');

-- Complaint 2: NON-MAINTAINABLE - Filed before window (no 30-day wait)
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, COMPLAINANT_ADDRESS, BANK_ID, BANK_BRANCH, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ASSIGNED_OFFICER, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/DEL/000002', 'Priya Sharma', 'priya.sharma@yahoo.com', '9988776655', 'B-15, Saket, New Delhi 110017', 2, 'Saket Branch', 5, 'Excess EMI charged on home loan',
'PNB has been charging excess EMI of Rs 2,500 per month since January 2026 despite the RBI repo rate cut. I complained to the bank 5 days ago and have not waited for their response.',
'Refund of excess EMI charged and correction of interest rate', 'pending', 'MEDIUM', 'ONLINE', 'RBIO', 'RBIO_OFFICER', 'officer.rbio1', 'PNB', 'TRIAGE',
1, DATE '2026-06-25', 'PNB/LOAN/2026/789', 0, 0, 'RED', TIMESTAMP '2026-06-28 14:20:00');

-- Complaint 3: NON-MAINTAINABLE - No prior RE complaint
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, BANK_ID, BANK_BRANCH, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ASSIGNED_OFFICER, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/BLR/000003', 'Suresh Reddy', 'suresh.r@outlook.com', '8877665544', 12, 'Whitefield Branch', 3, 'UPI payment failed but money debited',
'I made a UPI payment of Rs 5,000 via Google Pay to a merchant but the transaction failed. Money was debited from my HDFC account but not credited to merchant. I have not complained to HDFC yet.',
'Immediate reversal of Rs 5,000', 'pending', 'MEDIUM', 'ONLINE', 'CEPC', 'CEPC_DO', 'officer.cepc1', 'HDFC', 'TRIAGE',
0, 0, 'RED', TIMESTAMP '2026-06-30 09:15:00');

-- Complaint 4: MAINTAINABLE - RE replied and dissatisfied
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, COMPLAINANT_ADDRESS, BANK_ID, BANK_BRANCH, ACCOUNT_NUMBER, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ASSIGNED_OFFICER, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, RE_LAST_COMMUNICATION_DATE, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/CHN/000004', 'Lakshmi Venkatesh', 'lakshmi.v@gmail.com', '9123456780', '12, Anna Nagar, Chennai 600040', 13, 'Anna Nagar Branch', '0012345678', 2, 'Unauthorized credit card charges of Rs 15,000',
'ICICI Bank has levied unauthorized charges of Rs 15,000 on my credit card. I complained to the bank on 10-Apr-2026 and received an unsatisfactory response on 20-Apr-2026 refusing refund. The charges are for a subscription I never authorized.',
'Full refund of Rs 15,000 and compensation for harassment', 'in_progress', 'HIGH', 'ONLINE', 'CEPC', 'CEPC_DO', 'officer.cepc1', 'ICICI', 'ASSESSMENT',
1, DATE '2026-04-10', 'ICICI/CC/2026/34567', 1, DATE '2026-04-20', 0, 'GREEN', TIMESTAMP '2026-05-15 11:00:00');

-- Complaint 5: NON-MAINTAINABLE - Beyond limitation period (>3 years)
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, BANK_ID, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, RE_LAST_COMMUNICATION_DATE, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/KOL/000005', 'Arun Ghosh', 'arun.ghosh@hotmail.com', '7788990011', 14, 6, 'Fixed deposit not renewed as per instructions',
'Axis Bank did not auto-renew my FD of Rs 5 lakh in March 2022 as per my standing instruction. I only noticed now. I complained to the bank in April 2022.',
'Renewal of FD with applicable interest from March 2022', 'pending', 'LOW', 'ONLINE', 'CEPC', 'CEPC_DO', 'AXIS', 'TRIAGE',
1, DATE '2022-04-15', 'AXIS/FD/2022/112233', 0, DATE '2022-04-20', 0, 'RED', TIMESTAMP '2026-07-01 16:45:00');

-- Complaint 6: MAINTAINABLE - NBFC complaint (senior citizen)
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, COMPLAINANT_ADDRESS, BANK_ID, BANK_BRANCH, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ASSIGNED_OFFICER, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, RE_LAST_COMMUNICATION_DATE, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/PUN/000006', 'Shantabai Pawar', 'shantabai.p@gmail.com', '9090909090', '25, Model Colony, Pune 411016', 33, 'Pune Main Branch', 5, 'Gold loan foreclosure excess charge by Bajaj Finance',
'Bajaj Finance charged Rs 8,000 as foreclosure penalty on my gold loan despite RBI circular prohibiting such charges on floating rate loans. I am a 72 year old senior citizen. Complained on 01-May-2026, bank refused on 25-May-2026.',
'Refund of Rs 8,000 foreclosure charges plus compensation for harassment of a senior citizen', 'in_progress', 'HIGH', 'ONLINE', 'RBIO', 'RBIO_OFFICER', 'officer.rbio2', 'BAJAJ_FIN', 'ASSESSMENT',
1, DATE '2026-05-01', 'BJF/GL/2026/99887', 1, DATE '2026-05-25', 0, 'GREEN', TIMESTAMP '2026-06-15 09:00:00');

-- Complaint 7: Resolved complaint (for timeline testing)
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, BANK_ID, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ASSIGNED_OFFICER, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, MAINTAINABILITY_DETERMINATION, MAINTAINABILITY_DETERMINED_BY, MAINTAINABILITY_DETERMINED_AT, AWARD_AMOUNT, FILED_AT, RESOLVED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/MUM/000007', 'Deepak Mehta', 'deepak.m@gmail.com', '9812345678', 12, 1, 'ATM dispensed less cash than debited',
'HDFC ATM dispensed only Rs 5,000 against debit of Rs 10,000. Complained to bank on 01-Mar-2026, bank denied on 20-Mar-2026.',
'Reversal of Rs 5,000 and interest', 'resolved', 'MEDIUM', 'ONLINE', 'RBIO', 'RBIO_OFFICER', 'officer.rbio1', 'HDFC', 'CLOSED',
1, DATE '2026-03-01', 'HDFC/ATM/2026/55555', 1, 0, 'GREEN', 'MAINTAINABLE', 'officer.rbio1', TIMESTAMP '2026-04-10 14:30:00', 5000.00, TIMESTAMP '2026-04-02 10:00:00', TIMESTAMP '2026-04-25 15:30:00');

-- Complaint 8: Duplicate grievance test
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, BANK_ID, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/MUM/000008', 'Rajesh Kumar', 'rajesh.kumar@gmail.com', '9876543210', 1, 1, 'ATM cash not dispensed - duplicate filing',
'Same complaint as CMS/2026/MUM/000001 - filing again as I have not received resolution yet.',
'Immediate reversal of Rs 10,000', 'pending', 'MEDIUM', 'ONLINE', 'RBIO', 'RBIO_OFFICER', 'SBI', 'TRIAGE',
1, DATE '2026-05-02', 'SBI/CMP/2026/45678', 1, 1, 'RED', TIMESTAMP '2026-07-01 08:00:00');

-- ============================================================
-- 8. COMPLAINT TIMELINE ENTRIES
-- ============================================================

INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 1, 'FILED', 'SYSTEM', 'Complaint filed online by citizen', NULL, 'pending', TIMESTAMP '2026-06-02 10:30:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 1, 'ASSIGNED', 'SYSTEM', 'Auto-assigned to RBIO department by MRE rule ASGN-001', 'pending', 'in_progress', TIMESTAMP '2026-06-02 10:31:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 1, 'MRE_ASSESSED', 'SYSTEM', 'MRE assessment: GREEN - all grounds pass', 'in_progress', 'in_progress', TIMESTAMP '2026-06-02 10:31:05');

INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 7, 'FILED', 'SYSTEM', 'Complaint filed online', NULL, 'pending', TIMESTAMP '2026-04-02 10:00:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 7, 'ASSIGNED', 'SYSTEM', 'Assigned to RBIO', 'pending', 'in_progress', TIMESTAMP '2026-04-02 10:01:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 7, 'DETERMINATION', 'officer.rbio1', 'Determined MAINTAINABLE - all Q13/Q16/Q17 conditions satisfied', 'in_progress', 'in_progress', TIMESTAMP '2026-04-10 14:30:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 7, 'FORWARDED_TO_RE', 'officer.rbio1', 'Forwarded to HDFC Bank for response within 15 days', 'in_progress', 'in_progress', TIMESTAMP '2026-04-10 14:35:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 7, 'RE_RESPONDED', 'HDFC Bank', 'RE has submitted response and agreed to refund', 'in_progress', 'in_progress', TIMESTAMP '2026-04-20 11:00:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 7, 'RESOLVED', 'officer.rbio1', 'Resolved with award of Rs 5,000 to complainant', 'in_progress', 'resolved', TIMESTAMP '2026-04-25 15:30:00');

-- ============================================================
-- 9. RE_RESPONSE_TRACKER
-- ============================================================

INSERT INTO RE_RESPONSE_TRACKER (ID, COMPLAINT_ID, REGULATED_ENTITY_ID, FORWARDED_AT, RESPONDED_AT, WINDOW_DAYS, WINDOW_EXPIRES_AT, BREACHED, EX_PARTE_ELIGIBLE, NOTES) VALUES (
RE_RESPONSE_TRACKER_SEQ.NEXTVAL, 7, 6, TIMESTAMP '2026-04-10 14:35:00', TIMESTAMP '2026-04-20 11:00:00', 15, TIMESTAMP '2026-04-25 14:35:00', 0, 0, 'HDFC responded within window');

INSERT INTO RE_RESPONSE_TRACKER (ID, COMPLAINT_ID, REGULATED_ENTITY_ID, FORWARDED_AT, RESPONDED_AT, WINDOW_DAYS, WINDOW_EXPIRES_AT, BREACHED, EX_PARTE_ELIGIBLE, NOTES) VALUES (
RE_RESPONSE_TRACKER_SEQ.NEXTVAL, 1, 1, TIMESTAMP '2026-06-05 10:00:00', NULL, 15, TIMESTAMP '2026-06-20 10:00:00', 1, 1, 'SBI has not responded - window breached');

COMMIT;
