-- ============================================================
-- CMS 2.0 — Assignment Engine Seed Data
-- Attribute registry + COMPLAINT_INTAKE starter ruleset (Appendix A)
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- 1. ATTRIBUTE REGISTRY
-- ─────────────────────────────────────────────────────────────
INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'claimAmount', 'Claim Amount', 'Monetary amount of the complaint', 'MONEY', '$.complaint.claimAmount', 0, 'FREE_TEXT', 1, 10, 1, 'EQ,NEQ,GT,GTE,LT,LTE,BETWEEN,IN,NOT_IN,IS_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'complaintCategory', 'Complaint Category', 'Primary category of the complaint', 'ENUM', '$.complaint.category', 0, 'STATIC_LIST', 1, 20, 1, 'EQ,NEQ,IN,NOT_IN,IS_NULL,IS_NOT_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'complaintSubCategory', 'Sub-Category', 'Sub-category of the complaint', 'ENUM', '$.complaint.subCategory', 0, 'STATIC_LIST', 0, 30, 1, 'EQ,NEQ,IN,NOT_IN,IS_NULL,IS_NOT_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'regulatedEntityId', 'Regulated Entity', 'ID of the regulated entity (bank/NBFC)', 'STRING', '$.entity.regulatedEntityId', 0, 'LOOKUP_API', 0, 40, 1, 'EQ,NEQ,IN,NOT_IN,IS_NULL,IS_NOT_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'regulatedEntityType', 'Entity Type', 'Type: BANK, NBFC, etc.', 'ENUM', '$.entity.regulatedEntityType', 0, 'STATIC_LIST', 1, 50, 1, 'EQ,NEQ,IN,NOT_IN,IS_NULL,IS_NOT_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'branchCode', 'Branch Code', 'Branch of the regulated entity', 'STRING', '$.geo.branchCode', 0, 'LOOKUP_API', 0, 60, 1, 'EQ,NEQ,IN,NOT_IN,STARTS_WITH,IS_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'state', 'State', 'Indian state code (2-letter)', 'ENUM', '$.geo.state', 0, 'STATIC_LIST', 1, 70, 1, 'EQ,NEQ,IN,NOT_IN,IS_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'district', 'District', 'District name', 'STRING', '$.geo.district', 0, 'LOOKUP_API', 0, 80, 1, 'EQ,NEQ,IN,NOT_IN,IS_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'zone', 'Zone', 'RBI administrative zone', 'ENUM', '$.geo.zone', 0, 'STATIC_LIST', 1, 90, 1, 'EQ,NEQ,IN,NOT_IN,IS_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'channel', 'Channel', 'Complaint filing channel', 'ENUM', '$.complaint.channel', 0, 'STATIC_LIST', 0, 100, 1, 'EQ,NEQ,IN,NOT_IN,IS_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'language', 'Language', 'Preferred language of complainant', 'ENUM', '$.complaint.language', 0, 'STATIC_LIST', 0, 110, 1, 'EQ,IN,IS_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'escalationLevel', 'Escalation Level', 'Current escalation level', 'ENUM', '$.complaint.escalationLevel', 0, 'STATIC_LIST', 1, 120, 1, 'EQ,NEQ,IN,NOT_IN,IS_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'complainantType', 'Complainant Type', 'Individual, Company, Trust etc.', 'ENUM', '$.complainant.type', 0, 'STATIC_LIST', 0, 130, 1, 'EQ,IN,NOT_IN,IS_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'isSeniorCitizen', 'Senior Citizen', 'Whether complainant is a senior citizen', 'BOOLEAN', '$.complainant.isSeniorCitizen', 0, 'FREE_TEXT', 0, 140, 1, 'IS_TRUE,IS_FALSE,IS_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'isRepeatComplaint', 'Repeat Complaint', 'Whether this is a repeat filing', 'BOOLEAN', '$.complaint.isRepeatComplaint', 0, 'FREE_TEXT', 0, 150, 1, 'IS_TRUE,IS_FALSE,IS_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'daysOpen', 'Days Open', 'Number of days since complaint was filed', 'NUMBER', '$.complaint.daysOpen', 0, 'FREE_TEXT', 0, 160, 1, 'EQ,GT,GTE,LT,LTE,BETWEEN,IS_NULL');

INSERT INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, INDEXABLE, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS)
VALUES ('RBI-CMS', 'sourceSystem', 'Source System', 'System that originated the complaint', 'ENUM', '$.complaint.sourceSystem', 0, 'STATIC_LIST', 0, 170, 1, 'EQ,IN,NOT_IN,IS_NULL');

-- ─────────────────────────────────────────────────────────────
-- 2. ATTRIBUTE VALUES (ENUM values)
-- ─────────────────────────────────────────────────────────────

-- regulatedEntityType
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'regulatedEntityType', 'BANK', 'Bank', 1, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'regulatedEntityType', 'NBFC', 'Non-Banking Financial Company', 2, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'regulatedEntityType', 'PAYMENT_SYSTEM', 'Payment System Operator', 3, 1);

-- complaintCategory
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'complaintCategory', 'UPI', 'UPI', 1, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'complaintCategory', 'CARD_FRAUD', 'Card Fraud', 2, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'complaintCategory', 'NET_BANKING', 'Net Banking', 3, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'complaintCategory', 'ATM', 'ATM', 4, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'complaintCategory', 'LOAN', 'Loan', 5, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'complaintCategory', 'DEPOSIT', 'Deposit', 6, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'complaintCategory', 'DIGITAL', 'Digital Banking', 7, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'complaintCategory', 'INSURANCE', 'Insurance', 8, 1);

-- escalationLevel
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'escalationLevel', 'L1', 'Level 1', 1, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'escalationLevel', 'L2', 'Level 2', 2, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'escalationLevel', 'APPEAL', 'Appeal', 3, 1);

-- state (sample)
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'state', 'MH', 'Maharashtra', 1, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'state', 'GJ', 'Gujarat', 2, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'state', 'GA', 'Goa', 3, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'state', 'KA', 'Karnataka', 4, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'state', 'TN', 'Tamil Nadu', 5, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'state', 'KL', 'Kerala', 6, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'state', 'AP', 'Andhra Pradesh', 7, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'state', 'TS', 'Telangana', 8, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'state', 'DL', 'Delhi', 9, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'state', 'UP', 'Uttar Pradesh', 10, 1);

-- channel
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'channel', 'PORTAL', 'Online Portal', 1, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'channel', 'EMAIL', 'Email', 2, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'channel', 'PHYSICAL', 'Physical Letter', 3, 1);
INSERT INTO ASGN_ATTRIBUTE_VALUE (TENANT_ID, ATTRIBUTE_CODE, VALUE_CODE, VALUE_LABEL, SORT_ORDER, ACTIVE) VALUES ('RBI-CMS', 'channel', 'PHONE', 'Phone', 4, 1);

-- ─────────────────────────────────────────────────────────────
-- 3. COMPLAINT_INTAKE RULESET
-- ─────────────────────────────────────────────────────────────
INSERT INTO ASGN_RULE_SET (TENANT_ID, DECISION_POINT, NAME, DESCRIPTION, HIT_POLICY, ACTIVE)
VALUES ('RBI-CMS', 'COMPLAINT_INTAKE', 'Complaint Intake Assignment', 'Routes new complaints to the appropriate team/officer', 'FIRST', 1);

-- Version 1 (PUBLISHED)
INSERT INTO ASGN_RULE_SET_VERSION (TENANT_ID, RULE_SET_ID, VERSION_NO, STATUS, EFFECTIVE_FROM, PUBLISHED_BY, PUBLISHED_AT)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE_SET WHERE DECISION_POINT='COMPLAINT_INTAKE'), 1, 'PUBLISHED', SYSTIMESTAMP, 'system', SYSTIMESTAMP);

-- Rules (Appendix A)
-- R-001: Very high value >= 2500000
INSERT INTO ASGN_RULE (TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE_SET_VERSION WHERE VERSION_NO=1 AND RULE_SET_ID=(SELECT ID FROM ASGN_RULE_SET WHERE DECISION_POINT='COMPLAINT_INTAKE')), 'R-001', 'Very high value', 10, 10, 1);

-- R-002: High value banks [500000, 2500000) + BANK
INSERT INTO ASGN_RULE (TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE_SET_VERSION WHERE VERSION_NO=1 AND RULE_SET_ID=(SELECT ID FROM ASGN_RULE_SET WHERE DECISION_POINT='COMPLAINT_INTAKE')), 'R-002', 'High value banks', 20, 20, 1);

-- R-003: Digital fraud fast-track
INSERT INTO ASGN_RULE (TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE_SET_VERSION WHERE VERSION_NO=1 AND RULE_SET_ID=(SELECT ID FROM ASGN_RULE_SET WHERE DECISION_POINT='COMPLAINT_INTAKE')), 'R-003', 'Digital fraud fast-track', 30, 30, 1);

-- R-004: NBFC cell
INSERT INTO ASGN_RULE (TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE_SET_VERSION WHERE VERSION_NO=1 AND RULE_SET_ID=(SELECT ID FROM ASGN_RULE_SET WHERE DECISION_POINT='COMPLAINT_INTAKE')), 'R-004', 'NBFC cell', 40, 40, 1);

-- R-005: West zone general [0, 500000)
INSERT INTO ASGN_RULE (TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE_SET_VERSION WHERE VERSION_NO=1 AND RULE_SET_ID=(SELECT ID FROM ASGN_RULE_SET WHERE DECISION_POINT='COMPLAINT_INTAKE')), 'R-005', 'West zone general', 50, 50, 1);

-- R-006: South zone general [0, 500000)
INSERT INTO ASGN_RULE (TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE_SET_VERSION WHERE VERSION_NO=1 AND RULE_SET_ID=(SELECT ID FROM ASGN_RULE_SET WHERE DECISION_POINT='COMPLAINT_INTAKE')), 'R-006', 'South zone general', 60, 60, 1);

-- R-007: Appeal to AA
INSERT INTO ASGN_RULE (TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE_SET_VERSION WHERE VERSION_NO=1 AND RULE_SET_ID=(SELECT ID FROM ASGN_RULE_SET WHERE DECISION_POINT='COMPLAINT_INTAKE')), 'R-007', 'Appeal to AA', 70, 70, 1);

-- R-008: Senior citizen priority (deliberately shadowed for UNREACHABLE test)
INSERT INTO ASGN_RULE (TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE_SET_VERSION WHERE VERSION_NO=1 AND RULE_SET_ID=(SELECT ID FROM ASGN_RULE_SET WHERE DECISION_POINT='COMPLAINT_INTAKE')), 'R-008', 'Senior citizen priority', 80, 80, 1);

-- ─────────────────────────────────────────────────────────────
-- 4. CONDITIONS
-- ─────────────────────────────────────────────────────────────

-- R-001: claimAmount >= 2500000
INSERT INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_NUM_FROM)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-001'), 'claimAmount', 'GTE', 2500000);

-- R-002: claimAmount BETWEEN [500000, 2500000)
INSERT INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_NUM_FROM, VALUE_NUM_TO)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-002'), 'claimAmount', 'BETWEEN', 500000, 2500000);
-- R-002: regulatedEntityType = BANK
INSERT INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_TEXT)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-002'), 'regulatedEntityType', 'EQ', 'BANK');

-- R-003: complaintCategory IN (UPI, CARD_FRAUD, NET_BANKING)
INSERT INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_LIST)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-003'), 'complaintCategory', 'IN', 'UPI,CARD_FRAUD,NET_BANKING');

-- R-004: regulatedEntityType = NBFC
INSERT INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_TEXT)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-004'), 'regulatedEntityType', 'EQ', 'NBFC');

-- R-005: claimAmount BETWEEN [0, 500000) + state IN (MH, GJ, GA)
INSERT INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_NUM_FROM, VALUE_NUM_TO)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-005'), 'claimAmount', 'BETWEEN', 0, 500000);
INSERT INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_LIST)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-005'), 'state', 'IN', 'MH,GJ,GA');

-- R-006: claimAmount BETWEEN [0, 500000) + state IN (KA, TN, KL, AP, TS)
INSERT INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_NUM_FROM, VALUE_NUM_TO)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-006'), 'claimAmount', 'BETWEEN', 0, 500000);
INSERT INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_LIST)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-006'), 'state', 'IN', 'KA,TN,KL,AP,TS');

-- R-007: escalationLevel = APPEAL
INSERT INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_TEXT)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-007'), 'escalationLevel', 'EQ', 'APPEAL');

-- R-008: isSeniorCitizen = true
INSERT INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_TEXT)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-008'), 'isSeniorCitizen', 'IS_TRUE', null);

-- ─────────────────────────────────────────────────────────────
-- 5. OUTCOMES
-- ─────────────────────────────────────────────────────────────
INSERT INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, OUTCOME_TYPE, TARGET_ID, ASSIGN_MODE, DISTRIBUTION_STRATEGY)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-001'), 'GROUP', 'SENIOR_ADJUDICATION', 'PICK_MEMBER', 'LEAST_ACTIVE_CASES');

INSERT INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, OUTCOME_TYPE, TARGET_ID, ASSIGN_MODE)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-002'), 'GROUP', 'BANK_HIGH_VALUE', 'AS_GROUP');

INSERT INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, OUTCOME_TYPE, TARGET_ID, ASSIGN_MODE, DISTRIBUTION_STRATEGY)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-003'), 'GROUP', 'DIGITAL_FRAUD_CELL', 'PICK_MEMBER', 'SKILL_MATCH');

INSERT INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, OUTCOME_TYPE, TARGET_ID, ASSIGN_MODE)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-004'), 'GROUP', 'NBFC_CELL', 'AS_GROUP');

INSERT INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, OUTCOME_TYPE, TARGET_ID, ASSIGN_MODE)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-005'), 'GROUP', 'ORBIO_MUMBAI', 'AS_GROUP');

INSERT INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, OUTCOME_TYPE, TARGET_ID, ASSIGN_MODE)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-006'), 'GROUP', 'ORBIO_CHENNAI', 'AS_GROUP');

INSERT INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, OUTCOME_TYPE, TARGET_ID, ORG_UNIT_FROM_ATTRIBUTE)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-007'), 'ROLE_IN_ORG_UNIT', 'APPELLATE_AUTHORITY', 'zone');

INSERT INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, OUTCOME_TYPE, TARGET_ID, ASSIGN_MODE)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE WHERE RULE_CODE='R-008'), 'GROUP', 'PRIORITY_DESK', 'AS_GROUP');

-- DEFAULT outcome
INSERT INTO ASGN_RULE_OUTCOME (TENANT_ID, VERSION_ID, IS_DEFAULT, OUTCOME_TYPE, TARGET_ID)
VALUES ('RBI-CMS', (SELECT ID FROM ASGN_RULE_SET_VERSION WHERE VERSION_NO=1 AND RULE_SET_ID=(SELECT ID FROM ASGN_RULE_SET WHERE DECISION_POINT='COMPLAINT_INTAKE')), 1, 'QUEUE', 'GENERAL_INTAKE_POOL');

-- ─────────────────────────────────────────────────────────────
-- 6. PUBLICATION RECORD (activates the cache)
-- ─────────────────────────────────────────────────────────────
INSERT INTO ASGN_RULE_SET_PUBLICATION (TENANT_ID, DECISION_POINT, ACTIVE_VERSION_ID, PUBLISHED_AT)
VALUES ('RBI-CMS', 'COMPLAINT_INTAKE', (SELECT ID FROM ASGN_RULE_SET_VERSION WHERE VERSION_NO=1 AND RULE_SET_ID=(SELECT ID FROM ASGN_RULE_SET WHERE DECISION_POINT='COMPLAINT_INTAKE')), SYSTIMESTAMP);

COMMIT;
