-- ============================================================
-- CMS 2.0 — V9: Complaint Comments, Officer Availability,
--               and Closure Fields on COMPLAINTS table
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- 1. NEW TABLE: COMPLAINT_COMMENTS
-- ─────────────────────────────────────────────────────────────
CREATE TABLE COMPLAINT_COMMENTS (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_number    VARCHAR2(100)  NOT NULL,
    author              VARCHAR2(100)  NOT NULL,
    initials            VARCHAR2(10),
    text                VARCHAR2(2000) NOT NULL,
    role                VARCHAR2(50),
    color               VARCHAR2(10)   DEFAULT '#6366f1',
    created_at          TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_comment_complaint ON COMPLAINT_COMMENTS (complaint_number);
CREATE INDEX idx_comment_created   ON COMPLAINT_COMMENTS (created_at);

-- ─────────────────────────────────────────────────────────────
-- 2. NEW TABLE: OFFICER_AVAILABILITY
-- ─────────────────────────────────────────────────────────────
CREATE TABLE OFFICER_AVAILABILITY (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             VARCHAR2(100)  NOT NULL,
    role                VARCHAR2(50)   NOT NULL,
    active              NUMBER(1)      DEFAULT 1 NOT NULL,
    on_leave            NUMBER(1)      DEFAULT 0 NOT NULL,
    leave_start_date    DATE,
    leave_end_date      DATE,
    leave_reason        VARCHAR2(200),
    current_workload    NUMBER         DEFAULT 0,
    max_workload        NUMBER         DEFAULT 20,
    office_code         VARCHAR2(50),
    updated_at          TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_officer_user_id ON OFFICER_AVAILABILITY (user_id);
CREATE INDEX idx_officer_role    ON OFFICER_AVAILABILITY (role);

-- ─────────────────────────────────────────────────────────────
-- 3. ALTER COMPLAINTS: Add entity_name and category_name columns
-- ─────────────────────────────────────────────────────────────
ALTER TABLE COMPLAINTS ADD (entity_name VARCHAR2(300));
ALTER TABLE COMPLAINTS ADD (category_name VARCHAR2(200));

-- ─────────────────────────────────────────────────────────────
-- 4. ALTER COMPLAINTS: Add closure-related columns
-- ─────────────────────────────────────────────────────────────
ALTER TABLE COMPLAINTS ADD (closure_clause_description CLOB);
ALTER TABLE COMPLAINTS ADD (complaint_status_on_portal VARCHAR2(100));
ALTER TABLE COMPLAINTS ADD (speaking_order_generated VARCHAR2(10));
ALTER TABLE COMPLAINTS ADD (gist_of_case CLOB);
ALTER TABLE COMPLAINTS ADD (gist_of_case_regional CLOB);
