apiVersion: v1
kind: Secret
metadata:
  name: cms-sms-secret
  namespace: rbi-cms
  labels:
    app.kubernetes.io/part-of: rbi-cms
type: Opaque
stringData:
  SMS_API_KEY: "CHANGE_ME_IN_PRODUCTION"
  SMS_SENDER_ID: "RBICMS"
  SMS_TEMPLATE_ID: "CHANGE_ME_IN_PRODUCTION"
  OTP_EXPIRY_MINUTES: "5"
