package com.hrms.cms.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * One append-only row per delivery attempt of a notification (UST845).
 *
 * <p>A separate table rather than status columns on {@code IN_APP_NOTIFICATION}: a notification may
 * be attempted more than once and over more than one channel, so delivery state is one-to-many and
 * would not fit on the notification row without losing the earlier attempts. Keeping attempts
 * distinct is the point — "failed once then succeeded" and "succeeded first time" are different
 * facts when diagnosing why an officer says they were never told.
 *
 * <p>A retry appends a new attempt; the failed one stays visible. The identifying columns of an
 * attempt are therefore immutable, but {@link #status} is NOT — an EMAIL or SMS attempt is created
 * {@link #STATUS_PENDING} and settled later by cms-notification-service, which owns the only real
 * mail transport. That makes this table the dispatch queue as well as the audit trail: a row still
 * PENDING is a message that was never handed to a gateway, so it can be re-published rather than
 * silently lost if the Kafka publish or the consumer failed.
 */
@Entity
@Table(name = "NOTIFICATION_DELIVERY_LOG", indexes = {
    @Index(name = "idx_ndl_notification", columnList = "notificationId"),
    @Index(name = "idx_ndl_recipient", columnList = "recipientUserId"),
    @Index(name = "idx_ndl_status", columnList = "status"),
    @Index(name = "idx_ndl_attempted_at", columnList = "attemptedAt"),
    @Index(name = "idx_ndl_type", columnList = "notificationType"),
    @Index(name = "idx_ndl_dispatch_ref", columnList = "dispatchRef")
})
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class NotificationDeliveryLog {

    /** Handed to a queue but not yet confirmed by the sending service. EMAIL/SMS only. */
    public static final String STATUS_PENDING = "PENDING";
    public static final String STATUS_SENT = "SENT";
    public static final String STATUS_FAILED = "FAILED";

    public static final String CHANNEL_IN_APP = "IN_APP";

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Reference to the IN_APP_NOTIFICATIONS row, nullable by design: a failure that happened before
     * the notification could be persisted still has to be recorded, and that is precisely the case
     * worth logging.
     */
    private Long notificationId;

    @Column(nullable = false, length = 200, updatable = false)
    private String recipientUserId;

    /** Translation key of the notification, so the log is readable without re-deriving the text. */
    @Column(length = 200, updatable = false)
    private String notificationType;

    /** IN_APP for now. A column rather than an assumption, so adding email needs no schema change. */
    @Column(nullable = false, length = 20, updatable = false)
    private String channel;

    /** PENDING | SENT | FAILED — mutable, settled by whichever service performs the send. */
    @Column(nullable = false, length = 20)
    private String status;

    /** Truncated at the service boundary; a stack trace does not belong in an audit row. */
    @Column(length = 1000)
    private String errorMessage;

    @Column(length = 50, updatable = false)
    private String relatedComplaintNumber;

    @Column(updatable = false)
    private LocalDateTime attemptedAt;

    /**
     * Correlation key for a queued dispatch, generated by the publisher.
     *
     * <p>A UUID rather than this row's generated id: the Kafka message is built before the insert is
     * flushed, so the publisher cannot know the id yet. cms-notification-service settles the row by
     * this value. Null for IN_APP, which never leaves the application.
     */
    @Column(length = 64, updatable = false)
    private String dispatchRef;

    /** When a PENDING attempt was settled to SENT or FAILED. Null while still queued. */
    private LocalDateTime settledAt;

    @PrePersist
    protected void onCreate() {
        if (attemptedAt == null) attemptedAt = LocalDateTime.now();
    }
}
