-- ═══════════════════════════════════════════════════════════════════════════════════
-- CMS 2.0 — Complete Database Initialization Script
-- Date: 09 July 2026
-- Database: Oracle 21c XE / Enterprise
-- ═══════════════════════════════════════════════════════════════════════════════════
--
-- INSTRUCTIONS:
-- 1. Run this script ONCE on a fresh Oracle schema
-- 2. Hibernate ddl-auto=update will auto-create tables on first boot
-- 3. This script creates sequences, tables, and seeds ALL reference data
-- 4. Pincodes and Translations are loaded from CSV at application startup
--    (via PincodeDataInitializer and TranslationDataInitializer)
-- 5. After running this script, start the Spring Boot application
--
-- EXECUTION:
--   sqlplus cms_user/cms_password@//localhost:1521/XEPDB1 @CMS-Database-Init-2026-07-09.sql
--
-- ═══════════════════════════════════════════════════════════════════════════════════


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 1: SEQUENCES
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CREATE SEQUENCE BANKS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COMPLAINT_CATEGORIES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PINCODES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE REGULATED_ENTITIES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COMPLAINTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EMAIL_DRAFTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE NOTIFICATIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COMMUNICATION_TEMPLATES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COMMENT_TEMPLATES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE APPEALS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COMPLAINT_TIMELINE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COMPLAINT_ATTACHMENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EMAIL_DRAFT_ATTACHMENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EMAIL_IGNORE_LIST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EXTRACTION_RULE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE HOLIDAYS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RE_RESPONSE_TRACKER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TRANSLATION_KEYS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TRANSLATIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SUPPORTED_LOCALES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE FORM_CONFIG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 2: TABLE CREATION (DDL)
-- Note: Hibernate ddl-auto=update will also create these on first boot.
-- This section is provided for DBA teams who prefer explicit DDL.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- ── BANKS ────────────────────────────────────────────────────────────────────────
CREATE TABLE BANKS (
    ID NUMBER(19) DEFAULT BANKS_SEQ.NEXTVAL PRIMARY KEY,
    NAME VARCHAR2(300) NOT NULL,
    CODE VARCHAR2(50),
    TYPE VARCHAR2(100),
    STATUS VARCHAR2(20) DEFAULT 'active',
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_BANK_TYPE ON BANKS(TYPE);
CREATE INDEX IDX_BANK_STATUS ON BANKS(STATUS);

-- ── COMPLAINT CATEGORIES ─────────────────────────────────────────────────────────
CREATE TABLE COMPLAINT_CATEGORIES (
    ID NUMBER(19) DEFAULT COMPLAINT_CATEGORIES_SEQ.NEXTVAL PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    PARENT_ID NUMBER(19),
    STATUS VARCHAR2(20) DEFAULT 'active',
    SORT_ORDER NUMBER(10) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_CATEGORY_PARENT ON COMPLAINT_CATEGORIES(PARENT_ID);
CREATE INDEX IDX_CATEGORY_STATUS ON COMPLAINT_CATEGORIES(STATUS);

-- ── PINCODES ─────────────────────────────────────────────────────────────────────
CREATE TABLE PINCODES (
    ID NUMBER(19) DEFAULT PINCODES_SEQ.NEXTVAL PRIMARY KEY,
    PINCODE VARCHAR2(6) NOT NULL,
    OFFICE_NAME VARCHAR2(100) NOT NULL,
    DISTRICT VARCHAR2(100) NOT NULL,
    STATE VARCHAR2(100) NOT NULL,
    REGION VARCHAR2(50),
    DIVISION VARCHAR2(50),
    OFFICE_TYPE VARCHAR2(20)
);
CREATE INDEX IDX_PINCODE_CODE ON PINCODES(PINCODE);
CREATE INDEX IDX_PINCODE_STATE ON PINCODES(STATE);
CREATE INDEX IDX_PINCODE_DISTRICT ON PINCODES(DISTRICT);

-- ── REGULATED ENTITIES ───────────────────────────────────────────────────────────
CREATE TABLE REGULATED_ENTITIES (
    ID NUMBER(19) DEFAULT REGULATED_ENTITIES_SEQ.NEXTVAL PRIMARY KEY,
    NAME VARCHAR2(500) NOT NULL,
    NAME_NORMALIZED VARCHAR2(500),
    DEPARTMENT VARCHAR2(10) NOT NULL,
    ENTITY_TYPE VARCHAR2(100),
    CITY VARCHAR2(100),
    STATE VARCHAR2(50),
    STATUS VARCHAR2(20) DEFAULT 'active',
    NODAL_OFFICER_NAME VARCHAR2(200),
    NODAL_OFFICER_EMAIL VARCHAR2(200),
    NODAL_OFFICER_PHONE VARCHAR2(20),
    NODAL_OFFICER_DESIGNATION VARCHAR2(100),
    PNO_NAME VARCHAR2(200),
    PNO_EMAIL VARCHAR2(200),
    PNO_PHONE VARCHAR2(20),
    REGISTRATION_DATE TIMESTAMP,
    LAST_LOGIN_AT TIMESTAMP,
    PORTAL_ENABLED NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_RE_DEPARTMENT ON REGULATED_ENTITIES(DEPARTMENT);
CREATE INDEX IDX_RE_NAME ON REGULATED_ENTITIES(NAME);
CREATE INDEX IDX_RE_ENTITY_TYPE ON REGULATED_ENTITIES(ENTITY_TYPE);

-- ── COMPLAINTS ───────────────────────────────────────────────────────────────────
CREATE TABLE COMPLAINTS (
    ID NUMBER(19) DEFAULT COMPLAINTS_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
    COMPLAINANT_NAME VARCHAR2(200) NOT NULL,
    COMPLAINANT_EMAIL VARCHAR2(200),
    COMPLAINANT_PHONE VARCHAR2(20),
    COMPLAINANT_ADDRESS VARCHAR2(500),
    BANK_ID NUMBER(19),
    BANK_BRANCH VARCHAR2(300),
    ACCOUNT_NUMBER VARCHAR2(100),
    CATEGORY_ID NUMBER(19),
    SUBJECT VARCHAR2(500) NOT NULL,
    DESCRIPTION CLOB,
    RELIEF_SOUGHT CLOB,
    STATUS VARCHAR2(30) NOT NULL,
    PRIORITY VARCHAR2(20),
    FILING_TYPE VARCHAR2(50),
    BANK_COMPLAINT_REFERENCE VARCHAR2(200),
    BANK_COMPLAINT_DATE TIMESTAMP,
    ASSIGNED_OFFICER VARCHAR2(200),
    DEPARTMENT VARCHAR2(20),
    ASSIGNED_ROLE VARCHAR2(50),
    ENTITY_CODE VARCHAR2(50),
    WORKFLOW_STAGE VARCHAR2(50),
    PRIOR_RE_COMPLAINT NUMBER(1),
    RE_COMPLAINT_DATE DATE,
    RE_COMPLAINT_REFERENCE VARCHAR2(200),
    RE_REPLIED_AND_DISSATISFIED NUMBER(1),
    RE_LAST_COMMUNICATION_DATE DATE,
    SAME_GRIEVANCE_PENDING NUMBER(1),
    TRIAGE_SIGNAL VARCHAR2(10),
    TRIAGE_FLAGS CLOB,
    ELIGIBILITY_TIMELINE CLOB,
    MAINTAINABILITY_DETERMINATION VARCHAR2(30),
    MAINTAINABILITY_DETERMINED_BY VARCHAR2(200),
    MAINTAINABILITY_DETERMINED_AT TIMESTAMP,
    AWARD_AMOUNT NUMBER(15,2),
    SLA_DEADLINE TIMESTAMP,
    SLA_PRIORITY VARCHAR2(10),
    CONCILIATION_DATE TIMESTAMP,
    CONCILIATION_OUTCOME VARCHAR2(100),
    ADJUDICATION_DATE TIMESTAMP,
    ADJUDICATION_OUTCOME VARCHAR2(100),
    CLOSURE_CAUSE VARCHAR2(50),
    REOPEN_COUNT NUMBER(10) DEFAULT 0,
    LAST_REOPENED_AT TIMESTAMP,
    ADVISORY_TEXT CLOB,
    ADVISORY_ISSUED_AT TIMESTAMP,
    NOTICE_13_1_ISSUED_AT TIMESTAMP,
    IMPLEADED_PARTIES VARCHAR2(1000),
    COMPENSATION_TYPE VARCHAR2(30),
    SCHEME_VERSION VARCHAR2(20),
    CURRENT_STAGE_DEADLINE TIMESTAMP,
    STAGE_ASSIGNED_AT TIMESTAMP,
    FILED_AT TIMESTAMP,
    RESOLVED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP
);
CREATE INDEX IDX_COMPLAINT_NUMBER ON COMPLAINTS(COMPLAINT_NUMBER);
CREATE INDEX IDX_COMPLAINT_STATUS ON COMPLAINTS(STATUS);
CREATE INDEX IDX_COMPLAINT_PRIORITY ON COMPLAINTS(PRIORITY);
CREATE INDEX IDX_COMPLAINT_EMAIL ON COMPLAINTS(COMPLAINANT_EMAIL);
CREATE INDEX IDX_COMPLAINT_CATEGORY ON COMPLAINTS(CATEGORY_ID);
CREATE INDEX IDX_COMPLAINT_BANK ON COMPLAINTS(BANK_ID);
CREATE INDEX IDX_COMPLAINT_CREATED ON COMPLAINTS(CREATED_AT);
CREATE INDEX IDX_COMPLAINT_STATUS_CREATED ON COMPLAINTS(STATUS, CREATED_AT);
CREATE INDEX IDX_COMPLAINT_TRIAGE ON COMPLAINTS(TRIAGE_SIGNAL);
CREATE INDEX IDX_COMPLAINT_MAINTAINABILITY ON COMPLAINTS(MAINTAINABILITY_DETERMINATION);

-- ── EMAIL DRAFTS ─────────────────────────────────────────────────────────────────
CREATE TABLE EMAIL_DRAFTS (
    ID NUMBER(19) DEFAULT EMAIL_DRAFTS_SEQ.NEXTVAL PRIMARY KEY,
    DRAFT_ID VARCHAR2(100) NOT NULL UNIQUE,
    THREAD_ID VARCHAR2(100),
    MESSAGE_ID VARCHAR2(200),
    SENDER_EMAIL VARCHAR2(200),
    SUBJECT VARCHAR2(500),
    BODY CLOB,
    COMPLAINANT_NAME VARCHAR2(200),
    COMPLAINANT_PHONE VARCHAR2(20),
    COMPLAINANT_ADDRESS VARCHAR2(500),
    COMPLAINANT_STATE VARCHAR2(100),
    COMPLAINANT_DISTRICT VARCHAR2(100),
    COMPLAINANT_PINCODE VARCHAR2(10),
    CPGRAMS_NUMBER VARCHAR2(50),
    COMPLAINT_SUMMARY VARCHAR2(500),
    CATEGORY VARCHAR2(50),
    MODE_OF_RECEIPT VARCHAR2(30),
    STATUS VARCHAR2(30),
    ASSIGNED_TO VARCHAR2(200),
    PARENT_COMPLAINT_ID VARCHAR2(50),
    IS_DUPLICATE NUMBER(1) DEFAULT 0,
    OCR_PROCESSED NUMBER(1) DEFAULT 0,
    OCR_CONFIDENCE NUMBER(10) DEFAULT 0,
    OCR_EXTRACTED_FIELDS_JSON CLOB,
    ENTITY_NAME VARCHAR2(100),
    ENTITY_TYPE VARCHAR2(30),
    AMOUNT_INVOLVED NUMBER(15,2),
    PROCESSED_BY VARCHAR2(200),
    DEO_DECISION VARCHAR2(30),
    DEO_REMARKS CLOB,
    NON_MAINTAINABLE_REASON VARCHAR2(100),
    REVIEWER_ASSIGNED_TO VARCHAR2(200),
    REVIEWER_DECISION VARCHAR2(30),
    REVIEWER_REMARKS CLOB,
    TARGET_OFFICE VARCHAR2(100),
    CONVERTED_COMPLAINT_ID VARCHAR2(50),
    DETECTED_LANGUAGE VARCHAR2(50),
    LANGUAGE_NAME VARCHAR2(100),
    IS_VERNACULAR NUMBER(1) DEFAULT 0,
    TRANSLATION_CONFIDENCE NUMBER(5,2),
    TRANSLATED_BODY CLOB,
    RECEIVED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP
);
CREATE INDEX IDX_DRAFT_THREAD ON EMAIL_DRAFTS(THREAD_ID);
CREATE INDEX IDX_DRAFT_STATUS ON EMAIL_DRAFTS(STATUS);
CREATE INDEX IDX_DRAFT_ASSIGNED ON EMAIL_DRAFTS(ASSIGNED_TO);
CREATE INDEX IDX_DRAFT_SENDER ON EMAIL_DRAFTS(SENDER_EMAIL);
CREATE INDEX IDX_DRAFT_VERNACULAR ON EMAIL_DRAFTS(IS_VERNACULAR);
CREATE INDEX IDX_DRAFT_CPGRAMS ON EMAIL_DRAFTS(CPGRAMS_NUMBER);

-- ── IN-APP NOTIFICATIONS ─────────────────────────────────────────────────────────
CREATE TABLE IN_APP_NOTIFICATIONS (
    ID NUMBER(19) DEFAULT NOTIFICATIONS_SEQ.NEXTVAL PRIMARY KEY,
    TARGET_USER_ID VARCHAR2(100) NOT NULL,
    TYPE VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(500) NOT NULL,
    MESSAGE CLOB,
    RELATED_ENTITY_ID VARCHAR2(100),
    RELATED_ENTITY_TYPE VARCHAR2(50),
    ACTION_URL VARCHAR2(200),
    IS_READ NUMBER(1) DEFAULT 0,
    READ_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_NOTIF_USER ON IN_APP_NOTIFICATIONS(TARGET_USER_ID);
CREATE INDEX IDX_NOTIF_READ ON IN_APP_NOTIFICATIONS(TARGET_USER_ID, IS_READ);
CREATE INDEX IDX_NOTIF_CREATED ON IN_APP_NOTIFICATIONS(CREATED_AT);

-- ── COMMUNICATION TEMPLATES ──────────────────────────────────────────────────────
CREATE TABLE COMMUNICATION_TEMPLATES (
    ID NUMBER(19) DEFAULT COMMUNICATION_TEMPLATES_SEQ.NEXTVAL PRIMARY KEY,
    TEMPLATE_NAME VARCHAR2(200) NOT NULL,
    MODE VARCHAR2(20) NOT NULL,
    TRIGGER_CONDITION VARCHAR2(100),
    SCHEME_VERSION VARCHAR2(20),
    SUBJECT_TEMPLATE CLOB NOT NULL,
    BODY_TEMPLATE CLOB NOT NULL,
    DESCRIPTION VARCHAR2(500),
    CATEGORY VARCHAR2(50),
    ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP
);
CREATE INDEX IDX_TEMPLATE_TRIGGER ON COMMUNICATION_TEMPLATES(TRIGGER_CONDITION);
CREATE INDEX IDX_TEMPLATE_SCHEME ON COMMUNICATION_TEMPLATES(SCHEME_VERSION);
CREATE INDEX IDX_TEMPLATE_MODE ON COMMUNICATION_TEMPLATES(MODE);

-- ── COMMENT TEMPLATES ────────────────────────────────────────────────────────────
CREATE TABLE COMMENT_TEMPLATES (
    ID NUMBER(19) DEFAULT COMMENT_TEMPLATES_SEQ.NEXTVAL PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    CONTENT CLOB NOT NULL,
    MODE_OF_RECEIPT VARCHAR2(30),
    CATEGORY VARCHAR2(50),
    ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- ── APPEALS ──────────────────────────────────────────────────────────────────────
CREATE TABLE APPEALS (
    ID NUMBER(19) DEFAULT APPEALS_SEQ.NEXTVAL PRIMARY KEY,
    APPEAL_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
    ORIGINAL_COMPLAINT_NUMBER VARCHAR2(50) NOT NULL,
    APPELLANT_NAME VARCHAR2(200),
    APPELLANT_EMAIL VARCHAR2(200),
    APPELLANT_PHONE VARCHAR2(20),
    GROUNDS_OF_APPEAL CLOB,
    RELIEF_SOUGHT CLOB,
    STATUS VARCHAR2(30) NOT NULL,
    ASSIGNED_ROLE VARCHAR2(50),
    ASSIGNED_OFFICER VARCHAR2(200),
    HEARING_DATE TIMESTAMP,
    ORDER_TEXT CLOB,
    ORDER_DATE TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP
);
CREATE INDEX IDX_APPEAL_NUMBER ON APPEALS(APPEAL_NUMBER);
CREATE INDEX IDX_APPEAL_ORIGINAL ON APPEALS(ORIGINAL_COMPLAINT_NUMBER);
CREATE INDEX IDX_APPEAL_STATUS ON APPEALS(STATUS);
CREATE INDEX IDX_APPEAL_ROLE ON APPEALS(ASSIGNED_ROLE);
CREATE INDEX IDX_APPEAL_OFFICER ON APPEALS(ASSIGNED_OFFICER);
CREATE INDEX IDX_APPEAL_CREATED ON APPEALS(CREATED_AT);

-- ── COMPLAINT TIMELINE ───────────────────────────────────────────────────────────
CREATE TABLE COMPLAINT_TIMELINE (
    ID NUMBER(19) DEFAULT COMPLAINT_TIMELINE_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_ID NUMBER(19) NOT NULL,
    ACTION VARCHAR2(100),
    PERFORMED_BY VARCHAR2(200),
    PERFORMED_AT TIMESTAMP,
    REMARKS CLOB,
    FROM_STATUS VARCHAR2(30),
    TO_STATUS VARCHAR2(30)
);
CREATE INDEX IDX_TIMELINE_COMPLAINT ON COMPLAINT_TIMELINE(COMPLAINT_ID);
CREATE INDEX IDX_TIMELINE_PERFORMED ON COMPLAINT_TIMELINE(PERFORMED_AT);

-- ── COMPLAINT ATTACHMENTS ────────────────────────────────────────────────────────
CREATE TABLE COMPLAINT_ATTACHMENTS (
    ID NUMBER(19) DEFAULT COMPLAINT_ATTACHMENTS_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_ID NUMBER(19) NOT NULL,
    FILE_NAME VARCHAR2(300),
    FILE_PATH VARCHAR2(500),
    FILE_SIZE NUMBER(19),
    CONTENT_TYPE VARCHAR2(100),
    UPLOADED_BY VARCHAR2(200),
    UPLOADED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_ATTACHMENT_COMPLAINT ON COMPLAINT_ATTACHMENTS(COMPLAINT_ID);

-- ── AUDIT LOG ────────────────────────────────────────────────────────────────────
CREATE TABLE AUDIT_LOG (
    ID NUMBER(19) DEFAULT AUDIT_LOG_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_NUMBER VARCHAR2(50),
    ACTION VARCHAR2(100),
    ACTOR VARCHAR2(200),
    ACTION_TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP,
    DETAILS CLOB,
    IP_ADDRESS VARCHAR2(50)
);
CREATE INDEX IDX_AUDIT_COMPLAINT ON AUDIT_LOG(COMPLAINT_NUMBER);
CREATE INDEX IDX_AUDIT_ACTION ON AUDIT_LOG(ACTION);
CREATE INDEX IDX_AUDIT_ACTOR ON AUDIT_LOG(ACTOR);
CREATE INDEX IDX_AUDIT_TIMESTAMP ON AUDIT_LOG(ACTION_TIMESTAMP);

-- ── EMAIL DRAFT ATTACHMENTS ──────────────────────────────────────────────────────
CREATE TABLE EMAIL_DRAFT_ATTACHMENTS (
    ID NUMBER(19) DEFAULT EMAIL_DRAFT_ATTACHMENTS_SEQ.NEXTVAL PRIMARY KEY,
    DRAFT_ID VARCHAR2(100) NOT NULL,
    FILE_NAME VARCHAR2(300),
    FILE_PATH VARCHAR2(500),
    FILE_SIZE NUMBER(19),
    CONTENT_TYPE VARCHAR2(100),
    OCR_TEXT CLOB,
    UPLOADED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_DRAFT_ATT_DRAFT ON EMAIL_DRAFT_ATTACHMENTS(DRAFT_ID);

-- ── EMAIL IGNORE LIST ────────────────────────────────────────────────────────────
CREATE TABLE EMAIL_IGNORE_LIST (
    ID NUMBER(19) DEFAULT EMAIL_IGNORE_LIST_SEQ.NEXTVAL PRIMARY KEY,
    EMAIL_PATTERN VARCHAR2(300) NOT NULL,
    PATTERN_TYPE VARCHAR2(20) NOT NULL,
    REASON VARCHAR2(500),
    ADDED_BY VARCHAR2(100),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ── EXTRACTION RULES ─────────────────────────────────────────────────────────────
CREATE TABLE EXTRACTION_RULE (
    ID NUMBER(19) DEFAULT EXTRACTION_RULE_SEQ.NEXTVAL PRIMARY KEY,
    RULE_NAME VARCHAR2(200) NOT NULL,
    RULE_CODE VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(500),
    PATTERN_TYPE VARCHAR2(20) NOT NULL,
    PATTERN CLOB NOT NULL,
    TARGET_FIELD VARCHAR2(100) NOT NULL,
    EXTRACT_GROUP NUMBER(10),
    TRANSFORM VARCHAR2(50),
    PRIORITY NUMBER(10) DEFAULT 100,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    SOURCE_SCOPE VARCHAR2(20) NOT NULL,
    CREATED_BY VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_BY VARCHAR2(100),
    UPDATED_AT TIMESTAMP
);
CREATE INDEX IDX_RULE_ACTIVE_PRIORITY ON EXTRACTION_RULE(IS_ACTIVE, PRIORITY);
CREATE INDEX IDX_RULE_TARGET_FIELD ON EXTRACTION_RULE(TARGET_FIELD, IS_ACTIVE);

-- ── HOLIDAYS ─────────────────────────────────────────────────────────────────────
CREATE TABLE HOLIDAYS (
    ID NUMBER(19) DEFAULT HOLIDAYS_SEQ.NEXTVAL PRIMARY KEY,
    HOLIDAY_DATE DATE NOT NULL UNIQUE,
    NAME VARCHAR2(200),
    TYPE VARCHAR2(50),
    YEAR NUMBER(4) NOT NULL,
    IS_NATIONAL NUMBER(1) DEFAULT 1
);
CREATE INDEX IDX_HOLIDAY_DATE ON HOLIDAYS(HOLIDAY_DATE);
CREATE INDEX IDX_HOLIDAY_YEAR ON HOLIDAYS(YEAR);

-- ── RE RESPONSE TRACKER ──────────────────────────────────────────────────────────
CREATE TABLE RE_RESPONSE_TRACKER (
    ID NUMBER(19) DEFAULT RE_RESPONSE_TRACKER_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_ID NUMBER(19),
    REGULATED_ENTITY_ID NUMBER(19),
    FORWARDED_AT TIMESTAMP,
    RESPONDED_AT TIMESTAMP,
    WINDOW_DAYS NUMBER(10),
    WINDOW_EXPIRES_AT TIMESTAMP,
    BREACHED NUMBER(1) DEFAULT 0,
    EX_PARTE_ELIGIBLE NUMBER(1) DEFAULT 0,
    NOTES VARCHAR2(500)
);
CREATE INDEX IDX_RE_TRACKER_COMPLAINT ON RE_RESPONSE_TRACKER(COMPLAINT_ID);
CREATE INDEX IDX_RE_TRACKER_RE ON RE_RESPONSE_TRACKER(REGULATED_ENTITY_ID);
CREATE INDEX IDX_RE_TRACKER_BREACHED ON RE_RESPONSE_TRACKER(BREACHED);

-- ── TRANSLATION KEYS (populated by CSV at app startup) ───────────────────────────
CREATE TABLE TRANSLATION_KEYS (
    ID NUMBER(19) DEFAULT TRANSLATION_KEYS_SEQ.NEXTVAL PRIMARY KEY,
    CODE VARCHAR2(200) NOT NULL UNIQUE,
    MODULE VARCHAR2(50),
    DESCRIPTION VARCHAR2(500),
    DEFAULT_VALUE CLOB,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP
);
CREATE INDEX IDX_TKEY_CODE ON TRANSLATION_KEYS(CODE);
CREATE INDEX IDX_TKEY_MODULE ON TRANSLATION_KEYS(MODULE);

-- ── TRANSLATIONS (populated by CSV at app startup) ───────────────────────────────
CREATE TABLE TRANSLATIONS (
    ID NUMBER(19) DEFAULT TRANSLATIONS_SEQ.NEXTVAL PRIMARY KEY,
    TRANSLATION_KEY_ID NUMBER(19) NOT NULL,
    LOCALE VARCHAR2(10) NOT NULL,
    VALUE CLOB,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT UQ_TRANS_KEY_LOCALE UNIQUE (TRANSLATION_KEY_ID, LOCALE)
);
CREATE INDEX IDX_TRANS_LOCALE ON TRANSLATIONS(LOCALE);

-- ── SUPPORTED LOCALES ────────────────────────────────────────────────────────────
CREATE TABLE SUPPORTED_LOCALES (
    ID NUMBER(19) DEFAULT SUPPORTED_LOCALES_SEQ.NEXTVAL PRIMARY KEY,
    LOCALE_CODE VARCHAR2(10) NOT NULL UNIQUE,
    DISPLAY_NAME VARCHAR2(100) NOT NULL,
    IS_DEFAULT NUMBER(1) DEFAULT 0,
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

-- ── FORM CONFIG ──────────────────────────────────────────────────────────────────
CREATE TABLE FORM_CONFIG (
    ID NUMBER(19) DEFAULT FORM_CONFIG_SEQ.NEXTVAL PRIMARY KEY,
    FORM_KEY VARCHAR2(100) NOT NULL UNIQUE,
    FORM_JSON CLOB,
    VERSION NUMBER(10) DEFAULT 1,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 3: SEED DATA — BANKS (40 entities: Public, Private, Foreign, NBFC,
--            Payment Banks, Payment Systems, Card Networks)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- Public Sector Banks (11)
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'State Bank of India', 'SBI', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Punjab National Bank', 'PNB', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Bank of Baroda', 'BOB', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Canara Bank', 'CANARA', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Union Bank of India', 'UBI', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Bank of India', 'BOI', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Indian Bank', 'IB', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Central Bank of India', 'CBI', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Indian Overseas Bank', 'IOB', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'UCO Bank', 'UCO', 'PUBLIC_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Punjab & Sind Bank', 'PSB', 'PUBLIC_SECTOR', 'active');

-- Private Sector Banks (12)
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'HDFC Bank', 'HDFC', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'ICICI Bank', 'ICICI', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Axis Bank', 'AXIS', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Kotak Mahindra Bank', 'KOTAK', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'IndusInd Bank', 'INDUSIND', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Yes Bank', 'YES', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'IDBI Bank', 'IDBI', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Federal Bank', 'FEDERAL', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'South Indian Bank', 'SIB', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'RBL Bank', 'RBL', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Bandhan Bank', 'BANDHAN', 'PRIVATE_SECTOR', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'IDFC First Bank', 'IDFC', 'PRIVATE_SECTOR', 'active');

-- Foreign Banks (5)
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Citibank N.A.', 'CITI', 'FOREIGN', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'HSBC', 'HSBC', 'FOREIGN', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Standard Chartered Bank', 'SCB', 'FOREIGN', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Deutsche Bank', 'DB', 'FOREIGN', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Barclays Bank', 'BARCLAYS', 'FOREIGN', 'active');

-- Payment System Operators (1)
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'National Payments Corporation of India', 'NPCI', 'PAYMENT_SYSTEM', 'active');

-- Card Networks (3)
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Visa Inc.', 'VISA', 'CARD_NETWORK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Mastercard Inc.', 'MASTERCARD', 'CARD_NETWORK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'RuPay (NPCI)', 'RUPAY', 'CARD_NETWORK', 'active');

-- NBFCs (3)
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Bajaj Finance Ltd', 'BAJAJ_FIN', 'NBFC', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Muthoot Finance', 'MUTHOOT', 'NBFC', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Manappuram Finance', 'MANAPPURAM', 'NBFC', 'active');

-- Payment Banks (5)
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Paytm Payments Bank', 'PAYTM', 'PAYMENT_BANK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Airtel Payments Bank', 'AIRTEL', 'PAYMENT_BANK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'India Post Payments Bank', 'IPPB', 'PAYMENT_BANK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Jio Payments Bank', 'JIO', 'PAYMENT_BANK', 'active');
INSERT INTO BANKS (ID, NAME, CODE, TYPE, STATUS) VALUES (BANKS_SEQ.NEXTVAL, 'Fino Payments Bank', 'FINO', 'PAYMENT_BANK', 'active');


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 4: SEED DATA — COMPLAINT CATEGORIES (RB-IOS 2026 Grounds)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- Top-level categories
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'ATM/Debit Card', 'Issues related to ATM transactions and debit card usage', NULL, 'active', 1);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Credit Card', 'Issues related to credit card charges, billing, and services', NULL, 'active', 2);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'UPI/Mobile Banking', 'Issues related to UPI, BHIM, PhonePe, Google Pay transactions', NULL, 'active', 3);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'IMPS/NEFT/RTGS', 'Issues related to electronic fund transfers', NULL, 'active', 4);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Loan/Advance', 'Issues related to loans, EMIs, interest rates, prepayment penalties', NULL, 'active', 5);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Deposit Account', 'Issues related to savings, current, and fixed deposit accounts', NULL, 'active', 6);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Insurance', 'Issues related to mis-selling, claim rejection, policy lapses', NULL, 'active', 7);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Internet Banking', 'Issues related to net banking access, security, and transactions', NULL, 'active', 8);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'NACH/ECS/Mandate', 'Issues related to auto-debit mandates and recurring payments', NULL, 'active', 9);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Pension', 'Issues related to pension disbursement and delays', NULL, 'active', 10);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Remittance', 'Issues related to money transfer and foreign exchange', NULL, 'active', 11);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Staff Behaviour', 'Issues related to rude behaviour, non-cooperation by bank staff', NULL, 'active', 12);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'KYC/Account Opening', 'Issues related to KYC compliance, account opening/closure', NULL, 'active', 13);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Fraud/Unauthorized Transaction', 'Fraud, phishing, unauthorized debit, identity theft', NULL, 'active', 14);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Other', 'Issues not covered under above categories', NULL, 'active', 99);

-- Sub-categories for ATM/Debit Card (parent_id = 1)
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Cash not dispensed', 'ATM debited but cash not dispensed', 1, 'active', 1);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Card swallowed by ATM', 'ATM retained debit card', 1, 'active', 2);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Excess debit', 'Amount debited exceeds withdrawal amount', 1, 'active', 3);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'POS transaction failure', 'POS swipe deducted but merchant shows failure', 1, 'active', 4);

-- Sub-categories for UPI/Mobile Banking (parent_id = 3)
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'UPI transaction failed - amount debited', 'Money debited but not credited to beneficiary via UPI', 3, 'active', 1);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'UPI fraud', 'Unauthorized UPI collect/debit', 3, 'active', 2);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'UPI mandate issue', 'Auto-pay UPI mandate unauthorized debit', 3, 'active', 3);

-- Sub-categories for Credit Card (parent_id = 2)
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Unauthorized charges', 'Charge without consent on credit card', 2, 'active', 1);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Excessive interest/fees', 'Hidden fees or excessive charges', 2, 'active', 2);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Card not delivered', 'Card not received after approval', 2, 'active', 3);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Settlement/closure issues', 'Issues in closing credit card account', 2, 'active', 4);

-- Sub-categories for Loan/Advance (parent_id = 5)
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Recovery harassment', 'Harassment by recovery agents', 5, 'active', 1);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Excess interest charged', 'Higher interest than agreed', 5, 'active', 2);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Loan closure/NOC issues', 'Problems in loan closure or NOC', 5, 'active', 3);
INSERT INTO COMPLAINT_CATEGORIES (ID, NAME, DESCRIPTION, PARENT_ID, STATUS, SORT_ORDER) VALUES (COMPLAINT_CATEGORIES_SEQ.NEXTVAL, 'Unauthorized loan disbursement', 'Loan sanctioned without consent', 5, 'active', 4);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 5: SEED DATA — REGULATED ENTITIES
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'State Bank of India', 'STATE BANK OF INDIA', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Punjab National Bank', 'PUNJAB NATIONAL BANK', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'New Delhi', 'Delhi', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Bank of Baroda', 'BANK OF BARODA', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'Vadodara', 'Gujarat', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Canara Bank', 'CANARA BANK', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'Bengaluru', 'Karnataka', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Union Bank of India', 'UNION BANK OF INDIA', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'HDFC Bank', 'HDFC BANK', 'CEPC', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'ICICI Bank', 'ICICI BANK', 'CEPC', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Axis Bank', 'AXIS BANK', 'CEPC', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Kotak Mahindra Bank', 'KOTAK MAHINDRA BANK', 'CEPC', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'IndusInd Bank', 'INDUSIND BANK', 'CEPC', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Yes Bank', 'YES BANK', 'CEPC', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'IDBI Bank', 'IDBI BANK', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Federal Bank', 'FEDERAL BANK', 'RBIO', 'SCHEDULED_COMMERCIAL_BANK', 'Aluva', 'Kerala', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Citibank N.A.', 'CITIBANK NA', 'CEPC', 'FOREIGN_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'HSBC', 'HSBC', 'CEPC', 'FOREIGN_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Standard Chartered Bank', 'STANDARD CHARTERED BANK', 'CEPC', 'FOREIGN_BANK', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Bajaj Finance Ltd', 'BAJAJ FINANCE LTD', 'RBIO', 'NBFC', 'Pune', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Muthoot Finance', 'MUTHOOT FINANCE', 'RBIO', 'NBFC', 'Kochi', 'Kerala', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Paytm Payments Bank', 'PAYTM PAYMENTS BANK', 'CEPC', 'PAYMENT_BANK', 'Noida', 'Uttar Pradesh', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Airtel Payments Bank', 'AIRTEL PAYMENTS BANK', 'CEPC', 'PAYMENT_BANK', 'New Delhi', 'Delhi', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'India Post Payments Bank', 'INDIA POST PAYMENTS BANK', 'CEPC', 'PAYMENT_BANK', 'New Delhi', 'Delhi', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'National Payments Corporation of India', 'NATIONAL PAYMENTS CORPORATION OF INDIA', 'CEPC', 'PAYMENT_SYSTEM_OPERATOR', 'Mumbai', 'Maharashtra', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'PhonePe Private Limited', 'PHONEPE PRIVATE LIMITED', 'CEPC', 'PAYMENT_AGGREGATOR', 'Bengaluru', 'Karnataka', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Google Pay (Google India Digital Services)', 'GOOGLE PAY', 'CEPC', 'PAYMENT_AGGREGATOR', 'Bengaluru', 'Karnataka', 'active');
INSERT INTO REGULATED_ENTITIES (ID, NAME, NAME_NORMALIZED, DEPARTMENT, ENTITY_TYPE, CITY, STATE, STATUS) VALUES (REGULATED_ENTITIES_SEQ.NEXTVAL, 'Razorpay Software Private Limited', 'RAZORPAY SOFTWARE PRIVATE LIMITED', 'CEPC', 'PAYMENT_AGGREGATOR', 'Bengaluru', 'Karnataka', 'active');


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 6: SEED DATA — HOLIDAYS 2026-2027 (RBI & National Holidays)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- 2026 Holidays
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-01-26', 'Republic Day', 'NATIONAL', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-03-10', 'Maha Shivaratri', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-03-14', 'Holi', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-03-30', 'Id-ul-Fitr', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-04-03', 'Good Friday', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-04-06', 'Ram Navami', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-04-14', 'Dr. Ambedkar Jayanti', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-05-01', 'May Day', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-05-24', 'Buddha Purnima', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-06-07', 'Id-ul-Zuha (Bakrid)', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-07-06', 'Muharram', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-08-15', 'Independence Day', 'NATIONAL', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-08-16', 'Janmashtami', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-09-04', 'Milad-un-Nabi', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-10-02', 'Mahatma Gandhi Jayanti', 'NATIONAL', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-10-20', 'Dussehra', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-11-09', 'Diwali (Lakshmi Puja)', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-11-10', 'Diwali (Govardhan Puja)', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-11-24', 'Guru Nanak Jayanti', 'GAZETTED', 2026, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2026-12-25', 'Christmas', 'GAZETTED', 2026, 1);

-- 2027 Holidays
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-01-26', 'Republic Day', 'NATIONAL', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-03-01', 'Maha Shivaratri', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-03-04', 'Holi', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-03-19', 'Id-ul-Fitr', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-03-26', 'Good Friday', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-04-14', 'Dr. Ambedkar Jayanti', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-05-01', 'May Day', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-05-13', 'Buddha Purnima', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-05-27', 'Id-ul-Zuha (Bakrid)', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-06-26', 'Muharram', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-08-15', 'Independence Day', 'NATIONAL', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-08-25', 'Milad-un-Nabi', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-10-02', 'Mahatma Gandhi Jayanti', 'NATIONAL', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-10-08', 'Dussehra', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-10-28', 'Diwali', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-11-14', 'Guru Nanak Jayanti', 'GAZETTED', 2027, 1);
INSERT INTO HOLIDAYS (ID, HOLIDAY_DATE, NAME, TYPE, YEAR, IS_NATIONAL) VALUES (HOLIDAYS_SEQ.NEXTVAL, DATE '2027-12-25', 'Christmas', 'GAZETTED', 2027, 1);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 7: SEED DATA — SUPPORTED LOCALES
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'en', 'English', 1, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'hi', 'Hindi', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'mr', 'Marathi', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'ta', 'Tamil', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'te', 'Telugu', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'kn', 'Kannada', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'bn', 'Bengali', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'gu', 'Gujarati', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'ml', 'Malayalam', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'pa', 'Punjabi', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'or', 'Odia', 0, 1);
INSERT INTO SUPPORTED_LOCALES (ID, LOCALE_CODE, DISPLAY_NAME, IS_DEFAULT, IS_ACTIVE) VALUES (SUPPORTED_LOCALES_SEQ.NEXTVAL, 'as', 'Assamese', 0, 1);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 8: SEED DATA — COMMUNICATION TEMPLATES
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO COMMUNICATION_TEMPLATES (ID, TEMPLATE_NAME, MODE, TRIGGER_CONDITION, SCHEME_VERSION, SUBJECT_TEMPLATE, BODY_TEMPLATE, DESCRIPTION, CATEGORY, ACTIVE, CREATED_BY) VALUES (
    COMMUNICATION_TEMPLATES_SEQ.NEXTVAL,
    'New Complaint Acknowledgement - Email', 'EMAIL', 'NEW_COMPLAINT_ACK', 'BOTH',
    'Acknowledgement: Your complaint {{complaintNumber}} has been registered',
    'Dear {{complainantName}},' || CHR(10) || CHR(10) || 'This is to acknowledge receipt of your complaint bearing reference number {{complaintNumber}}.' || CHR(10) || CHR(10) || 'Subject: {{subject}}' || CHR(10) || 'Date of Registration: {{currentDate}}' || CHR(10) || CHR(10) || 'Your complaint is being examined and you will be informed of the outcome in due course.' || CHR(10) || CHR(10) || 'Regards,' || CHR(10) || 'CRPC Cell' || CHR(10) || 'Reserve Bank of India',
    'Sent automatically when a new complaint is registered', 'ACKNOWLEDGEMENT', 1, 'SYSTEM');

INSERT INTO COMMUNICATION_TEMPLATES (ID, TEMPLATE_NAME, MODE, TRIGGER_CONDITION, SCHEME_VERSION, SUBJECT_TEMPLATE, BODY_TEMPLATE, DESCRIPTION, CATEGORY, ACTIVE, CREATED_BY) VALUES (
    COMMUNICATION_TEMPLATES_SEQ.NEXTVAL,
    'New Complaint Acknowledgement - SMS', 'SMS', 'NEW_COMPLAINT_ACK', 'BOTH',
    'CMS Alert',
    'Dear {{complainantName}}, Your complaint {{complaintNumber}} has been registered with RBI. Track at: cms.rbi.org.in/track/{{complaintNumber}}',
    'SMS acknowledgement for new complaint', 'ACKNOWLEDGEMENT', 1, 'SYSTEM');

INSERT INTO COMMUNICATION_TEMPLATES (ID, TEMPLATE_NAME, MODE, TRIGGER_CONDITION, SCHEME_VERSION, SUBJECT_TEMPLATE, BODY_TEMPLATE, DESCRIPTION, CATEGORY, ACTIVE, CREATED_BY) VALUES (
    COMMUNICATION_TEMPLATES_SEQ.NEXTVAL,
    'Closure Communication - RBIOS 2026 - Email', 'EMAIL', 'CLOSURE', 'RBIOS_2026',
    'Closure of Complaint {{complaintNumber}}',
    'Dear {{complainantName}},' || CHR(10) || CHR(10) || 'Ref: Complaint No. {{complaintNumber}}' || CHR(10) || 'Subject: {{subject}}' || CHR(10) || CHR(10) || 'With reference to the above complaint, we wish to inform you that the same has been examined and is being closed on {{closureDate}}.' || CHR(10) || CHR(10) || 'The Regulated Entity ({{bankName}}) has provided a satisfactory resolution.' || CHR(10) || CHR(10) || 'If you are not satisfied with the resolution, you may file an appeal with the Appellate Authority within 30 days of this communication.' || CHR(10) || CHR(10) || 'For filing an appeal, please visit: cms.rbi.org.in/public/appeal' || CHR(10) || CHR(10) || 'Yours faithfully,' || CHR(10) || 'CRPC Cell' || CHR(10) || 'Reserve Bank of India',
    'Closure letter for RBIOS 2026 scheme complaints via email', 'CLOSURE', 1, 'SYSTEM');

INSERT INTO COMMUNICATION_TEMPLATES (ID, TEMPLATE_NAME, MODE, TRIGGER_CONDITION, SCHEME_VERSION, SUBJECT_TEMPLATE, BODY_TEMPLATE, DESCRIPTION, CATEGORY, ACTIVE, CREATED_BY) VALUES (
    COMMUNICATION_TEMPLATES_SEQ.NEXTVAL,
    'Closure Communication - RBIOS 2026 - Letter', 'LETTER', 'CLOSURE', 'RBIOS_2026',
    'Closure of Complaint {{complaintNumber}} - Official Communication',
    'RESERVE BANK OF INDIA' || CHR(10) || 'Complaint Resolution & Process Cell' || CHR(10) || CHR(10) || 'Ref: {{complaintNumber}}' || CHR(10) || 'Date: {{currentDate}}' || CHR(10) || CHR(10) || 'To,' || CHR(10) || '{{complainantName}}' || CHR(10) || '{{complainantAddress}}' || CHR(10) || CHR(10) || 'Subject: Closure of your complaint regarding {{subject}}' || CHR(10) || CHR(10) || 'Dear Sir/Madam,' || CHR(10) || CHR(10) || 'With reference to your complaint bearing number {{complaintNumber}} filed against {{bankName}}, this is to inform you that after due examination, the matter has been resolved satisfactorily.' || CHR(10) || CHR(10) || 'The complaint is being closed with effect from {{closureDate}}.' || CHR(10) || CHR(10) || 'You may file an appeal within 30 days if not satisfied with the resolution.' || CHR(10) || CHR(10) || 'Yours faithfully,' || CHR(10) || CHR(10) || '(Authorized Signatory)' || CHR(10) || 'CRPC Cell, Reserve Bank of India',
    'Formal closure letter for physical post', 'CLOSURE', 1, 'SYSTEM');

INSERT INTO COMMUNICATION_TEMPLATES (ID, TEMPLATE_NAME, MODE, TRIGGER_CONDITION, SCHEME_VERSION, SUBJECT_TEMPLATE, BODY_TEMPLATE, DESCRIPTION, CATEGORY, ACTIVE, CREATED_BY) VALUES (
    COMMUNICATION_TEMPLATES_SEQ.NEXTVAL,
    'CRPC Rejection - Insufficient Details', 'EMAIL', 'INSUFFICIENT_DETAILS', 'BOTH',
    'Additional information required for complaint {{complaintNumber}}',
    'Dear {{complainantName}},' || CHR(10) || CHR(10) || 'With reference to your complaint {{complaintNumber}}, we require additional details to process your complaint.' || CHR(10) || CHR(10) || 'Please provide the following:' || CHR(10) || '1. Complete account details (account number and branch)' || CHR(10) || '2. Transaction reference numbers' || CHR(10) || '3. Date(s) of disputed transaction' || CHR(10) || '4. Supporting documents (screenshots, statements)' || CHR(10) || CHR(10) || 'Please reply to this email with the required information within 15 days. Failure to provide the information may result in closure of the complaint.' || CHR(10) || CHR(10) || 'Regards,' || CHR(10) || 'CRPC Cell' || CHR(10) || 'Reserve Bank of India',
    'Sent when complaint lacks sufficient details', 'NOTIFICATION', 1, 'SYSTEM');

INSERT INTO COMMUNICATION_TEMPLATES (ID, TEMPLATE_NAME, MODE, TRIGGER_CONDITION, SCHEME_VERSION, SUBJECT_TEMPLATE, BODY_TEMPLATE, DESCRIPTION, CATEGORY, ACTIVE, CREATED_BY) VALUES (
    COMMUNICATION_TEMPLATES_SEQ.NEXTVAL,
    'Sent to Other Regulator', 'EMAIL', 'SENT_TO_OTHER_REG', 'BOTH',
    'Your complaint {{complaintNumber}} - Forwarded to appropriate authority',
    'Dear {{complainantName}},' || CHR(10) || CHR(10) || 'Your complaint {{complaintNumber}} pertaining to "{{subject}}" has been examined.' || CHR(10) || CHR(10) || 'Upon review, we find that the matter does not fall under the regulatory jurisdiction of the Reserve Bank of India. Accordingly, the same has been forwarded to the appropriate regulatory authority for necessary action.' || CHR(10) || CHR(10) || 'You may also directly approach the concerned authority for expeditious resolution.' || CHR(10) || CHR(10) || 'Regards,' || CHR(10) || 'CRPC Cell' || CHR(10) || 'Reserve Bank of India',
    'Sent when complaint is forwarded to another regulator (SEBI/IRDAI/PFRDA)', 'NOTIFICATION', 1, 'SYSTEM');

INSERT INTO COMMUNICATION_TEMPLATES (ID, TEMPLATE_NAME, MODE, TRIGGER_CONDITION, SCHEME_VERSION, SUBJECT_TEMPLATE, BODY_TEMPLATE, DESCRIPTION, CATEGORY, ACTIVE, CREATED_BY) VALUES (
    COMMUNICATION_TEMPLATES_SEQ.NEXTVAL,
    'Forwarded to RE - Response Required', 'EMAIL', 'FORWARDED_TO_RE', 'BOTH',
    'CMS Complaint {{complaintNumber}} - Response Required within 30 days',
    'Dear Nodal Officer,' || CHR(10) || CHR(10) || 'A complaint has been received against your institution. Details below:' || CHR(10) || CHR(10) || 'Complaint No: {{complaintNumber}}' || CHR(10) || 'Complainant: {{complainantName}}' || CHR(10) || 'Subject: {{subject}}' || CHR(10) || 'Date Filed: {{currentDate}}' || CHR(10) || CHR(10) || 'You are requested to look into the matter and submit your response/resolution within 30 days from the date of this communication.' || CHR(10) || CHR(10) || 'Please log in to the RE Portal at cms.rbi.org.in/re-portal to submit your response.' || CHR(10) || CHR(10) || 'Regards,' || CHR(10) || 'CRPC Cell' || CHR(10) || 'Reserve Bank of India',
    'Sent to Regulated Entity when complaint is forwarded', 'NOTIFICATION', 1, 'SYSTEM');


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 9: SEED DATA — COMMENT TEMPLATES
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO COMMENT_TEMPLATES (ID, TITLE, DESCRIPTION, CONTENT, MODE_OF_RECEIPT, CATEGORY, ACTIVE, CREATED_BY) VALUES (COMMENT_TEMPLATES_SEQ.NEXTVAL, 'Standard Closure - Resolved by Bank', 'Used when bank has satisfactorily resolved the issue', 'The complaint has been examined. The Regulated Entity has provided a satisfactory resolution and the complainant has been informed accordingly. Closing the complaint.', 'ALL', 'CLOSURE', 1, 'SYSTEM');
INSERT INTO COMMENT_TEMPLATES (ID, TITLE, DESCRIPTION, CONTENT, MODE_OF_RECEIPT, CATEGORY, ACTIVE, CREATED_BY) VALUES (COMMENT_TEMPLATES_SEQ.NEXTVAL, 'Closure - No response from complainant', 'Used when complainant does not respond within 15 days', 'Additional information was sought from the complainant vide our communication dated [DATE]. No response has been received within the stipulated period of 15 days. In the absence of required details, the complaint is being closed.', 'ALL', 'CLOSURE', 1, 'SYSTEM');
INSERT INTO COMMENT_TEMPLATES (ID, TITLE, DESCRIPTION, CONTENT, MODE_OF_RECEIPT, CATEGORY, ACTIVE, CREATED_BY) VALUES (COMMENT_TEMPLATES_SEQ.NEXTVAL, 'Closure - Out of RBI jurisdiction', 'Used for complaints not under RBI purview', 'The complaint has been examined. The subject matter does not fall within the regulatory jurisdiction of RBI under the applicable scheme. The complainant has been advised to approach the appropriate forum.', 'ALL', 'CLOSURE', 1, 'SYSTEM');
INSERT INTO COMMENT_TEMPLATES (ID, TITLE, DESCRIPTION, CONTENT, MODE_OF_RECEIPT, CATEGORY, ACTIVE, CREATED_BY) VALUES (COMMENT_TEMPLATES_SEQ.NEXTVAL, 'Not-a-Complaint - Spam/Promotional', 'For spam or irrelevant emails', 'This email is identified as spam/promotional content and does not constitute a valid complaint under the Banking Ombudsman Scheme. Marking as Not-a-Complaint.', 'EMAIL', 'REJECTION', 1, 'SYSTEM');
INSERT INTO COMMENT_TEMPLATES (ID, TITLE, DESCRIPTION, CONTENT, MODE_OF_RECEIPT, CATEGORY, ACTIVE, CREATED_BY) VALUES (COMMENT_TEMPLATES_SEQ.NEXTVAL, 'Not-a-Complaint - Auto-reply', 'For automated email responses', 'This is an automated reply (out-of-office/delivery notification) and does not constitute a complaint. Marking as Not-a-Complaint.', 'EMAIL', 'REJECTION', 1, 'SYSTEM');
INSERT INTO COMMENT_TEMPLATES (ID, TITLE, DESCRIPTION, CONTENT, MODE_OF_RECEIPT, CATEGORY, ACTIVE, CREATED_BY) VALUES (COMMENT_TEMPLATES_SEQ.NEXTVAL, 'Not-a-Complaint - Internal Communication', 'For internal/bank-to-bank emails', 'This email is an internal communication and does not represent a customer complaint. Marking as Not-a-Complaint.', 'EMAIL', 'REJECTION', 1, 'SYSTEM');
INSERT INTO COMMENT_TEMPLATES (ID, TITLE, DESCRIPTION, CONTENT, MODE_OF_RECEIPT, CATEGORY, ACTIVE, CREATED_BY) VALUES (COMMENT_TEMPLATES_SEQ.NEXTVAL, 'Follow-up Pending from Complainant', 'When awaiting response from complainant', 'Additional details/documents have been requested from the complainant via [EMAIL/LETTER]. Awaiting response. Will follow up if no response received within 15 days.', 'ALL', 'FOLLOWUP', 1, 'SYSTEM');
INSERT INTO COMMENT_TEMPLATES (ID, TITLE, DESCRIPTION, CONTENT, MODE_OF_RECEIPT, CATEGORY, ACTIVE, CREATED_BY) VALUES (COMMENT_TEMPLATES_SEQ.NEXTVAL, 'Follow-up - RE Response Pending', 'When waiting for bank/NBFC response', 'Complaint has been forwarded to the Regulated Entity for response. RE has been given 30 days to respond. Will escalate if no response received within the stipulated time.', 'ALL', 'FOLLOWUP', 1, 'SYSTEM');
INSERT INTO COMMENT_TEMPLATES (ID, TITLE, DESCRIPTION, CONTENT, MODE_OF_RECEIPT, CATEGORY, ACTIVE, CREATED_BY) VALUES (COMMENT_TEMPLATES_SEQ.NEXTVAL, 'Standard Forward to Reviewer', 'DEO forwards to reviewer with assessment', 'Assessment completed. All mandatory fields populated. Entity identified. Category and mode of receipt confirmed. Complainant details verified. Forwarding to reviewer for approval.', 'ALL', 'GENERAL', 1, 'SYSTEM');
INSERT INTO COMMENT_TEMPLATES (ID, TITLE, DESCRIPTION, CONTENT, MODE_OF_RECEIPT, CATEGORY, ACTIVE, CREATED_BY) VALUES (COMMENT_TEMPLATES_SEQ.NEXTVAL, 'Duplicate Complaint Identified', 'When complaint appears to be duplicate', 'This appears to be a duplicate of complaint [NUMBER]. Same complainant, same subject matter, filed within the same period. Recommending marking as duplicate.', 'ALL', 'GENERAL', 1, 'SYSTEM');
INSERT INTO COMMENT_TEMPLATES (ID, TITLE, DESCRIPTION, CONTENT, MODE_OF_RECEIPT, CATEGORY, ACTIVE, CREATED_BY) VALUES (COMMENT_TEMPLATES_SEQ.NEXTVAL, 'Insufficient Details - Physical Letter', 'For physical letters with incomplete info', 'The physical letter received does not contain sufficient details for processing (missing: account number / bank branch / contact details / address for correspondence). Requesting additional information from complainant.', 'PHYSICAL_LETTER', 'REJECTION', 1, 'SYSTEM');
INSERT INTO COMMENT_TEMPLATES (ID, TITLE, DESCRIPTION, CONTENT, MODE_OF_RECEIPT, CATEGORY, ACTIVE, CREATED_BY) VALUES (COMMENT_TEMPLATES_SEQ.NEXTVAL, 'CPGRAMS Referral', 'For complaints referred from CPGRAMS portal', 'Complaint received via CPGRAMS referral. CPGRAMS reference number noted. Proceeding with standard assessment process.', 'ALL', 'GENERAL', 1, 'SYSTEM');


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 10: SEED DATA — EMAIL IGNORE LIST
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO EMAIL_IGNORE_LIST (ID, EMAIL_PATTERN, PATTERN_TYPE, REASON, ADDED_BY, IS_ACTIVE) VALUES (EMAIL_IGNORE_LIST_SEQ.NEXTVAL, 'noreply@*', 'WILDCARD', 'No-reply addresses are automated', 'SYSTEM', 1);
INSERT INTO EMAIL_IGNORE_LIST (ID, EMAIL_PATTERN, PATTERN_TYPE, REASON, ADDED_BY, IS_ACTIVE) VALUES (EMAIL_IGNORE_LIST_SEQ.NEXTVAL, 'no-reply@*', 'WILDCARD', 'No-reply addresses are automated', 'SYSTEM', 1);
INSERT INTO EMAIL_IGNORE_LIST (ID, EMAIL_PATTERN, PATTERN_TYPE, REASON, ADDED_BY, IS_ACTIVE) VALUES (EMAIL_IGNORE_LIST_SEQ.NEXTVAL, 'mailer-daemon@*', 'WILDCARD', 'Mail delivery failure notifications', 'SYSTEM', 1);
INSERT INTO EMAIL_IGNORE_LIST (ID, EMAIL_PATTERN, PATTERN_TYPE, REASON, ADDED_BY, IS_ACTIVE) VALUES (EMAIL_IGNORE_LIST_SEQ.NEXTVAL, 'postmaster@*', 'WILDCARD', 'Mail system notifications', 'SYSTEM', 1);
INSERT INTO EMAIL_IGNORE_LIST (ID, EMAIL_PATTERN, PATTERN_TYPE, REASON, ADDED_BY, IS_ACTIVE) VALUES (EMAIL_IGNORE_LIST_SEQ.NEXTVAL, '*@spam.com', 'WILDCARD', 'Known spam domain', 'SYSTEM', 1);
INSERT INTO EMAIL_IGNORE_LIST (ID, EMAIL_PATTERN, PATTERN_TYPE, REASON, ADDED_BY, IS_ACTIVE) VALUES (EMAIL_IGNORE_LIST_SEQ.NEXTVAL, 'notifications@linkedin.com', 'EXACT', 'LinkedIn notifications', 'SYSTEM', 1);
INSERT INTO EMAIL_IGNORE_LIST (ID, EMAIL_PATTERN, PATTERN_TYPE, REASON, ADDED_BY, IS_ACTIVE) VALUES (EMAIL_IGNORE_LIST_SEQ.NEXTVAL, '*@newsletter.*', 'WILDCARD', 'Newsletter emails', 'SYSTEM', 1);
INSERT INTO EMAIL_IGNORE_LIST (ID, EMAIL_PATTERN, PATTERN_TYPE, REASON, ADDED_BY, IS_ACTIVE) VALUES (EMAIL_IGNORE_LIST_SEQ.NEXTVAL, 'donotreply@*', 'WILDCARD', 'Auto-generated emails', 'SYSTEM', 1);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 11: SEED DATA — EXTRACTION RULES (OCR Field Extraction)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO EXTRACTION_RULE (ID, RULE_NAME, RULE_CODE, DESCRIPTION, PATTERN_TYPE, PATTERN, TARGET_FIELD, EXTRACT_GROUP, PRIORITY, IS_ACTIVE, SOURCE_SCOPE, CREATED_BY) VALUES (EXTRACTION_RULE_SEQ.NEXTVAL, 'Phone Number Extraction', 'PHONE_10DIGIT', 'Extracts 10-digit Indian phone numbers', 'REGEX', '(?:(?:\+91|91|0)?[\s-]?)([6-9]\d{9})', 'complainantPhone', 1, 10, 1, 'BODY', 'SYSTEM');
INSERT INTO EXTRACTION_RULE (ID, RULE_NAME, RULE_CODE, DESCRIPTION, PATTERN_TYPE, PATTERN, TARGET_FIELD, EXTRACT_GROUP, PRIORITY, IS_ACTIVE, SOURCE_SCOPE, CREATED_BY) VALUES (EXTRACTION_RULE_SEQ.NEXTVAL, 'Email Address Extraction', 'EMAIL_EXTRACT', 'Extracts email addresses from body', 'REGEX', '([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})', 'complainantEmail', 1, 20, 1, 'BODY', 'SYSTEM');
INSERT INTO EXTRACTION_RULE (ID, RULE_NAME, RULE_CODE, DESCRIPTION, PATTERN_TYPE, PATTERN, TARGET_FIELD, EXTRACT_GROUP, PRIORITY, IS_ACTIVE, SOURCE_SCOPE, CREATED_BY) VALUES (EXTRACTION_RULE_SEQ.NEXTVAL, 'Account Number Extraction', 'ACCOUNT_NUM', 'Extracts bank account numbers (9-18 digits)', 'REGEX', '(?:a/c|account|acct)[\s.:]*#?\s*(\d{9,18})', 'accountNumber', 1, 30, 1, 'BODY', 'SYSTEM');
INSERT INTO EXTRACTION_RULE (ID, RULE_NAME, RULE_CODE, DESCRIPTION, PATTERN_TYPE, PATTERN, TARGET_FIELD, EXTRACT_GROUP, PRIORITY, IS_ACTIVE, SOURCE_SCOPE, CREATED_BY) VALUES (EXTRACTION_RULE_SEQ.NEXTVAL, 'IFSC Code Extraction', 'IFSC_CODE', 'Extracts IFSC codes', 'REGEX', '(?:IFSC|ifsc)[\s.:]*([A-Z]{4}0[A-Z0-9]{6})', 'ifscCode', 1, 40, 1, 'BODY', 'SYSTEM');
INSERT INTO EXTRACTION_RULE (ID, RULE_NAME, RULE_CODE, DESCRIPTION, PATTERN_TYPE, PATTERN, TARGET_FIELD, EXTRACT_GROUP, PRIORITY, IS_ACTIVE, SOURCE_SCOPE, CREATED_BY) VALUES (EXTRACTION_RULE_SEQ.NEXTVAL, 'PAN Card Extraction', 'PAN_EXTRACT', 'Extracts PAN card numbers', 'REGEX', '(?:PAN|pan)[\s.:]*([A-Z]{5}\d{4}[A-Z])', 'panNumber', 1, 50, 1, 'BODY', 'SYSTEM');
INSERT INTO EXTRACTION_RULE (ID, RULE_NAME, RULE_CODE, DESCRIPTION, PATTERN_TYPE, PATTERN, TARGET_FIELD, EXTRACT_GROUP, PRIORITY, IS_ACTIVE, SOURCE_SCOPE, CREATED_BY) VALUES (EXTRACTION_RULE_SEQ.NEXTVAL, 'Pincode Extraction', 'PINCODE_EXTRACT', 'Extracts 6-digit Indian pincodes', 'REGEX', '(?:pin|pincode|pin code|zip)[\s.:]*([1-9]\d{5})', 'complainantPincode', 1, 60, 1, 'BODY', 'SYSTEM');
INSERT INTO EXTRACTION_RULE (ID, RULE_NAME, RULE_CODE, DESCRIPTION, PATTERN_TYPE, PATTERN, TARGET_FIELD, EXTRACT_GROUP, PRIORITY, IS_ACTIVE, SOURCE_SCOPE, CREATED_BY) VALUES (EXTRACTION_RULE_SEQ.NEXTVAL, 'CPGRAMS Number', 'CPGRAMS_REF', 'Extracts CPGRAMS reference numbers', 'REGEX', '(?:CPGRAM|cpgram)[S]?[\s.:/#]*([A-Z0-9/-]+)', 'cpgramsNumber', 1, 70, 1, 'SUBJECT', 'SYSTEM');
INSERT INTO EXTRACTION_RULE (ID, RULE_NAME, RULE_CODE, DESCRIPTION, PATTERN_TYPE, PATTERN, TARGET_FIELD, EXTRACT_GROUP, PRIORITY, IS_ACTIVE, SOURCE_SCOPE, CREATED_BY) VALUES (EXTRACTION_RULE_SEQ.NEXTVAL, 'Amount Extraction', 'AMOUNT_INR', 'Extracts Indian Rupee amounts', 'REGEX', '(?:Rs\.?|INR|\u20B9)[\s]*(\d{1,3}(?:,\d{2,3})*(?:\.\d{1,2})?)', 'amountInvolved', 1, 80, 1, 'BODY', 'SYSTEM');
INSERT INTO EXTRACTION_RULE (ID, RULE_NAME, RULE_CODE, DESCRIPTION, PATTERN_TYPE, PATTERN, TARGET_FIELD, EXTRACT_GROUP, PRIORITY, IS_ACTIVE, SOURCE_SCOPE, CREATED_BY) VALUES (EXTRACTION_RULE_SEQ.NEXTVAL, 'Date Extraction (DD/MM/YYYY)', 'DATE_DDMMYYYY', 'Extracts dates in DD/MM/YYYY format', 'REGEX', '(\d{2}[/-]\d{2}[/-]\d{4})', 'transactionDate', 1, 90, 1, 'BODY', 'SYSTEM');
INSERT INTO EXTRACTION_RULE (ID, RULE_NAME, RULE_CODE, DESCRIPTION, PATTERN_TYPE, PATTERN, TARGET_FIELD, EXTRACT_GROUP, PRIORITY, IS_ACTIVE, SOURCE_SCOPE, CREATED_BY) VALUES (EXTRACTION_RULE_SEQ.NEXTVAL, 'Name from Salutation', 'NAME_SALUTATION', 'Extracts name after greeting', 'REGEX', '(?:Dear|Respected|To|Shri|Smt|Mr|Mrs|Ms)\.?\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,3})', 'complainantName', 1, 100, 1, 'BODY', 'SYSTEM');


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 12: SEED DATA — FORM CONFIG (Complaint Filing Form)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO FORM_CONFIG (ID, FORM_KEY, FORM_JSON, VERSION, IS_ACTIVE) VALUES (FORM_CONFIG_SEQ.NEXTVAL, 'complaint_filing_v1',
'{"formId":"complaint_filing_v1","title":"File a Complaint","sections":[{"id":"personal","title":"Personal Details","fields":[{"name":"complainantName","type":"text","label":"Full Name","required":true,"maxLength":200},{"name":"complainantEmail","type":"email","label":"Email Address","required":true},{"name":"complainantPhone","type":"tel","label":"Mobile Number","required":true,"pattern":"^[6-9]\\d{9}$"},{"name":"complainantAddress","type":"textarea","label":"Address","required":false}]},{"id":"entity","title":"Regulated Entity Details","fields":[{"name":"entityType","type":"select","label":"Entity Type","required":true,"options":["Bank","NBFC","Payment System"]},{"name":"bankId","type":"autocomplete","label":"Entity Name","required":true},{"name":"bankBranch","type":"text","label":"Branch","required":false},{"name":"accountNumber","type":"text","label":"Account/Card Number","required":false}]},{"id":"complaint","title":"Complaint Details","fields":[{"name":"categoryId","type":"select","label":"Nature of Complaint","required":true},{"name":"subject","type":"text","label":"Subject","required":true,"maxLength":500},{"name":"description","type":"richtext","label":"Description","required":true},{"name":"reliefSought","type":"textarea","label":"Relief Sought","required":true}]},{"id":"prior_re","title":"Prior Complaint to Entity","fields":[{"name":"priorReComplaint","type":"radio","label":"Did you first complain to the entity?","required":true,"options":["Yes","No"]},{"name":"reComplaintDate","type":"date","label":"Date of complaint to entity","required":false,"showIf":"priorReComplaint==Yes"},{"name":"reComplaintReference","type":"text","label":"Reference number","required":false},{"name":"reRepliedAndDissatisfied","type":"radio","label":"Did entity reply and you are dissatisfied?","required":false,"options":["Yes","No"]},{"name":"reLastCommunicationDate","type":"date","label":"Date of last communication","required":false}]}]}',
1, 1);


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 13: SAMPLE COMPLAINTS (for testing MRE assessment)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- Complaint 1: MAINTAINABLE - All conditions met
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, COMPLAINANT_ADDRESS, BANK_ID, BANK_BRANCH, ACCOUNT_NUMBER, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ASSIGNED_OFFICER, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, RE_LAST_COMMUNICATION_DATE, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/MUM/000001', 'Rajesh Kumar', 'rajesh.kumar@gmail.com', '9876543210', '42, MG Road, Andheri West, Mumbai 400058', 1, 'Andheri West Branch', '30129876543', 1, 'ATM cash not dispensed - Rs 10000 debited',
'I attempted to withdraw Rs 10,000 from SBI ATM at Andheri West on 01-May-2026. The machine showed transaction successful but no cash was dispensed. Amount has been debited from my account. I have the ATM slip.',
'Immediate reversal of Rs 10,000 and compensation for mental harassment', 'in_progress', 'HIGH', 'ONLINE', 'RBIO', 'RBIO_OFFICER', 'officer.rbio1', 'SBI', 'ASSESSMENT',
1, DATE '2026-05-02', 'SBI/CMP/2026/45678', 1, DATE '2026-05-20', 0, 'GREEN', TIMESTAMP '2026-06-02 10:30:00');

-- Complaint 2: NON-MAINTAINABLE - Filed before window (no 30-day wait)
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, COMPLAINANT_ADDRESS, BANK_ID, BANK_BRANCH, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ASSIGNED_OFFICER, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/DEL/000002', 'Priya Sharma', 'priya.sharma@yahoo.com', '9988776655', 'B-15, Saket, New Delhi 110017', 2, 'Saket Branch', 5, 'Excess EMI charged on home loan',
'PNB has been charging excess EMI of Rs 2,500 per month since January 2026 despite the RBI repo rate cut. I complained to the bank 5 days ago and have not waited for their response.',
'Refund of excess EMI charged and correction of interest rate', 'pending', 'MEDIUM', 'ONLINE', 'RBIO', 'RBIO_OFFICER', 'officer.rbio1', 'PNB', 'TRIAGE',
1, DATE '2026-06-25', 'PNB/LOAN/2026/789', 0, 0, 'RED', TIMESTAMP '2026-06-28 14:20:00');

-- Complaint 3: NON-MAINTAINABLE - No prior RE complaint
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, BANK_ID, BANK_BRANCH, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ASSIGNED_OFFICER, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/BLR/000003', 'Suresh Reddy', 'suresh.r@outlook.com', '8877665544', 12, 'Whitefield Branch', 3, 'UPI payment failed but money debited',
'I made a UPI payment of Rs 5,000 via Google Pay to a merchant but the transaction failed. Money was debited from my HDFC account but not credited to merchant. I have not complained to HDFC yet.',
'Immediate reversal of Rs 5,000', 'pending', 'MEDIUM', 'ONLINE', 'CEPC', 'CEPC_DO', 'officer.cepc1', 'HDFC', 'TRIAGE',
0, 0, 'RED', TIMESTAMP '2026-06-30 09:15:00');

-- Complaint 4: MAINTAINABLE - RE replied and dissatisfied
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, COMPLAINANT_ADDRESS, BANK_ID, BANK_BRANCH, ACCOUNT_NUMBER, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ASSIGNED_OFFICER, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, RE_LAST_COMMUNICATION_DATE, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/CHN/000004', 'Lakshmi Venkatesh', 'lakshmi.v@gmail.com', '9123456780', '12, Anna Nagar, Chennai 600040', 13, 'Anna Nagar Branch', '0012345678', 2, 'Unauthorized credit card charges of Rs 15,000',
'ICICI Bank has levied unauthorized charges of Rs 15,000 on my credit card. I complained to the bank on 10-Apr-2026 and received an unsatisfactory response on 20-Apr-2026 refusing refund. The charges are for a subscription I never authorized.',
'Full refund of Rs 15,000 and compensation for harassment', 'in_progress', 'HIGH', 'ONLINE', 'CEPC', 'CEPC_DO', 'officer.cepc1', 'ICICI', 'ASSESSMENT',
1, DATE '2026-04-10', 'ICICI/CC/2026/34567', 1, DATE '2026-04-20', 0, 'GREEN', TIMESTAMP '2026-05-15 11:00:00');

-- Complaint 5: NON-MAINTAINABLE - Beyond limitation period (>3 years)
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, BANK_ID, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, RE_LAST_COMMUNICATION_DATE, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/KOL/000005', 'Arun Ghosh', 'arun.ghosh@hotmail.com', '7788990011', 14, 6, 'Fixed deposit not renewed as per instructions',
'Axis Bank did not auto-renew my FD of Rs 5 lakh in March 2022 as per my standing instruction. I only noticed now. I complained to the bank in April 2022.',
'Renewal of FD with applicable interest from March 2022', 'pending', 'LOW', 'ONLINE', 'CEPC', 'CEPC_DO', 'AXIS', 'TRIAGE',
1, DATE '2022-04-15', 'AXIS/FD/2022/112233', 0, DATE '2022-04-20', 0, 'RED', TIMESTAMP '2026-07-01 16:45:00');

-- Complaint 6: MAINTAINABLE - NBFC complaint (senior citizen)
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, COMPLAINANT_ADDRESS, BANK_ID, BANK_BRANCH, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ASSIGNED_OFFICER, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, RE_LAST_COMMUNICATION_DATE, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/PUN/000006', 'Shantabai Pawar', 'shantabai.p@gmail.com', '9090909090', '25, Model Colony, Pune 411016', 33, 'Pune Main Branch', 5, 'Gold loan foreclosure excess charge by Bajaj Finance',
'Bajaj Finance charged Rs 8,000 as foreclosure penalty on my gold loan despite RBI circular prohibiting such charges on floating rate loans. I am a 72 year old senior citizen. Complained on 01-May-2026, bank refused on 25-May-2026.',
'Refund of Rs 8,000 foreclosure charges plus compensation for harassment of a senior citizen', 'in_progress', 'HIGH', 'ONLINE', 'RBIO', 'RBIO_OFFICER', 'officer.rbio2', 'BAJAJ_FIN', 'ASSESSMENT',
1, DATE '2026-05-01', 'BJF/GL/2026/99887', 1, DATE '2026-05-25', 0, 'GREEN', TIMESTAMP '2026-06-15 09:00:00');

-- Complaint 7: Resolved complaint (for timeline testing)
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, BANK_ID, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ASSIGNED_OFFICER, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, MAINTAINABILITY_DETERMINATION, MAINTAINABILITY_DETERMINED_BY, MAINTAINABILITY_DETERMINED_AT, AWARD_AMOUNT, FILED_AT, RESOLVED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/MUM/000007', 'Deepak Mehta', 'deepak.m@gmail.com', '9812345678', 12, 1, 'ATM dispensed less cash than debited',
'HDFC ATM dispensed only Rs 5,000 against debit of Rs 10,000. Complained to bank on 01-Mar-2026, bank denied on 20-Mar-2026.',
'Reversal of Rs 5,000 and interest', 'resolved', 'MEDIUM', 'ONLINE', 'RBIO', 'RBIO_OFFICER', 'officer.rbio1', 'HDFC', 'CLOSED',
1, DATE '2026-03-01', 'HDFC/ATM/2026/55555', 1, 0, 'GREEN', 'MAINTAINABLE', 'officer.rbio1', TIMESTAMP '2026-04-10 14:30:00', 5000.00, TIMESTAMP '2026-04-02 10:00:00', TIMESTAMP '2026-04-25 15:30:00');

-- Complaint 8: Duplicate grievance test
INSERT INTO COMPLAINTS (ID, COMPLAINT_NUMBER, COMPLAINANT_NAME, COMPLAINANT_EMAIL, COMPLAINANT_PHONE, BANK_ID, CATEGORY_ID, SUBJECT, DESCRIPTION, RELIEF_SOUGHT, STATUS, PRIORITY, FILING_TYPE, DEPARTMENT, ASSIGNED_ROLE, ENTITY_CODE, WORKFLOW_STAGE, PRIOR_RE_COMPLAINT, RE_COMPLAINT_DATE, RE_COMPLAINT_REFERENCE, RE_REPLIED_AND_DISSATISFIED, SAME_GRIEVANCE_PENDING, TRIAGE_SIGNAL, FILED_AT) VALUES (
COMPLAINTS_SEQ.NEXTVAL, 'CMS/2026/MUM/000008', 'Rajesh Kumar', 'rajesh.kumar@gmail.com', '9876543210', 1, 1, 'ATM cash not dispensed - duplicate filing',
'Same complaint as CMS/2026/MUM/000001 - filing again as I have not received resolution yet.',
'Immediate reversal of Rs 10,000', 'pending', 'MEDIUM', 'ONLINE', 'RBIO', 'RBIO_OFFICER', 'SBI', 'TRIAGE',
1, DATE '2026-05-02', 'SBI/CMP/2026/45678', 1, 1, 'RED', TIMESTAMP '2026-07-01 08:00:00');


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 14: COMPLAINT TIMELINE ENTRIES
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 1, 'FILED', 'SYSTEM', 'Complaint filed online by citizen', NULL, 'pending', TIMESTAMP '2026-06-02 10:30:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 1, 'ASSIGNED', 'SYSTEM', 'Auto-assigned to RBIO department by MRE rule ASGN-001', 'pending', 'in_progress', TIMESTAMP '2026-06-02 10:31:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 1, 'MRE_ASSESSED', 'SYSTEM', 'MRE assessment: GREEN - all grounds pass', 'in_progress', 'in_progress', TIMESTAMP '2026-06-02 10:31:05');

INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 7, 'FILED', 'SYSTEM', 'Complaint filed online', NULL, 'pending', TIMESTAMP '2026-04-02 10:00:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 7, 'ASSIGNED', 'SYSTEM', 'Assigned to RBIO', 'pending', 'in_progress', TIMESTAMP '2026-04-02 10:01:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 7, 'DETERMINATION', 'officer.rbio1', 'Determined MAINTAINABLE - all Q13/Q16/Q17 conditions satisfied', 'in_progress', 'in_progress', TIMESTAMP '2026-04-10 14:30:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 7, 'FORWARDED_TO_RE', 'officer.rbio1', 'Forwarded to HDFC Bank for response within 15 days', 'in_progress', 'in_progress', TIMESTAMP '2026-04-10 14:35:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 7, 'RE_RESPONDED', 'HDFC Bank', 'RE has submitted response and agreed to refund', 'in_progress', 'in_progress', TIMESTAMP '2026-04-20 11:00:00');
INSERT INTO COMPLAINT_TIMELINE (ID, COMPLAINT_ID, ACTION, PERFORMED_BY, REMARKS, FROM_STATUS, TO_STATUS, PERFORMED_AT) VALUES (COMPLAINT_TIMELINE_SEQ.NEXTVAL, 7, 'RESOLVED', 'officer.rbio1', 'Resolved with award of Rs 5,000 to complainant', 'in_progress', 'resolved', TIMESTAMP '2026-04-25 15:30:00');


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 15: RE RESPONSE TRACKER
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO RE_RESPONSE_TRACKER (ID, COMPLAINT_ID, REGULATED_ENTITY_ID, FORWARDED_AT, RESPONDED_AT, WINDOW_DAYS, WINDOW_EXPIRES_AT, BREACHED, EX_PARTE_ELIGIBLE, NOTES) VALUES (
RE_RESPONSE_TRACKER_SEQ.NEXTVAL, 7, 6, TIMESTAMP '2026-04-10 14:35:00', TIMESTAMP '2026-04-20 11:00:00', 15, TIMESTAMP '2026-04-25 14:35:00', 0, 0, 'HDFC responded within window');

INSERT INTO RE_RESPONSE_TRACKER (ID, COMPLAINT_ID, REGULATED_ENTITY_ID, FORWARDED_AT, RESPONDED_AT, WINDOW_DAYS, WINDOW_EXPIRES_AT, BREACHED, EX_PARTE_ELIGIBLE, NOTES) VALUES (
RE_RESPONSE_TRACKER_SEQ.NEXTVAL, 1, 1, TIMESTAMP '2026-06-05 10:00:00', NULL, 15, TIMESTAMP '2026-06-20 10:00:00', 1, 1, 'SBI has not responded - window breached');


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SECTION 16: VERIFICATION QUERIES
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SELECT 'BANKS' AS ENTITY, COUNT(*) AS CNT FROM BANKS
UNION ALL SELECT 'COMPLAINT_CATEGORIES', COUNT(*) FROM COMPLAINT_CATEGORIES
UNION ALL SELECT 'REGULATED_ENTITIES', COUNT(*) FROM REGULATED_ENTITIES
UNION ALL SELECT 'COMMUNICATION_TEMPLATES', COUNT(*) FROM COMMUNICATION_TEMPLATES
UNION ALL SELECT 'COMMENT_TEMPLATES', COUNT(*) FROM COMMENT_TEMPLATES
UNION ALL SELECT 'HOLIDAYS', COUNT(*) FROM HOLIDAYS
UNION ALL SELECT 'EMAIL_IGNORE_LIST', COUNT(*) FROM EMAIL_IGNORE_LIST
UNION ALL SELECT 'EXTRACTION_RULES', COUNT(*) FROM EXTRACTION_RULE
UNION ALL SELECT 'SUPPORTED_LOCALES', COUNT(*) FROM SUPPORTED_LOCALES
UNION ALL SELECT 'SAMPLE_COMPLAINTS', COUNT(*) FROM COMPLAINTS
UNION ALL SELECT 'FORM_CONFIG', COUNT(*) FROM FORM_CONFIG;

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════════════════
-- END OF SCRIPT
-- Expected counts after execution:
--   BANKS: 40 (11 Public + 12 Private + 5 Foreign + 1 Payment System + 3 Card Network + 3 NBFC + 5 Payment Bank)
--   COMPLAINT_CATEGORIES: 30 (15 top-level + 15 sub-categories)
--   REGULATED_ENTITIES: 25
--   COMMUNICATION_TEMPLATES: 7
--   COMMENT_TEMPLATES: 12
--   HOLIDAYS: 37 (20 in 2026 + 17 in 2027)
--   EMAIL_IGNORE_LIST: 8
--   EXTRACTION_RULES: 10
--   SUPPORTED_LOCALES: 12
--   SAMPLE_COMPLAINTS: 8
--   FORM_CONFIG: 1
--
-- NOTE: Pincodes (797 entries) are loaded from CSV at startup via PincodeDataInitializer
-- NOTE: Translations (118 keys × 10 locales = 1180 entries) are loaded from CSV via TranslationDataInitializer
-- ═══════════════════════════════════════════════════════════════════════════════════
