-- Dev-local seed data for Assignment Engine (H2)
-- Only runs when spring.jpa.hibernate.ddl-auto=create-drop (dev-local profile)

-- ═══════════════════════════════════════════════════════════════
-- ATTRIBUTES (metadata-driven condition columns)
-- ═══════════════════════════════════════════════════════════════
INSERT IGNORE INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, CASE_SENSITIVE, PII_FLAG, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS) VALUES
('RBI-CMS', 'claimAmount', 'Claim Amount', 'Monetary value of the claim in INR', 'MONEY', 'complaint.claimAmount', false, 'FREE_TEXT', false, false, 1, true, 'GTE,LTE,GT,LT,BETWEEN,EQ,IS_NULL,IS_NOT_NULL');
INSERT IGNORE INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, CASE_SENSITIVE, PII_FLAG, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS) VALUES
('RBI-CMS', 'complaintCategory', 'Category', 'Complaint category code', 'ENUM', 'complaint.category', false, 'STATIC_LIST', false, false, 2, true, 'EQ,NEQ,IN,NOT_IN,IS_NULL,IS_NOT_NULL');
INSERT IGNORE INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, CASE_SENSITIVE, PII_FLAG, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS) VALUES
('RBI-CMS', 'state', 'State', 'Complainant state code', 'ENUM', 'complaint.state', false, 'STATIC_LIST', false, false, 3, true, 'EQ,NEQ,IN,NOT_IN,IS_NULL,IS_NOT_NULL');
INSERT IGNORE INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, CASE_SENSITIVE, PII_FLAG, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS) VALUES
('RBI-CMS', 'channel', 'Channel', 'Intake channel', 'ENUM', 'complaint.channel', false, 'STATIC_LIST', false, false, 4, true, 'EQ,NEQ,IN,NOT_IN,IS_NULL,IS_NOT_NULL');
INSERT IGNORE INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, CASE_SENSITIVE, PII_FLAG, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS) VALUES
('RBI-CMS', 'regulatedEntityType', 'RE Type', 'Regulated entity type', 'ENUM', 'complaint.regulatedEntityType', false, 'STATIC_LIST', false, false, 5, true, 'EQ,NEQ,IN,NOT_IN,IS_NULL,IS_NOT_NULL');
INSERT IGNORE INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, CASE_SENSITIVE, PII_FLAG, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS) VALUES
('RBI-CMS', 'escalationLevel', 'Escalation', 'Current escalation level', 'NUMBER', 'complaint.escalationLevel', false, 'FREE_TEXT', false, false, 6, true, 'EQ,GTE,LTE,GT,LT');
INSERT IGNORE INTO ASGN_ATTRIBUTE (TENANT_ID, CODE, LABEL, DESCRIPTION, DATA_TYPE, SOURCE_PATH, REQUIRED, VALUE_SOURCE, CASE_SENSITIVE, PII_FLAG, DISPLAY_ORDER, ACTIVE, ALLOWED_OPERATORS) VALUES
('RBI-CMS', 'isRepeatComplaint', 'Repeat?', 'Whether complainant has prior complaints', 'BOOLEAN', 'complaint.isRepeat', false, 'FREE_TEXT', false, false, 7, true, 'IS_TRUE,IS_FALSE');

-- ═══════════════════════════════════════════════════════════════
-- SAMPLE RULESET: Complaint Assignment (Appendix A)
-- ═══════════════════════════════════════════════════════════════
INSERT IGNORE INTO ASGN_RULE_SET (TENANT_ID, DECISION_POINT, NAME, DESCRIPTION, HIT_POLICY, ACTIVE, CREATED_AT) VALUES
('RBI-CMS', 'COMPLAINT_ASSIGNMENT', 'Default Complaint Assignment Rules', 'Routes complaints to appropriate groups based on amount, category, state, and channel', 'FIRST', true, CURRENT_TIMESTAMP);

-- Version 1 (DRAFT so you can edit it)
INSERT IGNORE INTO ASGN_RULE_SET_VERSION (TENANT_ID, RULE_SET_ID, VERSION_NO, STATUS, CREATED_AT) VALUES
('RBI-CMS', 1, 1, 'DRAFT', CURRENT_TIMESTAMP);

-- Rules
INSERT IGNORE INTO ASGN_RULE(TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED) VALUES
('RBI-CMS', 1, 'R-001', 'High Value Claims', 10, 10, true);
INSERT IGNORE INTO ASGN_RULE(TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED) VALUES
('RBI-CMS', 1, 'R-002', 'Credit Card Complaints', 20, 20, true);
INSERT IGNORE INTO ASGN_RULE(TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED) VALUES
('RBI-CMS', 1, 'R-003', 'Western Region Banking', 30, 30, true);
INSERT IGNORE INTO ASGN_RULE(TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED) VALUES
('RBI-CMS', 1, 'R-004', 'Email Channel', 40, 40, true);
INSERT IGNORE INTO ASGN_RULE(TENANT_ID, VERSION_ID, RULE_CODE, NAME, PRIORITY, ROW_ORDER, ENABLED) VALUES
('RBI-CMS', 1, 'R-005', 'Catch-All', 100, 100, true);

-- Conditions for R-001: claimAmount >= 10,00,000
INSERT IGNORE INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_NUM_FROM) VALUES
('RBI-CMS', 1, 'claimAmount', 'GTE', 1000000);

-- Conditions for R-002: complaintCategory = CREDIT_CARD
INSERT IGNORE INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_TEXT) VALUES
('RBI-CMS', 2, 'complaintCategory', 'EQ', 'CREDIT_CARD');

-- Conditions for R-003: state IN (MH, GJ, RJ, GA)
INSERT IGNORE INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_LIST) VALUES
('RBI-CMS', 3, 'state', 'IN', 'MH,GJ,RJ,GA');

-- Conditions for R-004: channel = EMAIL
INSERT IGNORE INTO ASGN_RULE_CONDITION (TENANT_ID, RULE_ID, ATTRIBUTE_CODE, OPERATOR, VALUE_TEXT) VALUES
('RBI-CMS', 4, 'channel', 'EQ', 'EMAIL');

-- R-005 has no conditions (catch-all)

-- Outcomes
INSERT IGNORE INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, VERSION_ID, IS_DEFAULT, OUTCOME_TYPE, TARGET_ID, ASSIGN_MODE) VALUES
('RBI-CMS', 1, 1, false, 'GROUP', 'SENIOR_OFFICERS', 'PICK_MEMBER');
INSERT IGNORE INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, VERSION_ID, IS_DEFAULT, OUTCOME_TYPE, TARGET_ID, ASSIGN_MODE, DISTRIBUTION_STRATEGY) VALUES
('RBI-CMS', 2, 1, false, 'GROUP', 'CREDIT_CARD_TEAM', 'PICK_MEMBER', 'ROUND_ROBIN');
INSERT IGNORE INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, VERSION_ID, IS_DEFAULT, OUTCOME_TYPE, TARGET_ID, ASSIGN_MODE) VALUES
('RBI-CMS', 3, 1, false, 'GROUP', 'WESTERN_REGION_POOL', 'AS_GROUP');
INSERT IGNORE INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, VERSION_ID, IS_DEFAULT, OUTCOME_TYPE, TARGET_ID, ASSIGN_MODE) VALUES
('RBI-CMS', 4, 1, false, 'QUEUE', 'EMAIL_TRIAGE_QUEUE', 'AS_GROUP');
INSERT IGNORE INTO ASGN_RULE_OUTCOME (TENANT_ID, RULE_ID, VERSION_ID, IS_DEFAULT, OUTCOME_TYPE, TARGET_ID, ASSIGN_MODE) VALUES
('RBI-CMS', 5, 1, false, 'QUEUE', 'GENERAL_INTAKE_POOL', 'AS_GROUP');

-- Default outcome (fallback)
INSERT IGNORE INTO ASGN_RULE_OUTCOME (TENANT_ID, VERSION_ID, IS_DEFAULT, OUTCOME_TYPE, TARGET_ID) VALUES
('RBI-CMS', 1, true, 'QUEUE', 'GENERAL_INTAKE_POOL');
