/**
 * Run with: node generate_remaining_locales.js > oracle_translation_seed_part3.sql
 *
 * Generates idempotent Oracle SQL for Gujarati (gu), Urdu (ur), Kannada (kn), Malayalam (ml)
 * translations from the Java seeder source files.
 */
const fs = require('fs');
const path = require('path');

// __dirname = cms-backend/src/main/resources/db
// Go up 4 levels to reach cms-backend/
const baseDir = path.resolve(__dirname, '../../../..');
const eligFile = fs.readFileSync(path.join(baseDir, 'src/main/java/com/hrms/cms/config/EligibilityTranslationSeeder.java'), 'utf8');
const portalFile = fs.readFileSync(path.join(baseDir, 'src/main/java/com/hrms/cms/config/PortalFullTranslationSeeder.java'), 'utf8');

function escapeSQL(val) {
  return val.replace(/'/g, "''");
}

function extractEntries(text, methodName) {
  const start = text.indexOf('private void ' + methodName + '()');
  if (start === -1) return [];
  const afterStart = text.substring(start);
  const endMarkers = ['saveLocaleTranslations(m,', 'saveTranslations(m,'];
  let endIdx = afterStart.length;
  for (const marker of endMarkers) {
    const idx = afterStart.indexOf(marker);
    if (idx !== -1 && idx < endIdx) endIdx = idx;
  }
  const block = afterStart.substring(0, endIdx);
  const regex = /m\.put\("([^"]+)",\s*"((?:[^"\\]|\\.)*)"\)/g;
  const results = [];
  let match;
  while ((match = regex.exec(block)) !== null) {
    results.push([match[1], match[2]]);
  }
  return results;
}

const locales = [
  { code: 'gu', name: 'Gujarati', eligMethod: 'seedGujaratiTranslations', portalMethod: 'seedGujarati' },
  { code: 'ur', name: 'Urdu', eligMethod: 'seedUrduTranslations', portalMethod: 'seedUrdu' },
  { code: 'kn', name: 'Kannada', eligMethod: 'seedKannadaTranslations', portalMethod: 'seedKannada' },
  { code: 'ml', name: 'Malayalam', eligMethod: 'seedMalayalamTranslations', portalMethod: 'seedMalayalam' }
];

let sql = `-- ============================================================
-- oracle_translation_seed_part3.sql
-- Gujarati (gu), Urdu (ur), Kannada (kn), Malayalam (ml)
-- Run AFTER oracle_translation_seed.sql and oracle_translation_seed_part2.sql
-- Generated by: node generate_remaining_locales.js
-- ============================================================
SET DEFINE OFF;
`;

for (const locale of locales) {
  const eligEntries = extractEntries(eligFile, locale.eligMethod);
  const portalEntries = extractEntries(portalFile, locale.portalMethod);

  sql += `\n-- ============================================================\n`;
  sql += `-- ${locale.name} (${locale.code}) translations\n`;
  sql += `-- ============================================================\n\n`;

  // Eligibility block
  sql += `-- ${locale.name} Eligibility (${eligEntries.length} entries)\n`;
  sql += `DECLARE\n`;
  sql += `    PROCEDURE et(p_code VARCHAR2, p_locale VARCHAR2, p_value VARCHAR2) IS\n`;
  sql += `        v_tk_id NUMBER; v_exists NUMBER;\n`;
  sql += `    BEGIN\n`;
  sql += `        BEGIN SELECT id INTO v_tk_id FROM translation_key WHERE code = p_code; EXCEPTION WHEN NO_DATA_FOUND THEN RETURN; END;\n`;
  sql += `        SELECT COUNT(*) INTO v_exists FROM translation WHERE translation_key_id = v_tk_id AND locale = p_locale;\n`;
  sql += `        IF v_exists = 0 THEN INSERT INTO translation (id, translation_key_id, locale, value) VALUES (translation_seq.NEXTVAL, v_tk_id, p_locale, p_value); END IF;\n`;
  sql += `    END;\n`;
  sql += `BEGIN\n`;
  for (const [code, value] of eligEntries) {
    sql += `    et('${escapeSQL(code)}','${locale.code}','${escapeSQL(value)}');\n`;
  }
  sql += `    COMMIT;\nEND;\n/\n\n`;

  // Portal block
  sql += `-- ${locale.name} Portal (${portalEntries.length} entries)\n`;
  sql += `DECLARE\n`;
  sql += `    PROCEDURE et(p_code VARCHAR2, p_locale VARCHAR2, p_value VARCHAR2) IS\n`;
  sql += `        v_tk_id NUMBER; v_exists NUMBER;\n`;
  sql += `    BEGIN\n`;
  sql += `        BEGIN SELECT id INTO v_tk_id FROM translation_key WHERE code = p_code; EXCEPTION WHEN NO_DATA_FOUND THEN RETURN; END;\n`;
  sql += `        SELECT COUNT(*) INTO v_exists FROM translation WHERE translation_key_id = v_tk_id AND locale = p_locale;\n`;
  sql += `        IF v_exists = 0 THEN INSERT INTO translation (id, translation_key_id, locale, value) VALUES (translation_seq.NEXTVAL, v_tk_id, p_locale, p_value); END IF;\n`;
  sql += `    END;\n`;
  sql += `BEGIN\n`;
  for (const [code, value] of portalEntries) {
    sql += `    et('${escapeSQL(code)}','${locale.code}','${escapeSQL(value)}');\n`;
  }
  sql += `    COMMIT;\nEND;\n/\n`;
}

sql += `\n-- ============================================================\n`;
sql += `-- COMPLETE SUMMARY (all 3 files combined)\n`;
sql += `-- ============================================================\n`;
sql += `-- oracle_translation_seed.sql:      keys (290) + hi + mr + bn + te\n`;
sql += `-- oracle_translation_seed_part2.sql: ta\n`;
sql += `-- oracle_translation_seed_part3.sql: gu + ur + kn + ml\n`;
sql += `-- Total: ~290 keys x 9 locales = ~2600 translation entries\n`;
sql += `-- ============================================================\n`;

fs.writeFileSync(path.join(__dirname, 'oracle_translation_seed_part3.sql'), sql, 'utf8');
console.log('Generated oracle_translation_seed_part3.sql');
console.log('Locales generated: gu, ur, kn, ml');
