cms:
  opensearch:
    host: localhost
    port: 9200
    scheme: http
    enabled: false

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: cms-search-dev
      enable-auto-commit: false
    listener:
      type: single
      missing-topics-fatal: false
      ack-mode: manual
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

logging:
  level:
    com.rbi.cms: DEBUG
