-- Create application schemas for CMS services
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER cms_eligibility IDENTIFIED BY cms_eligibility DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO cms_eligibility;

CREATE USER cms_ingestion IDENTIFIED BY cms_ingestion DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO cms_ingestion;

CREATE USER cms_workflow IDENTIFIED BY cms_workflow DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO cms_workflow;

CREATE USER cms_assignment IDENTIFIED BY cms_assignment DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO cms_assignment;

CREATE USER cms_sla IDENTIFIED BY cms_sla DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO cms_sla;

CREATE USER cms_audit IDENTIFIED BY cms_audit DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO cms_audit;

CREATE USER cms_outbox IDENTIFIED BY cms_outbox DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO cms_outbox;

COMMIT;
