spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/cms
          jwk-set-uri: http://localhost:8180/realms/cms/protocol/openid-connect/certs
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

logging:
  level:
    com.rbi.cms: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
