export interface PincodeEntry {
  pincode: string;
  state: string;
  district: string;
  areas: string[];
}

export const PINCODE_DATABASE: PincodeEntry[] = [
  // ═══ DELHI ═══
  { pincode: '110001', state: 'Delhi', district: 'Central Delhi', areas: ['Connaught Place', 'Barakhamba Road', 'Janpath'] },
  { pincode: '110002', state: 'Delhi', district: 'Central Delhi', areas: ['Darya Ganj', 'Rajghat', 'Delhi Gate'] },
  { pincode: '110003', state: 'Delhi', district: 'Central Delhi', areas: ['Civil Lines', 'Kashmere Gate', 'Tis Hazari'] },
  { pincode: '110004', state: 'Delhi', district: 'Central Delhi', areas: ['Chanakyapuri', 'Race Course Road'] },
  { pincode: '110005', state: 'Delhi', district: 'Central Delhi', areas: ['Karol Bagh', 'Dev Nagar', 'Patel Nagar'] },
  { pincode: '110006', state: 'Delhi', district: 'Central Delhi', areas: ['Chandni Chowk', 'Red Fort', 'Jama Masjid'] },
  { pincode: '110007', state: 'Delhi', district: 'Central Delhi', areas: ['Kamla Nagar', 'Shakti Nagar', 'Roop Nagar'] },
  { pincode: '110008', state: 'Delhi', district: 'West Delhi', areas: ['Patel Nagar', 'Rajendra Place', 'Baljit Nagar'] },
  { pincode: '110009', state: 'Delhi', district: 'North Delhi', areas: ['Model Town', 'Azadpur', 'Adarsh Nagar'] },
  { pincode: '110010', state: 'Delhi', district: 'South Delhi', areas: ['Saket', 'Malviya Nagar', 'Hauz Khas'] },
  { pincode: '110011', state: 'Delhi', district: 'New Delhi', areas: ['Nirman Bhavan', 'India Gate', 'Parliament Street'] },
  { pincode: '110012', state: 'Delhi', district: 'New Delhi', areas: ['Willingdon Crescent', 'Teen Murti', 'South Avenue'] },
  { pincode: '110013', state: 'Delhi', district: 'Central Delhi', areas: ['Paharganj', 'Ram Nagar', 'DB Gupta Road'] },
  { pincode: '110014', state: 'Delhi', district: 'South Delhi', areas: ['Jangpura', 'Bhogal', 'Ashram'] },
  { pincode: '110015', state: 'Delhi', district: 'West Delhi', areas: ['Moti Nagar', 'Kirti Nagar', 'Ramesh Nagar'] },
  { pincode: '110016', state: 'Delhi', district: 'South Delhi', areas: ['Hauz Khas', 'Green Park', 'Yusuf Sarai'] },
  { pincode: '110017', state: 'Delhi', district: 'South Delhi', areas: ['Malviya Nagar', 'Sarvapriya Vihar'] },
  { pincode: '110018', state: 'Delhi', district: 'West Delhi', areas: ['Tilak Nagar', 'Janakpuri East', 'Subhash Nagar'] },
  { pincode: '110019', state: 'Delhi', district: 'South Delhi', areas: ['Kalkaji', 'Nehru Place', 'Govindpuri'] },
  { pincode: '110020', state: 'Delhi', district: 'South Delhi', areas: ['Okhla', 'Jamia Nagar', 'New Friends Colony'] },
  { pincode: '110021', state: 'Delhi', district: 'South West Delhi', areas: ['Vasant Vihar', 'Munirka', 'JNU Campus'] },
  { pincode: '110022', state: 'Delhi', district: 'New Delhi', areas: ['Lodi Road', 'Jor Bagh', 'Safdarjung'] },
  { pincode: '110023', state: 'Delhi', district: 'New Delhi', areas: ['Lodi Colony', 'Defence Colony Market'] },
  { pincode: '110024', state: 'Delhi', district: 'South Delhi', areas: ['Defence Colony', 'Lajpat Nagar', 'South Extension'] },
  { pincode: '110025', state: 'Delhi', district: 'South Delhi', areas: ['Badarpur', 'Tughlakabad', 'Sangam Vihar'] },
  { pincode: '110026', state: 'Delhi', district: 'West Delhi', areas: ['Rajouri Garden', 'Tagore Garden', 'Hari Nagar'] },
  { pincode: '110027', state: 'Delhi', district: 'West Delhi', areas: ['Punjabi Bagh', 'Shivaji Park', 'Madipur'] },
  { pincode: '110028', state: 'Delhi', district: 'South Delhi', areas: ['Vasant Kunj', 'Kishangarh', 'Mahipalpur'] },
  { pincode: '110029', state: 'Delhi', district: 'South Delhi', areas: ['Greater Kailash', 'CR Park', 'Alaknanda'] },
  { pincode: '110030', state: 'Delhi', district: 'South Delhi', areas: ['Mehrauli', 'Qutab Minar', 'Chattarpur'] },
  { pincode: '110031', state: 'Delhi', district: 'East Delhi', areas: ['Gandhi Nagar', 'Krishna Nagar', 'Laxmi Nagar'] },
  { pincode: '110032', state: 'Delhi', district: 'East Delhi', areas: ['Shahdara', 'Mansarovar Park', 'Jhilmil'] },
  { pincode: '110033', state: 'Delhi', district: 'North West Delhi', areas: ['Saraswati Vihar', 'Pitampura', 'Rohini'] },
  { pincode: '110034', state: 'Delhi', district: 'North West Delhi', areas: ['Punjabi Bagh West', 'Paschim Vihar'] },
  { pincode: '110035', state: 'Delhi', district: 'North West Delhi', areas: ['Shalimar Bagh', 'Wazirpur', 'Ashok Vihar'] },
  { pincode: '110036', state: 'Delhi', district: 'North Delhi', areas: ['Alipur', 'GT Karnal Road', 'Samaypur'] },
  { pincode: '110037', state: 'Delhi', district: 'South West Delhi', areas: ['Palam', 'Dwarka Sector 1', 'Sadh Nagar'] },
  { pincode: '110038', state: 'Delhi', district: 'South West Delhi', areas: ['Uttam Nagar', 'Bindapur', 'Hastsal'] },
  { pincode: '110039', state: 'Delhi', district: 'North West Delhi', areas: ['Badli', 'Jahangirpuri', 'Libaspur'] },
  { pincode: '110040', state: 'Delhi', district: 'North Delhi', areas: ['Narela', 'Bawana', 'Alipur'] },
  { pincode: '110041', state: 'Delhi', district: 'West Delhi', areas: ['Najafgarh', 'Paprawat', 'Nangli Sakrawati'] },
  { pincode: '110042', state: 'Delhi', district: 'North West Delhi', areas: ['Mangolpuri', 'Sultan Puri', 'Pooth Kalan'] },
  { pincode: '110043', state: 'Delhi', district: 'South West Delhi', areas: ['Bijwasan', 'Kapashera', 'Rajokri'] },
  { pincode: '110044', state: 'Delhi', district: 'South Delhi', areas: ['Lajpat Nagar', 'Amar Colony', 'Andrews Ganj'] },
  { pincode: '110045', state: 'Delhi', district: 'South West Delhi', areas: ['Dwarka Sector 6', 'Dwarka Sector 7', 'Nasirpur'] },
  { pincode: '110046', state: 'Delhi', district: 'West Delhi', areas: ['Nangloi Jat', 'Mundka', 'Tikri Kalan'] },
  { pincode: '110047', state: 'Delhi', district: 'South Delhi', areas: ['Mehrauli', 'Lado Sarai', 'Andheria Modh'] },
  { pincode: '110048', state: 'Delhi', district: 'South Delhi', areas: ['Greater Kailash II', 'Masjid Moth', 'Panchsheel Park'] },
  { pincode: '110049', state: 'Delhi', district: 'South Delhi', areas: ['East of Kailash', 'Garhi', 'Moolchand'] },
  { pincode: '110051', state: 'Delhi', district: 'East Delhi', areas: ['Patparganj', 'Mayur Vihar Phase 1', 'IP Extension'] },
  { pincode: '110052', state: 'Delhi', district: 'North West Delhi', areas: ['Wazirpur Industrial', 'Tri Nagar', 'Rampura'] },
  { pincode: '110053', state: 'Delhi', district: 'North Delhi', areas: ['Timarpur', 'Mukherjee Nagar', 'Jawahar Nagar'] },
  { pincode: '110054', state: 'Delhi', district: 'Central Delhi', areas: ['Sadar Bazar', 'Filmistan', 'Qutab Road'] },
  { pincode: '110055', state: 'Delhi', district: 'Central Delhi', areas: ['Pahar Ganj', 'Multani Dhanda', 'Chuna Mandi'] },
  { pincode: '110056', state: 'Delhi', district: 'North Delhi', areas: ['Ashok Vihar', 'Derawal Nagar', 'Kingsway Camp'] },
  { pincode: '110057', state: 'Delhi', district: 'South West Delhi', areas: ['Vasant Vihar', 'Kishangarh', 'Aruna Asaf Ali Marg'] },
  { pincode: '110058', state: 'Delhi', district: 'West Delhi', areas: ['Janakpuri', 'Vikas Puri', 'Uttam Nagar'] },
  { pincode: '110059', state: 'Delhi', district: 'West Delhi', areas: ['Rajouri Garden Extension', 'Mahabir Nagar'] },
  { pincode: '110060', state: 'Delhi', district: 'North West Delhi', areas: ['Rani Bagh', 'Shakur Basti', 'Saraswati Garden'] },
  { pincode: '110061', state: 'Delhi', district: 'South Delhi', areas: ['Chhatarpur Extension', 'Sultanpur', 'Ghitorni'] },
  { pincode: '110062', state: 'Delhi', district: 'South Delhi', areas: ['Sangam Vihar', 'Tigri', 'Dakshinpuri'] },
  { pincode: '110063', state: 'Delhi', district: 'North Delhi', areas: ['Burari', 'Mukundpur', 'Bhalswa'] },
  { pincode: '110064', state: 'Delhi', district: 'North Delhi', areas: ['Narela', 'Holambi Kalan', 'Bankner'] },
  { pincode: '110065', state: 'Delhi', district: 'South Delhi', areas: ['Ambedkar Nagar', 'Madanpur Khadar', 'Sarita Vihar'] },
  { pincode: '110066', state: 'Delhi', district: 'North West Delhi', areas: ['Bawana', 'Prahladpur Bangar'] },
  { pincode: '110067', state: 'Delhi', district: 'South West Delhi', areas: ['Munirka Vihar', 'R K Puram Sector 1-12'] },
  { pincode: '110070', state: 'Delhi', district: 'South Delhi', areas: ['Pushp Vihar', 'Saket', 'Sheikh Sarai'] },
  { pincode: '110071', state: 'Delhi', district: 'South Delhi', areas: ['Sangam Vihar', 'Aya Nagar', 'Jonapur'] },
  { pincode: '110074', state: 'Delhi', district: 'South Delhi', areas: ['Badarpur Border', 'Molarband', 'Tajpur Pahari'] },
  { pincode: '110075', state: 'Delhi', district: 'West Delhi', areas: ['Dabri', 'Palam Colony', 'Sagarpur'] },
  { pincode: '110076', state: 'Delhi', district: 'South Delhi', areas: ['Sukhdev Vihar', 'Haji Colony', 'Okhla Phase 2'] },
  { pincode: '110077', state: 'Delhi', district: 'South West Delhi', areas: ['Dwarka Sector 3', 'Dwarka Sector 4', 'Dwarka Sector 5'] },
  { pincode: '110078', state: 'Delhi', district: 'South West Delhi', areas: ['Dwarka Sector 8', 'Dwarka Sector 9', 'Dwarka Sector 10'] },
  { pincode: '110085', state: 'Delhi', district: 'North West Delhi', areas: ['Rohini Sector 1-5', 'Prashant Vihar'] },
  { pincode: '110086', state: 'Delhi', district: 'North West Delhi', areas: ['Rohini Sector 6-11', 'Avantika'] },
  { pincode: '110087', state: 'Delhi', district: 'North West Delhi', areas: ['Rohini Sector 15-16', 'Budh Vihar'] },
  { pincode: '110088', state: 'Delhi', district: 'North West Delhi', areas: ['Rohini Sector 24-25', 'Rithala'] },
  { pincode: '110089', state: 'Delhi', district: 'North West Delhi', areas: ['Rohini Sector 20-22', 'Begumpur'] },
  { pincode: '110091', state: 'Delhi', district: 'East Delhi', areas: ['Mayur Vihar Phase 2', 'Trilokpuri', 'Kalyanpuri'] },
  { pincode: '110092', state: 'Delhi', district: 'East Delhi', areas: ['Mayur Vihar Phase 3', 'New Ashok Nagar', 'Vasundhara Enclave'] },
  { pincode: '110093', state: 'Delhi', district: 'North East Delhi', areas: ['Nand Nagri', 'Dilshad Garden', 'Seelampur'] },
  { pincode: '110094', state: 'Delhi', district: 'East Delhi', areas: ['Anand Vihar', 'Karkardooma', 'Yojna Vihar'] },
  { pincode: '110095', state: 'Delhi', district: 'East Delhi', areas: ['Noida Link Road', 'Kondli', 'Gharoli'] },
  { pincode: '110096', state: 'Delhi', district: 'East Delhi', areas: ['Vivek Vihar', 'Harsh Vihar', 'Jhilmil Colony'] },

  // ═══ MUMBAI ═══
  { pincode: '400001', state: 'Maharashtra', district: 'Mumbai', areas: ['Fort', 'GPO', 'Flora Fountain'] },
  { pincode: '400002', state: 'Maharashtra', district: 'Mumbai', areas: ['Kalbadevi', 'Marine Lines', 'Girgaon'] },
  { pincode: '400003', state: 'Maharashtra', district: 'Mumbai', areas: ['Mandvi', 'Masjid', 'Sandhurst Road'] },
  { pincode: '400004', state: 'Maharashtra', district: 'Mumbai', areas: ['Girgaon', 'Charni Road', 'Opera House'] },
  { pincode: '400005', state: 'Maharashtra', district: 'Mumbai', areas: ['Colaba', 'Cuffe Parade', 'Navy Nagar'] },
  { pincode: '400006', state: 'Maharashtra', district: 'Mumbai', areas: ['Malabar Hill', 'Walkeshwar', 'Hanging Garden'] },
  { pincode: '400007', state: 'Maharashtra', district: 'Mumbai', areas: ['Grant Road', 'Tardeo', 'Nana Chowk'] },
  { pincode: '400008', state: 'Maharashtra', district: 'Mumbai', areas: ['Mumbai Central', 'Agripada', 'Belasis Road'] },
  { pincode: '400009', state: 'Maharashtra', district: 'Mumbai', areas: ['Nagpada', 'Byculla', 'Madanpura'] },
  { pincode: '400010', state: 'Maharashtra', district: 'Mumbai', areas: ['Mazgaon', 'Dockyard Road', 'Wadi Bunder'] },
  { pincode: '400011', state: 'Maharashtra', district: 'Mumbai', areas: ['Jacob Circle', 'Mahalaxmi', 'Haji Ali'] },
  { pincode: '400012', state: 'Maharashtra', district: 'Mumbai', areas: ['Parel', 'Lalbaug', 'Lower Parel'] },
  { pincode: '400013', state: 'Maharashtra', district: 'Mumbai', areas: ['Delisle Road', 'Chinchpokli', 'NM Joshi Marg'] },
  { pincode: '400014', state: 'Maharashtra', district: 'Mumbai', areas: ['Dadar West', 'Prabhadevi', 'Sayani Road'] },
  { pincode: '400015', state: 'Maharashtra', district: 'Mumbai', areas: ['Sewri', 'Wadala', 'Antop Hill'] },
  { pincode: '400016', state: 'Maharashtra', district: 'Mumbai', areas: ['Mahim', 'Matunga', 'Dharavi'] },
  { pincode: '400017', state: 'Maharashtra', district: 'Mumbai', areas: ['Dharavi', 'Sion Koliwada'] },
  { pincode: '400018', state: 'Maharashtra', district: 'Mumbai', areas: ['Worli', 'Worli Sea Face', 'Worli Naka'] },
  { pincode: '400019', state: 'Maharashtra', district: 'Mumbai', areas: ['Matunga', 'Wadala East', 'GTB Nagar'] },
  { pincode: '400020', state: 'Maharashtra', district: 'Mumbai', areas: ['Churchgate', 'Nariman Point', 'Mantralaya'] },
  { pincode: '400021', state: 'Maharashtra', district: 'Mumbai', areas: ['Breach Candy', 'Cumballa Hill', 'Kemps Corner'] },
  { pincode: '400022', state: 'Maharashtra', district: 'Mumbai', areas: ['Sion', 'Chunabhatti', 'GTB Nagar'] },
  { pincode: '400023', state: 'Maharashtra', district: 'Mumbai', areas: ['Dadar TT', 'Kohinoor Mill', 'Five Garden'] },
  { pincode: '400024', state: 'Maharashtra', district: 'Mumbai', areas: ['Kurla West', 'Nehru Nagar', 'BKC'] },
  { pincode: '400025', state: 'Maharashtra', district: 'Mumbai', areas: ['Prabhadevi', 'Siddhivinayak', 'Sayani Road'] },
  { pincode: '400026', state: 'Maharashtra', district: 'Mumbai', areas: ['Byculla East', 'Reay Road', 'Dockyard'] },
  { pincode: '400027', state: 'Maharashtra', district: 'Mumbai', areas: ['Bandra West', 'Carter Road', 'Pali Hill'] },
  { pincode: '400028', state: 'Maharashtra', district: 'Mumbai', areas: ['Dadar East', 'Matunga East', 'King Circle'] },
  { pincode: '400029', state: 'Maharashtra', district: 'Mumbai', areas: ['Bandra East', 'BKC', 'Kalanagar'] },
  { pincode: '400030', state: 'Maharashtra', district: 'Mumbai', areas: ['Worli Colony', 'Century Mill', 'Prabhadevi'] },
  { pincode: '400031', state: 'Maharashtra', district: 'Mumbai', areas: ['Wadala', 'Antop Hill', 'Naigaon'] },
  { pincode: '400032', state: 'Maharashtra', district: 'Mumbai', areas: ['Kemps Corner', 'Pedder Road', 'Altamount Road'] },
  { pincode: '400033', state: 'Maharashtra', district: 'Mumbai', areas: ['Cotton Green', 'Reay Road East', 'Sewri'] },
  { pincode: '400034', state: 'Maharashtra', district: 'Mumbai', areas: ['Haji Ali', 'Lotus Colony', 'Worli BDD'] },
  { pincode: '400036', state: 'Maharashtra', district: 'Mumbai', areas: ['Malabar Hill', 'Nepean Sea Road', 'Priyadarshini Park'] },
  { pincode: '400037', state: 'Maharashtra', district: 'Mumbai', areas: ['Antop Hill', 'Wadala East', 'Anik Nagar'] },
  { pincode: '400042', state: 'Maharashtra', district: 'Mumbai', areas: ['Santacruz East', 'Vakola', 'Kalina'] },
  { pincode: '400049', state: 'Maharashtra', district: 'Mumbai', areas: ['Juhu', 'JVPD Scheme', 'Vile Parle West'] },
  { pincode: '400050', state: 'Maharashtra', district: 'Mumbai', areas: ['Bandra West', 'Hill Road', 'Linking Road'] },
  { pincode: '400051', state: 'Maharashtra', district: 'Mumbai', areas: ['Bandra East', 'Kherwadi', 'Bandra Reclamation'] },
  { pincode: '400052', state: 'Maharashtra', district: 'Mumbai', areas: ['Khar West', 'Khar Danda', 'Linking Road'] },
  { pincode: '400053', state: 'Maharashtra', district: 'Mumbai', areas: ['Andheri West', 'Four Bungalows', 'Versova'] },
  { pincode: '400054', state: 'Maharashtra', district: 'Mumbai', areas: ['Santacruz West', 'Juhu Tara Road'] },
  { pincode: '400055', state: 'Maharashtra', district: 'Mumbai', areas: ['Santacruz East', 'Vakola', 'Nehru Road'] },
  { pincode: '400056', state: 'Maharashtra', district: 'Mumbai', areas: ['Vile Parle East', 'Hanuman Road'] },
  { pincode: '400057', state: 'Maharashtra', district: 'Mumbai', areas: ['Vile Parle West', 'Irla', 'Gulmohar Road'] },
  { pincode: '400058', state: 'Maharashtra', district: 'Mumbai', areas: ['Andheri East', 'MIDC', 'Marol'] },
  { pincode: '400059', state: 'Maharashtra', district: 'Mumbai', areas: ['Goregaon West', 'Oshiwara', 'Lokhandwala'] },
  { pincode: '400060', state: 'Maharashtra', district: 'Mumbai', areas: ['Jogeshwari West', 'SV Road', 'Oshiwara'] },
  { pincode: '400061', state: 'Maharashtra', district: 'Mumbai', areas: ['Jogeshwari East', 'JVLR', 'Meghwadi'] },
  { pincode: '400062', state: 'Maharashtra', district: 'Mumbai', areas: ['Goregaon East', 'Film City', 'Aarey Colony'] },
  { pincode: '400063', state: 'Maharashtra', district: 'Mumbai', areas: ['Goregaon East', 'Dindoshi', 'Oberoi Garden City'] },
  { pincode: '400064', state: 'Maharashtra', district: 'Mumbai', areas: ['Malad West', 'Marve Road', 'Evershine Nagar'] },
  { pincode: '400065', state: 'Maharashtra', district: 'Mumbai', areas: ['Goregaon East', 'Piramal Nagar'] },
  { pincode: '400066', state: 'Maharashtra', district: 'Mumbai', areas: ['Borivali East', 'LIC Colony', 'Western Express Highway'] },
  { pincode: '400067', state: 'Maharashtra', district: 'Mumbai', areas: ['Kandivali West', 'Charkop', 'Mahavir Nagar'] },
  { pincode: '400068', state: 'Maharashtra', district: 'Mumbai', areas: ['Dahisar', 'Borivali West', 'IC Colony'] },
  { pincode: '400069', state: 'Maharashtra', district: 'Mumbai', areas: ['Andheri East', 'Sakinaka', 'Chandivali'] },
  { pincode: '400070', state: 'Maharashtra', district: 'Mumbai', areas: ['Kurla East', 'LBS Marg', 'Kamani'] },
  { pincode: '400071', state: 'Maharashtra', district: 'Mumbai', areas: ['Chembur', 'Tilak Nagar', 'Sindhi Society'] },
  { pincode: '400072', state: 'Maharashtra', district: 'Mumbai', areas: ['Vikhroli East', 'Kannamwar Nagar', 'Tagore Nagar'] },
  { pincode: '400073', state: 'Maharashtra', district: 'Mumbai', areas: ['Vikhroli West', 'Godrej Colony', 'Pirojshanagar'] },
  { pincode: '400074', state: 'Maharashtra', district: 'Mumbai', areas: ['Ghatkopar West', 'LBS Marg', 'Pant Nagar'] },
  { pincode: '400075', state: 'Maharashtra', district: 'Mumbai', areas: ['Powai', 'Hiranandani', 'IIT Bombay'] },
  { pincode: '400076', state: 'Maharashtra', district: 'Mumbai', areas: ['Ghatkopar East', 'Pant Nagar', 'Rajawadi'] },
  { pincode: '400077', state: 'Maharashtra', district: 'Mumbai', areas: ['Mulund East', 'Nahur', 'Bhandup East'] },
  { pincode: '400078', state: 'Maharashtra', district: 'Mumbai', areas: ['Bhandup West', 'Kanjurmarg', 'LBS Marg'] },
  { pincode: '400079', state: 'Maharashtra', district: 'Mumbai', areas: ['Vikhroli East', 'Surya Nagar', 'Kannamwar Nagar'] },
  { pincode: '400080', state: 'Maharashtra', district: 'Mumbai', areas: ['Mulund West', 'Zaver Road', 'MG Road'] },
  { pincode: '400081', state: 'Maharashtra', district: 'Mumbai', areas: ['Mulund Colony', 'Mulund East', 'Nahur'] },
  { pincode: '400082', state: 'Maharashtra', district: 'Mumbai', areas: ['Chembur Colony', 'RCF Colony', 'Swastik Park'] },
  { pincode: '400083', state: 'Maharashtra', district: 'Mumbai', areas: ['Ghatkopar East', 'Kirol Road', 'Asalpha'] },
  { pincode: '400084', state: 'Maharashtra', district: 'Mumbai', areas: ['Trombay', 'Mankhurd', 'Chembur East'] },
  { pincode: '400085', state: 'Maharashtra', district: 'Mumbai', areas: ['Bhandup East', 'Sonapur', 'Bhandup Village'] },
  { pincode: '400086', state: 'Maharashtra', district: 'Mumbai', areas: ['Ghatkopar East', 'Vidyavihar', 'LBS Marg'] },
  { pincode: '400087', state: 'Maharashtra', district: 'Mumbai', areas: ['Chembur', 'Diamond Garden', 'Basant Park'] },
  { pincode: '400088', state: 'Maharashtra', district: 'Mumbai', areas: ['Tilak Nagar', 'Chembur', 'Sion Trombay Road'] },
  { pincode: '400089', state: 'Maharashtra', district: 'Mumbai', areas: ['Govandi', 'Deonar', 'Shivaji Nagar'] },
  { pincode: '400091', state: 'Maharashtra', district: 'Mumbai', areas: ['Borivali East', 'Magathane', 'Kasturba Cross Road'] },
  { pincode: '400092', state: 'Maharashtra', district: 'Mumbai', areas: ['Borivali West', 'Gorai', 'Mandapeshwar'] },
  { pincode: '400093', state: 'Maharashtra', district: 'Mumbai', areas: ['Dahisar East', 'Anand Nagar', 'Rawalpada'] },
  { pincode: '400094', state: 'Maharashtra', district: 'Mumbai', areas: ['Dahisar West', 'Shimpoli', 'SV Road'] },
  { pincode: '400095', state: 'Maharashtra', district: 'Mumbai', areas: ['Malad East', 'Kurar Village', 'Dindoshi'] },
  { pincode: '400096', state: 'Maharashtra', district: 'Mumbai', areas: ['Kandivali East', 'Thakur Village', 'Akurli Road'] },
  { pincode: '400097', state: 'Maharashtra', district: 'Mumbai', areas: ['Malad East', 'Maroshi', 'Rani Sati Marg'] },
  { pincode: '400098', state: 'Maharashtra', district: 'Mumbai', areas: ['Malad West', 'Jankalyan Nagar', 'Pushpa Park'] },
  { pincode: '400099', state: 'Maharashtra', district: 'Mumbai', areas: ['Goregaon West', 'MG Road', 'SV Road'] },
  { pincode: '400101', state: 'Maharashtra', district: 'Mumbai', areas: ['Kandivali East', 'Lokhandwala Township', 'Mahavir Nagar'] },
  { pincode: '400102', state: 'Maharashtra', district: 'Mumbai', areas: ['Andheri East', 'Chakala', 'Airport Area'] },
  { pincode: '400103', state: 'Maharashtra', district: 'Mumbai', areas: ['Jogeshwari East', 'MIDC', 'Majas'] },
  { pincode: '400104', state: 'Maharashtra', district: 'Mumbai Suburban', areas: ['Mira Road', 'Bhayandar East'] },

  // ═══ NAVI MUMBAI ═══
  { pincode: '400614', state: 'Maharashtra', district: 'Thane', areas: ['Panvel', 'Old Panvel', 'New Panvel'] },
  { pincode: '400701', state: 'Maharashtra', district: 'Thane', areas: ['Navi Mumbai', 'Vashi', 'Sanpada'] },
  { pincode: '400703', state: 'Maharashtra', district: 'Thane', areas: ['Nerul', 'Seawoods', 'NRI Complex'] },
  { pincode: '400705', state: 'Maharashtra', district: 'Thane', areas: ['Belapur', 'CBD Belapur', 'Kharghar'] },
  { pincode: '400706', state: 'Maharashtra', district: 'Thane', areas: ['Airoli', 'Kopar Khairane', 'Ghansoli'] },
  { pincode: '400708', state: 'Maharashtra', district: 'Thane', areas: ['Turbhe', 'MIDC Turbhe', 'Sanpada East'] },
  { pincode: '400709', state: 'Maharashtra', district: 'Thane', areas: ['Kharghar', 'Sector 1-20', 'Owe'] },
  { pincode: '400710', state: 'Maharashtra', district: 'Thane', areas: ['Kalamboli', 'Panvel', 'Roadpali'] },

  // ═══ THANE ═══
  { pincode: '400601', state: 'Maharashtra', district: 'Thane', areas: ['Thane West', 'Naupada', 'Ram Maruti Road'] },
  { pincode: '400602', state: 'Maharashtra', district: 'Thane', areas: ['Thane East', 'Kopri', 'Eastern Express Highway'] },
  { pincode: '400603', state: 'Maharashtra', district: 'Thane', areas: ['Thane West', 'Ghodbunder Road', 'Manpada'] },
  { pincode: '400604', state: 'Maharashtra', district: 'Thane', areas: ['Thane East', 'Wagle Estate', 'MIDC'] },
  { pincode: '400605', state: 'Maharashtra', district: 'Thane', areas: ['Thane West', 'Pokhran Road', 'Majiwada'] },
  { pincode: '400606', state: 'Maharashtra', district: 'Thane', areas: ['Thane West', 'Kolshet', 'Balkum'] },
  { pincode: '400607', state: 'Maharashtra', district: 'Thane', areas: ['Thane West', 'Gaimukh', 'Brahmand'] },
  { pincode: '400610', state: 'Maharashtra', district: 'Thane', areas: ['Thane East', 'Airoli', 'Mulund Check Naka'] },
  { pincode: '400612', state: 'Maharashtra', district: 'Thane', areas: ['Dombivli East', 'Manpada', 'Kalyan Shil Road'] },
  { pincode: '400615', state: 'Maharashtra', district: 'Thane', areas: ['Ulhasnagar', 'Camp 1-5', 'Central Avenue'] },

  // ═══ PUNE ═══
  { pincode: '411001', state: 'Maharashtra', district: 'Pune', areas: ['Pune GPO', 'Shivaji Nagar', 'Deccan Gymkhana'] },
  { pincode: '411002', state: 'Maharashtra', district: 'Pune', areas: ['Mangalwar Peth', 'Budhwar Peth', 'Shukrawar Peth'] },
  { pincode: '411003', state: 'Maharashtra', district: 'Pune', areas: ['Sadashiv Peth', 'Narayan Peth', 'Tilak Road'] },
  { pincode: '411004', state: 'Maharashtra', district: 'Pune', areas: ['Shivaji Nagar', 'Model Colony', 'FC Road'] },
  { pincode: '411005', state: 'Maharashtra', district: 'Pune', areas: ['Shaniwar Peth', 'Kasba Peth', 'Raviwar Peth'] },
  { pincode: '411006', state: 'Maharashtra', district: 'Pune', areas: ['Deccan Gymkhana', 'Erandwane', 'Karve Road'] },
  { pincode: '411007', state: 'Maharashtra', district: 'Pune', areas: ['Ganeshkhind', 'Aundh', 'University of Pune'] },
  { pincode: '411008', state: 'Maharashtra', district: 'Pune', areas: ['Shivajinagar', 'Sangamwadi', 'Yerawada'] },
  { pincode: '411009', state: 'Maharashtra', district: 'Pune', areas: ['Kothrud', 'Paud Road', 'Karve Nagar'] },
  { pincode: '411011', state: 'Maharashtra', district: 'Pune', areas: ['Bibvewadi', 'Dhankawadi', 'Katraj'] },
  { pincode: '411012', state: 'Maharashtra', district: 'Pune', areas: ['Pune Cantonment', 'Wanawadi', 'Fatima Nagar'] },
  { pincode: '411013', state: 'Maharashtra', district: 'Pune', areas: ['Dapodi', 'Bopodi', 'Khadki'] },
  { pincode: '411014', state: 'Maharashtra', district: 'Pune', areas: ['Hadapsar', 'Mundhwa', 'Keshav Nagar'] },
  { pincode: '411015', state: 'Maharashtra', district: 'Pune', areas: ['Parvati', 'Sinhagad Road', 'Anand Nagar'] },
  { pincode: '411016', state: 'Maharashtra', district: 'Pune', areas: ['Kothrud', 'Bavdhan', 'Sutarwadi'] },
  { pincode: '411017', state: 'Maharashtra', district: 'Pune', areas: ['Navi Peth', 'Swargate', 'Market Yard'] },
  { pincode: '411018', state: 'Maharashtra', district: 'Pune', areas: ['Erandwane', 'Law College Road', 'Prabhat Road'] },
  { pincode: '411019', state: 'Maharashtra', district: 'Pune', areas: ['Undri', 'Pisoli', 'NIBM Road'] },
  { pincode: '411020', state: 'Maharashtra', district: 'Pune', areas: ['Pimpri', 'Chinchwad', 'Pradhikaran'] },
  { pincode: '411021', state: 'Maharashtra', district: 'Pune', areas: ['Hinjewadi', 'Wakad', 'Pimple Saudagar'] },
  { pincode: '411027', state: 'Maharashtra', district: 'Pune', areas: ['Pashan', 'Sus Road', 'Baner'] },
  { pincode: '411028', state: 'Maharashtra', district: 'Pune', areas: ['Kothrud', 'Warje', 'Karve Nagar'] },
  { pincode: '411030', state: 'Maharashtra', district: 'Pune', areas: ['Bavdhan', 'NDA Road', 'Pashan'] },
  { pincode: '411032', state: 'Maharashtra', district: 'Pune', areas: ['Wagholi', 'Kharadi', 'Viman Nagar'] },
  { pincode: '411033', state: 'Maharashtra', district: 'Pune', areas: ['Mundhwa', 'Hadapsar', 'Koregaon Park'] },
  { pincode: '411036', state: 'Maharashtra', district: 'Pune', areas: ['Dhanori', 'Vishrantwadi', 'Kalyani Nagar'] },
  { pincode: '411037', state: 'Maharashtra', district: 'Pune', areas: ['Kondhwa', 'Wanawadi', 'NIBM'] },
  { pincode: '411038', state: 'Maharashtra', district: 'Pune', areas: ['Kalyani Nagar', 'Koregaon Park', 'Boat Club Road'] },
  { pincode: '411039', state: 'Maharashtra', district: 'Pune', areas: ['Wanawadi', 'Salisbury Park', 'Ghorpadi'] },
  { pincode: '411040', state: 'Maharashtra', district: 'Pune', areas: ['Swargate', 'Bibvewadi', 'Balaji Nagar'] },
  { pincode: '411041', state: 'Maharashtra', district: 'Pune', areas: ['Kharadi', 'Chandannagar', 'Viman Nagar'] },
  { pincode: '411042', state: 'Maharashtra', district: 'Pune', areas: ['Lohegaon', 'Dhanori', 'Airport'] },
  { pincode: '411043', state: 'Maharashtra', district: 'Pune', areas: ['Kondhwa Budruk', 'Undri', 'Handewadi'] },
  { pincode: '411044', state: 'Maharashtra', district: 'Pune', areas: ['Pimpri', 'Chinchwad', 'Bhosari'] },
  { pincode: '411045', state: 'Maharashtra', district: 'Pune', areas: ['Baner', 'Balewadi', 'Aundh'] },
  { pincode: '411046', state: 'Maharashtra', district: 'Pune', areas: ['Katraj', 'Kondhwa', 'Ambegaon'] },
  { pincode: '411047', state: 'Maharashtra', district: 'Pune', areas: ['Lohegaon', 'Wadgaon Sheri', 'Kalyani Nagar'] },
  { pincode: '411048', state: 'Maharashtra', district: 'Pune', areas: ['Warje', 'Karve Nagar', 'Kothrud'] },
  { pincode: '411052', state: 'Maharashtra', district: 'Pune', areas: ['Akurdi', 'Nigdi', 'Pradhikaran'] },
  { pincode: '411057', state: 'Maharashtra', district: 'Pune', areas: ['Aundh', 'Baner', 'ITI Road'] },
  { pincode: '411058', state: 'Maharashtra', district: 'Pune', areas: ['Pimple Nilakh', 'Pimple Gurav', 'Wakad'] },

  // ═══ NAGPUR ═══
  { pincode: '440001', state: 'Maharashtra', district: 'Nagpur', areas: ['Nagpur GPO', 'Sitabuldi', 'Sadar'] },
  { pincode: '440002', state: 'Maharashtra', district: 'Nagpur', areas: ['Mahal', 'Itwari', 'Cotton Market'] },
  { pincode: '440003', state: 'Maharashtra', district: 'Nagpur', areas: ['Ramdaspeth', 'Dharampeth', 'Civil Lines'] },
  { pincode: '440004', state: 'Maharashtra', district: 'Nagpur', areas: ['Pardi', 'Empress Mill', 'Gandhibagh'] },
  { pincode: '440005', state: 'Maharashtra', district: 'Nagpur', areas: ['Sadar', 'Cantonment', 'Seminary Hills'] },
  { pincode: '440006', state: 'Maharashtra', district: 'Nagpur', areas: ['Nagpur University', 'Amravati Road', 'Shankar Nagar'] },
  { pincode: '440008', state: 'Maharashtra', district: 'Nagpur', areas: ['Ajni', 'Laxmi Nagar', 'Byramji Town'] },
  { pincode: '440009', state: 'Maharashtra', district: 'Nagpur', areas: ['Jaripatka', 'Indora', 'Lakadganj'] },
  { pincode: '440010', state: 'Maharashtra', district: 'Nagpur', areas: ['Dharampeth', 'Laxmi Nagar', 'Bajaj Nagar'] },
  { pincode: '440012', state: 'Maharashtra', district: 'Nagpur', areas: ['Dhantoli', 'Hanuman Nagar', 'Gokulpeth'] },
  { pincode: '440013', state: 'Maharashtra', district: 'Nagpur', areas: ['Nandanwan', 'Sakkardara', 'Tajbagh'] },
  { pincode: '440014', state: 'Maharashtra', district: 'Nagpur', areas: ['Pratap Nagar', 'Narendra Nagar', 'Manewada'] },
  { pincode: '440015', state: 'Maharashtra', district: 'Nagpur', areas: ['Cotton Market', 'Wardhaman Nagar', 'Pachpaoli'] },
  { pincode: '440016', state: 'Maharashtra', district: 'Nagpur', areas: ['Kamptee Road', 'Gittikhadan', 'Parsodi'] },
  { pincode: '440017', state: 'Maharashtra', district: 'Nagpur', areas: ['Trimurti Nagar', 'Manish Nagar', 'Somalwada'] },
  { pincode: '440018', state: 'Maharashtra', district: 'Nagpur', areas: ['Koradi Road', 'Besa', 'Pipla'] },
  { pincode: '440019', state: 'Maharashtra', district: 'Nagpur', areas: ['Hingna', 'MIDC', 'Wadi'] },
  { pincode: '440020', state: 'Maharashtra', district: 'Nagpur', areas: ['Butibori', 'MIDC Butibori'] },
  { pincode: '440022', state: 'Maharashtra', district: 'Nagpur', areas: ['Wardhaman Nagar', 'Bhandara Road', 'Kamptee'] },
  { pincode: '440024', state: 'Maharashtra', district: 'Nagpur', areas: ['Khamla', 'Shivaji Nagar', 'Friends Colony'] },
  { pincode: '440025', state: 'Maharashtra', district: 'Nagpur', areas: ['Wardha Road', 'Manewada', 'Beltarodi'] },
  { pincode: '440027', state: 'Maharashtra', district: 'Nagpur', areas: ['Umred Road', 'Nari', 'Pardi'] },
  { pincode: '440030', state: 'Maharashtra', district: 'Nagpur', areas: ['Amravati Road', 'Ring Road', 'Wathoda'] },
  { pincode: '440032', state: 'Maharashtra', district: 'Nagpur', areas: ['Lakadganj', 'Panchpaoli', 'Godhni'] },
  { pincode: '440033', state: 'Maharashtra', district: 'Nagpur', areas: ['Narendra Nagar', 'Narsala', 'Hudkeshwar'] },
  { pincode: '440034', state: 'Maharashtra', district: 'Nagpur', areas: ['Mankapur', 'Koradi', 'Fetri'] },
  { pincode: '440035', state: 'Maharashtra', district: 'Nagpur', areas: ['Wadi', 'Besa Road', 'Pipla'] },

  // ═══ NASHIK ═══
  { pincode: '422001', state: 'Maharashtra', district: 'Nashik', areas: ['Nashik City', 'Panchavati', 'Main Road'] },
  { pincode: '422002', state: 'Maharashtra', district: 'Nashik', areas: ['Nashik Road', 'Deolali', 'Vilholi'] },
  { pincode: '422003', state: 'Maharashtra', district: 'Nashik', areas: ['Nashik West', 'College Road', 'Ashok Stambh'] },
  { pincode: '422005', state: 'Maharashtra', district: 'Nashik', areas: ['Satpur', 'MIDC', 'Ambad'] },
  { pincode: '422006', state: 'Maharashtra', district: 'Nashik', areas: ['Panchavati', 'Mhasrul', 'Gangapur Road'] },
  { pincode: '422007', state: 'Maharashtra', district: 'Nashik', areas: ['Gangapur Road', 'CIDCO', 'Indira Nagar'] },
  { pincode: '422008', state: 'Maharashtra', district: 'Nashik', areas: ['Pathardi Phata', 'Pavan Nagar', 'Nashik Road'] },
  { pincode: '422009', state: 'Maharashtra', district: 'Nashik', areas: ['Cidco', 'Satpur Colony', 'Pipeline Road'] },
  { pincode: '422010', state: 'Maharashtra', district: 'Nashik', areas: ['Dwarka', 'Gangapur Road', 'College Road'] },
  { pincode: '422011', state: 'Maharashtra', district: 'Nashik', areas: ['Deolali Camp', 'Bhagur', 'Anandvalli'] },
  { pincode: '422013', state: 'Maharashtra', district: 'Nashik', areas: ['Cidco Nashik', 'CBS', 'Shalimar'] },

  // ═══ AURANGABAD ═══
  { pincode: '431001', state: 'Maharashtra', district: 'Aurangabad', areas: ['Aurangabad City', 'Gulmandi', 'Kranti Chowk'] },
  { pincode: '431002', state: 'Maharashtra', district: 'Aurangabad', areas: ['Cantonment', 'Cidco', 'Hudco'] },
  { pincode: '431003', state: 'Maharashtra', district: 'Aurangabad', areas: ['Cidco N-1 to N-5', 'Waluj', 'MIDC'] },
  { pincode: '431004', state: 'Maharashtra', district: 'Aurangabad', areas: ['Garkheda', 'Satara Parisar', 'Beed Bypass'] },
  { pincode: '431005', state: 'Maharashtra', district: 'Aurangabad', areas: ['Jalna Road', 'Seven Hills', 'MIDC Chikalthana'] },

  // ═══ KOLHAPUR ═══
  { pincode: '416001', state: 'Maharashtra', district: 'Kolhapur', areas: ['Kolhapur City', 'Shahupuri', 'Rajarampuri'] },
  { pincode: '416002', state: 'Maharashtra', district: 'Kolhapur', areas: ['Shivaji Park', 'Tarabai Park', 'Rankala'] },
  { pincode: '416003', state: 'Maharashtra', district: 'Kolhapur', areas: ['Nagala Park', 'Shivaji University', 'Sangli Road'] },
  { pincode: '416004', state: 'Maharashtra', district: 'Kolhapur', areas: ['Laxmipuri', 'Kasba Bawda', 'Morewadi'] },
  { pincode: '416005', state: 'Maharashtra', district: 'Kolhapur', areas: ['Kadamwadi', 'Pachgaon', 'Shiroli MIDC'] },
  { pincode: '416006', state: 'Maharashtra', district: 'Kolhapur', areas: ['Kolhapur North', 'Gandhinagar', 'Dabholkar Corner'] },

  // ═══ SOLAPUR ═══
  { pincode: '413001', state: 'Maharashtra', district: 'Solapur', areas: ['Solapur City', 'Main Road', 'Budhwar Peth'] },
  { pincode: '413002', state: 'Maharashtra', district: 'Solapur', areas: ['Vijapur Road', 'Railway Lines', 'Akkalkot Road'] },
  { pincode: '413003', state: 'Maharashtra', district: 'Solapur', areas: ['Solapur Cantonment', 'Murarji Peth'] },
  { pincode: '413004', state: 'Maharashtra', district: 'Solapur', areas: ['Majrewadi', 'Kumatha Naka', 'Nehru Nagar'] },
  { pincode: '413005', state: 'Maharashtra', district: 'Solapur', areas: ['Jule Solapur', 'New City', 'Sadar Bazar'] },
  { pincode: '413006', state: 'Maharashtra', district: 'Solapur', areas: ['Latur Road', 'Hotgi Road', 'Saat Rasta'] },

  // ═══ RAIGAD ═══
  { pincode: '410201', state: 'Maharashtra', district: 'Raigad', areas: ['Panvel', 'Kharghar', 'Kamothe'] },
  { pincode: '410206', state: 'Maharashtra', district: 'Raigad', areas: ['Khopoli', 'Pali', 'Pen'] },
  { pincode: '410210', state: 'Maharashtra', district: 'Raigad', areas: ['Alibag', 'Rewas', 'Kashid'] },
  { pincode: '410218', state: 'Maharashtra', district: 'Raigad', areas: ['Uran', 'JNPT', 'Nhava'] },

  // ═══ SATARA ═══
  { pincode: '415001', state: 'Maharashtra', district: 'Satara', areas: ['Satara City', 'Sadar Bazar', 'Power House Road'] },
  { pincode: '415002', state: 'Maharashtra', district: 'Satara', areas: ['Satara', 'Shaniwar Peth', 'Raviwar Peth'] },
  { pincode: '415110', state: 'Maharashtra', district: 'Satara', areas: ['Karad', 'Malkapur', 'Supane'] },

  // ═══ SANGLI ═══
  { pincode: '416416', state: 'Maharashtra', district: 'Sangli', areas: ['Sangli City', 'Vishrambag', 'Ganapati Peth'] },
  { pincode: '416410', state: 'Maharashtra', district: 'Sangli', areas: ['Miraj', 'Station Road', 'Sangli-Miraj Road'] },

  // ═══ AHMEDNAGAR ═══
  { pincode: '414001', state: 'Maharashtra', district: 'Ahmednagar', areas: ['Ahmednagar City', 'Station Road', 'Nagar'] },
  { pincode: '414002', state: 'Maharashtra', district: 'Ahmednagar', areas: ['Savedi', 'Bhingar', 'Camp'] },
  { pincode: '414003', state: 'Maharashtra', district: 'Ahmednagar', areas: ['Kedgaon', 'MIDC', 'Shendra'] },

  // ═══ WEST BENGAL — KOLKATA ═══
  { pincode: '700001', state: 'West Bengal', district: 'Kolkata', areas: ['GPO', 'BBD Bagh', 'Dalhousie'] },
  { pincode: '700002', state: 'West Bengal', district: 'Kolkata', areas: ['Bowbazar', 'Central Avenue', 'Chandni Chowk'] },
  { pincode: '700003', state: 'West Bengal', district: 'Kolkata', areas: ['Esplanade', 'Dharmatala', 'New Market'] },
  { pincode: '700004', state: 'West Bengal', district: 'Kolkata', areas: ['Burrabazar', 'Jorasanko', 'Girish Park'] },
  { pincode: '700005', state: 'West Bengal', district: 'Kolkata', areas: ['Bagbazar', 'Chitpur', 'Kumartuli'] },
  { pincode: '700006', state: 'West Bengal', district: 'Kolkata', areas: ['Shyambazar', 'Hatibagan', 'Bidhan Sarani'] },
  { pincode: '700007', state: 'West Bengal', district: 'Kolkata', areas: ['Jorasanko', 'Pathuriaghata', 'College Street'] },
  { pincode: '700008', state: 'West Bengal', district: 'Kolkata', areas: ['Kidderpore', 'Watgunge', 'Ekbalpur'] },
  { pincode: '700009', state: 'West Bengal', district: 'Kolkata', areas: ['Hastings', 'Maidan', 'Princep Ghat'] },
  { pincode: '700010', state: 'West Bengal', district: 'Kolkata', areas: ['Maniktala', 'Belgachia', 'Rajabazar'] },
  { pincode: '700011', state: 'West Bengal', district: 'Kolkata', areas: ['Salkia', 'Liluah', 'Belur'] },
  { pincode: '700012', state: 'West Bengal', district: 'Kolkata', areas: ['Entally', 'Sealdah', 'Beleghata'] },
  { pincode: '700013', state: 'West Bengal', district: 'Kolkata', areas: ['Park Circus', 'Taltala', 'Ripon Street'] },
  { pincode: '700014', state: 'West Bengal', district: 'Kolkata', areas: ['Bhowanipore', 'Kalighat', 'Hazra'] },
  { pincode: '700015', state: 'West Bengal', district: 'Kolkata', areas: ['Kankurgachi', 'Phoolbagan', 'Parsibagan'] },
  { pincode: '700016', state: 'West Bengal', district: 'Kolkata', areas: ['Circus Avenue', 'AJC Bose Road', 'Elgin Road'] },
  { pincode: '700017', state: 'West Bengal', district: 'Kolkata', areas: ['Park Street', 'Camac Street', 'Theatre Road'] },
  { pincode: '700018', state: 'West Bengal', district: 'Kolkata', areas: ['Alipore', 'National Library', 'Zoo'] },
  { pincode: '700019', state: 'West Bengal', district: 'Kolkata', areas: ['Ballygunge', 'Gariahat', 'Golpark'] },
  { pincode: '700020', state: 'West Bengal', district: 'Kolkata', areas: ['Kalighat', 'Rashbehari Avenue', 'Chetla'] },
  { pincode: '700021', state: 'West Bengal', district: 'Kolkata', areas: ['Raja Bazar', 'CIT Road', 'Ultadanga'] },
  { pincode: '700022', state: 'West Bengal', district: 'Kolkata', areas: ['Lake Market', 'Southern Avenue', 'Dhakuria'] },
  { pincode: '700023', state: 'West Bengal', district: 'Kolkata', areas: ['Garden Reach', 'Taratala', 'Metiabruz'] },
  { pincode: '700024', state: 'West Bengal', district: 'Kolkata', areas: ['Tiljala', 'Topsia', 'Tangra'] },
  { pincode: '700025', state: 'West Bengal', district: 'Kolkata', areas: ['Bhowanipore', 'Sarat Bose Road', 'Lansdowne'] },
  { pincode: '700026', state: 'West Bengal', district: 'Kolkata', areas: ['Ballygunge', 'Jodhpur Park', 'South End Park'] },
  { pincode: '700027', state: 'West Bengal', district: 'Kolkata', areas: ['Alipore', 'Tollygunge', 'New Alipore'] },
  { pincode: '700028', state: 'West Bengal', district: 'Kolkata', areas: ['Tollygunge', 'Kudghat', 'Bansdroni'] },
  { pincode: '700029', state: 'West Bengal', district: 'Kolkata', areas: ['Dhakuria', 'Gariahat', 'Jodhpur Park'] },
  { pincode: '700030', state: 'West Bengal', district: 'Kolkata', areas: ['Tangra', 'Tiljala', 'EM Bypass'] },
  { pincode: '700031', state: 'West Bengal', district: 'Kolkata', areas: ['Beliaghata', 'CIT Road', 'Narkeldanga'] },
  { pincode: '700032', state: 'West Bengal', district: 'Kolkata', areas: ['Beleghata', 'Maniktala', 'CIT Road'] },
  { pincode: '700033', state: 'West Bengal', district: 'Kolkata', areas: ['Kasba', 'EM Bypass', 'Anandapur'] },
  { pincode: '700034', state: 'West Bengal', district: 'Kolkata', areas: ['Dum Dum', 'Airport', 'South Dum Dum'] },
  { pincode: '700035', state: 'West Bengal', district: 'Kolkata', areas: ['Cossipur', 'Belgachia', 'Chitpur'] },
  { pincode: '700036', state: 'West Bengal', district: 'Kolkata', areas: ['Sinthee', 'Lake Town', 'Bangur'] },
  { pincode: '700037', state: 'West Bengal', district: 'Kolkata', areas: ['Belgharia', 'Kamarhati', 'Ariadaha'] },
  { pincode: '700038', state: 'West Bengal', district: 'Kolkata', areas: ['Santoshpur', 'Garia', 'Narendrapur'] },
  { pincode: '700039', state: 'West Bengal', district: 'Kolkata', areas: ['Behala', 'Parnashree', 'Sakherbazar'] },
  { pincode: '700040', state: 'West Bengal', district: 'Kolkata', areas: ['New Alipore', 'Chetla', 'Bakery Road'] },
  { pincode: '700041', state: 'West Bengal', district: 'Kolkata', areas: ['Netaji Nagar', 'Regent Park', 'South City'] },
  { pincode: '700042', state: 'West Bengal', district: 'Kolkata', areas: ['Jadavpur', 'Dhakuria', 'Jadavpur University'] },
  { pincode: '700043', state: 'West Bengal', district: 'Kolkata', areas: ['Thakurpukur', 'Joka', 'Pailan'] },
  { pincode: '700044', state: 'West Bengal', district: 'Kolkata', areas: ['South Suburban', 'Behala', 'Barisha'] },
  { pincode: '700045', state: 'West Bengal', district: 'Kolkata', areas: ['Lake Gardens', 'Prince Anwar Shah Road'] },
  { pincode: '700046', state: 'West Bengal', district: 'Kolkata', areas: ['Dhapa', 'EM Bypass', 'Science City'] },
  { pincode: '700047', state: 'West Bengal', district: 'Kolkata', areas: ['Bansdroni', 'Naktala', 'Garia'] },
  { pincode: '700048', state: 'West Bengal', district: 'Kolkata', areas: ['Belghoria', 'BT Road', 'Dunlop'] },
  { pincode: '700049', state: 'West Bengal', district: 'Kolkata', areas: ['Baranagar', 'Dakshineswar', 'Titagarh'] },
  { pincode: '700050', state: 'West Bengal', district: 'Kolkata', areas: ['Dum Dum', 'Nagerbazar', 'Motilal Colony'] },
  { pincode: '700051', state: 'West Bengal', district: 'Kolkata', areas: ['Ultadanga', 'Bagmari', 'Canal Circular Road'] },
  { pincode: '700052', state: 'West Bengal', district: 'Kolkata', areas: ['Shyamnagar', 'Panihati', 'Sodepur'] },
  { pincode: '700053', state: 'West Bengal', district: 'Kolkata', areas: ['Birati', 'Madhyamgram', 'New Barrackpur'] },
  { pincode: '700054', state: 'West Bengal', district: 'Kolkata', areas: ['Airport', 'Rajarhat', 'New Town'] },
  { pincode: '700055', state: 'West Bengal', district: 'Kolkata', areas: ['Sealdah', 'Moulali', 'Chandni Chowk'] },
  { pincode: '700056', state: 'West Bengal', district: 'Kolkata', areas: ['Dum Dum Cantonment', 'Jessore Road'] },
  { pincode: '700058', state: 'West Bengal', district: 'Kolkata', areas: ['Maheshtala', 'Budge Budge', 'Batanagar'] },
  { pincode: '700059', state: 'West Bengal', district: 'Kolkata', areas: ['Santragachi', 'Shibpur', 'Botanic Garden'] },
  { pincode: '700060', state: 'West Bengal', district: 'Kolkata', areas: ['Baruipur', 'Sonarpur', 'Rajpur'] },
  { pincode: '700061', state: 'West Bengal', district: 'Kolkata', areas: ['Lake Town', 'VIP Road', 'Kaikhali'] },
  { pincode: '700064', state: 'West Bengal', district: 'Kolkata', areas: ['Mukundapur', 'EM Bypass', 'Patuli'] },
  { pincode: '700065', state: 'West Bengal', district: 'Kolkata', areas: ['Garia', 'Boral', 'Narendrapur'] },
  { pincode: '700066', state: 'West Bengal', district: 'Kolkata', areas: ['Santoshpur', 'Haltu', 'Bosepukur'] },
  { pincode: '700068', state: 'West Bengal', district: 'Kolkata', areas: ['Baghajatin', 'Regent Estate', 'NSC Bose Road'] },
  { pincode: '700069', state: 'West Bengal', district: 'Kolkata', areas: ['Behala', 'Parnashree Pally', 'Manton'] },
  { pincode: '700070', state: 'West Bengal', district: 'Kolkata', areas: ['Kalikapur', 'EM Bypass', 'Haridevpur'] },
  { pincode: '700071', state: 'West Bengal', district: 'Kolkata', areas: ['Regent Park', 'Anwar Shah Road', 'Ruby'] },
  { pincode: '700074', state: 'West Bengal', district: 'Kolkata', areas: ['Barasat', 'Madhyamgram', 'Hridaypur'] },
  { pincode: '700075', state: 'West Bengal', district: 'Kolkata', areas: ['Sodepur', 'Agarpara', 'Khardah'] },
  { pincode: '700078', state: 'West Bengal', district: 'Kolkata', areas: ['Joka', 'Diamond Harbour Road', 'Thakurpukur'] },
  { pincode: '700080', state: 'West Bengal', district: 'Kolkata', areas: ['New Town', 'Rajarhat', 'Action Area I'] },
  { pincode: '700084', state: 'West Bengal', district: 'Kolkata', areas: ['VIP Road', 'Baguiati', 'Teghoria'] },
  { pincode: '700091', state: 'West Bengal', district: 'Kolkata', areas: ['Kasba Industrial Estate', 'Ruby', 'EM Bypass'] },
  { pincode: '700094', state: 'West Bengal', district: 'Kolkata', areas: ['Garia Station', 'Naktala', 'Kamalgazi'] },
  { pincode: '700095', state: 'West Bengal', district: 'Kolkata', areas: ['Patuli', 'EM Bypass', 'Panchasayar'] },
  { pincode: '700097', state: 'West Bengal', district: 'Kolkata', areas: ['Rajarhat', 'New Town Action Area II', 'Eco Park'] },
  { pincode: '700098', state: 'West Bengal', district: 'Kolkata', areas: ['New Town Action Area III', 'Rajarhat Gopalpur'] },
  { pincode: '700099', state: 'West Bengal', district: 'Kolkata', areas: ['Salt Lake', 'Sector V', 'Bidhannagar'] },
  { pincode: '700100', state: 'West Bengal', district: 'Kolkata', areas: ['Narendrapur', 'Sonarpur', 'Baruipur'] },
  { pincode: '700101', state: 'West Bengal', district: 'Kolkata', areas: ['Garia', 'Kamalgazi', 'Sonarpur'] },
  { pincode: '700102', state: 'West Bengal', district: 'Kolkata', areas: ['Rajarhat', 'Chinar Park', 'City Centre 2'] },
  { pincode: '700103', state: 'West Bengal', district: 'Kolkata', areas: ['Madhyamgram', 'Barasat', 'Nilgunj'] },
  { pincode: '700104', state: 'West Bengal', district: 'Kolkata', areas: ['New Town', 'Action Area IID', 'Biswa Bangla Gate'] },
  { pincode: '700105', state: 'West Bengal', district: 'Kolkata', areas: ['Salt Lake Sector I-III', 'Karunamayee'] },
  { pincode: '700106', state: 'West Bengal', district: 'Kolkata', areas: ['Salt Lake', 'Sector IV', 'Central Park'] },
  { pincode: '700107', state: 'West Bengal', district: 'Kolkata', areas: ['VIP Road', 'Airport Gate 1', 'Kaikhali'] },

  // ═══ WEST BENGAL — HOWRAH ═══
  { pincode: '711101', state: 'West Bengal', district: 'Howrah', areas: ['Howrah Station', 'Pilkhana', 'Dobson Road'] },
  { pincode: '711102', state: 'West Bengal', district: 'Howrah', areas: ['Shibpur', 'Botanic Garden', 'BE College'] },
  { pincode: '711103', state: 'West Bengal', district: 'Howrah', areas: ['Bally', 'Belur', 'Liluah'] },
  { pincode: '711104', state: 'West Bengal', district: 'Howrah', areas: ['Santragachi', 'Botanical Garden', 'Ramrajatala'] },
  { pincode: '711106', state: 'West Bengal', district: 'Howrah', areas: ['Kadamtala', 'Golabari', 'Dasnagar'] },
  { pincode: '711107', state: 'West Bengal', district: 'Howrah', areas: ['Mahata', 'Salkia', 'Ghusuri'] },
  { pincode: '711108', state: 'West Bengal', district: 'Howrah', areas: ['Mourigram', 'Bamunari', 'Bakshi'] },
  { pincode: '711109', state: 'West Bengal', district: 'Howrah', areas: ['Andul', 'Mundamala', 'Panchanantala'] },
  { pincode: '711110', state: 'West Bengal', district: 'Howrah', areas: ['Domjur', 'Panchla', 'Sankrail'] },
  { pincode: '711112', state: 'West Bengal', district: 'Howrah', areas: ['Uluberia', 'Bagnan', 'Mahishadal'] },

  // ═══ WEST BENGAL — NORTH 24 PARGANAS ═══
  { pincode: '700124', state: 'West Bengal', district: 'North 24 Parganas', areas: ['Barasat', 'Kazipara', 'Talpukur'] },
  { pincode: '700125', state: 'West Bengal', district: 'North 24 Parganas', areas: ['Barrackpore', 'Titagarh', 'Ichhapur'] },
  { pincode: '700126', state: 'West Bengal', district: 'North 24 Parganas', areas: ['Basirhat', 'Taki', 'Hasnabad'] },
  { pincode: '700127', state: 'West Bengal', district: 'North 24 Parganas', areas: ['Bongaon', 'Gaighata', 'Bagda'] },
  { pincode: '700128', state: 'West Bengal', district: 'North 24 Parganas', areas: ['Habra', 'Ashoknagar', 'Gobardanga'] },
  { pincode: '700129', state: 'West Bengal', district: 'North 24 Parganas', areas: ['Dum Dum', 'New Barrackpore', 'Halisahar'] },
  { pincode: '700130', state: 'West Bengal', district: 'North 24 Parganas', areas: ['Naihati', 'Kalyani', 'Kanchrapara'] },
  { pincode: '743201', state: 'West Bengal', district: 'North 24 Parganas', areas: ['Barasat Town', 'Nilgunj Road', 'Talpukur'] },
  { pincode: '743268', state: 'West Bengal', district: 'North 24 Parganas', areas: ['Basirhat', 'Hingalganj', 'Sandeshkhali'] },

  // ═══ WEST BENGAL — SOUTH 24 PARGANAS ═══
  { pincode: '700140', state: 'West Bengal', district: 'South 24 Parganas', areas: ['Diamond Harbour', 'Falta', 'Kakdwip'] },
  { pincode: '700141', state: 'West Bengal', district: 'South 24 Parganas', areas: ['Baruipur', 'Canning', 'Joynagar'] },
  { pincode: '700142', state: 'West Bengal', district: 'South 24 Parganas', areas: ['Budge Budge', 'Maheshtala', 'Pujali'] },
  { pincode: '700143', state: 'West Bengal', district: 'South 24 Parganas', areas: ['Sonarpur', 'Rajpur', 'Subhasgram'] },
  { pincode: '700144', state: 'West Bengal', district: 'South 24 Parganas', areas: ['Behala', 'Bishnupur', 'Joka'] },
  { pincode: '743302', state: 'West Bengal', district: 'South 24 Parganas', areas: ['Diamond Harbour', 'Sarisha', 'Raidighi'] },
  { pincode: '743355', state: 'West Bengal', district: 'South 24 Parganas', areas: ['Kakdwip', 'Sagar', 'Namkhana'] },

  // ═══ WEST BENGAL — HOOGHLY ═══
  { pincode: '712101', state: 'West Bengal', district: 'Hooghly', areas: ['Chinsurah', 'Hooghly', 'Bandel'] },
  { pincode: '712103', state: 'West Bengal', district: 'Hooghly', areas: ['Serampore', 'Rishra', 'Konnagar'] },
  { pincode: '712104', state: 'West Bengal', district: 'Hooghly', areas: ['Chandannagar', 'Mankundu', 'Bhadreswar'] },
  { pincode: '712136', state: 'West Bengal', district: 'Hooghly', areas: ['Dankuni', 'Uttarpara', 'Kotrung'] },
  { pincode: '712201', state: 'West Bengal', district: 'Hooghly', areas: ['Arambagh', 'Pursurah', 'Goghat'] },
  { pincode: '712232', state: 'West Bengal', district: 'Hooghly', areas: ['Tarakeswar', 'Haripal', 'Dhaniakhali'] },

  // ═══ WEST BENGAL — NADIA ═══
  { pincode: '741101', state: 'West Bengal', district: 'Nadia', areas: ['Krishnanagar', 'Nabadwip', 'Santipur'] },
  { pincode: '741201', state: 'West Bengal', district: 'Nadia', areas: ['Ranaghat', 'Chakdah', 'Haringhata'] },
  { pincode: '741235', state: 'West Bengal', district: 'Nadia', areas: ['Kalyani', 'Gayeshpur', 'Shantipur'] },
  { pincode: '741302', state: 'West Bengal', district: 'Nadia', areas: ['Nabadwip', 'Mayapur', 'Jalangi'] },

  // ═══ WEST BENGAL — BARDHAMAN ═══
  { pincode: '713101', state: 'West Bengal', district: 'Bardhaman', areas: ['Burdwan', 'Rajbati', 'GT Road'] },
  { pincode: '713102', state: 'West Bengal', district: 'Bardhaman', areas: ['Durgapur', 'Steel Township', 'City Centre'] },
  { pincode: '713103', state: 'West Bengal', district: 'Bardhaman', areas: ['Durgapur', 'Benachity', 'Bidhannagar'] },
  { pincode: '713104', state: 'West Bengal', district: 'Bardhaman', areas: ['Asansol', 'Burnpur', 'Kulti'] },
  { pincode: '713204', state: 'West Bengal', district: 'Bardhaman', areas: ['Durgapur MIDC', 'Andal', 'Pandaveswar'] },
  { pincode: '713301', state: 'West Bengal', district: 'Bardhaman', areas: ['Asansol', 'Hirapur', 'Barakar'] },
  { pincode: '713304', state: 'West Bengal', district: 'Bardhaman', areas: ['Raniganj', 'Jamuria', 'Ondal'] },

  // ═══ WEST BENGAL — DARJEELING ═══
  { pincode: '734101', state: 'West Bengal', district: 'Darjeeling', areas: ['Darjeeling Town', 'Mall Road', 'Chowrasta'] },
  { pincode: '734102', state: 'West Bengal', district: 'Darjeeling', areas: ['Ghoom', 'Tiger Hill', 'Jorebunglow'] },
  { pincode: '734103', state: 'West Bengal', district: 'Darjeeling', areas: ['Kurseong', 'Dow Hill', 'Mirik'] },
  { pincode: '734104', state: 'West Bengal', district: 'Darjeeling', areas: ['Kalimpong', 'Pedong', 'Lava'] },
  { pincode: '734001', state: 'West Bengal', district: 'Darjeeling', areas: ['Siliguri', 'Hill Cart Road', 'Junction'] },
  { pincode: '734002', state: 'West Bengal', district: 'Darjeeling', areas: ['Siliguri', 'Pradhan Nagar', 'Sevok Road'] },
  { pincode: '734003', state: 'West Bengal', district: 'Darjeeling', areas: ['Siliguri', 'Matigara', 'Sukna'] },
  { pincode: '734004', state: 'West Bengal', district: 'Darjeeling', areas: ['Siliguri', 'Salugara', 'Dagapur'] },
  { pincode: '734005', state: 'West Bengal', district: 'Darjeeling', areas: ['Siliguri', 'Ashram Para', 'Bhaktinagar'] },

  // ═══ WEST BENGAL — MURSHIDABAD ═══
  { pincode: '742101', state: 'West Bengal', district: 'Murshidabad', areas: ['Berhampore', 'Murshidabad', 'Cossimbazar'] },
  { pincode: '742102', state: 'West Bengal', district: 'Murshidabad', areas: ['Lalbag', 'Jangipur', 'Dhulian'] },
  { pincode: '742103', state: 'West Bengal', district: 'Murshidabad', areas: ['Kandi', 'Khargram', 'Nabagram'] },
];

export function lookupPincode(pincode: string): PincodeEntry | undefined {
  return PINCODE_DATABASE.find(entry => entry.pincode === pincode);
}
