import { SelectOption } from '../models';

export const INITIAL_FORM_DATA: Record<string, any> = {
  firstName: '',
  middleName: '',
  lastName: '',
  age: '',
  gender: '',
  email: '',
  complainantCategory: '',
  phone: '',
  state: '',
  district: '',
  pincode: '',
  address: '',
  organizationName: '',
  orgLandline: '',
  bankComplaintDate: '',
  bankComplaintRef: '',
  disputeDate: '',
  receivedReplyFromEntity: '',
  replyDate: '',
  isWalletComplaint: '',
  walletName: '',
  transactionRefNumber: '',
  isBusinessCorrespondent: '',
  cardNumber: '',
  loanAccountNumber: '',
  complaintCategory: '',
  subCategory1: '',
  subCategory2: '',
  complaintText: '',
  hasAccountWithRE: '',
  accountType: '',
  savingsAccountNumber: '',
  atmDebitCardNumber: '',
  disputeAmount: '',
  compensationSought: '',
  reliefSought: '',
  isCreditCardComplaint: '',
  entityState: '',
  entityDistrict: '',
  entityBranch: '',
  creditCardNumber: '',
  reminderDate: '',
  isComplainantSelf: '',
  hasAuthRep: '',
  throughAdvocate: '',
  authorizeRepresentative: '',
  repName: '',
  repPhone: '',
  repEmail: '',
  repPincode: '',
  repState: '',
  repDistrict: '',
  repCity: '',
  repAddress: '',
};

export const TOOLTIPS: Record<string, string> = {
  name: 'Enter your full legal name as it appears on official documents',
  email: 'Optional. Used for sending updates about your complaint',
  complainantCategory: 'Select Individual for personal complaints, Business for company-related issues',
  state: 'Select the state where you reside',
  pincode: 'Enter 6-digit postal code of your area',
  bankComplaintRef: 'Reference/acknowledgement number provided by the bank when you filed the complaint',
  disputeDate: 'Date when the disputed transaction or issue occurred',
  complaintCategory: 'Select the broad category that best describes your complaint',
  subCategory1: 'Select specific nature of your complaint within the chosen category',
  complaintText: 'Describe your complaint in detail including all relevant facts, dates, and amounts',
  disputeAmount: 'Total monetary amount involved in the dispute (in Indian Rupees)',
  compensationSought: 'Amount of compensation you are seeking for the loss/inconvenience',
  reliefSought: 'Describe what action or remedy you expect from the Ombudsman',
  repName: 'Full name of the person authorised to represent you',
};

export const STEP_TITLES = [
  'Complainant Details',
  'Regulated Entity Details',
  'Complaint Details',
  'Representative Authorisation',
  'Declaration',
  'Review and Submit',
];

export const DEFAULT_CATEGORIES: SelectOption[] = [
  { label: 'ATM / Debit Card', value: 'ATM_DEBIT_CARD' },
  { label: 'Credit Card', value: 'CREDIT_CARD' },
  { label: 'Internet / Mobile Banking', value: 'INTERNET_MOBILE_BANKING' },
  { label: 'UPI', value: 'UPI' },
  { label: 'Loans and Advances', value: 'LOANS_ADVANCES' },
  { label: 'Deposit Accounts', value: 'DEPOSIT_ACCOUNTS' },
  { label: 'Remittances (NEFT/RTGS/IMPS)', value: 'REMITTANCES' },
  { label: 'Insurance', value: 'INSURANCE' },
  { label: 'Pension', value: 'PENSION' },
  { label: 'Para Banking', value: 'PARA_BANKING' },
  { label: 'Others', value: 'OTHERS' },
];

export const CATEGORY_LABEL_MAP: Record<string, string> = {
  individual: 'Individual',
  pwd: 'Person with Disabilities',
  senior_citizen: 'Senior Citizen',
  individual_business: 'Individual – Business',
  proprietorship: 'Proprietorship',
  partnership: 'Partnership',
  msme: 'MSME',
  association: 'Association',
  trust: 'Trust',
  limited_company: 'Limited Company',
  government_department: 'Government Department',
  psu: 'PSU',
};

export const GENDER_LABEL_MAP: Record<string, string> = {
  male: 'Male',
  female: 'Female',
  transgender: 'Transgender',
  not_disclosed: 'Do not wish to disclose',
  other: 'Other',
};

export const ACCOUNT_TYPE_FIELD_MAP: Record<string, string> = {
  savings: 'savingsAccountNumber',
  loan: 'loanAccountNumber',
  atm_debit: 'atmDebitCardNumber',
  credit_card: 'creditCardNumber',
};
