INSERT INTO PUBLIC.QUESTION_MASTER (QUESTION_ID, QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (1, 'APPROACHED_BANK', 'Have you already approached your bank/financial institution with this complaint?', 'YES_NO', NULL, true, 1, 'YES,NO', 'YES', 'approachedBank', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO PUBLIC.QUESTION_MASTER (QUESTION_ID, QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (2, 'DAYS_ELAPSED', 'Have 30 days elapsed since you complained to the bank without resolution?', 'YES_NO', NULL, true, 2, 'YES,NO', 'YES', 'daysElapsed', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO PUBLIC.QUESTION_MASTER (QUESTION_ID, QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (3, 'NOT_IN_COURT', 'Is the matter NOT pending in any court, tribunal, or consumer forum?', 'YES_NO', NULL, true, 3, 'YES,NO', 'YES', 'notInCourt', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO PUBLIC.QUESTION_MASTER (QUESTION_ID, QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (4, 'WITHIN_ONE_YEAR', 'Is the complaint being filed within one year of the bank''s final response (or one year and 30 days of your initial complaint)?', 'YES_NO', NULL, true, 4, 'YES,NO', 'YES', 'withinOneYear', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO PUBLIC.QUESTION_MASTER (QUESTION_ID, QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (5, 'COMPLAINT_CATEGORY', 'What category does your complaint fall under?', 'SINGLE_CHOICE', NULL, true, 5, 'ATM,UPI,NEFT_RTGS,LOAN,CREDIT_CARD,DEPOSIT,INSURANCE,GENERAL', NULL, 'complaintCategory', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
