-- ═══════════════════════════════════════════════════════════════════════════
-- V107 — NOTIFICATION_DELIVERY_LOG becomes the outbound dispatch queue
-- ═══════════════════════════════════════════════════════════════════════════
--
-- cms-backend holds no SMTP credentials and no SMS gateway; cms-notification-service
-- owns the only JavaMailSender in the repository. So an EMAIL or SMS attempt is now
-- recorded PENDING when cms-backend publishes it to the notification.dispatch Kafka
-- topic, and cms-notification-service settles it to SENT or FAILED after the real send.
--
-- This relaxes the append-only rule V29 established for this table. Only STATUS,
-- ERROR_MESSAGE and SETTLED_AT are mutable; the columns identifying WHICH attempt a row
-- is remain immutable, so a retry still appends rather than overwriting. The reason for
-- the change is that PENDING -> SENT is a queue state machine, and a row still PENDING
-- is the only durable evidence that a message reached no gateway — which makes it
-- re-drivable. Writing SENT at hand-off time, as the code previously did, destroyed that
-- distinction: a broker outage and a successful delivery looked identical.
--
-- IN_APP rows keep DISPATCH_REF NULL and are still settled inline — they never leave the
-- application, so there is nothing for another service to confirm.

ALTER TABLE NOTIFICATION_DELIVERY_LOG
    ADD COLUMN dispatch_ref VARCHAR(64) NULL COMMENT
        'Correlation key the sending service settles this row by. UUID generated by the publisher, because the Kafka message is built before the insert is flushed and cannot know the generated id. NULL for IN_APP.';

ALTER TABLE NOTIFICATION_DELIVERY_LOG
    ADD COLUMN settled_at DATETIME(6) NULL COMMENT
        'When a PENDING attempt was resolved to SENT or FAILED. NULL while still queued.';

CREATE INDEX idx_ndl_dispatch_ref ON NOTIFICATION_DELIVERY_LOG (dispatch_ref);

-- Existing rows predate the queue and were written already-terminal. Backfilling SETTLED_AT
-- from ATTEMPTED_AT keeps "settled_at IS NULL AND status = 'PENDING'" a reliable test for
-- "still queued" — without it every historical row would answer that query. No automated
-- re-drive of stuck rows exists yet; for now this is an operator query.
UPDATE NOTIFICATION_DELIVERY_LOG
   SET settled_at = attempted_at
 WHERE settled_at IS NULL
   AND status IN ('SENT', 'FAILED');
