-- ============================================================
-- RBI CMS Phase 1 - Oracle Database Schema
-- Version: 1.0.0
-- Description: Initial DDL for all CMS tables
-- ============================================================

-- ============================================================
-- SEQUENCES
-- ============================================================

CREATE SEQUENCE QUESTION_MASTER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ELIGIBILITY_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COMPLAINT_MASTER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COMPLAINT_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ATTACHMENT_METADATA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE OUTBOX_EVENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- TABLE: QUESTION_MASTER
-- Stores configurable eligibility questionnaire
-- ============================================================

CREATE TABLE QUESTION_MASTER (
    QUESTION_ID       NUMBER(19) DEFAULT QUESTION_MASTER_SEQ.NEXTVAL PRIMARY KEY,
    QUESTION_CODE     VARCHAR2(50) NOT NULL UNIQUE,
    QUESTION_TEXT     VARCHAR2(1000) NOT NULL,
    QUESTION_TYPE     VARCHAR2(30) NOT NULL,
    CATEGORY          VARCHAR2(50),
    IS_MANDATORY      NUMBER(1) DEFAULT 1 NOT NULL,
    DISPLAY_ORDER     NUMBER(5) NOT NULL,
    OPTIONS           VARCHAR2(2000),
    EXPECTED_ANSWER   VARCHAR2(200),
    RULE_ATTRIBUTE    VARCHAR2(100),
    IS_ACTIVE         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_QUESTION_ACTIVE ON QUESTION_MASTER(IS_ACTIVE, DISPLAY_ORDER);
CREATE INDEX IDX_QUESTION_CATEGORY ON QUESTION_MASTER(CATEGORY, IS_ACTIVE);

-- ============================================================
-- TABLE: ELIGIBILITY_AUDIT
-- Immutable record of every eligibility check
-- ============================================================

CREATE TABLE ELIGIBILITY_AUDIT (
    AUDIT_ID          NUMBER(19) DEFAULT ELIGIBILITY_AUDIT_SEQ.NEXTVAL PRIMARY KEY,
    SESSION_ID        VARCHAR2(100) NOT NULL,
    CHANNEL           VARCHAR2(30) NOT NULL,
    ANSWERS_JSON      VARCHAR2(4000) NOT NULL,
    OUTCOME           VARCHAR2(20) NOT NULL,
    REASON_CODE       VARCHAR2(50),
    REASON_MESSAGE    VARCHAR2(500),
    STANDARD_RESPONSE VARCHAR2(2000),
    IP_ADDRESS        VARCHAR2(50),
    EVALUATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_ELIG_AUDIT_SESSION ON ELIGIBILITY_AUDIT(SESSION_ID);
CREATE INDEX IDX_ELIG_AUDIT_DATE ON ELIGIBILITY_AUDIT(EVALUATED_AT);

-- ============================================================
-- TABLE: COMPLAINT_MASTER
-- Primary complaint entity - source of truth
-- ============================================================

CREATE TABLE COMPLAINT_MASTER (
    ID                NUMBER(19) DEFAULT COMPLAINT_MASTER_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_ID      VARCHAR2(30) NOT NULL UNIQUE,
    CHANNEL           VARCHAR2(20) NOT NULL,
    CATEGORY          VARCHAR2(30) NOT NULL,
    STATUS            VARCHAR2(20) DEFAULT 'NEW' NOT NULL,
    PRIORITY          VARCHAR2(10) DEFAULT 'MEDIUM' NOT NULL,
    COMPLAINANT_NAME  VARCHAR2(200) NOT NULL,
    COMPLAINANT_EMAIL VARCHAR2(200),
    COMPLAINANT_PHONE VARCHAR2(20),
    ENTITY_NAME       VARCHAR2(200) NOT NULL,
    ENTITY_TYPE       VARCHAR2(50),
    SUBJECT           VARCHAR2(500) NOT NULL,
    DESCRIPTION       VARCHAR2(4000) NOT NULL,
    AMOUNT_INVOLVED   NUMBER(15,2),
    TRANSACTION_DATE  DATE,
    JURISDICTION_CODE VARCHAR2(20),
    ASSIGNED_TO       VARCHAR2(100),
    ASSIGNED_TEAM     VARCHAR2(50),
    SLA_DUE_DATE      TIMESTAMP,
    RESOLUTION_SUMMARY VARCHAR2(4000),
    RESOLVED_AT       TIMESTAMP,
    CLOSED_AT         TIMESTAMP,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    VERSION           NUMBER(19) DEFAULT 0
);

CREATE INDEX IDX_COMPLAINT_STATUS ON COMPLAINT_MASTER(STATUS);
CREATE INDEX IDX_COMPLAINT_PHONE ON COMPLAINT_MASTER(COMPLAINANT_PHONE);
CREATE INDEX IDX_COMPLAINT_ASSIGNED ON COMPLAINT_MASTER(ASSIGNED_TO);
CREATE INDEX IDX_COMPLAINT_SLA ON COMPLAINT_MASTER(SLA_DUE_DATE, STATUS);
CREATE INDEX IDX_COMPLAINT_CATEGORY ON COMPLAINT_MASTER(CATEGORY, STATUS);
CREATE INDEX IDX_COMPLAINT_CREATED ON COMPLAINT_MASTER(CREATED_AT);

-- ============================================================
-- TABLE: COMPLAINT_HISTORY
-- State transition history for audit trail
-- ============================================================

CREATE TABLE COMPLAINT_HISTORY (
    HISTORY_ID        NUMBER(19) DEFAULT COMPLAINT_HISTORY_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_ID      VARCHAR2(30) NOT NULL,
    PREVIOUS_STATUS   VARCHAR2(20),
    NEW_STATUS        VARCHAR2(20) NOT NULL,
    ACTION            VARCHAR2(100) NOT NULL,
    REMARKS           VARCHAR2(2000),
    PERFORMED_BY      VARCHAR2(100) NOT NULL,
    PERFORMED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_HISTORY_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINT_MASTER(COMPLAINT_ID)
);

CREATE INDEX IDX_HISTORY_COMPLAINT ON COMPLAINT_HISTORY(COMPLAINT_ID, PERFORMED_AT);

-- ============================================================
-- TABLE: ATTACHMENT_METADATA
-- File/document attachment metadata
-- ============================================================

CREATE TABLE ATTACHMENT_METADATA (
    ATTACHMENT_ID     NUMBER(19) DEFAULT ATTACHMENT_METADATA_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_ID      VARCHAR2(30) NOT NULL,
    FILE_NAME         VARCHAR2(255) NOT NULL,
    CONTENT_TYPE      VARCHAR2(100) NOT NULL,
    FILE_SIZE         NUMBER(19) NOT NULL,
    STORAGE_PATH      VARCHAR2(500) NOT NULL,
    CHECKSUM          VARCHAR2(64),
    UPLOADED_BY       VARCHAR2(100),
    UPLOADED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ATTACH_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINT_MASTER(COMPLAINT_ID)
);

CREATE INDEX IDX_ATTACH_COMPLAINT ON ATTACHMENT_METADATA(COMPLAINT_ID);

-- ============================================================
-- TABLE: OUTBOX_EVENT
-- Transactional outbox for reliable Kafka publishing
-- ============================================================

CREATE TABLE OUTBOX_EVENT (
    EVENT_ID          NUMBER(19) DEFAULT OUTBOX_EVENT_SEQ.NEXTVAL PRIMARY KEY,
    AGGREGATE_ID      VARCHAR2(50) NOT NULL,
    AGGREGATE_TYPE    VARCHAR2(50) NOT NULL,
    EVENT_TYPE        VARCHAR2(100) NOT NULL,
    TOPIC             VARCHAR2(100) NOT NULL,
    PAYLOAD           CLOB NOT NULL,
    STATUS            VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    RETRY_COUNT       NUMBER(5) DEFAULT 0,
    ERROR_MESSAGE     VARCHAR2(2000),
    CORRELATION_ID    VARCHAR2(100),
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    PUBLISHED_AT      TIMESTAMP
);

CREATE INDEX IDX_OUTBOX_STATUS ON OUTBOX_EVENT(STATUS, CREATED_AT);
CREATE INDEX IDX_OUTBOX_AGGREGATE ON OUTBOX_EVENT(AGGREGATE_ID, AGGREGATE_TYPE);

-- ============================================================
-- TABLE: AUDIT_LOG
-- Immutable audit log for all operations
-- ============================================================

CREATE TABLE AUDIT_LOG (
    LOG_ID            NUMBER(19) DEFAULT AUDIT_LOG_SEQ.NEXTVAL PRIMARY KEY,
    ENTITY_TYPE       VARCHAR2(50) NOT NULL,
    ENTITY_ID         VARCHAR2(50) NOT NULL,
    ACTION            VARCHAR2(100) NOT NULL,
    PREVIOUS_VALUE    VARCHAR2(4000),
    NEW_VALUE         VARCHAR2(4000),
    PERFORMED_BY      VARCHAR2(100) NOT NULL,
    CORRELATION_ID    VARCHAR2(100),
    IP_ADDRESS        VARCHAR2(50),
    USER_AGENT        VARCHAR2(500),
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_AUDIT_ENTITY ON AUDIT_LOG(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IDX_AUDIT_USER ON AUDIT_LOG(PERFORMED_BY, CREATED_AT);
CREATE INDEX IDX_AUDIT_DATE ON AUDIT_LOG(CREATED_AT);

-- ============================================================
-- TABLE: SHEDLOCK (for distributed scheduler locking)
-- ============================================================

CREATE TABLE SHEDLOCK (
    NAME       VARCHAR2(64) NOT NULL PRIMARY KEY,
    LOCK_UNTIL TIMESTAMP NOT NULL,
    LOCKED_AT  TIMESTAMP NOT NULL,
    LOCKED_BY  VARCHAR2(255) NOT NULL
);

-- ============================================================
-- SEED DATA: Default eligibility questions
-- ============================================================

INSERT INTO QUESTION_MASTER (QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE)
VALUES ('Q_COURT_MATTER', 'Is the matter currently pending in any court/tribunal/arbitration?', 'YES_NO', 'GENERAL', 1, 1, 'YES|NO', 'NO', 'courtMatterPending', 1);

INSERT INTO QUESTION_MASTER (QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE)
VALUES ('Q_APPROACHED_BANK', 'Have you approached your bank/financial institution with this complaint?', 'YES_NO', 'GENERAL', 1, 2, 'YES|NO', 'YES', 'approachedBank', 1);

INSERT INTO QUESTION_MASTER (QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE)
VALUES ('Q_WAITING_PERIOD', 'Has 30 days elapsed since you approached the bank?', 'YES_NO', 'GENERAL', 1, 3, 'YES|NO', 'YES', 'waitingPeriodCompleted', 1);

INSERT INTO QUESTION_MASTER (QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE)
VALUES ('Q_DUPLICATE', 'Have you already filed a complaint with RBI for the same issue?', 'YES_NO', 'GENERAL', 1, 4, 'YES|NO', 'NO', 'duplicateComplaint', 1);

INSERT INTO QUESTION_MASTER (QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE)
VALUES ('Q_CATEGORY', 'What is the nature of your complaint?', 'SINGLE_CHOICE', 'GENERAL', 1, 5, 'ATM|UPI|NEFT_RTGS|LOAN|CREDIT_CARD|DEPOSIT|INSURANCE|GENERAL', NULL, 'complaintCategory', 1);

INSERT INTO QUESTION_MASTER (QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE)
VALUES ('Q_JURISDICTION', 'Which state/UT does the bank branch belong to?', 'SINGLE_CHOICE', 'GENERAL', 0, 6, NULL, NULL, 'jurisdictionCode', 1);

COMMIT;
