apiVersion: v1
kind: Secret
metadata:
  name: cms-kafka-secret
  namespace: rbi-cms
  labels:
    app.kubernetes.io/part-of: rbi-cms
type: Opaque
stringData:
  KAFKA_SASL_USERNAME: "cms_kafka"
  KAFKA_SASL_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  KAFKA_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
  KAFKA_SASL_MECHANISM: "SCRAM-SHA-512"
