apiVersion: v1
kind: Secret
metadata:
  name: cms-opensearch-secret
  namespace: rbi-cms
  labels:
    app.kubernetes.io/part-of: rbi-cms
type: Opaque
stringData:
  OPENSEARCH_USER: "cms_search"
  OPENSEARCH_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
