apiVersion: v1
kind: Secret
metadata:
  name: cms-keycloak-secret
  namespace: rbi-cms
  labels:
    app.kubernetes.io/part-of: rbi-cms
type: Opaque
stringData:
  KEYCLOAK_CLIENT_ID: "cms-backend"
  KEYCLOAK_CLIENT_SECRET: "CHANGE_ME_IN_PRODUCTION"
  KEYCLOAK_ADMIN_USER: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
