apiVersion: v1
kind: Secret
metadata:
  name: cms-db-secret
  namespace: rbi-cms
  labels:
    app.kubernetes.io/part-of: rbi-cms
type: Opaque
stringData:
  DB_USER: "cms_app"
  DB_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  SMTP_USER: "cms-notifications"
  SMTP_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
