import { EligibilityQuestion } from '../models';

const YES_NO_OPTIONS = [
  { label: 'Yes', value: 'yes', translationKey: 'eligibility.opt_yes' },
  { label: 'No', value: 'no', translationKey: 'eligibility.opt_no' },
];

export const ELIGIBILITY_QUESTIONS: EligibilityQuestion[] = [
  {
    key: 'regulatedEntity',
    question: 'Select Regulated Entity Name',
    translationKey: 'eligibility.q_select_re',
    type: 'select',
    options: [],
    blockOn: null,
    blockMessage: '',
  },
  {
    key: 'filedWithRE',
    question: 'Have you filed a written / electronic complaint with the <RE Name>?',
    translationKey: 'eligibility.q_filed_with_re',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'no',
    blockMessage: 'In terms of clause 10(1)(e) of Reserve Bank \u2013 Integrated Ombudsman Scheme, you are required to approach the Regulated Entity first before filing the complaint with the Ombudsman. Therefore, such complaints cannot be registered.\nAccordingly, we regret to inform you that your present grievance against <RE Name> cannot be registered under the Scheme. In case the response was furnished erroneously, you may change the response.',
    blockMessageKey: 'eligibility.block_not_filed',
    nonMaintainable: true,
    clauseCode: '10(1)(e)',
    statusCode: 'PORTAL_REJECTION',
    closureLetterPara2: 'As you have indicated \u201cNo\u201d in response to the query \u2013 \u201cHave you filed a written/electronic complaint with the Regulated Entity?\u201d in terms of clause 10(1)(e) of Reserve Bank \u2013 Integrated Ombudsman Scheme, 2026, as the Complainant is required to first make a complaint in writing or through any other mode to the Regulated Entity concerned, before making a complaint under the Scheme; this representation alleging deficiency in service on the part of <RE Name> cannot be processed under the Scheme.',
    cepcBlockMessage: 'It may be noted that customers should first approach the Regulated Entity for resolution of grievances, before filing the complaint with Reserve Bank of India. If a complaint is filed with us without approaching the Regulated Entity first, such complaints cannot be registered with us.',
    cepcClosureLetter: 'Madam / Sir,\n\nYou are required to approach the Regulated Entity first before filing the complaint with Reserve Bank of India. Therefore, we regret to inform you that your complaint is not registered.\nYou may file a fresh complaint with us only after approaching the concerned Regulated Entity and if you are not satisfied with the resolution provided by it or your complaint is not responded to/resolved by the Regulated Entity within 30 days from the date of filing the complaint with the Regulated Entity.',
  },
  {
    key: 'receivedReply',
    question: 'Have you received any reply from the Entity?',
    translationKey: 'eligibility.q_received_reply',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: null,
    blockMessage: '',
    nonMaintainable: true,
  },
  {
    key: 'sentReminder',
    question: 'Have you sent any reminder to the <RE Name>?',
    translationKey: 'eligibility.q_sent_reminder',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: null,
    blockMessage: '',
    nonMaintainable: true,
  },
  {
    key: 'isSubJudice',
    question: 'Is the complaint relating to the same grievance which is already pending before any Court, Tribunal, Arbitrator or any other judicial or quasi-judicial forum (excluding criminal proceedings pending or decided before a Court/ Tribunal or any police investigation initiated in a criminal offence)?',
    translationKey: 'eligibility.q_sub_judice',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'In terms of clause 10(1)(j) of Reserve Bank \u2013 Integrated Ombudsman Scheme, 2026, a complaint relating to the same grievance which is already pending before any Court, Tribunal or Arbitrator or any other judicial or quasi-judicial forum, shall not be considered again under the Scheme. Therefore, such complaints cannot be registered.\nAccordingly, we regret to inform you that your present grievance against <RE Name> cannot be registered under the Scheme. In case the response was furnished erroneously, you may change the response.',
    blockMessageKey: 'eligibility.block_sub_judice',
    nonMaintainable: true,
    clauseCode: '10(1)(j)',
    statusCode: 'PORTAL_REJECTION',
    closureLetterPara2: 'As you have indicated \u201cYes\u201d in response to the query \u2013 \u201cIs the complaint relating to the same grievance which is already pending before any Court, Tribunal, Arbitrator or any other judicial or quasi-judicial forum (excluding criminal proceedings pending or decided before a Court/ Tribunal or any police investigation initiated in a criminal offence)?\u201d, in terms of clause 10(1)(j) of Reserve Bank \u2013 Integrated Ombudsman Scheme, 2026, a complaint in respect of the same cause of action relating to the same grievance which is already pending before any Court, Tribunal or Arbitrator or any other judicial or quasi-judicial forum; cannot be processed under the Scheme.',
    simplifiedText: 'Have you already taken this exact problem to a court, arbitrator, or another official legal authority (excluding criminal cases or police investigations)?',
    simplifiedTextKey: 'eligibility.q_sub_judice_simple',
  },
  {
    key: 'alreadySettled',
    question: 'Is the complaint relating to the same grievance which is already settled or dealt before any Court, Tribunal, Arbitrator or any other judicial or quasi-judicial forum (excluding criminal proceedings pending or decided before a Court/ Tribunal or any police investigation initiated in a criminal offence)?',
    translationKey: 'eligibility.q_already_settled',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'In terms of clause 10(1)(k) of Reserve Bank \u2013 Integrated Ombudsman Scheme, 2026, a complaint relating to the same grievance which is already settled or dealt before any Court, Tribunal or Arbitrator or any other judicial or quasi-judicial forum, shall not be considered again under the Scheme. Therefore, such complaints cannot be registered.\nAccordingly, we regret to inform you that your present grievance against <RE Name> cannot be registered under the Scheme. In case the response was furnished erroneously, you may change the response.',
    blockMessageKey: 'eligibility.block_already_settled',
    nonMaintainable: true,
    clauseCode: '10(1)(k)',
    statusCode: 'PORTAL_REJECTION',
    closureLetterPara2: 'As you have indicated \u201cYes\u201d in response to the query \u2013 \u201cIs the complaint relating to the same grievance which is already settled or dealt by any Court, Tribunal, Arbitrator or any other judicial or quasi-judicial forum (excluding criminal proceedings pending or decided before a Court/ Tribunal or any police investigation initiated in a criminal offence)?\u201d, in terms of clause 10(1)(k) of Reserve Bank \u2013 Integrated Ombudsman Scheme, 2026, a complaint in respect of the same cause of action relating to the same grievance which is already settled or dealt with on merits, by any Court, Tribunal or Arbitrator or any other judicial or quasi-judicial forum; cannot be processed under the Scheme.',
    simplifiedText: 'Has this exact problem already been resolved by a court, arbitrator, or another official legal authority (excluding criminal cases or police investigations)?',
    simplifiedTextKey: 'eligibility.q_already_settled_simple',
  },
  {
    key: 'throughAdvocateEligibility',
    question: 'Is your complaint being made through an advocate?',
    translationKey: 'eligibility.q_through_advocate',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: null,
    blockMessage: '',
    simplifiedText: '',
    simplifiedTextKey: '',
  },
  {
    key: 'pendingBeforeOmbudsman',
    question: 'Is the complaint relating to the same grievance which is already pending before the Ombudsman?',
    translationKey: 'eligibility.q_pending_ombudsman',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'In terms of clause 10(1)(h) of Reserve Bank \u2013 Integrated Ombudsman Scheme, a complaint relating to the same grievance, which is already pending before the Ombudsman, cannot be registered again.\nAccordingly, we regret to inform you that your present grievance against <RE Name> cannot be registered under the Scheme. In case the response was furnished erroneously, you may change the response.',
    blockMessageKey: 'eligibility.block_pending_ombudsman',
    nonMaintainable: true,
    clauseCode: '10(1)(h)',
    statusCode: 'PORTAL_REJECTION',
    closureLetterPara2: 'As you have indicated \u201cYes\u201d in response to the query \u2013 \u201cIs the complaint relating to the same grievance which is already pending before the Ombudsman?\u201d, in terms of clause 10(1)(h) of Reserve Bank \u2013 Integrated Ombudsman Scheme, 2026, complaint is relating to the same grievance, which is already pending before the Office of the RBI Ombudsman; cannot be processed under the Scheme.',
    simplifiedText: '',
    simplifiedTextKey: '',
  },
  {
    key: 'settledByOmbudsman',
    question: 'Is the complaint relating to the same grievance which is already settled or dealt with on merits by the Ombudsman?',
    translationKey: 'eligibility.q_settled_ombudsman',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'In terms of clause 10(1)(i) of Reserve Bank \u2013 Integrated Ombudsman Scheme, a complaint relating to the same grievance which is already settled or dealt with on merits by the Ombudsman, cannot be registered again.\nAccordingly, we regret to inform you that your present grievance against <RE Name> cannot be registered under the Scheme. In case the response was furnished erroneously, you may change the response.',
    blockMessageKey: 'eligibility.block_settled_ombudsman',
    nonMaintainable: true,
    clauseCode: '10(1)(i)',
    statusCode: 'PORTAL_REJECTION',
    closureLetterPara2: 'As you have indicated \u201cYes\u201d in response to the query \u2013 \u201cIs the complaint relating to the same grievance which is already settled or dealt with on merits by the Ombudsman?\u201d in terms of clause 10(1)(i) of Reserve Bank \u2013 Integrated Ombudsman Scheme, 2026, complaint is relating to the same grievance, which is already settled or dealt with on merits, by the Office of the RBI Ombudsman; cannot be processed under the Scheme.',
    simplifiedText: '',
    simplifiedTextKey: '',
  },
  {
    key: 'staffOfRE',
    question: 'Is the Complainant a staff of the RE and complaint involves employer-employee relationship?',
    translationKey: 'eligibility.q_staff_of_re',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'In terms of clause 10(2)(g) of Reserve Bank \u2013 Integrated Ombudsman Scheme, a complaint involving the employee-employer relationship of a Regulated Entity cannot be handled under the Scheme. Therefore, such complaints cannot be registered.\nAccordingly, we regret to inform you that your present grievance against <RE Name> cannot be registered under the Scheme. In case the response was furnished erroneously, you may change the response.',
    blockMessageKey: 'eligibility.block_staff_of_re',
    nonMaintainable: true,
    clauseCode: '10(2)(g)',
    statusCode: 'PORTAL_REJECTION',
    closureLetterPara2: 'As you have indicated \u201cYes\u201d in response to the query \u2013 \u201cIs the Complainant a staff of the RE and complaint involves employer-employee relationship?\u201d in terms of clause 10(2)(g) of Reserve Bank \u2013 Integrated Ombudsman Scheme, 2026, a dispute involving the employee-employer relationship of a Regulated Entity; cannot be processed under the Scheme.',
    simplifiedText: '',
    simplifiedTextKey: '',
  },
  {
    key: 'previouslyFiledWithCEPC',
    question: 'Have you filed a complaint on the same matter with the Consumer Education and Protection Cell (CEPC), the Reserve Bank of India (RBI) previously?',
    translationKey: 'eligibility.q_previously_filed_cepc',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'As your complaint on the same subject matter has already been filed with CEPC/RBI, it will be closed as Non-Maintainable under the Reserve Bank - Integrated Ombudsman Scheme, 2026.',
    blockMessageKey: 'eligibility.block_previously_filed_cepc',
    nonMaintainable: true,
    cepcBlockMessage: 'If a complaint in respect of the same cause of action relating to the same grievance which is already filed before Consumer Education and Protection Cell (CEPC), the Reserve Bank of India (RBI), cannot be registered again.',
    cepcClosureLetter: 'Madam / Sir,\nIt is informed that a complaint in respect of the same cause of action relating to the same grievance which is already filed with Consumer Education and Protection Cell (CEPC), the Reserve Bank of India (RBI), cannot be registered again. Therefore, we regret to inform you that the present complaint is not registered.\nFurther, if your previous complaint is pending with CEPC, RBI, you may check the status of the complaint on our website https://cms.rbi.org.in.',
    simplifiedText: '',
    simplifiedTextKey: '',
  },
  {
    key: 'employeeOfRE',
    question: 'Are / were you an employee of the Regulated Entity against whom this complaint is being filed?',
    translationKey: 'eligibility.q_employee_of_re',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: null,
    blockMessage: '',
    nonMaintainable: true,
    cepcBlockMessage: 'A complaint involving the employee-employer relationship of a Regulated Entity, cannot be handled by RBI. Therefore, such complaints shall not be registered.',
    cepcClosureLetter: 'Madam / Sir,\nA complaint involving the employee-employer relationship of a Regulated Entity, cannot be handled by CEPC or RBI. Therefore, we regret to inform you that your complaint is not registered.',
    simplifiedText: '',
    simplifiedTextKey: '',
  },
  {
    key: 'employerRelationship',
    question: 'If Yes, Is your complaint involves the employee-employer relationship of the Regulated Entity?',
    translationKey: 'eligibility.q_employer_relationship',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'In terms of clause 10(2)(g) of Reserve Bank \u2013 Integrated Ombudsman Scheme, a complaint involving the employee-employer relationship of a Regulated Entity cannot be handled under the Scheme. Therefore, such complaints cannot be registered.\nAccordingly, we regret to inform you that your present grievance against <RE Name> cannot be registered under the Scheme. In case the response was furnished erroneously, you may change the response.',
    blockMessageKey: 'eligibility.block_employer_relationship',
    nonMaintainable: true,
    clauseCode: '10(2)(g)',
    statusCode: 'PORTAL_REJECTION',
    closureLetterPara2: 'As you have indicated \u201cYes\u201d in response to the query \u2013 \u201cIs the Complainant a staff of the RE and complaint involves employer-employee relationship?\u201d in terms of clause 10(2)(g) of Reserve Bank \u2013 Integrated Ombudsman Scheme, 2026, a dispute involving the employee-employer relationship of a Regulated Entity; cannot be processed under the Scheme.',
    simplifiedText: '',
    simplifiedTextKey: '',
  },
];
