-- Assignment pool and counter tables for jBPM round-robin workflow

CREATE TABLE WF_OFFICER_POOL (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID         VARCHAR2(100) NOT NULL,
    DISPLAY_NAME    VARCHAR2(200),
    ROLE_GROUP      VARCHAR2(50) NOT NULL,
    REGIONAL_OFFICE VARCHAR2(50),
    IS_ACTIVE       NUMBER(1) DEFAULT 1 NOT NULL,
    IS_ON_LEAVE     NUMBER(1) DEFAULT 0 NOT NULL,
    CURRENT_WORKLOAD NUMBER DEFAULT 0,
    MAX_WORKLOAD    NUMBER DEFAULT 40
);

CREATE INDEX IDX_OFFICER_POOL_ROLE ON WF_OFFICER_POOL (ROLE_GROUP, IS_ACTIVE, IS_ON_LEAVE);
CREATE INDEX IDX_OFFICER_POOL_USER ON WF_OFFICER_POOL (USER_ID);

CREATE TABLE WF_ASSIGNMENT_COUNTER (
    ID                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_GROUP          VARCHAR2(50) NOT NULL UNIQUE,
    LAST_ASSIGNED_INDEX NUMBER DEFAULT 0 NOT NULL,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed CRPC DEOs
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('deo.raghav', 'Raghav Sharma', 'CRPC_DEO', 'MUMBAI', 1, 0, 0, 50);
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('deo.priya', 'Priya Nair', 'CRPC_DEO', 'MUMBAI', 1, 0, 0, 50);
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('deo.amit', 'Amit Kulkarni', 'CRPC_DEO', 'DELHI', 1, 0, 0, 50);
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('deo.sunita', 'Sunita Desai', 'CRPC_DEO', 'CHENNAI', 1, 0, 0, 50);

-- Seed CRPC Reviewers
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('rev.radhika', 'Radhika Rao', 'CRPC_REVIEWER', 'MUMBAI', 1, 0, 0, 30);
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('rev.bhupinder', 'Bhupinder Singh', 'CRPC_REVIEWER', 'DELHI', 1, 0, 0, 30);
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('rev.meena', 'Meena Iyer', 'CRPC_REVIEWER', 'CHENNAI', 1, 0, 0, 30);

-- Seed RBIO Officers
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('rbio.officer1', 'Vikram Mehta', 'RBIO_OFFICER', 'MUMBAI', 1, 0, 0, 40);
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('rbio.officer2', 'Anjali Gupta', 'RBIO_OFFICER', 'MUMBAI', 1, 0, 0, 40);
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('rbio.officer3', 'Suresh Kumar', 'RBIO_OFFICER', 'DELHI', 1, 0, 0, 40);
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('rbio.officer4', 'Kavita Reddy', 'RBIO_OFFICER', 'CHENNAI', 1, 0, 0, 40);

-- Seed CEPC Officers
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('cepc.officer1', 'Rohan Patil', 'CEPC_OFFICER', 'MUMBAI', 1, 0, 0, 40);
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('cepc.officer2', 'Deepa Krishnan', 'CEPC_OFFICER', 'MUMBAI', 1, 0, 0, 40);
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('cepc.officer3', 'Manish Tiwari', 'CEPC_OFFICER', 'DELHI', 1, 0, 0, 40);

-- Seed Supervisors
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('rbio.super1', 'Rajesh Verma', 'RBIO_SUPERVISOR', 'MUMBAI', 1, 0, 0, 20);
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('rbio.super2', 'Lakshmi Pillai', 'RBIO_SUPERVISOR', 'DELHI', 1, 0, 0, 20);
INSERT INTO WF_OFFICER_POOL (USER_ID, DISPLAY_NAME, ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD)
VALUES ('cepc.super1', 'Arun Joshi', 'CEPC_SUPERVISOR', 'MUMBAI', 1, 0, 0, 20);

-- Seed counters
INSERT INTO WF_ASSIGNMENT_COUNTER (ROLE_GROUP, LAST_ASSIGNED_INDEX) VALUES ('CRPC_DEO', 0);
INSERT INTO WF_ASSIGNMENT_COUNTER (ROLE_GROUP, LAST_ASSIGNED_INDEX) VALUES ('CRPC_REVIEWER', 0);
INSERT INTO WF_ASSIGNMENT_COUNTER (ROLE_GROUP, LAST_ASSIGNED_INDEX) VALUES ('RBIO_OFFICER', 0);
INSERT INTO WF_ASSIGNMENT_COUNTER (ROLE_GROUP, LAST_ASSIGNED_INDEX) VALUES ('CEPC_OFFICER', 0);
INSERT INTO WF_ASSIGNMENT_COUNTER (ROLE_GROUP, LAST_ASSIGNED_INDEX) VALUES ('RBIO_SUPERVISOR', 0);
INSERT INTO WF_ASSIGNMENT_COUNTER (ROLE_GROUP, LAST_ASSIGNED_INDEX) VALUES ('CEPC_SUPERVISOR', 0);
