import { test, expect } from '../fixtures';
import { createTestComplaint } from '../utils/test-data';
import { readFileSync } from 'fs';

/**
 * UST97 / D5: the citizen-facing PDFs used to stamp a green
 * "DIGITALLY SIGNED | RBI CMS Digital Certificate Authority" seal on documents that carry no
 * cryptographic signature at all — there is no CMS certificate authority, no signing key, and no
 * PKCS#7 envelope. A citizen could reasonably have treated a freely editable PDF as tamper-proof
 * evidence of RBI's decision.
 *
 * Until a real DSC/HSM is provisioned the only honest position is to say the document is
 * unsigned, so these tests assert the false claim is gone and the disclaimer is present.
 *
 * jsPDF emits its text as uncompressed PDF string literals, so the generated bytes can be
 * inspected directly without adding a PDF-parsing dependency.
 */

const APP_BASE = process.env['APP_BASE_URL'] || process.env['UI_BASE_URL'] || 'http://localhost:4200';

/** Strips PDF text-operator syntax so wrapped/kerned strings can be matched as plain prose. */
function pdfText(buffer: Buffer): string {
  const raw = buffer.toString('latin1');
  const chunks: string[] = [];
  for (const m of raw.matchAll(/\(((?:\\.|[^\\()])*)\)\s*Tj/g)) {
    chunks.push(m[1].replace(/\\([()\\])/g, '$1'));
  }
  return chunks.join(' ');
}

test.describe('UST97 — Downloaded PDFs do not claim a digital signature (D5)', () => {

  test('the complaint status report is labelled unsigned, not digitally signed', async ({ page, request }) => {
    const complaint = await createTestComplaint(request, {
      subject: 'PDF signature disclaimer check',
    });

    await page.goto(`${APP_BASE}/track/${complaint.complaintNumber}`);
    await page.waitForLoadState('networkidle');

    const button = page.locator('button.btn-download-pdf');
    await expect(button).toBeVisible({ timeout: 20000 });

    const downloadPromise = page.waitForEvent('download');
    await button.click();
    const download = await downloadPromise;

    const path = await download.path();
    expect(path).toBeTruthy();
    const text = pdfText(readFileSync(path!));

    // The report itself must still be intact.
    expect(text).toContain('COMPLAINT STATUS REPORT');
    expect(text).toContain(complaint.complaintNumber);

    // The false assurance must be gone...
    expect(text).not.toMatch(/DIGITALLY SIGNED \|/);
    expect(text).not.toContain('Digital Certificate Authority');

    // ...and replaced with an explicit statement that the file is unsigned.
    expect(text).toContain('NOT A DIGITALLY SIGNED DOCUMENT');
    // The citizen is pointed at the portal, which is the authoritative source.
    expect(text).toContain('Verify the current status online');
  });

  test('the PDF never asserts a signing time it cannot prove', async ({ page, request }) => {
    const complaint = await createTestComplaint(request, {
      subject: 'PDF signing timestamp check',
    });

    await page.goto(`${APP_BASE}/track/${complaint.complaintNumber}`);
    await page.waitForLoadState('networkidle');

    const downloadPromise = page.waitForEvent('download');
    await page.locator('button.btn-download-pdf').click();
    const text = pdfText(readFileSync((await (await downloadPromise).path())!));

    // "Signed at: <time>" implied a signing event that never happened. A generation timestamp is
    // fine; a signing timestamp is not.
    expect(text).not.toMatch(/Signed at/i);
  });
});
