import { EligibilityQuestion } from './complaint-form.models';

const YES_NO_OPTIONS = [
  { label: 'Yes', value: 'yes', translationKey: 'eligibility.opt_yes' },
  { label: 'No', value: 'no', translationKey: 'eligibility.opt_no' },
];

export const ELIGIBILITY_QUESTIONS: EligibilityQuestion[] = [
  {
    key: 'regulatedEntity',
    question: 'Select Regulated Entity Name',
    translationKey: 'eligibility.q_select_re',
    type: 'select',
    options: [],
    blockOn: null,
    blockMessage: '',
  },
  {
    key: 'filedWithRE',
    question: 'Have you filed a written / electronic complaint with the <RE Name>?',
    translationKey: 'eligibility.q_filed_with_re',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'no',
    blockMessage: 'in terms of clause 10(1)(j) of Reserve Bank – Integrated Ombudsman Scheme, 2026, the complaint cannot be processed under the Scheme.',
    blockMessageKey: 'eligibility.block_not_filed',
    nonMaintainable: true,
  },
  {
    key: 'receivedReply',
    question: 'Have you received any reply from the Entity?',
    translationKey: 'eligibility.q_received_reply',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: null,
    blockMessage: '',
    nonMaintainable: true,
  },
  {
    key: 'sentReminder',
    question: 'Have you sent any reminder to the <RE Name>?',
    translationKey: 'eligibility.q_sent_reminder',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: null,
    blockMessage: '',
    nonMaintainable: true,
  },
  {
    key: 'isSubJudice',
    question: 'Is the complaint relating to the same grievance which is already pending before any Court, Tribunal, Arbitrator or any other judicial or quasi-judicial forum (excluding criminal proceedings pending or decided before a Court/ Tribunal or any police investigation initiated in a criminal offence)?',
    translationKey: 'eligibility.q_sub_judice',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'As your complaint is sub-judice/under arbitration/already dealt with on merits by a Court/Tribunal/Arbitrator/Authority, it will be closed as Non-Maintainable under clause 10(2)(b)(ii) of the Reserve Bank - Integrated Ombudsman Scheme, 2026.',
    blockMessageKey: 'eligibility.block_sub_judice',
    nonMaintainable: true,
    simplifiedText: 'Have you already taken this exact problem to a court, arbitrator, or another official legal authority (excluding criminal cases or police investigations)?',
    simplifiedTextKey: 'eligibility.q_sub_judice_simple',
  },
  {
    key: 'alreadySettled',
    question: 'Is the complaint relating to the same grievance which is already settled or dealt before any Court, Tribunal, Arbitrator or any other judicial or quasi-judicial forum (excluding criminal proceedings pending or decided before a Court/ Tribunal or any police investigation initiated in a criminal offence)?',
    translationKey: 'eligibility.q_already_settled',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'As your complaint has already been settled or dealt with by a Court/Tribunal/Arbitrator/Authority, it will be closed as Non-Maintainable under the Reserve Bank - Integrated Ombudsman Scheme, 2026.',
    blockMessageKey: 'eligibility.block_already_settled',
    nonMaintainable: true,
    simplifiedText: 'Has this exact problem already been resolved by a court, arbitrator, or another official legal authority (excluding criminal cases or police investigations)?',
    simplifiedTextKey: 'eligibility.q_already_settled_simple',
  },
  {
    key: 'throughAdvocateEligibility',
    question: 'Is your complaint being made through an advocate?',
    translationKey: 'eligibility.q_through_advocate',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: null,
    blockMessage: '',
    simplifiedText: '',
    simplifiedTextKey: '',
  },
  {
    key: 'pendingBeforeOmbudsman',
    question: 'Is the complaint relating to the same grievance which is already pending before the Ombudsman?',
    translationKey: 'eligibility.q_pending_ombudsman',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'Your complaint is already pending before the Ombudsman on the same grievance. Duplicate complaints cannot be filed.',
    blockMessageKey: 'eligibility.block_pending_ombudsman',
    nonMaintainable: true,
    simplifiedText: '',
    simplifiedTextKey: '',
  },
  {
    key: 'settledByOmbudsman',
    question: 'Is the complaint relating to the same grievance which is already settled or dealt with on merits by the Ombudsman?',
    translationKey: 'eligibility.q_settled_ombudsman',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'Your complaint has already been settled or dealt with on merits by the Ombudsman. You cannot file a fresh complaint on the same issue.',
    blockMessageKey: 'eligibility.block_settled_ombudsman',
    nonMaintainable: true,
    simplifiedText: '',
    simplifiedTextKey: '',
  },
  {
    key: 'staffOfRE',
    question: 'Is the Complainant a staff of the RE and complaint involves employer-employee relationship?',
    translationKey: 'eligibility.q_staff_of_re',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'As the complaint involves the employer-employee relationship with the Regulated Entity, it cannot be processed under the Integrated Ombudsman Scheme, 2026.',
    blockMessageKey: 'eligibility.block_staff_of_re',
    nonMaintainable: true,
    simplifiedText: '',
    simplifiedTextKey: '',
  },
  {
    key: 'previouslyFiledWithCEPC',
    question: 'Have you previously filed a complaint on the same subject matter with CEPC/RBI Ombudsman?',
    translationKey: 'eligibility.q_previously_filed_cepc',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'As your complaint on the same subject matter has already been filed with CEPC/RBI, it will be closed as Non-Maintainable under the Reserve Bank - Integrated Ombudsman Scheme, 2026.',
    blockMessageKey: 'eligibility.block_previously_filed_cepc',
    nonMaintainable: true,
    simplifiedText: '',
    simplifiedTextKey: '',
  },
  {
    key: 'employeeOfRE',
    question: 'Are / were you an employee of the Regulated Entity against whom this complaint is being filed?',
    translationKey: 'eligibility.q_employee_of_re',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: null,
    blockMessage: '',
    nonMaintainable: true,
    simplifiedText: '',
    simplifiedTextKey: '',
  },
  {
    key: 'employerRelationship',
    question: 'If Yes, Is your complaint involves the employee-employer relationship of the Regulated Entity?',
    translationKey: 'eligibility.q_employer_relationship',
    type: 'radio',
    options: YES_NO_OPTIONS,
    blockOn: 'yes',
    blockMessage: 'As your complaint involves the employee-employer relationship with the Regulated Entity, it cannot be processed under the Integrated Ombudsman Scheme, 2026.',
    blockMessageKey: 'eligibility.block_employer_relationship',
    nonMaintainable: true,
    simplifiedText: '',
    simplifiedTextKey: '',
  },
];
