#!/usr/bin/env node
/**
 * Generates src/sitemap.xml and src/robots.txt from the SEO route table.
 *
 * WHY GENERATED. The committed sitemap.xml was hand-maintained: it listed 6 URLs, one of which
 * (/public/login) was fine but /public/faq — a page of genuinely useful public content — was missing
 * entirely, while /public/file-complaint was advertised at priority 0.9 despite sitting behind an auth
 * guard. A hand-written sitemap drifts from the router the moment anyone adds a route. Reading the same
 * table the application uses for its meta tags means the two cannot disagree.
 *
 * Run:  node scripts/generate-sitemap.mjs
 * Then: ng build (angular.json already copies src/sitemap.xml and src/robots.txt as assets)
 */

import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const ORIGIN = process.env.CMS_CANONICAL_ORIGIN || 'https://cms.rbi.org.in';

/**
 * Parsed out of the TypeScript route table rather than duplicated here.
 *
 * A second hardcoded copy in this script would be one more thing to forget to update — exactly the
 * failure mode being fixed. The table is plain object literals, so a targeted regex is adequate and
 * avoids adding a TS build step to a one-file script.
 */
function readSeoRoutes() {
  const src = readFileSync(join(root, 'src/app/seo/seo-routes.ts'), 'utf8');

  const localeMatch = src.match(/SUPPORTED_LOCALES = \[([\s\S]*?)\]/);
  const locales = [...localeMatch[1].matchAll(/'([a-z-]+)'/g)].map(m => m[1]);

  const routes = [];
  const blockRe = /\{\s*(?:\/\/[^\n]*\n\s*)*path:\s*'([^']+)'[\s\S]*?indexable:\s*(true|false)([\s\S]*?)\n\s*\},/g;
  for (const m of src.matchAll(blockRe)) {
    const [, path, indexable, tail] = m;
    if (indexable !== 'true') continue;
    routes.push({
      path,
      priority: (tail.match(/priority:\s*'([^']+)'/) || [, '0.5'])[1],
      changefreq: (tail.match(/changefreq:\s*'([^']+)'/) || [, 'monthly'])[1],
    });
  }
  return { locales, routes };
}

const { locales, routes } = readSeoRoutes();

if (routes.length === 0) {
  console.error('Refusing to write an empty sitemap: no indexable routes were parsed.');
  process.exit(1);
}

const lastmod = new Date().toISOString().slice(0, 10);

/**
 * One <url> per route, with an xhtml:link alternate per locale.
 *
 * Alternates rather than separate <url> entries per language: the locale is a query parameter, not a
 * distinct path, so listing 11 near-identical URLs would look like duplicate content. Declaring them as
 * alternates of one canonical URL is what tells a crawler they are translations.
 */
const urls = routes.map(r => {
  const loc = `${ORIGIN}${r.path}`;
  const alternates = locales
    .map(l => `    <xhtml:link rel="alternate" hreflang="${l}" href="${loc}?lang=${l}"/>`)
    .join('\n');
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
${alternates}
    <xhtml:link rel="alternate" hreflang="x-default" href="${loc}"/>
  </url>`;
}).join('\n');

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by scripts/generate-sitemap.mjs from src/app/seo/seo-routes.ts. Do not edit by hand.
  Only routes marked indexable=true appear here; everything behind publicAuthGuard is excluded
  because its URL is crawlable even though its content is not.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls}
</urlset>
`;

writeFileSync(join(root, 'src/sitemap.xml'), sitemap, 'utf8');

/**
 * robots.txt, with EVERY staff surface disallowed.
 *
 * The previous file listed /admin/ /staff/ /crpc/ /officer/ /re-portal/ and missed /cepc/, /rbio/, /aa/
 * and /email-syndication/ — all real, routable staff prefixes. A guarded route is still a crawlable URL,
 * so an omission here leaks the shape of the internal application into search results.
 */
const STAFF_PREFIXES = [
  '/admin/', '/staff/', '/crpc/', '/officer/', '/re-portal/', '/re/',
  '/cepc/', '/rbio/', '/aa/', '/email-syndication/', '/search/',
  '/report-builder/', '/senior-dashboard/', '/landing/',
];

/**
 * Public paths that must not be indexed because they require a session or carry a secret.
 *
 * `/public/upload/` is the important one: it is a TOKENISED upload link sent to a complainant, so the
 * token IS the credential. A crawler that fetched one and a search engine that indexed it would publish
 * a working upload URL for someone else's complaint.
 *
 * `/file-complaint` (no /public prefix) is a second, older top-level route to a complaint form. It was
 * missing from the previous robots.txt entirely, which is why this list is checked against app.routes.ts
 * rather than written from memory.
 */
const PRIVATE_PUBLIC_PATHS = [
  '/public/file-complaint', '/public/history', '/public/appeal',
  '/public/feedback', '/public/withdraw', '/public/complaint/',
  '/public/upload/',
  '/file-complaint',
];

const robots = `# GENERATED by scripts/generate-sitemap.mjs. Do not edit by hand.
User-agent: *
Allow: /

# Staff modules. Guarded by route guards and server @PreAuthorize, but a guarded URL is still crawlable,
# so it is also excluded here to keep the internal application out of search results.
${STAFF_PREFIXES.map(p => `Disallow: ${p}`).join('\n')}

# Citizen pages requiring a session. Indexing these advertises pages a visitor cannot open, and a
# per-complaint URL would confirm that a particular reference number exists.
${PRIVATE_PUBLIC_PATHS.map(p => `Disallow: ${p}`).join('\n')}

Sitemap: ${ORIGIN}/sitemap.xml
`;

writeFileSync(join(root, 'src/robots.txt'), robots, 'utf8');

console.log(`sitemap.xml: ${routes.length} indexable URLs x ${locales.length} locales`);
console.log(`robots.txt: ${STAFF_PREFIXES.length} staff prefixes + ${PRIVATE_PUBLIC_PATHS.length} private paths disallowed`);
