-- ============================================================
-- RBI CMS 2.0 — FINAL CONSOLIDATED INIT SCRIPT
-- All tables + seed data for fresh deployment
-- Oracle-compatible syntax (with MySQL notes where applicable)
-- Generated: August 2026
-- ============================================================

-- ============================================================
-- SECTION 1: SEQUENCES
-- ============================================================

CREATE SEQUENCE QUESTION_MASTER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ELIGIBILITY_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COMPLAINT_MASTER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COMPLAINT_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ATTACHMENT_METADATA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE OUTBOX_EVENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MRE_RULE_CATEGORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MRE_RULE_DEFINITION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MRE_RULE_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MRE_DEPLOYMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- SECTION 2: CORE TABLES
-- ============================================================

-- 2.1 QUESTION_MASTER (Eligibility Wizard)
CREATE TABLE QUESTION_MASTER (
    QUESTION_ID       NUMBER(19) DEFAULT QUESTION_MASTER_SEQ.NEXTVAL PRIMARY KEY,
    QUESTION_CODE     VARCHAR2(50) NOT NULL UNIQUE,
    QUESTION_TEXT     VARCHAR2(1000) NOT NULL,
    QUESTION_TYPE     VARCHAR2(30) NOT NULL,
    CATEGORY          VARCHAR2(50),
    IS_MANDATORY      NUMBER(1) DEFAULT 1 NOT NULL,
    DISPLAY_ORDER     NUMBER(5) NOT NULL,
    OPTIONS           VARCHAR2(2000),
    EXPECTED_ANSWER   VARCHAR2(200),
    RULE_ATTRIBUTE    VARCHAR2(100),
    IS_ACTIVE         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_QUESTION_ACTIVE ON QUESTION_MASTER(IS_ACTIVE, DISPLAY_ORDER);
CREATE INDEX IDX_QUESTION_CATEGORY ON QUESTION_MASTER(CATEGORY, IS_ACTIVE);

-- 2.2 ELIGIBILITY_AUDIT (Eligibility Check Records)
CREATE TABLE ELIGIBILITY_AUDIT (
    AUDIT_ID          NUMBER(19) DEFAULT ELIGIBILITY_AUDIT_SEQ.NEXTVAL PRIMARY KEY,
    SESSION_ID        VARCHAR2(100) NOT NULL,
    CHANNEL           VARCHAR2(30) NOT NULL,
    ANSWERS_JSON      VARCHAR2(4000) NOT NULL,
    OUTCOME           VARCHAR2(20) NOT NULL,
    REASON_CODE       VARCHAR2(50),
    REASON_MESSAGE    VARCHAR2(500),
    STANDARD_RESPONSE VARCHAR2(2000),
    IP_ADDRESS        VARCHAR2(50),
    EVALUATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_ELIG_AUDIT_SESSION ON ELIGIBILITY_AUDIT(SESSION_ID);
CREATE INDEX IDX_ELIG_AUDIT_DATE ON ELIGIBILITY_AUDIT(EVALUATED_AT);

-- 2.3 COMPLAINT_MASTER (Primary Complaint Entity)
CREATE TABLE COMPLAINT_MASTER (
    ID                NUMBER(19) DEFAULT COMPLAINT_MASTER_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_ID      VARCHAR2(30) NOT NULL UNIQUE,
    CHANNEL           VARCHAR2(20) NOT NULL,
    CATEGORY          VARCHAR2(30) NOT NULL,
    STATUS            VARCHAR2(20) DEFAULT 'NEW' NOT NULL,
    PRIORITY          VARCHAR2(10) DEFAULT 'MEDIUM' NOT NULL,
    COMPLAINANT_NAME  VARCHAR2(200) NOT NULL,
    COMPLAINANT_EMAIL VARCHAR2(200),
    COMPLAINANT_PHONE VARCHAR2(20),
    COMPLAINANT_STATE VARCHAR2(100),
    COMPLAINANT_DISTRICT VARCHAR2(100),
    ENTITY_NAME       VARCHAR2(200) NOT NULL,
    ENTITY_CODE       VARCHAR2(50),
    ENTITY_TYPE       VARCHAR2(50),
    DEPARTMENT        VARCHAR2(20),
    SUBJECT           VARCHAR2(500) NOT NULL,
    DESCRIPTION       VARCHAR2(4000) NOT NULL,
    AMOUNT_INVOLVED   NUMBER(15,2),
    TRANSACTION_DATE  DATE,
    JURISDICTION_CODE VARCHAR2(20),
    ASSIGNED_TO       VARCHAR2(100),
    ASSIGNED_TEAM     VARCHAR2(50),
    ASSIGNED_ROLE     VARCHAR2(50),
    WORKFLOW_STAGE    VARCHAR2(50),
    SLA_DUE_DATE      TIMESTAMP,
    FILING_TYPE       VARCHAR2(30),
    BANK_COMPLAINT_REFERENCE VARCHAR2(200),
    BANK_COMPLAINT_DATE DATE,
    -- Prior RE Complaint fields (RB-IOS Q16/Q17)
    PRIOR_RE_COMPLAINT       NUMBER(1),
    RE_COMPLAINT_DATE        DATE,
    RE_COMPLAINT_REFERENCE   VARCHAR2(200),
    RE_REPLIED_AND_DISSATISFIED NUMBER(1),
    -- Triage & Maintainability
    TRIAGE_SIGNAL            VARCHAR2(10),
    TRIAGE_FLAGS             CLOB,
    ELIGIBILITY_TIMELINE     CLOB,
    MAINTAINABILITY_DETERMINATION VARCHAR2(30),
    MAINTAINABILITY_DETERMINED_BY VARCHAR2(200),
    MAINTAINABILITY_DETERMINED_AT TIMESTAMP,
    AWARD_AMOUNT             NUMBER(15,2),
    -- Closure fields
    CUSTOM_CLOSURE_TEXT      VARCHAR2(2000),
    CLOSURE_LETTER_SENT_AT   TIMESTAMP,
    CLOSURE_CLAUSE           VARCHAR2(100),
    CLOSURE_AUTHORITY_NAME   VARCHAR2(200),
    CLOSURE_AUTHORITY_DESIGNATION VARCHAR2(200),
    RE_RESPONSE_DEADLINE     DATE,
    LAST_STATUS_CHANGE_DATE  TIMESTAMP,
    -- Resolution & timestamps
    RESOLUTION_SUMMARY VARCHAR2(4000),
    RESOLVED_AT       TIMESTAMP,
    ESCALATED_AT      TIMESTAMP,
    CLOSED_AT         TIMESTAMP,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    VERSION           NUMBER(19) DEFAULT 0
);

CREATE INDEX IDX_COMPLAINT_STATUS ON COMPLAINT_MASTER(STATUS);
CREATE INDEX IDX_COMPLAINT_PHONE ON COMPLAINT_MASTER(COMPLAINANT_PHONE);
CREATE INDEX IDX_COMPLAINT_ASSIGNED ON COMPLAINT_MASTER(ASSIGNED_TO);
CREATE INDEX IDX_COMPLAINT_SLA ON COMPLAINT_MASTER(SLA_DUE_DATE, STATUS);
CREATE INDEX IDX_COMPLAINT_CATEGORY ON COMPLAINT_MASTER(CATEGORY, STATUS);
CREATE INDEX IDX_COMPLAINT_CREATED ON COMPLAINT_MASTER(CREATED_AT);
CREATE INDEX IDX_COMPLAINT_DEPARTMENT ON COMPLAINT_MASTER(DEPARTMENT, STATUS);
CREATE INDEX IDX_COMPLAINT_RE_DATE ON COMPLAINT_MASTER(RE_COMPLAINT_DATE);
CREATE INDEX IDX_COMPLAINT_TRIAGE ON COMPLAINT_MASTER(TRIAGE_SIGNAL);
CREATE INDEX IDX_COMPLAINT_MAINTAINABILITY ON COMPLAINT_MASTER(MAINTAINABILITY_DETERMINATION);

-- 2.4 COMPLAINT_HISTORY (State Transitions)
CREATE TABLE COMPLAINT_HISTORY (
    HISTORY_ID        NUMBER(19) DEFAULT COMPLAINT_HISTORY_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_ID      VARCHAR2(30) NOT NULL,
    PREVIOUS_STATUS   VARCHAR2(20),
    NEW_STATUS        VARCHAR2(20) NOT NULL,
    ACTION            VARCHAR2(100) NOT NULL,
    REMARKS           VARCHAR2(2000),
    PERFORMED_BY      VARCHAR2(100) NOT NULL,
    PERFORMED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_HISTORY_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINT_MASTER(COMPLAINT_ID)
);

CREATE INDEX IDX_HISTORY_COMPLAINT ON COMPLAINT_HISTORY(COMPLAINT_ID, PERFORMED_AT);

-- 2.5 ATTACHMENT_METADATA (File Attachments)
CREATE TABLE ATTACHMENT_METADATA (
    ATTACHMENT_ID     NUMBER(19) DEFAULT ATTACHMENT_METADATA_SEQ.NEXTVAL PRIMARY KEY,
    COMPLAINT_ID      VARCHAR2(30) NOT NULL,
    FILE_NAME         VARCHAR2(255) NOT NULL,
    CONTENT_TYPE      VARCHAR2(100) NOT NULL,
    FILE_SIZE         NUMBER(19) NOT NULL,
    STORAGE_PATH      VARCHAR2(500) NOT NULL,
    CHECKSUM          VARCHAR2(64),
    UPLOADED_BY       VARCHAR2(100),
    UPLOADED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ATTACH_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINT_MASTER(COMPLAINT_ID)
);

CREATE INDEX IDX_ATTACH_COMPLAINT ON ATTACHMENT_METADATA(COMPLAINT_ID);

-- 2.6 OUTBOX_EVENT (Transactional Outbox for Kafka)
CREATE TABLE OUTBOX_EVENT (
    EVENT_ID          NUMBER(19) DEFAULT OUTBOX_EVENT_SEQ.NEXTVAL PRIMARY KEY,
    AGGREGATE_ID      VARCHAR2(50) NOT NULL,
    AGGREGATE_TYPE    VARCHAR2(50) NOT NULL,
    EVENT_TYPE        VARCHAR2(100) NOT NULL,
    TOPIC             VARCHAR2(100) NOT NULL,
    PAYLOAD           CLOB NOT NULL,
    STATUS            VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    RETRY_COUNT       NUMBER(5) DEFAULT 0,
    ERROR_MESSAGE     VARCHAR2(2000),
    CORRELATION_ID    VARCHAR2(100),
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    PUBLISHED_AT      TIMESTAMP
);

CREATE INDEX IDX_OUTBOX_STATUS ON OUTBOX_EVENT(STATUS, CREATED_AT);
CREATE INDEX IDX_OUTBOX_AGGREGATE ON OUTBOX_EVENT(AGGREGATE_ID, AGGREGATE_TYPE);

-- 2.7 AUDIT_LOG (System-Wide Audit)
CREATE TABLE AUDIT_LOG (
    LOG_ID            NUMBER(19) DEFAULT AUDIT_LOG_SEQ.NEXTVAL PRIMARY KEY,
    ENTITY_TYPE       VARCHAR2(50) NOT NULL,
    ENTITY_ID         VARCHAR2(50) NOT NULL,
    ACTION            VARCHAR2(100) NOT NULL,
    PREVIOUS_VALUE    VARCHAR2(4000),
    NEW_VALUE         VARCHAR2(4000),
    PERFORMED_BY      VARCHAR2(100) NOT NULL,
    CORRELATION_ID    VARCHAR2(100),
    IP_ADDRESS        VARCHAR2(50),
    USER_AGENT        VARCHAR2(500),
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_AUDIT_ENTITY ON AUDIT_LOG(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IDX_AUDIT_USER ON AUDIT_LOG(PERFORMED_BY, CREATED_AT);
CREATE INDEX IDX_AUDIT_DATE ON AUDIT_LOG(CREATED_AT);

-- 2.8 SHEDLOCK (Distributed Scheduler Locking)
CREATE TABLE SHEDLOCK (
    NAME       VARCHAR2(64) NOT NULL PRIMARY KEY,
    LOCK_UNTIL TIMESTAMP NOT NULL,
    LOCKED_AT  TIMESTAMP NOT NULL,
    LOCKED_BY  VARCHAR2(255) NOT NULL
);

-- 2.9 RE_RESPONSE_TRACKER (RE Responsiveness Radar)
CREATE TABLE RE_RESPONSE_TRACKER (
    ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COMPLAINT_ID      NUMBER(19) NOT NULL,
    REGULATED_ENTITY_ID NUMBER(19) NOT NULL,
    FORWARDED_AT      TIMESTAMP NOT NULL,
    RESPONDED_AT      TIMESTAMP,
    WINDOW_DAYS       NUMBER(5) DEFAULT 30 NOT NULL,
    WINDOW_EXPIRES_AT TIMESTAMP,
    BREACHED          NUMBER(1) DEFAULT 0 NOT NULL,
    EX_PARTE_ELIGIBLE NUMBER(1) DEFAULT 0 NOT NULL,
    NOTES             VARCHAR2(500),
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_RE_TRACKER_COMPLAINT ON RE_RESPONSE_TRACKER(COMPLAINT_ID);
CREATE INDEX IDX_RE_TRACKER_RE ON RE_RESPONSE_TRACKER(REGULATED_ENTITY_ID);
CREATE INDEX IDX_RE_TRACKER_BREACHED ON RE_RESPONSE_TRACKER(BREACHED);

-- ============================================================
-- SECTION 3: MRE RULES ENGINE TABLES
-- ============================================================

-- 3.1 MRE_RULE_CATEGORY
CREATE TABLE MRE_RULE_CATEGORY (
    ID                NUMBER(19) DEFAULT MRE_RULE_CATEGORY_SEQ.NEXTVAL PRIMARY KEY,
    CATEGORY_CODE     VARCHAR2(50) NOT NULL UNIQUE,
    CATEGORY_NAME     VARCHAR2(200) NOT NULL,
    DESCRIPTION       VARCHAR2(1000),
    IS_ACTIVE         NUMBER(1) DEFAULT 1 NOT NULL,
    DISPLAY_ORDER     NUMBER(5) DEFAULT 0,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_RULE_CAT_ACTIVE ON MRE_RULE_CATEGORY(IS_ACTIVE, DISPLAY_ORDER);

-- 3.2 MRE_RULE_DEFINITION
CREATE TABLE MRE_RULE_DEFINITION (
    ID                NUMBER(19) DEFAULT MRE_RULE_DEFINITION_SEQ.NEXTVAL PRIMARY KEY,
    RULE_CODE         VARCHAR2(50) NOT NULL UNIQUE,
    RULE_NAME         VARCHAR2(300) NOT NULL,
    CATEGORY_ID       NUMBER(19) NOT NULL,
    DRL_CONTENT       CLOB NOT NULL,
    SALIENCE          NUMBER(5) DEFAULT 10,
    VERSION           NUMBER(10) DEFAULT 1 NOT NULL,
    STATUS            VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    EFFECTIVE_FROM    TIMESTAMP,
    EFFECTIVE_TO      TIMESTAMP,
    CREATED_BY        VARCHAR2(100) NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY        VARCHAR2(100),
    UPDATED_AT        TIMESTAMP,
    APPROVED_BY       VARCHAR2(100),
    APPROVED_AT       TIMESTAMP,
    CONSTRAINT FK_RULE_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES MRE_RULE_CATEGORY(ID),
    CONSTRAINT CHK_RULE_STATUS CHECK (STATUS IN ('DRAFT','PENDING_REVIEW','ACTIVE','INACTIVE','ARCHIVED'))
);

CREATE INDEX IDX_RULE_DEF_STATUS ON MRE_RULE_DEFINITION(STATUS);
CREATE INDEX IDX_RULE_DEF_CATEGORY ON MRE_RULE_DEFINITION(CATEGORY_ID, STATUS);

-- 3.3 MRE_RULE_HISTORY
CREATE TABLE MRE_RULE_HISTORY (
    ID                NUMBER(19) DEFAULT MRE_RULE_HISTORY_SEQ.NEXTVAL PRIMARY KEY,
    RULE_ID           NUMBER(19) NOT NULL,
    VERSION           NUMBER(10) NOT NULL,
    DRL_CONTENT       CLOB NOT NULL,
    CHANGE_REASON     VARCHAR2(1000),
    ACTION            VARCHAR2(50) NOT NULL,
    CHANGED_BY        VARCHAR2(100) NOT NULL,
    CHANGED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_HISTORY_RULE FOREIGN KEY (RULE_ID) REFERENCES MRE_RULE_DEFINITION(ID)
);

CREATE INDEX IDX_RULE_HIST_RULE ON MRE_RULE_HISTORY(RULE_ID, VERSION);

-- 3.4 MRE_DEPLOYMENT
CREATE TABLE MRE_DEPLOYMENT (
    ID                NUMBER(19) DEFAULT MRE_DEPLOYMENT_SEQ.NEXTVAL PRIMARY KEY,
    DEPLOYMENT_ID     VARCHAR2(50) NOT NULL UNIQUE,
    RULES_DEPLOYED    NUMBER(10) NOT NULL,
    STATUS            VARCHAR2(20) NOT NULL,
    DEPLOYED_BY       VARCHAR2(100) NOT NULL,
    DEPLOYED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ERROR_MESSAGE     VARCHAR2(2000),
    CONSTRAINT CHK_DEPLOY_STATUS CHECK (STATUS IN ('SUCCESS','FAILED','ROLLED_BACK'))
);

CREATE INDEX IDX_DEPLOYMENT_STATUS ON MRE_DEPLOYMENT(STATUS, DEPLOYED_AT);

-- 3.5 MRE_GROUND_CONFIG
CREATE TABLE MRE_GROUND_CONFIG (
    ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GROUND_CODE       VARCHAR2(50) NOT NULL UNIQUE,
    CLAUSE_REF        VARCHAR2(20) NOT NULL,
    DESCRIPTION       VARCHAR2(500) NOT NULL,
    IS_ACTIVE         NUMBER(1) DEFAULT 1 NOT NULL,
    EVALUATION_ORDER  NUMBER(5) DEFAULT 0,
    FAIL_MESSAGE      VARCHAR2(1000),
    PASS_MESSAGE      VARCHAR2(1000),
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_GROUND_ACTIVE ON MRE_GROUND_CONFIG(IS_ACTIVE, EVALUATION_ORDER);

-- 3.6 MRE_WINDOW_CONFIG
CREATE TABLE MRE_WINDOW_CONFIG (
    ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATEGORY_CODE     VARCHAR2(50) NOT NULL,
    ENTITY_TYPE       VARCHAR2(50) DEFAULT 'ALL',
    WINDOW_DAYS       NUMBER(5) NOT NULL,
    FILING_DEADLINE   NUMBER(5) DEFAULT 365 NOT NULL,
    WINDOW_BASIS      VARCHAR2(20) DEFAULT 'CALENDAR' NOT NULL,
    IS_ACTIVE         NUMBER(1) DEFAULT 1 NOT NULL,
    EFFECTIVE_FROM    DATE NOT NULL,
    EFFECTIVE_TO      DATE,
    CREATED_BY        VARCHAR2(100),
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CHK_WINDOW_BASIS CHECK (WINDOW_BASIS IN ('CALENDAR','BUSINESS'))
);

CREATE UNIQUE INDEX IDX_WINDOW_UNIQUE ON MRE_WINDOW_CONFIG(CATEGORY_CODE, ENTITY_TYPE, EFFECTIVE_FROM);

-- ============================================================
-- SECTION 4: COMPLAINT NUMBER GENERATION TABLES
-- ============================================================

-- 4.1 OMBUDSMAN_OFFICE_MASTER (24 RBI Ombudsman offices)
CREATE TABLE OMBUDSMAN_OFFICE_MASTER (
    ID                NUMBER(5) PRIMARY KEY,
    OFFICE_NAME       VARCHAR2(100) NOT NULL,
    JURISDICTION      VARCHAR2(1000) NOT NULL,
    IS_ACTIVE         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 4.2 OFFICE_CODE_MASTER (Office → 3-digit code + counter)
CREATE TABLE OFFICE_CODE_MASTER (
    ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OFFICE_TYPE       VARCHAR2(10) NOT NULL,
    OFFICE_NAME       VARCHAR2(100) NOT NULL,
    OFFICE_CODE       VARCHAR2(10) NOT NULL UNIQUE,
    COUNTER           NUMBER(10) DEFAULT 0 NOT NULL,
    THRESHOLD         NUMBER(10) DEFAULT 2 NOT NULL,
    IS_ACTIVE         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 4.3 COMPLAINT_NUMBER_SEQUENCE (Per-office per-FY sequence)
CREATE TABLE COMPLAINT_NUMBER_SEQUENCE (
    ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OFFICE_CODE       VARCHAR2(10) NOT NULL,
    FINANCIAL_YEAR    VARCHAR2(6) NOT NULL,
    LAST_SEQUENCE     NUMBER(10) DEFAULT 0 NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_OFFICE_FY UNIQUE (OFFICE_CODE, FINANCIAL_YEAR)
);

-- 4.4 OFFICE_OVERFLOW_MAPPING (Priority overflow routing)
CREATE TABLE OFFICE_OVERFLOW_MAPPING (
    ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OFFICE_CODE       VARCHAR2(10) NOT NULL UNIQUE,
    OFFICE_NAME       VARCHAR2(100) NOT NULL,
    PRIORITY1_OFFICE_NAME VARCHAR2(100) NOT NULL,
    PRIORITY2_OFFICE_NAME VARCHAR2(100) NOT NULL,
    IS_ACTIVE         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 4.5 OFFICE_GLOBAL_THRESHOLD_CONFIG (Single-row config)
CREATE TABLE OFFICE_GLOBAL_THRESHOLD_CONFIG (
    ID                NUMBER(5) DEFAULT 1 PRIMARY KEY,
    THRESHOLD_VALUE   NUMBER(10) DEFAULT 2 NOT NULL,
    UPDATED_BY        VARCHAR2(200),
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_SINGLE_ROW CHECK (ID = 1)
);

-- ============================================================
-- SECTION 5: SEED DATA
-- ============================================================

-- 5.1 QUESTION_MASTER (Default Eligibility Questions)
INSERT INTO QUESTION_MASTER (QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE)
VALUES ('Q_COURT_MATTER', 'Is the matter currently pending in any court/tribunal/arbitration?', 'YES_NO', 'GENERAL', 1, 1, 'YES|NO', 'NO', 'courtMatterPending', 1);

INSERT INTO QUESTION_MASTER (QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE)
VALUES ('Q_APPROACHED_BANK', 'Have you approached your bank/financial institution with this complaint?', 'YES_NO', 'GENERAL', 1, 2, 'YES|NO', 'YES', 'approachedBank', 1);

INSERT INTO QUESTION_MASTER (QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE)
VALUES ('Q_WAITING_PERIOD', 'Has 30 days elapsed since you approached the bank?', 'YES_NO', 'GENERAL', 1, 3, 'YES|NO', 'YES', 'waitingPeriodCompleted', 1);

INSERT INTO QUESTION_MASTER (QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE)
VALUES ('Q_DUPLICATE', 'Have you already filed a complaint with RBI for the same issue?', 'YES_NO', 'GENERAL', 1, 4, 'YES|NO', 'NO', 'duplicateComplaint', 1);

INSERT INTO QUESTION_MASTER (QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE)
VALUES ('Q_CATEGORY', 'What is the nature of your complaint?', 'SINGLE_CHOICE', 'GENERAL', 1, 5, 'ATM|UPI|NEFT_RTGS|LOAN|CREDIT_CARD|DEPOSIT|INSURANCE|GENERAL', NULL, 'complaintCategory', 1);

INSERT INTO QUESTION_MASTER (QUESTION_CODE, QUESTION_TEXT, QUESTION_TYPE, CATEGORY, IS_MANDATORY, DISPLAY_ORDER, OPTIONS, EXPECTED_ANSWER, RULE_ATTRIBUTE, IS_ACTIVE)
VALUES ('Q_JURISDICTION', 'Which state/UT does the bank branch belong to?', 'SINGLE_CHOICE', 'GENERAL', 0, 6, NULL, NULL, 'jurisdictionCode', 1);

-- 5.2 OMBUDSMAN_OFFICE_MASTER (24 offices)
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(1, 'Ahmedabad', 'Gujarat, Union Territories of Dadra and Nagar Haveli, Daman and Diu');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(2, 'Bengaluru', 'Karnataka');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(3, 'Bhopal', 'Madhya Pradesh');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(4, 'Bhubaneswar', 'Odisha');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(5, 'Chandigarh', 'Punjab and Union Territory of Chandigarh');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(6, 'Chennai-I', 'Nine districts of Tamil Nadu viz., Thiruvallur, Chennai, Vellore, Ranipet, Kancheepuram, Chengalpattu, Krishnagiri, Tirupathur and Tiruvannamalai; and Union Territory of Andaman and Nicobar Islands');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(7, 'Chennai-II', 'Tamil Nadu (excluding Districts of Thiruvallur, Chennai, Vellore, Ranipet, Kancheepuram, Chengalpattu, Krishnagiri, Tirupathur and Tiruvannamalai); and Union Territory of Puducherry (except Mahe Region)');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(8, 'Dehradun', 'Uttarakhand and seven districts of Uttar Pradesh viz., Saharanpur, Shamli (Prabudh Nagar), Muzaffarnagar, Baghpat, Meerut, Bijnor and Amroha (Jyotiba Phule Nagar)');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(9, 'Guwahati', 'Assam, Arunachal Pradesh, Manipur, Meghalaya, Mizoram, Nagaland and Tripura');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(10, 'Hyderabad', 'Andhra Pradesh and Telangana');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(11, 'Jaipur', 'Rajasthan');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(12, 'Jammu', 'Union Territories of Jammu & Kashmir and Ladakh');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(13, 'Kanpur', 'Uttar Pradesh (excluding Districts of Ghaziabad, Gautam Buddha Nagar, Saharanpur, Shamli (Prabudh Nagar), Muzaffarnagar, Baghpat, Meerut, Bijnor and Amroha (Jyotiba Phule Nagar))');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(14, 'Kolkata-I', 'Three districts of West Bengal viz., Kolkata, South 24 Parganas, Howrah; and Sikkim');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(15, 'Kolkata-II', 'West Bengal (excluding districts of Kolkata, South 24 Parganas and Howrah)');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(16, 'Mumbai-I', 'Districts of Mumbai, Mumbai Suburban and Thane');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(17, 'Mumbai-II', 'Goa and Maharashtra (except the districts of Mumbai, Mumbai Suburban and Thane)');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(18, 'New Delhi-I', 'Delhi');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(19, 'New Delhi-II', 'Haryana and Ghaziabad and Gautam Buddha Nagar districts of Uttar Pradesh');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(20, 'Patna', 'Bihar');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(21, 'Raipur', 'Chhattisgarh');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(22, 'Ranchi', 'Jharkhand');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(23, 'Shimla', 'Himachal Pradesh');
INSERT INTO OMBUDSMAN_OFFICE_MASTER (ID, OFFICE_NAME, JURISDICTION) VALUES
(24, 'Thiruvananthapuram', 'Kerala, Union Territory of Lakshadweep and Union Territory of Puducherry (only Mahe Region)');

-- 5.3 OFFICE_CODE_MASTER (25 offices with codes)
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Ahmedabad', '001');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Bengaluru', '002');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Bhubaneswar', '003');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Bhopal', '004');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Kolkata-I', '005');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Chennai-I', '006');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Chandigarh', '007');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Guwahati', '008');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Hyderabad', '009');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Jaipur', '010');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Kanpur', '011');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Patna', '012');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Mumbai-I', '013');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'New Delhi-I', '014');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Thiruvananthapuram', '015');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'New Delhi-II', '016');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Dehradun', '017');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Ranchi', '018');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Raipur', '019');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Jammu', '020');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Mumbai-II', '021');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Kolkata-II', '022');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Shimla', '023');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'Chennai-II', '024');
INSERT INTO OFFICE_CODE_MASTER (OFFICE_TYPE, OFFICE_NAME, OFFICE_CODE) VALUES ('BO', 'New Delhi-III', '025');

-- 5.4 OFFICE_OVERFLOW_MAPPING (24 offices overflow routing)
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('003', 'Bhubaneswar', 'Kolkata-II', 'Patna');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('008', 'Guwahati', 'Bhubaneswar', 'Kolkata-I');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('005', 'Kolkata-I', 'Ranchi', 'Kolkata-II');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('022', 'Kolkata-II', 'Kolkata-I', 'Guwahati');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('012', 'Patna', 'Guwahati', 'Ranchi');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('018', 'Ranchi', 'Patna', 'Bhubaneswar');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('007', 'Chandigarh', 'Dehradun', 'New Delhi-I');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('017', 'Dehradun', 'Chandigarh', 'Kanpur');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('010', 'Jaipur', 'Kanpur', 'Chandigarh');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('020', 'Jammu', 'New Delhi-II', 'Jaipur');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('011', 'Kanpur', 'Jaipur', 'Dehradun');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('014', 'New Delhi-I', 'Shimla', 'New Delhi-II');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('016', 'New Delhi-II', 'Jammu', 'Shimla');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('023', 'Shimla', 'New Delhi-I', 'Jammu');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('002', 'Bengaluru', 'Thiruvananthapuram', 'Hyderabad');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('006', 'Chennai-I', 'Chennai-II', 'Bengaluru');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('024', 'Chennai-II', 'Hyderabad', 'Chennai-I');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('009', 'Hyderabad', 'Chennai-I', 'Thiruvananthapuram');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('015', 'Thiruvananthapuram', 'Bengaluru', 'Chennai-II');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('001', 'Ahmedabad', 'Raipur', 'Mumbai-I');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('004', 'Bhopal', 'Ahmedabad', 'Mumbai-II');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('013', 'Mumbai-I', 'Mumbai-II', 'Bhopal');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('021', 'Mumbai-II', 'Mumbai-I', 'Raipur');
INSERT INTO OFFICE_OVERFLOW_MAPPING (OFFICE_CODE, OFFICE_NAME, PRIORITY1_OFFICE_NAME, PRIORITY2_OFFICE_NAME) VALUES ('019', 'Raipur', 'Bhopal', 'Ahmedabad');

-- 5.5 OFFICE_GLOBAL_THRESHOLD_CONFIG
INSERT INTO OFFICE_GLOBAL_THRESHOLD_CONFIG (ID, THRESHOLD_VALUE, UPDATED_BY) VALUES (1, 2, 'SYSTEM');

-- 5.6 MRE_GROUND_CONFIG (6 grounds)
INSERT INTO MRE_GROUND_CONFIG (GROUND_CODE, CLAUSE_REF, DESCRIPTION, IS_ACTIVE, EVALUATION_ORDER, FAIL_MESSAGE, PASS_MESSAGE)
VALUES ('ENTITY_NOT_COVERED', 'Q13', 'Entity not covered under RB-IOS 2026 Scheme', 1, 1,
  'Entity is not a Regulated Entity covered under the Integrated Ombudsman Scheme',
  'Entity is covered under the RB-IOS 2026 Scheme');

INSERT INTO MRE_GROUND_CONFIG (GROUND_CODE, CLAUSE_REF, DESCRIPTION, IS_ACTIVE, EVALUATION_ORDER, FAIL_MESSAGE, PASS_MESSAGE)
VALUES ('NO_PRIOR_RE_COMPLAINT', 'Q16', 'No prior complaint to the Regulated Entity', 1, 2,
  'Complainant has not first complained to the Regulated Entity as required',
  'Complainant has lodged prior complaint with the RE');

INSERT INTO MRE_GROUND_CONFIG (GROUND_CODE, CLAUSE_REF, DESCRIPTION, IS_ACTIVE, EVALUATION_ORDER, FAIL_MESSAGE, PASS_MESSAGE)
VALUES ('FILED_BEFORE_WINDOW', 'Q17', 'Filed before the RE response window has elapsed', 1, 3,
  'Complaint filed before the mandatory waiting period has elapsed',
  'Filed after the waiting period - window requirement satisfied');

INSERT INTO MRE_GROUND_CONFIG (GROUND_CODE, CLAUSE_REF, DESCRIPTION, IS_ACTIVE, EVALUATION_ORDER, FAIL_MESSAGE, PASS_MESSAGE)
VALUES ('FILED_BEYOND_DEADLINE', 'Q16/Q17', 'Filed beyond the maximum filing deadline', 1, 4,
  'Complaint filed beyond the maximum permissible deadline after window expiry',
  'Filed within the deadline period');

INSERT INTO MRE_GROUND_CONFIG (GROUND_CODE, CLAUSE_REF, DESCRIPTION, IS_ACTIVE, EVALUATION_ORDER, FAIL_MESSAGE, PASS_MESSAGE)
VALUES ('RE_COMPLAINT_BEYOND_LIMITATION', 'Q16', 'RE complaint made beyond Limitation Act 1963 period', 1, 5,
  'The complaint to the Regulated Entity was made beyond the Limitation Act 1963 period (3 years)',
  'RE complaint is within the Limitation Act period');

INSERT INTO MRE_GROUND_CONFIG (GROUND_CODE, CLAUSE_REF, DESCRIPTION, IS_ACTIVE, EVALUATION_ORDER, FAIL_MESSAGE, PASS_MESSAGE)
VALUES ('SAME_GRIEVANCE_PENDING', 'Q16', 'Same grievance already pending or decided', 1, 6,
  'Same grievance is already pending or has been decided by the Ombudsman or a court/tribunal',
  'No duplicate grievance found pending or decided');

-- 5.7 MRE_WINDOW_CONFIG (11 category configurations)
INSERT INTO MRE_WINDOW_CONFIG (CATEGORY_CODE, ENTITY_TYPE, WINDOW_DAYS, FILING_DEADLINE, WINDOW_BASIS, IS_ACTIVE, EFFECTIVE_FROM, CREATED_BY)
VALUES ('DEFAULT', 'ALL', 30, 365, 'CALENDAR', 1, DATE '2026-01-01', 'admin');
INSERT INTO MRE_WINDOW_CONFIG (CATEGORY_CODE, ENTITY_TYPE, WINDOW_DAYS, FILING_DEADLINE, WINDOW_BASIS, IS_ACTIVE, EFFECTIVE_FROM, CREATED_BY)
VALUES ('UPI_MOBILE', 'ALL', 30, 365, 'CALENDAR', 1, DATE '2026-01-01', 'admin');
INSERT INTO MRE_WINDOW_CONFIG (CATEGORY_CODE, ENTITY_TYPE, WINDOW_DAYS, FILING_DEADLINE, WINDOW_BASIS, IS_ACTIVE, EFFECTIVE_FROM, CREATED_BY)
VALUES ('IMPS', 'ALL', 30, 365, 'CALENDAR', 1, DATE '2026-01-01', 'admin');
INSERT INTO MRE_WINDOW_CONFIG (CATEGORY_CODE, ENTITY_TYPE, WINDOW_DAYS, FILING_DEADLINE, WINDOW_BASIS, IS_ACTIVE, EFFECTIVE_FROM, CREATED_BY)
VALUES ('NACH', 'ALL', 30, 365, 'CALENDAR', 1, DATE '2026-01-01', 'admin');
INSERT INTO MRE_WINDOW_CONFIG (CATEGORY_CODE, ENTITY_TYPE, WINDOW_DAYS, FILING_DEADLINE, WINDOW_BASIS, IS_ACTIVE, EFFECTIVE_FROM, CREATED_BY)
VALUES ('CREDIT_CARD', 'ALL', 60, 365, 'CALENDAR', 1, DATE '2026-01-01', 'admin');
INSERT INTO MRE_WINDOW_CONFIG (CATEGORY_CODE, ENTITY_TYPE, WINDOW_DAYS, FILING_DEADLINE, WINDOW_BASIS, IS_ACTIVE, EFFECTIVE_FROM, CREATED_BY)
VALUES ('DEBIT_CARD', 'ALL', 60, 365, 'CALENDAR', 1, DATE '2026-01-01', 'admin');
INSERT INTO MRE_WINDOW_CONFIG (CATEGORY_CODE, ENTITY_TYPE, WINDOW_DAYS, FILING_DEADLINE, WINDOW_BASIS, IS_ACTIVE, EFFECTIVE_FROM, CREATED_BY)
VALUES ('ATM_DEBIT', 'ALL', 30, 365, 'CALENDAR', 1, DATE '2026-01-01', 'admin');
INSERT INTO MRE_WINDOW_CONFIG (CATEGORY_CODE, ENTITY_TYPE, WINDOW_DAYS, FILING_DEADLINE, WINDOW_BASIS, IS_ACTIVE, EFFECTIVE_FROM, CREATED_BY)
VALUES ('LOAN', 'ALL', 30, 365, 'CALENDAR', 1, DATE '2026-01-01', 'admin');
INSERT INTO MRE_WINDOW_CONFIG (CATEGORY_CODE, ENTITY_TYPE, WINDOW_DAYS, FILING_DEADLINE, WINDOW_BASIS, IS_ACTIVE, EFFECTIVE_FROM, CREATED_BY)
VALUES ('INSURANCE', 'ALL', 30, 365, 'CALENDAR', 1, DATE '2026-01-01', 'admin');
INSERT INTO MRE_WINDOW_CONFIG (CATEGORY_CODE, ENTITY_TYPE, WINDOW_DAYS, FILING_DEADLINE, WINDOW_BASIS, IS_ACTIVE, EFFECTIVE_FROM, CREATED_BY)
VALUES ('DEPOSIT', 'ALL', 30, 365, 'CALENDAR', 1, DATE '2026-01-01', 'admin');
INSERT INTO MRE_WINDOW_CONFIG (CATEGORY_CODE, ENTITY_TYPE, WINDOW_DAYS, FILING_DEADLINE, WINDOW_BASIS, IS_ACTIVE, EFFECTIVE_FROM, CREATED_BY)
VALUES ('NEFT_RTGS', 'ALL', 30, 365, 'CALENDAR', 1, DATE '2026-01-01', 'admin');

COMMIT;

-- ============================================================
-- END OF CONSOLIDATED INIT SCRIPT
-- Total Tables: 18
-- Total Seed Records: ~100+
-- ============================================================
