-- ============================================================
-- RBI CMS Phase 4 - MRE Rules Engine Tables
-- Version: 3.0.0
-- Description: DDL for MRE rule definitions, categories,
--              rule history, deployments (Oracle-compatible)
-- ============================================================

-- ============================================================
-- SEQUENCES
-- ============================================================

CREATE SEQUENCE MRE_RULE_CATEGORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MRE_RULE_DEFINITION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MRE_RULE_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MRE_DEPLOYMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- TABLE: MRE_RULE_CATEGORY
-- Categorizes rules (Assignment, Escalation, Priority, etc.)
-- ============================================================

CREATE TABLE MRE_RULE_CATEGORY (
    ID                NUMBER(19) DEFAULT MRE_RULE_CATEGORY_SEQ.NEXTVAL PRIMARY KEY,
    CATEGORY_CODE     VARCHAR2(50) NOT NULL UNIQUE,
    CATEGORY_NAME     VARCHAR2(200) NOT NULL,
    DESCRIPTION       VARCHAR2(1000),
    IS_ACTIVE         NUMBER(1) DEFAULT 1 NOT NULL,
    DISPLAY_ORDER     NUMBER(5) DEFAULT 0,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_RULE_CAT_ACTIVE ON MRE_RULE_CATEGORY(IS_ACTIVE, DISPLAY_ORDER);

-- ============================================================
-- TABLE: MRE_RULE_DEFINITION
-- Stores each rule with DRL content, version, maker-checker
-- ============================================================

CREATE TABLE MRE_RULE_DEFINITION (
    ID                NUMBER(19) DEFAULT MRE_RULE_DEFINITION_SEQ.NEXTVAL PRIMARY KEY,
    RULE_CODE         VARCHAR2(50) NOT NULL UNIQUE,
    RULE_NAME         VARCHAR2(300) NOT NULL,
    CATEGORY_ID       NUMBER(19) NOT NULL,
    DRL_CONTENT       CLOB NOT NULL,
    SALIENCE          NUMBER(5) DEFAULT 10,
    VERSION           NUMBER(10) DEFAULT 1 NOT NULL,
    STATUS            VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    EFFECTIVE_FROM    TIMESTAMP,
    EFFECTIVE_TO      TIMESTAMP,
    CREATED_BY        VARCHAR2(100) NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY        VARCHAR2(100),
    UPDATED_AT        TIMESTAMP,
    APPROVED_BY       VARCHAR2(100),
    APPROVED_AT       TIMESTAMP,
    CONSTRAINT FK_RULE_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES MRE_RULE_CATEGORY(ID),
    CONSTRAINT CHK_RULE_STATUS CHECK (STATUS IN ('DRAFT','PENDING_REVIEW','ACTIVE','INACTIVE','ARCHIVED'))
);

CREATE INDEX IDX_RULE_DEF_STATUS ON MRE_RULE_DEFINITION(STATUS);
CREATE INDEX IDX_RULE_DEF_CATEGORY ON MRE_RULE_DEFINITION(CATEGORY_ID, STATUS);
CREATE INDEX IDX_RULE_DEF_CODE ON MRE_RULE_DEFINITION(RULE_CODE);

-- ============================================================
-- TABLE: MRE_RULE_HISTORY
-- Immutable audit trail of all rule changes
-- ============================================================

CREATE TABLE MRE_RULE_HISTORY (
    ID                NUMBER(19) DEFAULT MRE_RULE_HISTORY_SEQ.NEXTVAL PRIMARY KEY,
    RULE_ID           NUMBER(19) NOT NULL,
    VERSION           NUMBER(10) NOT NULL,
    DRL_CONTENT       CLOB NOT NULL,
    CHANGE_REASON     VARCHAR2(1000),
    ACTION            VARCHAR2(50) NOT NULL,
    CHANGED_BY        VARCHAR2(100) NOT NULL,
    CHANGED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_HISTORY_RULE FOREIGN KEY (RULE_ID) REFERENCES MRE_RULE_DEFINITION(ID)
);

CREATE INDEX IDX_RULE_HIST_RULE ON MRE_RULE_HISTORY(RULE_ID, VERSION);

-- ============================================================
-- TABLE: MRE_DEPLOYMENT
-- Tracks rule deployment events
-- ============================================================

CREATE TABLE MRE_DEPLOYMENT (
    ID                NUMBER(19) DEFAULT MRE_DEPLOYMENT_SEQ.NEXTVAL PRIMARY KEY,
    DEPLOYMENT_ID     VARCHAR2(50) NOT NULL UNIQUE,
    RULES_DEPLOYED    NUMBER(10) NOT NULL,
    STATUS            VARCHAR2(20) NOT NULL,
    DEPLOYED_BY       VARCHAR2(100) NOT NULL,
    DEPLOYED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ERROR_MESSAGE     VARCHAR2(2000),
    CONSTRAINT CHK_DEPLOY_STATUS CHECK (STATUS IN ('SUCCESS','FAILED','ROLLED_BACK'))
);

CREATE INDEX IDX_DEPLOYMENT_STATUS ON MRE_DEPLOYMENT(STATUS, DEPLOYED_AT);

-- ============================================================
-- TABLE: MRE_GROUND_CONFIG
-- Configurable MRE grounds (Q13, Q16, Q17 clauses)
-- ============================================================

CREATE TABLE MRE_GROUND_CONFIG (
    ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GROUND_CODE       VARCHAR2(50) NOT NULL UNIQUE,
    CLAUSE_REF        VARCHAR2(20) NOT NULL,
    DESCRIPTION       VARCHAR2(500) NOT NULL,
    IS_ACTIVE         NUMBER(1) DEFAULT 1 NOT NULL,
    EVALUATION_ORDER  NUMBER(5) DEFAULT 0,
    FAIL_MESSAGE      VARCHAR2(1000),
    PASS_MESSAGE      VARCHAR2(1000),
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_GROUND_ACTIVE ON MRE_GROUND_CONFIG(IS_ACTIVE, EVALUATION_ORDER);

-- ============================================================
-- TABLE: MRE_WINDOW_CONFIG
-- Configurable window days per category/entity type
-- ============================================================

CREATE TABLE MRE_WINDOW_CONFIG (
    ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATEGORY_CODE     VARCHAR2(50) NOT NULL,
    ENTITY_TYPE       VARCHAR2(50) DEFAULT 'ALL',
    WINDOW_DAYS       NUMBER(5) NOT NULL,
    FILING_DEADLINE   NUMBER(5) NOT NULL DEFAULT 365,
    WINDOW_BASIS      VARCHAR2(20) DEFAULT 'CALENDAR' NOT NULL,
    IS_ACTIVE         NUMBER(1) DEFAULT 1 NOT NULL,
    EFFECTIVE_FROM    DATE NOT NULL,
    EFFECTIVE_TO      DATE,
    CREATED_BY        VARCHAR2(100),
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CHK_WINDOW_BASIS CHECK (WINDOW_BASIS IN ('CALENDAR','BUSINESS'))
);

CREATE UNIQUE INDEX IDX_WINDOW_UNIQUE ON MRE_WINDOW_CONFIG(CATEGORY_CODE, ENTITY_TYPE, EFFECTIVE_FROM);

COMMIT;
