-- Seed DEO Users for Email Syndication Round-Robin
INSERT INTO DEO_USER (USER_ID, DISPLAY_NAME, EMAIL, IS_ACTIVE, IS_ON_LEAVE, MAX_THRESHOLD, CURRENT_ASSIGNED_COUNT, SORT_ORDER, CREATED_AT, UPDATED_AT)
VALUES ('DEO001', 'Rahul Sharma', 'rahul.sharma@rbi.org.in', true, false, 10, 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DEO_USER (USER_ID, DISPLAY_NAME, EMAIL, IS_ACTIVE, IS_ON_LEAVE, MAX_THRESHOLD, CURRENT_ASSIGNED_COUNT, SORT_ORDER, CREATED_AT, UPDATED_AT)
VALUES ('DEO002', 'Priya Patel', 'priya.patel@rbi.org.in', true, false, 10, 0, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DEO_USER (USER_ID, DISPLAY_NAME, EMAIL, IS_ACTIVE, IS_ON_LEAVE, MAX_THRESHOLD, CURRENT_ASSIGNED_COUNT, SORT_ORDER, CREATED_AT, UPDATED_AT)
VALUES ('DEO003', 'Amit Kumar', 'amit.kumar@rbi.org.in', true, false, 8, 0, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DEO_USER (USER_ID, DISPLAY_NAME, EMAIL, IS_ACTIVE, IS_ON_LEAVE, MAX_THRESHOLD, CURRENT_ASSIGNED_COUNT, SORT_ORDER, CREATED_AT, UPDATED_AT)
VALUES ('DEO004', 'Sneha Reddy', 'sneha.reddy@rbi.org.in', true, true, 10, 0, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DEO_USER (USER_ID, DISPLAY_NAME, EMAIL, IS_ACTIVE, IS_ON_LEAVE, MAX_THRESHOLD, CURRENT_ASSIGNED_COUNT, SORT_ORDER, CREATED_AT, UPDATED_AT)
VALUES ('DEO005', 'Vikram Singh', 'vikram.singh@rbi.org.in', true, false, 12, 0, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Seed Ignore List entries
INSERT INTO EMAIL_IGNORE_LIST (EMAIL_PATTERN, PATTERN_TYPE, REASON, ADDED_BY, IS_ACTIVE, CREATED_AT)
VALUES ('noreply@rbi.org.in', 'EXACT', 'System generated emails', 'system', true, CURRENT_TIMESTAMP);

INSERT INTO EMAIL_IGNORE_LIST (EMAIL_PATTERN, PATTERN_TYPE, REASON, ADDED_BY, IS_ACTIVE, CREATED_AT)
VALUES ('*@mailer-daemon.com', 'DOMAIN', 'Bounce-back emails', 'system', true, CURRENT_TIMESTAMP);

INSERT INTO EMAIL_IGNORE_LIST (EMAIL_PATTERN, PATTERN_TYPE, REASON, ADDED_BY, IS_ACTIVE, CREATED_AT)
VALUES ('no-reply@notifications.gov.in', 'EXACT', 'Government notification system', 'system', true, CURRENT_TIMESTAMP);

-- Seed sample email drafts
INSERT INTO EMAIL_DRAFT (DRAFT_ID, MESSAGE_ID, SENDER_EMAIL, SUBJECT, BODY, COMPLAINANT_NAME, CATEGORY, STATUS, ASSIGNED_TO, IS_DUPLICATE, OCR_PROCESSED, MODE_OF_RECEIPT, RECEIVED_AT, CREATED_AT, UPDATED_AT)
VALUES ('DRF-1001', 'msg-001@gmail.com', 'customer1@gmail.com', 'ATM transaction failed but amount debited', 'Dear Sir, I tried withdrawing Rs 10000 from SBI ATM at MG Road branch on 25th May 2026. Transaction failed but amount was debited from my account. Please help.', 'Ramesh Gupta', 'ATM', 'ASSIGNED', 'DEO001', false, false, 'EMAIL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO EMAIL_DRAFT (DRAFT_ID, MESSAGE_ID, SENDER_EMAIL, SUBJECT, BODY, COMPLAINANT_NAME, CATEGORY, STATUS, ASSIGNED_TO, IS_DUPLICATE, OCR_PROCESSED, MODE_OF_RECEIPT, RECEIVED_AT, CREATED_AT, UPDATED_AT)
VALUES ('DRF-1002', 'msg-002@yahoo.com', 'user2@yahoo.com', 'Unauthorized UPI transaction', 'I noticed an unauthorized UPI transaction of Rs 5000 from my account. I did not authorize this payment. Please investigate.', 'Sunita Devi', 'UPI', 'PENDING', NULL, false, false, 'EMAIL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO EMAIL_DRAFT (DRAFT_ID, MESSAGE_ID, SENDER_EMAIL, SUBJECT, BODY, COMPLAINANT_NAME, CATEGORY, STATUS, ASSIGNED_TO, IS_DUPLICATE, OCR_PROCESSED, MODE_OF_RECEIPT, RECEIVED_AT, CREATED_AT, UPDATED_AT)
VALUES ('DRF-1003', 'msg-003@gmail.com', 'customer3@gmail.com', 'Loan EMI overcharged', 'My home loan EMI was overcharged this month. The regular EMI is Rs 25000 but Rs 32000 was debited. Loan account number: HL20230045678.', 'Deepak Verma', 'LOAN', 'IN_PROGRESS', 'DEO002', false, true, 'EMAIL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
