-- ============================================================
-- V100 — Portal intake additions: account type master, complaint comments, wizard answer snapshot
--
-- Oracle counterpart of the current portal changes. The MySQL tree has no matching migration because
-- every MySQL profile (dev-local, h2) runs ddl-auto=update and Hibernate creates these itself; the
-- Oracle profile runs ddl-auto=validate, so the schema has to exist before the context starts or
-- startup fails on all three objects.
--
-- WHAT THIS ADDS AND WHY
--
--   1. ACCOUNT_TYPE_MASTER — the account-type dropdown on the file-complaint wizard was a hardcoded
--      list in the frontend. Moving it to a master table is what lets the label be changed without a
--      redeploy and what makes SORT_ORDER/ACTIVE curation possible. Seeded by DataInitializer, not
--      here, so the seed stays in one place and does not drift between the two trees.
--
--      VALUE is created unquoted, so Oracle stores it as uppercase VALUE. The entity maps it as
--      @Column(name = "\"value\"") because `value` is reserved in MySQL and must be quoted there, and
--      a quoted identifier is case-sensitive — so this migration deliberately mirrors the existing
--      TRANSLATIONS precedent in V1__complete_schema.sql (VALUE CLOB, unquoted, under the same quoted
--      entity mapping) rather than inventing a lowercase "value" column. If ddl-auto=validate ever
--      rejects one of these on Oracle it will reject both, and the fix belongs in the entity mapping
--      for both, not in a divergent column name here. VALUE is not an Oracle reserved word, so no
--      quoting is needed on this side.
--
--   2. COMPLAINT_COMMENTS — internal officer notes on a case. Previously the portal held these in
--      component state only, so a note vanished on reload and nothing was visible to the next officer.
--      COMPLAINT_NUMBER and NO_RECORD_NUMBER are both nullable and neither is a foreign key: a comment
--      can hang off a numbered complaint OR off an intake that was recorded as no-record and therefore
--      has no COMPLAINTS row to reference. Making either one NOT NULL would forbid one of the two
--      supported flows.
--
--   3. COMPLAINTS.ELIGIBILITY_ANSWERS_JSON / WIZARD_FORM_DATA_JSON — the normalised complaint columns
--      only cover the subset the workflow reads, but the review screen has to render every question
--      the citizen actually answered (eligibility Q&A, per-question sub-answers, the amount breakdown),
--      and those have no column of their own. Stored as CLOB for the same reason COMPLAINT_DRAFTS
--      stores its wizard state as CLOB. Note ELIGIBILITY_ANSWERS_JSON already exists on
--      COMPLAINT_DRAFTS (V5) — this is the distinct, submitted-and-frozen copy on COMPLAINTS.
--
-- Nothing is backfilled. The two snapshot columns are NULL for every pre-existing complaint, which is
-- correct: those submissions were never captured, and synthesising a snapshot from the normalised
-- columns would present a partial reconstruction as if it were what the citizen submitted.
--
-- Re-running is safe: guarded on USER_TABLES / USER_TAB_COLUMNS / USER_INDEXES.
-- ============================================================

DECLARE
    PROCEDURE add_table(p_table VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_column(p_table VARCHAR2, p_column VARCHAR2, p_definition VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_column;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_column || ' ' || p_definition || ')';
        END IF;
    END;

    PROCEDURE add_index(p_index VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;
BEGIN
    -- ── 1. Account type master ──
    -- ACTIVE is NUMBER(1), matching how the Oracle DDL renders the other Boolean master flags
    -- (MRE_RULE_CATEGORY.IS_ACTIVE etc. in V1) rather than the CHAR(1) 'Y'/'N' used where the entity
    -- field is itself a String.
    add_table('ACCOUNT_TYPE_MASTER',
        'CREATE TABLE ACCOUNT_TYPE_MASTER ('
        || ' ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
        || ' LABEL VARCHAR2(100) NOT NULL,'
        || ' VALUE VARCHAR2(50) NOT NULL,'
        || ' ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,'
        || ' SORT_ORDER NUMBER(10) DEFAULT 0 NOT NULL,'
        || ' CONSTRAINT UQ_ACCOUNT_TYPE_VALUE UNIQUE (VALUE))');

    add_index('IDX_ACCOUNT_TYPE_ACTIVE',
        'CREATE INDEX IDX_ACCOUNT_TYPE_ACTIVE ON ACCOUNT_TYPE_MASTER (ACTIVE, SORT_ORDER)');

    -- ── 2. Officer comments on a complaint or a no-record intake ──
    add_table('COMPLAINT_COMMENTS',
        'CREATE TABLE COMPLAINT_COMMENTS ('
        || ' ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
        || ' COMPLAINT_NUMBER VARCHAR2(50),'
        || ' NO_RECORD_NUMBER VARCHAR2(50),'
        || ' AUTHOR VARCHAR2(200) NOT NULL,'
        || ' INITIALS VARCHAR2(10),'
        || ' TEXT CLOB,'
        || ' ROLE VARCHAR2(50),'
        || ' TARGET VARCHAR2(50),'
        || ' COLOR VARCHAR2(20),'
        || ' CREATED_AT TIMESTAMP(6))');

    -- Two indexes rather than one because the two lookups are on different columns, and a comment
    -- populates only one of them. CREATED_AT is included as the trailing key since both read paths
    -- order by it; ascending, because a DESC index in Oracle is a function-based index and the
    -- optimiser can read an ascending one backwards anyway.
    add_index('IDX_CMT_COMPLAINT_CREATED',
        'CREATE INDEX IDX_CMT_COMPLAINT_CREATED ON COMPLAINT_COMMENTS (COMPLAINT_NUMBER, CREATED_AT)');
    add_index('IDX_CMT_NORECORD_CREATED',
        'CREATE INDEX IDX_CMT_NORECORD_CREATED ON COMPLAINT_COMMENTS (NO_RECORD_NUMBER, CREATED_AT)');

    -- ── 3. Submitted wizard answers, kept verbatim alongside the normalised columns ──
    add_column('COMPLAINTS', 'ELIGIBILITY_ANSWERS_JSON', 'CLOB');
    add_column('COMPLAINTS', 'WIZARD_FORM_DATA_JSON', 'CLOB');
END;
/
