-- ============================================================
-- V104 — NOTIFICATION_DELIVERY_LOG becomes the outbound dispatch queue
--
-- Oracle counterpart of MySQL V107. The two directories' V-numbers are NOT in sync.
--
-- WHY THIS EXISTS
--
--   cms-backend holds no SMTP credentials and no SMS gateway; cms-notification-service owns the only
--   JavaMailSender in the repository. An EMAIL or SMS attempt is therefore recorded PENDING when
--   cms-backend publishes it to the notification.dispatch Kafka topic, and cms-notification-service
--   settles it to SENT or FAILED once the real send has been attempted.
--
-- WHY THIS RELAXES THE APPEND-ONLY RULE FROM V28
--
--   Only STATUS, ERROR_MESSAGE and the new SETTLED_AT are mutable. The columns identifying which
--   attempt a row represents stay immutable, so a retry still appends a row rather than overwriting
--   one. PENDING -> SENT is a queue state machine, and a row still PENDING is the only durable
--   evidence that a message reached no gateway, which is what makes it re-drivable. The previous
--   code wrote SENT at hand-off time, which made a broker outage and a real delivery indistinguishable.
--
--   IN_APP rows keep DISPATCH_REF NULL and are still settled inline: they never leave the application,
--   so no other service has anything to confirm.
-- ============================================================

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'NOTIFICATION_DELIVERY_LOG' AND COLUMN_NAME = 'DISPATCH_REF';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE NOTIFICATION_DELIVERY_LOG ADD (DISPATCH_REF VARCHAR2(64))';
        EXECUTE IMMEDIATE
            'COMMENT ON COLUMN NOTIFICATION_DELIVERY_LOG.DISPATCH_REF IS ''Correlation key the sending service settles this row by. UUID generated by the publisher, because the Kafka message is built before the insert is flushed and cannot know the generated id. NULL for IN_APP.''';
    END IF;

    SELECT COUNT(*) INTO v_exists FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'NOTIFICATION_DELIVERY_LOG' AND COLUMN_NAME = 'SETTLED_AT';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE NOTIFICATION_DELIVERY_LOG ADD (SETTLED_AT TIMESTAMP(6))';
        EXECUTE IMMEDIATE
            'COMMENT ON COLUMN NOTIFICATION_DELIVERY_LOG.SETTLED_AT IS ''When a PENDING attempt was resolved to SENT or FAILED. NULL while still queued.''';
    END IF;

    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_NDL_DISPATCH_REF';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_NDL_DISPATCH_REF ON NOTIFICATION_DELIVERY_LOG (DISPATCH_REF)';
    END IF;
END;
/

-- Existing rows predate the queue and were written already-terminal. Backfilling SETTLED_AT from
-- ATTEMPTED_AT keeps "SETTLED_AT IS NULL AND STATUS = 'PENDING'" a reliable test for "still queued"
-- — without it every historical row would answer that query. No automated re-drive of stuck rows
-- exists yet; for now this is an operator query.
UPDATE NOTIFICATION_DELIVERY_LOG
   SET SETTLED_AT = ATTEMPTED_AT
 WHERE SETTLED_AT IS NULL
   AND STATUS IN ('SENT', 'FAILED');

COMMIT;
