-- ============================================================
-- V105 — FR-G-013: Non-Maintainable complaints get a Case ID instead of a Complaint Number
--
-- Oracle counterpart of MySQL V108. The two directories' V-numbers are NOT in sync.
--
-- See MySQL V108's header for the full rationale: COMPLAINTS.COMPLAINT_NUMBER is relaxed to nullable
-- so a non-maintainable row can be saved without one, CASE_ID is a new nullable column, and
-- CASE_ID_SEQUENCE is a separate counter mirroring COMPLAINT_NUMBER_SEQUENCE.
-- ============================================================

DECLARE
    v_nullable VARCHAR2(1);
BEGIN
    SELECT NULLABLE INTO v_nullable FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'COMPLAINT_NUMBER';
    IF v_nullable = 'N' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE COMPLAINTS MODIFY (COMPLAINT_NUMBER NULL)';
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'CASE_ID';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE COMPLAINTS ADD CASE_ID VARCHAR2(50) NULL';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'NON_MAINTAINABLE_CLAUSE_CODE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE COMPLAINTS ADD NON_MAINTAINABLE_CLAUSE_CODE VARCHAR2(100) NULL';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_COMPLAINT_CASE_ID';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_COMPLAINT_CASE_ID ON COMPLAINTS(CASE_ID)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'CASE_ID_SEQUENCE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE CASE_ID_SEQUENCE (
                ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                OFFICE_CODE VARCHAR2(10) NOT NULL,
                FINANCIAL_YEAR VARCHAR2(6) NOT NULL,
                LAST_SEQUENCE NUMBER(10) DEFAULT 0 NOT NULL,
                UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
                CONSTRAINT UK_CASE_ID_OFFICE_FY UNIQUE (OFFICE_CODE, FINANCIAL_YEAR)
            )';
    END IF;
END;
/
