-- ============================================================
-- V106 — CEPC_LEGAL_CASE: the legal-case dossier behind the Legal Case sidebar icon
--
-- Oracle counterpart of MySQL V109. The two directories' V-numbers are NOT in sync.
--
-- WHY THIS EXISTS
--
--   Mirrors MySQL V109's header: this is a new CEPC-owned table, parallel to (not shared with)
--   RBIO_LEGAL_CASE, which carries only 6 fields (a sub-judice flag, not a dossier) and is RBIO-
--   branded throughout. CEPC_LEGAL_CASE has one row per complaint — COMPLAINT_NUMBER is UNIQUE —
--   because the panel it backs has a single "Update Details" button, not an add/list UI.
--
-- ORACLE-SPECIFIC NOTES
--
--   TEXT is not an Oracle type (see V101's header for the full argument); the five long-text
--   columns are CLOB here, matching the entity's columnDefinition = "TEXT" for MySQL's sake.
--
--   The two Yes/No fields (RBI_FIRST_RESPONDENT, APPEARANCE_REQUIRED) map from a Java Boolean, so
--   they are NUMBER(1) and NOT CHAR(1) 'Y'/'N' — same distinction V101's header draws for the
--   Boolean- vs String-typed flags elsewhere in this schema.
--
--   Guarded on USER_TABLES so a re-run is safe. The guard compares TABLE_NAME against a bare
--   uppercase literal, which is correct here (opposite of MySQL V109's UPPER() form) — see V101's
--   header for the full argument; do not copy either file's guard into the other.
-- ============================================================

DECLARE
    PROCEDURE add_table(p_table VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;
BEGIN
    add_table('CEPC_LEGAL_CASE', '
        CREATE TABLE CEPC_LEGAL_CASE (
            ID                            NUMBER GENERATED BY DEFAULT AS IDENTITY,
            COMPLAINT_NUMBER              VARCHAR2(50)   NOT NULL,
            CASE_NUMBER                   VARCHAR2(100),
            COURT_NAME                    VARCHAR2(200),
            PARTIES_OF_CASE               VARCHAR2(500),
            REGION_OF_LEGAL_TEAM          VARCHAR2(100),
            RBI_FIRST_RESPONDENT          NUMBER(1),
            APPEARANCE_REQUIRED           NUMBER(1),
            SUBJECT_MATTER                CLOB,
            ADVOCATE_NAME                 VARCHAR2(200),
            ASSISTANT_LEGAL_ADVISOR       VARCHAR2(200),
            NEXT_HEARING_DATE             DATE,
            PRESENT_STATUS                CLOB,
            ACTION_TAKEN_SO_FAR           CLOB,
            ACTION_TO_BE_TAKEN            CLOB,
            MONETARY_CLAIM_DETAILS        CLOB,
            CREATED_BY                    VARCHAR2(200),
            LAST_MODIFIED_BY              VARCHAR2(200),
            CREATED_AT                    TIMESTAMP,
            LAST_MODIFIED_AT              TIMESTAMP,
            CONSTRAINT PK_CEPC_LEGAL_CASE PRIMARY KEY (ID),
            -- One dossier per complaint: every save is an upsert against this constraint.
            CONSTRAINT UK_CEPC_LEGAL_CASE_COMPLAINT UNIQUE (COMPLAINT_NUMBER)
        )');
END;
/
