-- V107: Threaded staff comments on a complaint, with PRIVATE / RESTRICTED / PUBLIC readership
-- Oracle version (mirrors database/V110__complaint_comment_thread.sql; the two directories' V-numbers
-- are not in sync)
--
-- Context: three partial comment-like surfaces already exist and NONE of them models readership.
-- COMPLAINT_QUERY_MESSAGE is the RE<->RBI correspondence thread (AUTHOR_SIDE RE|RBI, append-only per
-- UST857). COMPLAINT_INTERNAL_NOTE is flat, entity-side-only, and its service refuses any non-RE
-- caller. REASSIGNMENT_CLARIFICATION is scoped to a reassignment request. None of the three lets a
-- staff author choose an audience, so a staff-side note visible to a named few had nowhere to live.
-- All three are left untouched — their API shapes are pinned by E2E specs.
--
-- ═══ VISIBILITY IS NOT A CITIZEN-FACING SETTING ═══
-- PUBLIC means public-to-STAFF. The complainant has no readership of this table at ANY tier and no
-- endpoint serves it to a citizen session: ComplaintCommentService gates every path on an ALLOWLIST
-- of staff roles (a denylist would admit any identity nobody thought to name). The tier only ever
-- NARROWS the staff audience. Do not add a citizen-visible flag to this table; add a separate,
-- citizen-facing table if a citizen-visible remark is ever required.
--
-- RESTRICTED_TO_ROLES follows the CLOSURE_CLAUSE_MASTER.RESTRICTED_TO_ROLES precedent
-- (comma-separated, whole-token comparison in code — never a substring test, which would match
-- 'ADMIN' inside 'RBIO_ADMIN'). It differs in ONE respect, deliberately: there a blank column means
-- unrestricted, whereas a RESTRICTED comment with both lists blank stays visible to its AUTHOR ALONE,
-- because the author explicitly asked for narrow and failing open would publish it.
--
-- Threading is ONE level. PARENT_ID references this table; the service refuses a reply whose parent
-- already has a parent. A reply INHERITS its parent's visibility and both restriction lists, so a
-- PUBLIC reply cannot leak a RESTRICTED parent's substance.
--
-- Re-running is safe: the CREATE is guarded on USER_TABLES and every index on USER_INDEXES.
-- TIMESTAMP(6) is used where MySQL uses DATETIME(6) so that comments posted within the same second
-- still order deterministically.

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'COMPLAINT_COMMENT';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE COMPLAINT_COMMENT (
                ID                     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                COMPLAINT_ID           NUMBER(19)      NOT NULL,
                PARENT_ID              NUMBER(19),
                BODY                   CLOB            NOT NULL,
                VISIBILITY             VARCHAR2(20)    NOT NULL,
                RESTRICTED_TO_ROLES    VARCHAR2(1000),
                RESTRICTED_TO_USER_IDS VARCHAR2(2000),
                AUTHOR_USER_ID         VARCHAR2(100)   NOT NULL,
                AUTHOR_NAME            VARCHAR2(200)   NOT NULL,
                AUTHOR_ROLE            VARCHAR2(50),
                CREATED_AT             TIMESTAMP(6)    NOT NULL,
                UPDATED_AT             TIMESTAMP(6),
                EDIT_COUNT             NUMBER(10)      DEFAULT 0 NOT NULL,
                CONSTRAINT PK_COMPLAINT_COMMENT PRIMARY KEY (ID),
                CONSTRAINT FK_CCM_PARENT FOREIGN KEY (PARENT_ID) REFERENCES COMPLAINT_COMMENT(ID)
            )';
    END IF;
END;
/

DECLARE
    PROCEDURE add_idx(p_name VARCHAR2, p_ddl VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = p_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;
BEGIN
    add_idx('IDX_CCM_COMPLAINT',
            'CREATE INDEX IDX_CCM_COMPLAINT ON COMPLAINT_COMMENT(COMPLAINT_ID, CREATED_AT)');
    add_idx('IDX_CCM_PARENT',
            'CREATE INDEX IDX_CCM_PARENT ON COMPLAINT_COMMENT(PARENT_ID)');
    add_idx('IDX_CCM_AUTHOR',
            'CREATE INDEX IDX_CCM_AUTHOR ON COMPLAINT_COMMENT(AUTHOR_USER_ID)');
END;
/
