-- V109: Assistance rail — Tier 0 per-user memory table, and the two Tier 1 prior indexes
-- Oracle version (mirrors database/V112__assistance_rail.sql; the two directories' V-numbers are not
-- in sync — this is the twin of MySQL V112, not of any V109 there)
--
-- Brief 21. The rail carries exactly two tiers: Tier 0 is per-user/per-complaint continuity (what this
-- officer was doing here last time) and Tier 1 is precomputed aggregate priors. There is no Tier 2 —
-- no inference, no embeddings, no vector column — and this migration deliberately leaves no room for
-- one. If a signal needs reasoning over case text to decide whether it is worth saying, it does not
-- belong on the rail and it does not belong in this schema.
--
-- ═══ WHY A NEW TABLE RATHER THAN REUSING STAFF_DRAFT ═══
-- STAFF_DRAFT (oracle V97) is also per-owner and per-complaint, and the overlap is real, but it is the
-- wrong home for three reasons:
--   1. Its unique key is (MILESTONE, OWNER_USER_ID, COMPLAINT_NUMBER) — milestone-scoped by design,
--      because UST674 needs one draft per workflow milestone. The rail's memory is per SCREEN VISIT and
--      has no milestone; it would have to invent a fake one to key on.
--   2. FORM_DATA_JSON is NOT NULL and holds a serialised form. The rail records a section name and a
--      free-text fragment, so every row would carry a dummy JSON object to satisfy the constraint.
--   3. STAFF_DRAFT is resumable WORK. Deleting a draft loses an officer's typing. The rail's memory is
--      a convenience that can be dropped wholesale without harm. Mixing a disposable cache into the
--      table that holds unsaved work means neither can be pruned on its own schedule.
-- STAFF_DRAFT is left completely untouched.
--
-- ═══ CASE SENSITIVITY: WHY THIS FILE NEEDS NO COLLATION CLAUSE ═══
-- The MySQL twin must declare OWNER_USER_ID and COMPLAINT_NUMBER as utf8mb4_bin, because that schema's
-- prevailing utf8mb4_0900_ai_ci would make 'jdoe' and 'JDOE' compare EQUAL — collapsing two distinct
-- Keycloak principals onto ONE row, so that each would be served the other's unsaved text. Tier 0's
-- per-user key IS the privacy boundary, so that folding is a disclosure bug, not an inconvenience.
--   Oracle compares VARCHAR2 case-SENSITIVELY by default, so the unique key below is already exact and
-- no COLLATE clause is required. This is the one respect in which the two files legitimately differ,
-- and it is called out because the natural assumption on reading them side by side is that the MySQL
-- file's collation was forgotten here.
--   The application normalises both values regardless (AssistanceRailMemory.normaliseOwner lower-cases,
-- normaliseComplaint upper-cases) on every read and write path, so behaviour is IDENTICAL on both
-- engines rather than merely safe on each. That normalisation is the primary control: ddl-auto:update,
-- not this file, is what builds the schema in several environments.
--
-- ═══ THE UNIQUE KEY IS ALSO THE MULTI-POD LOCK ═══
-- No advisory lock and no SELECT ... FOR UPDATE. The frontend writes this as the officer leaves a
-- screen, so two pods can process the same officer leaving two tabs at once; both find no row and both
-- INSERT, and the constraint decides. AssistanceRailService catches the loser's
-- DataIntegrityViolationException and retries as an UPDATE. That is why the key must exist in the
-- database and not merely in the entity.
--
-- ═══ THE TWO INDEXES ON COMPLAINTS ═══
-- Column orders are carried over from the MySQL twin, where they were chosen from MEASURED EXPLAIN
-- output on a 2769-row dev dataset. The measurements were taken on MySQL because that is the only
-- engine with populated data available; the reasoning behind each order (equality columns before range
-- columns, selective column first, a trailing column present only so the index covers) is engine
-- -independent and holds on Oracle's optimiser too. The plans themselves are NOT verified on Oracle —
-- no Oracle instance was reachable — and that is reported rather than implied.
--
-- Re-running is safe: the CREATE is guarded on USER_TABLES and every index on USER_INDEXES.
-- TIMESTAMP(6) is used where MySQL uses DATETIME(6), matching the sibling migrations.

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'ASSISTANCE_RAIL_MEMORY';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE ASSISTANCE_RAIL_MEMORY (
                ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,

                -- Resolved from the JWT server-side and lower-cased, NEVER taken from a request payload.
                OWNER_USER_ID    VARCHAR2(200)   NOT NULL,

                -- Upper-cased on write. Deliberately NOT a foreign key to COMPLAINTS: this is
                -- disposable continuity state, and an FK would make a complaint purge fail on rows
                -- that nobody needs kept.
                COMPLAINT_NUMBER VARCHAR2(50)    NOT NULL,

                -- The tab or section the officer last had open, as the SCREEN names it. Opaque to the
                -- server: validating against an enum of known sections would make every new tab a
                -- backend release.
                LAST_SECTION     VARCHAR2(100),

                -- Unsaved text left behind, truncated to 4000 chars by the application. VARCHAR2 and
                -- NOT a CLOB, for two reasons: 4000 is exactly Oracle''s VARCHAR2 limit so no CLOB is
                -- needed, and the rail shows a recognisable REMINDER that a draft exists rather than
                -- the draft itself — STAFF_DRAFT is where resumable form state belongs, and
                -- duplicating it here would give an officer two places to resume from that can
                -- disagree.
                DRAFT_TEXT       VARCHAR2(4000),

                -- Server-assigned. A client-supplied timestamp would let a screen claim a visit that
                -- never happened, and "you were last here on..." is only worth showing if it is true.
                LAST_VIEWED_AT   TIMESTAMP(6)    NOT NULL,
                UPDATED_AT       TIMESTAMP(6),

                CONSTRAINT PK_ASSISTANCE_RAIL_MEMORY PRIMARY KEY (ID),

                -- The privacy boundary AND the multi-pod lock. See the header.
                CONSTRAINT UK_ARM_OWNER_COMPLAINT UNIQUE (OWNER_USER_ID, COMPLAINT_NUMBER)
            )';
    END IF;
END;
/

-- No index on COMPLAINT_NUMBER alone, on purpose. The only read this table serves is "my memory for
-- this complaint", which the unique constraint above already satisfies as a leading-column seek (Oracle
-- backs a UNIQUE constraint with an index automatically). A complaint-only index would exist solely to
-- support a query that reads ACROSS owners — the one query Tier 0 must not have.
-- AssistanceRailMemoryRepository declares no such finder either; the control is layered.

DECLARE
    PROCEDURE add_idx(p_name VARCHAR2, p_ddl VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = p_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;
BEGIN
    -- Serves "N complaints against this entity closed under this clause".
    --
    -- CLOSURE_CLAUSE leads and it is not arbitrary. Both predicates are equalities, so either order can
    -- be sought; clause leads because ENTITY_CODE is badly skewed in real data (2419 of 2769 rows share
    -- one value) while CLOSURE_CLAUSE spreads across 5 values with the largest at 461. Leading with the
    -- more selective column keeps the seeked slice small.
    --   Measured on the MySQL twin: with this composite the plan is a covering seek (key_len=606,
    -- 'Using index'); with only the pre-existing single-column clause index it reads 461 rows to answer
    -- one count, on every staff screen load.
    add_idx('IDX_ARM_CLAUSE_ENTITY',
            'CREATE INDEX IDX_ARM_CLAUSE_ENTITY ON COMPLAINTS (CLOSURE_CLAUSE, ENTITY_CODE)');

    -- Serves "this category's median closure time is N days".
    --
    -- THREE columns, and the order is forced by the shape of the query rather than by the order the
    -- columns appear in it: CATEGORY_ID is an equality so it must lead; CLOSED_AT follows because
    -- 'IS NOT NULL' is a RANGE predicate and equalities can only be sought up to the first range
    -- column; CREATED_AT is last purely so the index COVERS — it is never a predicate, only a value the
    -- query selects. A trailing column that exists to cover rather than to filter is the whole reason
    -- this is three columns wide and not two.
    add_idx('IDX_ARM_CATEGORY_CLOSED',
            'CREATE INDEX IDX_ARM_CATEGORY_CLOSED ON COMPLAINTS (CATEGORY_ID, CLOSED_AT, CREATED_AT)');
END;
/

-- ═══ PRIORS THAT WERE WANTED AND ARE NOT HERE ═══
-- Recorded so the absence is a decision rather than an oversight. In each case a requirement and the
-- "must be cheap enough to run on every screen load" constraint collided, and the constraint won.
-- (Measurements are from the MySQL twin; see that file for the EXPLAIN output.)
--
-- 1. COMPLAINANT HISTORY MATCHED ON PHONE AS WELL AS EMAIL.
--    Shipped on email only, which is already indexed. Phone would widen recall but COMPLAINANT_PHONE
--    has NO index, and an OR across two columns cannot be index-sought even if both were indexed.
--    NOT fixed here because the fix is an index on a PII column that no other query needs — a decision
--    to take deliberately rather than smuggle in under a rail feature.
--    CONSEQUENCE: a complainant who filed twice with different email addresses is reported as two
--    people. The recall gap is real and is reported, not hidden.
--
-- 2. "N COMPLAINTS AGAINST THIS ENTITY ARE STILL OPEN."
--    Dropped outright. ENTITY_CODE has no standalone index and the status half is an IN list, i.e. a
--    range, so no seek is available on either column. The clause-precedent prior above only works
--    because CLOSURE_CLAUSE is indexed and leads.
--
-- 3. ANYTHING OVER COMPLAINT TEXT — "similar wording", "reads like the batch closed last week".
--    This is the excluded Tier 2 and the honest version needs inference. A LIKE '%...%' over a CLOB is
--    not a cheap stand-in for it: it is a full table scan that also does not work.
--
-- 4. REOPEN HISTORY AS ITS OWN SIGNAL.
--    Cheap enough but dropped as redundant: it is already on the complaint record the officer is
--    looking at, so the rail would be repeating the screen.
