-- V11: DPDP Act, 2023 consent record for citizen complaint filing (UST5)
-- Oracle version
--
-- Maps com.hrms.cms.entity.CitizenConsent. NOTICE_TEXT holds a snapshot of the notice actually
-- served to the citizen in their locale, not a foreign key to TRANSLATIONS: the DPDP Act requires
-- the consent manager to demonstrate, per data principal, exactly what notice was accepted. A live
-- lookup would silently re-write history the moment the wording is revised.
--
-- CONSENT_VERSION carries the notice edition in force at capture time (cms.auth.consent.version).
-- Bumping that property makes existing rows non-current, so citizens are re-asked.

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'CITIZEN_CONSENTS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE CITIZEN_CONSENTS (
                ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                MOBILE_NUMBER   VARCHAR2(15)   NOT NULL,
                PURPOSE         VARCHAR2(50)   NOT NULL,
                CONSENT_VERSION VARCHAR2(20)   NOT NULL,
                LOCALE          VARCHAR2(10)   NOT NULL,
                NOTICE_TEXT     VARCHAR2(2000) NOT NULL,
                GRANTED_AT      TIMESTAMP      NOT NULL,
                CLIENT_IP       VARCHAR2(50),
                USER_AGENT      VARCHAR2(500)
            )';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CONSENT_MOBILE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_CONSENT_MOBILE ON CITIZEN_CONSENTS(MOBILE_NUMBER)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CONSENT_GRANTED_AT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_CONSENT_GRANTED_AT ON CITIZEN_CONSENTS(GRANTED_AT)';
    END IF;

    -- Supports the "does this mobile hold a current consent for this purpose" lookup
    -- (CitizenConsentRepository.findTopByMobileNumberAndPurposeOrderByGrantedAtDesc).
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CONSENT_MOBILE_PURPOSE_TS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_CONSENT_MOBILE_PURPOSE_TS ON CITIZEN_CONSENTS(MOBILE_NUMBER, PURPOSE, GRANTED_AT)';
    END IF;
END;
/

-- ═══ Complaint-level declaration flag (UST5 enforcement point) ═══
-- FileComplaintRequest.declarationAccepted is asserted for ONLINE filings only; email / physical /
-- walk-in intake never saw a checkbox and must not be rejected. Persisted so a filed complaint
-- carries its own evidence of the step-5 declaration rather than relying on the consent row alone.
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'DECLARATION_ACCEPTED';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE COMPLAINTS ADD DECLARATION_ACCEPTED NUMBER(1)';
    END IF;
END;
/
