-- V15: RE <-> RBI query/correspondence threads (UST853, UST854, UST855, UST856, UST857, UST860)
-- Oracle version (mirrors database/V16__complaint_query_threads.sql; the two directories' V-numbers
-- are not in sync)
--
-- Context: RE query state was three scalar columns on a per-complaint singleton row
-- (RE_RESPONSE_TRACKER.QUERY_TEXT / QUERY_RAISED_AT). RePortalService.raiseQuery did a blind
-- setQueryText(), so every new query silently OVERWROTE the previous one — the opposite of the
-- tamper-evident history UST857 requires. There was no GET for queries and no RBI-side reply
-- endpoint at all, so the RBI side could not answer an RE query except as a timeline remark
-- string, and the author was the hardcoded literal "RE_PORTAL".
--
-- RE_RESPONSE_TRACKER.QUERY_TEXT/QUERY_RAISED_AT are left in place and are now legacy-read-only.
-- EXTENSION_GRANTED/EXTENSION_DAYS were dead columns (no setter call existed anywhere in the tree)
-- and are now driven by the extension-request approval path.
--
-- Re-running is safe: every CREATE is guarded on USER_TABLES, every ALTER on USER_TAB_COLUMNS, and
-- every index on USER_INDEXES. TIMESTAMP(6) is used where MySQL uses DATETIME(6) so that messages
-- posted within the same second still order deterministically.

-- ═══════════════════════════════════════════════════════════════════════════
-- Thread header
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'COMPLAINT_QUERY';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE COMPLAINT_QUERY (
                ID                     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                COMPLAINT_ID           NUMBER(19)     NOT NULL,
                ENTITY_CODE            VARCHAR2(50)   NOT NULL,
                QUERY_TYPE             VARCHAR2(30)   NOT NULL,
                SUBJECT                VARCHAR2(500)  NOT NULL,
                DIRECTION              VARCHAR2(20)   NOT NULL,
                PENDING_WITH           VARCHAR2(10)   NOT NULL,
                STATUS                 VARCHAR2(20)   NOT NULL,
                RAISED_BY_USER_ID      VARCHAR2(100)  NOT NULL,
                RAISED_BY_NAME         VARCHAR2(200)  NOT NULL,
                RAISED_BY_ROLE         VARCHAR2(50),
                RAISED_BY_SIDE         VARCHAR2(10)   NOT NULL,
                RAISED_AT              TIMESTAMP(6)   NOT NULL,
                RESOLVED_AT            TIMESTAMP(6),
                RESOLVED_BY            VARCHAR2(100),
                PROPOSED_DEADLINE      TIMESTAMP(6),
                EXTENSION_REASON       CLOB,
                DECISION               VARCHAR2(20),
                DECIDED_BY             VARCHAR2(100),
                DECIDED_AT             TIMESTAMP(6),
                DECISION_REASON        CLOB,
                GRANTED_DEADLINE       TIMESTAMP(6),
                MEETING_PURPOSE        CLOB,
                MEETING_OUTCOME        VARCHAR2(20),
                MEETING_DECLINE_REASON CLOB,
                CREATED_AT             TIMESTAMP(6),
                UPDATED_AT             TIMESTAMP(6),
                CONSTRAINT PK_COMPLAINT_QUERY PRIMARY KEY (ID)
            )';
    END IF;
END;
/

DECLARE
    PROCEDURE add_idx(p_name VARCHAR2, p_ddl VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = p_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;
BEGIN
    add_idx('IDX_CQ_COMPLAINT', 'CREATE INDEX IDX_CQ_COMPLAINT ON COMPLAINT_QUERY(COMPLAINT_ID)');
    add_idx('IDX_CQ_PENDING',   'CREATE INDEX IDX_CQ_PENDING ON COMPLAINT_QUERY(PENDING_WITH, STATUS)');
    add_idx('IDX_CQ_ENTITY',    'CREATE INDEX IDX_CQ_ENTITY ON COMPLAINT_QUERY(ENTITY_CODE)');
    add_idx('IDX_CQ_TYPE',      'CREATE INDEX IDX_CQ_TYPE ON COMPLAINT_QUERY(QUERY_TYPE)');
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- Append-only messages (UST857). No UPDATE or DELETE path exists in the
-- application; corrections are made by posting a follow-up message.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'COMPLAINT_QUERY_MESSAGE';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE COMPLAINT_QUERY_MESSAGE (
                ID              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                QUERY_ID        NUMBER(19)     NOT NULL,
                BODY            CLOB           NOT NULL,
                AUTHOR_USER_ID  VARCHAR2(100)  NOT NULL,
                AUTHOR_NAME     VARCHAR2(200)  NOT NULL,
                AUTHOR_ROLE     VARCHAR2(50),
                AUTHOR_SIDE     VARCHAR2(10)   NOT NULL,
                MESSAGE_KIND    VARCHAR2(20)   NOT NULL,
                POSTED_AT       TIMESTAMP(6)   NOT NULL,
                CONSTRAINT PK_COMPLAINT_QUERY_MESSAGE PRIMARY KEY (ID),
                CONSTRAINT FK_CQM_QUERY FOREIGN KEY (QUERY_ID) REFERENCES COMPLAINT_QUERY(ID)
            )';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CQM_QUERY';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_CQM_QUERY ON COMPLAINT_QUERY_MESSAGE(QUERY_ID, POSTED_AT)';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- Document-request checklist (UST854)
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'COMPLAINT_QUERY_DOC_ITEM';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE COMPLAINT_QUERY_DOC_ITEM (
                ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                QUERY_ID         NUMBER(19)      NOT NULL,
                ITEM_LABEL       VARCHAR2(300)   NOT NULL,
                ITEM_DESCRIPTION VARCHAR2(1000),
                DISPLAY_ORDER    NUMBER(10)      DEFAULT 0 NOT NULL,
                RESOLVED         NUMBER(1)       DEFAULT 0 NOT NULL,
                RESOLVED_AT      TIMESTAMP(6),
                RESOLVED_BY      VARCHAR2(100),
                ATTACHMENT_ID    NUMBER(19),
                CONSTRAINT PK_COMPLAINT_QUERY_DOC_ITEM PRIMARY KEY (ID),
                CONSTRAINT FK_CQDOC_QUERY FOREIGN KEY (QUERY_ID) REFERENCES COMPLAINT_QUERY(ID)
            )';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CQ_DOC_QUERY';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_CQ_DOC_QUERY ON COMPLAINT_QUERY_DOC_ITEM(QUERY_ID)';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- Meeting slots (UST855). Counter-proposals append new PROPOSED rows rather
-- than mutating the original, so the negotiation stays auditable.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'COMPLAINT_QUERY_SLOT';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE COMPLAINT_QUERY_SLOT (
                ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                QUERY_ID         NUMBER(19)     NOT NULL,
                PROPOSED_START   TIMESTAMP(6)   NOT NULL,
                PROPOSED_END     TIMESTAMP(6),
                SLOT_STATUS      VARCHAR2(20)   NOT NULL,
                PROPOSED_BY_SIDE VARCHAR2(10)   NOT NULL,
                DISPLAY_ORDER    NUMBER(10)     DEFAULT 0 NOT NULL,
                CREATED_AT       TIMESTAMP(6),
                CONSTRAINT PK_COMPLAINT_QUERY_SLOT PRIMARY KEY (ID),
                CONSTRAINT FK_CQSLOT_QUERY FOREIGN KEY (QUERY_ID) REFERENCES COMPLAINT_QUERY(ID)
            )';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CQ_SLOT_QUERY';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_CQ_SLOT_QUERY ON COMPLAINT_QUERY_SLOT(QUERY_ID)';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- Per-user read receipts (UST856)
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'COMPLAINT_QUERY_READ';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE COMPLAINT_QUERY_READ (
                ID                   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                QUERY_ID             NUMBER(19)     NOT NULL,
                USER_ID              VARCHAR2(100)  NOT NULL,
                LAST_READ_MESSAGE_ID NUMBER(19),
                LAST_READ_AT         TIMESTAMP(6),
                CONSTRAINT PK_COMPLAINT_QUERY_READ PRIMARY KEY (ID),
                CONSTRAINT UK_CQ_READ UNIQUE (QUERY_ID, USER_ID),
                CONSTRAINT FK_CQREAD_QUERY FOREIGN KEY (QUERY_ID) REFERENCES COMPLAINT_QUERY(ID)
            )';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CQ_READ_USER';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_CQ_READ_USER ON COMPLAINT_QUERY_READ(USER_ID)';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- Entity-side internal notes (UST860). Deliberately a SEPARATE table from the
-- query thread: UST857 requires thread messages to be permanently immutable,
-- while UST860 allows the author a 5-minute edit window. Keeping them apart
-- means the tamper-evident table has no mutable rows at all.
-- EDIT_LOCKED_AT is written by the server at insert and is what the server
-- checks on edit — never a client-supplied timestamp.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'COMPLAINT_INTERNAL_NOTE';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE COMPLAINT_INTERNAL_NOTE (
                ID             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                COMPLAINT_ID   NUMBER(19)     NOT NULL,
                ENTITY_CODE    VARCHAR2(50)   NOT NULL,
                BODY           CLOB           NOT NULL,
                AUTHOR_USER_ID VARCHAR2(100)  NOT NULL,
                AUTHOR_NAME    VARCHAR2(200)  NOT NULL,
                AUTHOR_ROLE    VARCHAR2(50),
                CREATED_AT     TIMESTAMP(6)   NOT NULL,
                UPDATED_AT     TIMESTAMP(6),
                EDIT_LOCKED_AT TIMESTAMP(6)   NOT NULL,
                EDIT_COUNT     NUMBER(10)     DEFAULT 0 NOT NULL,
                CONSTRAINT PK_COMPLAINT_INTERNAL_NOTE PRIMARY KEY (ID)
            )';
    END IF;
END;
/

DECLARE
    PROCEDURE add_idx(p_name VARCHAR2, p_ddl VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = p_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;
BEGIN
    add_idx('IDX_CIN_COMPLAINT', 'CREATE INDEX IDX_CIN_COMPLAINT ON COMPLAINT_INTERNAL_NOTE(COMPLAINT_ID)');
    add_idx('IDX_CIN_ENTITY',    'CREATE INDEX IDX_CIN_ENTITY ON COMPLAINT_INTERNAL_NOTE(ENTITY_CODE)');
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- Link in-thread uploads to the message that carried them (UST854). Reuses
-- COMPLAINT_ATTACHMENTS so existing size/type/virus validation applies.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_count NUMBER;

    PROCEDURE add_col(p_table VARCHAR2, p_name VARCHAR2, p_type VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD ' || p_name || ' ' || p_type;
        END IF;
    END;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'COMPLAINT_ATTACHMENTS';
    IF v_count = 0 THEN
        RETURN;
    END IF;

    add_col('COMPLAINT_ATTACHMENTS', 'QUERY_MESSAGE_ID', 'NUMBER(19)');
    add_col('COMPLAINT_ATTACHMENTS', 'UPLOADED_BY',      'VARCHAR2(100)');
END;
/

DECLARE
    v_exists NUMBER;
    v_table  NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_table FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'COMPLAINT_ATTACHMENTS' AND COLUMN_NAME = 'QUERY_MESSAGE_ID';
    IF v_table = 0 THEN
        RETURN;
    END IF;

    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_ATTACH_QUERY_MSG';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_ATTACH_QUERY_MSG ON COMPLAINT_ATTACHMENTS(QUERY_MESSAGE_ID)';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- SLA clock pause for approved extensions (UST853). The clock keeps running
-- while a request is PENDING; on approval the server pauses it and sets the new
-- deadline. SLA_PAUSE_MINUTES accumulates so a second extension does not lose
-- the first pause.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_count NUMBER;

    PROCEDURE add_col(p_table VARCHAR2, p_name VARCHAR2, p_type VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD ' || p_name || ' ' || p_type;
        END IF;
    END;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'RE_RESPONSE_TRACKER';
    IF v_count = 0 THEN
        RETURN;
    END IF;

    add_col('RE_RESPONSE_TRACKER', 'SLA_PAUSED',        'NUMBER(1) DEFAULT 0');
    add_col('RE_RESPONSE_TRACKER', 'SLA_PAUSED_AT',     'TIMESTAMP(6)');
    add_col('RE_RESPONSE_TRACKER', 'SLA_PAUSE_MINUTES', 'NUMBER(19) DEFAULT 0');
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- Configurable limits. No hardcoded values in code — these are read from
-- SYSTEM_CONFIG at runtime.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    PROCEDURE add_cfg(p_key VARCHAR2, p_val VARCHAR2, p_desc VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM SYSTEM_CONFIG WHERE CONFIG_KEY = p_key;
        IF v_exists = 0 THEN
            INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_BY, UPDATED_AT)
            VALUES (p_key, p_val, p_desc, 'V15_MIGRATION', SYSTIMESTAMP);
        END IF;
    END;
BEGIN
    add_cfg('cms.query.internal_note_edit_window_minutes', '5',
            'Minutes an author may edit their own internal note before it locks (UST860)');
    add_cfg('cms.query.max_extension_days', '30',
            'Maximum extension days an RBI approver may grant on an RE response deadline (UST853)');
    add_cfg('cms.query.max_meeting_slots', '5',
            'Maximum proposed meeting slots per meeting-request query (UST855)');
    add_cfg('cms.query.max_checklist_items', '20',
            'Maximum checklist items per document-request query (UST854)');
    COMMIT;
END;
/
