-- ═══════════════════════════════════════════════════════════════════════════
-- V16 (Oracle) — Security enforcement, PII masking, anomaly detection, retention
--                (B1, UST873, UST875, UST877, UST890)
--
-- Oracle counterpart of database/V17__security_enforcement_and_retention.sql.
-- The V-numbers are deliberately offset by one: the MySQL and Oracle sequences
-- are tracked separately (see oracle/V15 header).
--
-- Safe to re-run: every DDL is guarded on USER_TABLES / USER_TAB_COLUMNS /
-- USER_INDEXES, and every seed on a COUNT(*) check.
-- Type mapping vs MySQL: TIMESTAMP(6) for DATETIME(6), CLOB for TEXT,
-- NUMBER(1) for TINYINT(1).
-- ═══════════════════════════════════════════════════════════════════════════

-- ───────────────────────── UST875: PII reveal audit ─────────────────────────
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'PII_REVEAL_AUDIT';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE PII_REVEAL_AUDIT (
                ID                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                USER_ID           VARCHAR2(200)  NOT NULL,
                DISPLAY_NAME      VARCHAR2(200),
                ROLES             VARCHAR2(500),
                COMPLAINT_NUMBER  VARCHAR2(50),
                FIELDS_REVEALED   VARCHAR2(1000) NOT NULL,
                CONTEXT           VARCHAR2(100),
                JUSTIFICATION     VARCHAR2(1000),
                IP_ADDRESS        VARCHAR2(50),
                REVEALED_AT       TIMESTAMP(6)   NOT NULL,
                CONSTRAINT PK_PII_REVEAL_AUDIT PRIMARY KEY (ID)
            )';
    END IF;
END;
/

-- ──────────────────── UST873: security events and alerts ────────────────────
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'SECURITY_EVENT';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE SECURITY_EVENT (
                ID                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                EVENT_TYPE        VARCHAR2(60)  NOT NULL,
                SUBJECT           VARCHAR2(200) NOT NULL,
                USER_ID           VARCHAR2(200),
                COMPLAINT_NUMBER  VARCHAR2(50),
                ENTITY_CODE       VARCHAR2(50),
                REQUEST_PATH      VARCHAR2(500),
                IP_ADDRESS        VARCHAR2(50),
                DETAILS           CLOB,
                OCCURRED_AT       TIMESTAMP(6)  NOT NULL,
                CONSTRAINT PK_SECURITY_EVENT PRIMARY KEY (ID)
            )';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'SECURITY_ALERT';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE SECURITY_ALERT (
                ID                    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                ALERT_TYPE            VARCHAR2(60)  NOT NULL,
                SEVERITY              VARCHAR2(20)  NOT NULL,
                SUBJECT               VARCHAR2(200) NOT NULL,
                SUBJECT_TYPE          VARCHAR2(50),
                EVENT_COUNT           NUMBER(10)    NOT NULL,
                THRESHOLD             NUMBER(10)    NOT NULL,
                WINDOW_LABEL          VARCHAR2(60),
                DETAILS               CLOB,
                IP_ADDRESS            VARCHAR2(50),
                STATUS                VARCHAR2(20)  NOT NULL,
                ACKNOWLEDGED_BY       VARCHAR2(200),
                ACKNOWLEDGED_AT       TIMESTAMP(6),
                ACKNOWLEDGEMENT_NOTE  VARCHAR2(1000),
                RAISED_AT             TIMESTAMP(6)  NOT NULL,
                CONSTRAINT PK_SECURITY_ALERT PRIMARY KEY (ID)
            )';
    END IF;
END;
/

-- ─────────────────── UST877: credential revocation list ───────────────────
-- Doubles as the server-side revocation list: tokens are validated offline, so
-- without these rows a revoked user's existing token would work until expiry.
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'CREDENTIAL_REVOCATION';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE CREDENTIAL_REVOCATION (
                ID                          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                USERNAME                    VARCHAR2(200) NOT NULL,
                KEYCLOAK_USER_ID            VARCHAR2(100),
                REASON                      VARCHAR2(50)  NOT NULL,
                NOTES                       VARCHAR2(1000),
                INITIATED_BY                VARCHAR2(200) NOT NULL,
                REVOKED_AT                  TIMESTAMP(6)  NOT NULL,
                ACTIVE                      NUMBER(1)     DEFAULT 1 NOT NULL,
                RESTORED_AT                 TIMESTAMP(6),
                RESTORED_BY                 VARCHAR2(200),
                ACCOUNT_DISABLED            NUMBER(1)     DEFAULT 0 NOT NULL,
                SESSIONS_TERMINATED         NUMBER(1)     DEFAULT 0 NOT NULL,
                SESSIONS_TERMINATED_COUNT   NUMBER(10),
                FAILURE_DETAIL              VARCHAR2(1000),
                CONSTRAINT PK_CREDENTIAL_REVOCATION PRIMARY KEY (ID)
            )';
    END IF;
END;
/

-- ───────────────────── UST890: retention and deletion log ─────────────────────
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'RETENTION_POLICY';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE RETENTION_POLICY (
                ID                        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                CATEGORY                  VARCHAR2(60)  NOT NULL,
                TARGET_TABLE              VARCHAR2(100) NOT NULL,
                TIMESTAMP_COLUMN          VARCHAR2(60)  NOT NULL,
                RETENTION_DAYS            NUMBER(10)    NOT NULL,
                AUDIT_CATEGORY            NUMBER(1)     DEFAULT 0 NOT NULL,
                REDACT_INSTEAD_OF_DELETE  NUMBER(1)     DEFAULT 0 NOT NULL,
                REDACT_COLUMNS            VARCHAR2(1000),
                ENABLED                   NUMBER(1)     DEFAULT 1 NOT NULL,
                DESCRIPTION               VARCHAR2(500),
                UPDATED_BY                VARCHAR2(200),
                UPDATED_AT                TIMESTAMP(6),
                CONSTRAINT PK_RETENTION_POLICY PRIMARY KEY (ID),
                CONSTRAINT UK_RETENTION_CATEGORY UNIQUE (CATEGORY)
            )';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'DELETION_LOG';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE DELETION_LOG (
                ID              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                CATEGORY        VARCHAR2(60)  NOT NULL,
                TARGET_TABLE    VARCHAR2(100) NOT NULL,
                RETENTION_DAYS  NUMBER(10)    NOT NULL,
                CUTOFF_DATE     TIMESTAMP(6)  NOT NULL,
                ROWS_AFFECTED   NUMBER(10)    NOT NULL,
                ACTION          VARCHAR2(20)  NOT NULL,
                DRY_RUN         NUMBER(1)     DEFAULT 1 NOT NULL,
                EXECUTED_BY     VARCHAR2(200) NOT NULL,
                EXECUTED_AT     TIMESTAMP(6)  NOT NULL,
                DETAILS         VARCHAR2(2000),
                SUCCEEDED       NUMBER(1)     DEFAULT 1 NOT NULL,
                ERROR_DETAIL    VARCHAR2(2000),
                CONSTRAINT PK_DELETION_LOG PRIMARY KEY (ID)
            )';
    END IF;
END;
/

-- ───────────────────────────── Indexes ─────────────────────────────
DECLARE
    PROCEDURE add_idx(p_name VARCHAR2, p_ddl VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = p_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;
BEGIN
    add_idx('IDX_REVEAL_USER',      'CREATE INDEX IDX_REVEAL_USER ON PII_REVEAL_AUDIT(USER_ID)');
    add_idx('IDX_REVEAL_COMPLAINT', 'CREATE INDEX IDX_REVEAL_COMPLAINT ON PII_REVEAL_AUDIT(COMPLAINT_NUMBER)');
    add_idx('IDX_REVEAL_AT',        'CREATE INDEX IDX_REVEAL_AT ON PII_REVEAL_AUDIT(REVEALED_AT)');
    add_idx('IDX_SECEVENT_SUBJECT', 'CREATE INDEX IDX_SECEVENT_SUBJECT ON SECURITY_EVENT(SUBJECT)');
    add_idx('IDX_SECEVENT_TYPE',    'CREATE INDEX IDX_SECEVENT_TYPE ON SECURITY_EVENT(EVENT_TYPE)');
    -- Composite: the threshold query filters subject + type + time together.
    add_idx('IDX_SECEVENT_LOOKUP',  'CREATE INDEX IDX_SECEVENT_LOOKUP ON SECURITY_EVENT(SUBJECT, EVENT_TYPE, OCCURRED_AT)');
    add_idx('IDX_ALERT_STATUS',     'CREATE INDEX IDX_ALERT_STATUS ON SECURITY_ALERT(STATUS)');
    add_idx('IDX_ALERT_SUPPRESS',   'CREATE INDEX IDX_ALERT_SUPPRESS ON SECURITY_ALERT(SUBJECT, ALERT_TYPE, RAISED_AT)');
    add_idx('IDX_REVOKE_USER',      'CREATE INDEX IDX_REVOKE_USER ON CREDENTIAL_REVOCATION(USERNAME)');
    add_idx('IDX_REVOKE_ACTIVE',    'CREATE INDEX IDX_REVOKE_ACTIVE ON CREDENTIAL_REVOCATION(ACTIVE)');
    add_idx('IDX_DELETION_AT',      'CREATE INDEX IDX_DELETION_AT ON DELETION_LOG(EXECUTED_AT)');
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- Tunable thresholds — no hardcoded security values in code.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    PROCEDURE add_cfg(p_key VARCHAR2, p_val VARCHAR2, p_desc VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM SYSTEM_CONFIG WHERE CONFIG_KEY = p_key;
        IF v_exists = 0 THEN
            INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_BY, UPDATED_AT)
            VALUES (p_key, p_val, p_desc, 'V16_MIGRATION', SYSTIMESTAMP);
        END IF;
    END;
BEGIN
    add_cfg('cms.security.pii.masking_enabled', 'true',
            'Master switch for complainant PII masking on API responses (UST875)');
    add_cfg('cms.security.pii.masked_fields',
            'complainantName,complainantPhone,complainantEmail,complainantAddress,accountNumber',
            'Comma-separated complainant fields masked by default (UST875)');
    add_cfg('cms.security.pii.reveal_roles',
            'ADMIN,CEPC_DO,CEPC_OFFICER,CEPC_INCHARGE,CEPC_SUPERVISOR,CEPC_CLOSING_AUTHORITY,RBIO_OFFICER,RBIO_SUPERVISOR,RBIO_CONCILIATOR,RBIO_ADJUDICATOR',
            'Roles permitted to request an audited PII reveal; RE roles excluded by design (UST875)');
    add_cfg('cms.security.pii.require_justification', 'true',
            'Require a typed reason before revealing complainant PII (UST875)');
    add_cfg('cms.security.pii.min_justification_length', '10',
            'Minimum characters in a PII reveal justification (UST875)');

    add_cfg('cms.security.anomaly.enabled', 'true',
            'Master switch for suspicious-access detection (UST873)');
    add_cfg('cms.security.anomaly.window_minutes', '10',
            'Sliding window in minutes over which security events are counted (UST873)');
    add_cfg('cms.security.anomaly.denied_access_threshold', '10',
            'Denied-access events by one subject in the window before an alert is raised (UST873)');
    add_cfg('cms.security.anomaly.cross_entity_threshold', '3',
            'Cross-entity access attempts before an alert; lower because it implies probing (UST873)');
    add_cfg('cms.security.anomaly.pii_reveal_threshold', '25',
            'Authorised PII reveals by one user in the window before it looks like harvesting (UST873)');
    add_cfg('cms.security.anomaly.distinct_entity_threshold', '3',
            'Distinct entities touched in the window before enumeration is suspected (UST873)');
    add_cfg('cms.security.anomaly.alert_suppression_minutes', '60',
            'Minutes before the same subject/type raises another alert (UST873)');

    add_cfg('cms.security.retention.enabled', 'true',
            'Whether the nightly retention sweep evaluates policies (UST890)');
    -- Deliberately false: dry run until an operator turns destruction on.
    add_cfg('cms.security.retention.destructive_enabled', 'false',
            'When false the retention sweep is a dry run and deletes nothing (UST890)');
    add_cfg('cms.security.retention.batch_limit', '5000',
            'Maximum rows one retention run may affect per policy (UST890)');
    COMMIT;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- Retention policies. Audit categories get 7 years (2555 days) independently of
-- the operational data they describe.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    PROCEDURE add_policy(p_category VARCHAR2, p_table VARCHAR2, p_ts_col VARCHAR2,
                         p_days NUMBER, p_audit NUMBER, p_redact NUMBER,
                         p_redact_cols VARCHAR2, p_enabled NUMBER, p_desc VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM RETENTION_POLICY WHERE CATEGORY = p_category;
        IF v_exists = 0 THEN
            INSERT INTO RETENTION_POLICY (CATEGORY, TARGET_TABLE, TIMESTAMP_COLUMN, RETENTION_DAYS,
                                          AUDIT_CATEGORY, REDACT_INSTEAD_OF_DELETE, REDACT_COLUMNS,
                                          ENABLED, DESCRIPTION, UPDATED_BY, UPDATED_AT)
            VALUES (p_category, p_table, p_ts_col, p_days, p_audit, p_redact, p_redact_cols,
                    p_enabled, p_desc, 'V16_MIGRATION', SYSTIMESTAMP);
        END IF;
    END;
BEGIN
    add_policy('AUDIT_LOG', 'AUDIT_LOG', 'TIMESTAMP', 2555, 1, 0, NULL, 1,
               'Workflow audit trail — 7 year statutory retention, independent of complaint retention');
    add_policy('PII_REVEAL_AUDIT', 'PII_REVEAL_AUDIT', 'REVEALED_AT', 2555, 1, 0, NULL, 1,
               'PII reveal trail — 7 year retention');
    add_policy('CONFIG_AUDIT_LOG', 'CONFIG_AUDIT_LOG', 'CHANGED_AT', 2555, 1, 0, NULL, 1,
               'Configuration change trail — 7 year retention');
    add_policy('SECURITY_EVENT', 'SECURITY_EVENT', 'OCCURRED_AT', 730, 1, 0, NULL, 1,
               'Raw security events — 2 years; the derived alerts are kept longer');
    add_policy('SECURITY_ALERT', 'SECURITY_ALERT', 'RAISED_AT', 2555, 1, 0, NULL, 1,
               'Security alerts — 7 year retention');
    add_policy('IN_APP_NOTIFICATION', 'IN_APP_NOTIFICATIONS', 'CREATED_AT', 365, 0, 0, NULL, 1,
               'In-app notifications — 1 year, transient operational data');
    -- Redacts rather than deletes: deleting a closed complaint would orphan its
    -- history, attachments and query threads. Disabled pending sign-off.
    add_policy('COMPLAINT_PII', 'COMPLAINTS', 'CLOSED_AT', 2555, 0, 1,
               'COMPLAINANT_NAME,COMPLAINANT_EMAIL,COMPLAINANT_PHONE,COMPLAINANT_ADDRESS,ACCOUNT_NUMBER',
               0,
               'Redacts complainant PII on complaints closed over 7 years ago, preserving the record shell. Disabled pending sign-off.');
    COMMIT;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- Translation keys for the security console and reveal / deactivation UI.
-- Per-locale values are seeded by SecurityTranslationSeeder for all ten locales.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    PROCEDURE add_key(p_code VARCHAR2, p_module VARCHAR2, p_desc VARCHAR2, p_default VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM TRANSLATION_KEYS WHERE CODE = p_code;
        IF v_exists = 0 THEN
            INSERT INTO TRANSLATION_KEYS (CODE, MODULE, DESCRIPTION, DEFAULT_VALUE)
            VALUES (p_code, p_module, p_desc, p_default);
        END IF;
    END;
BEGIN
    add_key('security.reveal_button', 'security', 'Button revealing masked complainant details', 'Reveal details');
    add_key('security.reveal_reason_label', 'security', 'Label for the reveal justification field', 'Reason for viewing');
    add_key('security.reveal_logged_notice', 'security', 'Warning that reveals are recorded',
            'This action is recorded against your name.');
    add_key('security.masked_hint', 'security', 'Hint shown beside a masked value', 'Hidden to protect personal data');
    add_key('security.reveal_not_permitted', 'security', 'Error when the role may not reveal PII',
            'You are not permitted to reveal complainant details.');
    add_key('security.alerts_title', 'security', 'Security alerts console heading', 'Security alerts');
    add_key('security.alerts_empty', 'security', 'Empty state for the alerts list', 'No security alerts');
    add_key('security.acknowledge', 'security', 'Acknowledge an alert', 'Acknowledge');
    add_key('security.severity', 'security', 'Alert severity column', 'Severity');
    add_key('security.subject', 'security', 'Alert subject column', 'User or IP');
    add_key('team.deactivate_title', 'team', 'Safe deactivation dialog heading', 'Deactivate team member');
    add_key('team.deactivate_open_records', 'team', 'Warning that open records must move',
            'This officer still holds open complaints. Choose who they transfer to.');
    add_key('team.reassign_to_label', 'team', 'Successor picker label', 'Reassign open complaints to');
    add_key('team.revoke_access_label', 'team', 'Checkbox to also revoke credentials',
            'Also revoke sign-in access immediately');
    add_key('team.deactivate_confirm', 'team', 'Confirm safe deactivation', 'Deactivate');
    add_key('team.deactivate_cancel', 'team', 'Cancel deactivation', 'Cancel');
    COMMIT;
END;
/
