-- ═══════════════════════════════════════════════════════════════════════════
-- V28 (Oracle) — RE nodal officer reassignment
--                (UST838, UST839, UST840, UST841, UST842, UST843, UST844, UST845)
--
-- Oracle counterpart of database/V29__re_nodal_reassignment.sql. The V-numbers are
-- deliberately offset by one: the MySQL and Oracle sequences are tracked separately
-- (see oracle/V15 and oracle/V16 headers).
--
-- Context: this cluster was entirely unbuilt. The only "bulk reassign" in the codebase was
-- CrpcHeadController.bulkReassign, a stub that returned {"status":"reassigned"} and persisted
-- nothing, and it was officer-side rather than RE-side in any case.
--
-- Six things this migration establishes:
--
--   1. NODAL_OFFICER_RECORDS. Unlike the MySQL twin, on Oracle this table is NOT new — it is
--      already defined unguarded in oracle/V5__complete_ddl_dml.sql:906, which is where the
--      canonical column set lives. The CREATE below is therefore guarded on USER_TABLES and
--      reproduces V5 exactly, so it only fires on a schema built without V5 (and is a no-op on
--      every existing database). The MySQL side is the mirror case: there the table had no written
--      definition at all and was created implicitly by Hibernate ddl-auto, so dev and prod schemas
--      had no shared source of truth. Both files now say the same thing.
--
--   2. VERSION on NODAL_OFFICER_RECORDS — the optimistic lock for UST839, and the first @Version
--      column in cms-backend. NULL on existing rows is intentional: Hibernate treats a null version
--      as unversioned and seeds it on first write, so there is no backfill and legacy writers keep
--      working. A DEFAULT would not help, because the rows already exist.
--
--   3. ENTITY_CODE on NODAL_OFFICER_RECORDS. The table previously identified an entity only by the
--      free-text ENTITY_NAME, but RequestIdentity supplies an entity *code*, so server-side
--      authorisation was not possible: two similarly-named entities could not be told apart. Left
--      NULL for historical rows, and the service refuses a record whose code is null rather than
--      assuming it belongs to the caller.
--
--   4. ENTITY_USERS — the candidate directory (UST841). Sourced from the database rather than
--      Keycloak because the `cms` realm contains no RE_* users and no RE_* roles at all, so
--      enumerating the identity provider returns nothing. RE_ROLE is a column, not a hardcoded Java
--      list, because the NO-vs-Contact-Person distinction is master data. NOTE: seeding real RE users
--      into the realm remains a prerequisite for actual SSO; this table is the source of record for
--      who exists, not a substitute for authentication.
--
--   5. REASSIGNMENT_REQUESTS / _CLARIFICATIONS / REASSIGNMENT_HISTORY. The reason column is
--      immutable at the JPA layer (updatable = false) per UST840; clarifications are separate
--      append-only rows. History is a separate table from requests because a report must count
--      movements that actually happened, not intents — counting requests would include rejections.
--      History is deliberately NOT written to COMPLAINT_TIMELINE: an entity-internal staffing change
--      is not part of the complaint narrative shared beyond the entity.
--
--   6. NOTIFICATION_DELIVERY_LOG — one append-only row per delivery attempt (UST845). A separate
--      table rather than columns on IN_APP_NOTIFICATIONS, because delivery is one-to-many (multiple
--      attempts, multiple channels) and would not fit on the notification row without discarding
--      earlier attempts.
--
-- Re-running is safe: every CREATE TABLE is guarded on USER_TABLES, every ADD COLUMN on
-- USER_TAB_COLUMNS, every CREATE INDEX on USER_INDEXES, and every seed on a COUNT(*). Guards
-- tolerate a table an earlier baseline (V5) or Hibernate already created.
--
-- Type mapping vs MySQL (as documented in oracle/V16): DATETIME(6) -> TIMESTAMP(6), TEXT -> CLOB,
-- TINYINT(1) -> NUMBER(1), BIGINT -> NUMBER(19), INT -> NUMBER(10), VARCHAR(n) -> VARCHAR2(n).
-- AUTO_INCREMENT primary keys become GENERATED BY DEFAULT AS IDENTITY, which needs no sequence
-- and therefore no sequence guard.
-- ═══════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. NODAL_OFFICER_RECORDS — guarded, column-for-column identical to
--    oracle/V5__complete_ddl_dml.sql:906. Present here only so a schema bootstrapped from a
--    partial baseline still gets the table the reassignment code depends on; on any database
--    that ran V5 the guard skips it and the existing table is left exactly as it is.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'NODAL_OFFICER_RECORDS';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE NODAL_OFFICER_RECORDS (
                ID                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                COMPLAINT_NUMBER    VARCHAR2(50) NOT NULL,
                ENTITY_NAME         VARCHAR2(200),
                NODAL_OFFICER_NAME  VARCHAR2(200),
                PNO_NAME            VARCHAR2(200),
                DESIGNATION         VARCHAR2(100),
                EMAIL               VARCHAR2(200),
                PHONE               VARCHAR2(20),
                STATUS              VARCHAR2(30) DEFAULT ''INFORMATION_REQUIRED'' NOT NULL,
                ASSIGNED_TO         VARCHAR2(200),
                CREATED_AT          TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
                LAST_MODIFIED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP
            )';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 2 + 3. VERSION and ENTITY_CODE on NODAL_OFFICER_RECORDS
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_count NUMBER;

    PROCEDURE add_col(p_table VARCHAR2, p_name VARCHAR2, p_type VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD ' || p_name || ' ' || p_type;
        END IF;
    END;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'NODAL_OFFICER_RECORDS';
    IF v_count > 0 THEN
        -- Nullable with no DEFAULT, not 0: Hibernate seeds a null version on first write, so
        -- existing rows need no backfill and writers that predate optimistic locking are
        -- unaffected. A DEFAULT would not help either way, because the rows already exist.
        add_col('NODAL_OFFICER_RECORDS', 'VERSION',     'NUMBER(19)');
        -- Nullable for the same reason, but with a different consequence: a record whose code is
        -- unknown is refused by the service rather than assumed to belong to the caller.
        add_col('NODAL_OFFICER_RECORDS', 'ENTITY_CODE', 'VARCHAR2(50)');
    END IF;
END;
/

-- The workload query filters (ENTITY_CODE, ASSIGNED_TO) and excludes statuses; the last two
-- indexes cover both it and the entity-scoped record list. The first four repeat V5's indexes so
-- that a schema which skipped V5 is not left without them; on a V5 database they are all no-ops.
DECLARE
    PROCEDURE add_idx(p_name VARCHAR2, p_ddl VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = p_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;
BEGIN
    add_idx('IDX_NO_COMPLAINT',
            'CREATE INDEX IDX_NO_COMPLAINT ON NODAL_OFFICER_RECORDS(COMPLAINT_NUMBER)');
    add_idx('IDX_NO_ENTITY',
            'CREATE INDEX IDX_NO_ENTITY ON NODAL_OFFICER_RECORDS(ENTITY_NAME)');
    add_idx('IDX_NO_STATUS',
            'CREATE INDEX IDX_NO_STATUS ON NODAL_OFFICER_RECORDS(STATUS)');
    add_idx('IDX_NO_LAST_MODIFIED',
            'CREATE INDEX IDX_NO_LAST_MODIFIED ON NODAL_OFFICER_RECORDS(LAST_MODIFIED_AT)');
    add_idx('IDX_NO_ENTITY_CODE_ASSIGNED',
            'CREATE INDEX IDX_NO_ENTITY_CODE_ASSIGNED ON NODAL_OFFICER_RECORDS(ENTITY_CODE, ASSIGNED_TO)');
    add_idx('IDX_NO_ENTITY_CODE_STATUS',
            'CREATE INDEX IDX_NO_ENTITY_CODE_STATUS ON NODAL_OFFICER_RECORDS(ENTITY_CODE, STATUS)');
END;
/

-- Backfill ENTITY_CODE from REGULATED_ENTITIES where the free-text name matches exactly.
-- Deliberately exact (after trimming and lowercasing), not fuzzy: a near-match that guessed wrong
-- would attach a record to the wrong bank and make it visible to an entity that should never see
-- it. Rows that do not match are left NULL and stay invisible to entity-scoped callers, which is
-- the safe direction.
--
-- Two Oracle-specific points:
--   * MySQL's `UPDATE t JOIN u ... SET` has no Oracle equivalent, so this is written as a
--     correlated scalar subquery with a matching EXISTS. The EXISTS is not redundant: without it,
--     a non-matching row would be set to NULL by the subquery returning no row, and although that
--     is the value it already holds, the statement would needlessly rewrite every unmatched row.
--     ROWNUM = 1 is deliberately NOT added to the subquery: if two REGULATED_ENTITIES rows share a
--     name, this raises ORA-01427 and the migration stops, rather than silently picking one of them
--     and attaching the record to a bank nobody chose. That is the same refusal-to-guess the exact
--     match above exists for. MySQL's JOIN form would have picked one arbitrarily, so on Oracle
--     this case is caught rather than absorbed.
--   * REGULATED_ENTITIES on the Oracle baseline (oracle/V1:65, V5:99) has NAME and no ENTITY_CODE
--     column at all, whereas the MySQL schema this backfill was written against has ENTITY_NAME
--     and ENTITY_CODE. The whole block is therefore guarded on those two columns existing, not
--     merely on the table existing, so on a stock Oracle schema this is a clean no-op instead of
--     an ORA-00904. Once REGULATED_ENTITIES gains ENTITY_CODE / ENTITY_NAME the backfill starts
--     working with no change here.
DECLARE
    v_table NUMBER;
    v_code  NUMBER;
    v_name  NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_table FROM USER_TABLES WHERE TABLE_NAME = 'REGULATED_ENTITIES';

    SELECT COUNT(*) INTO v_code FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'REGULATED_ENTITIES' AND COLUMN_NAME = 'ENTITY_CODE';

    SELECT COUNT(*) INTO v_name FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'REGULATED_ENTITIES' AND COLUMN_NAME = 'ENTITY_NAME';

    IF v_table > 0 AND v_code > 0 AND v_name > 0 THEN
        EXECUTE IMMEDIATE '
            UPDATE NODAL_OFFICER_RECORDS n
               SET n.ENTITY_CODE = (SELECT re.ENTITY_CODE
                                      FROM REGULATED_ENTITIES re
                                     WHERE TRIM(LOWER(re.ENTITY_NAME)) = TRIM(LOWER(n.ENTITY_NAME)))
             WHERE n.ENTITY_CODE IS NULL
               AND n.ENTITY_NAME IS NOT NULL
               AND EXISTS (SELECT 1
                             FROM REGULATED_ENTITIES re
                            WHERE TRIM(LOWER(re.ENTITY_NAME)) = TRIM(LOWER(n.ENTITY_NAME)))';
        COMMIT;
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. ENTITY_USERS — candidate directory (UST841)
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'ENTITY_USERS';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE ENTITY_USERS (
                ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,

                -- The login id this person authenticates as, matched against
                -- RequestIdentity.getUserId().
                USER_ID          VARCHAR2(200) NOT NULL,
                ENTITY_CODE      VARCHAR2(50)  NOT NULL,
                DISPLAY_NAME     VARCHAR2(200),
                EMAIL            VARCHAR2(200),
                DESIGNATION      VARCHAR2(100),

                -- NODAL_OFFICER | CONTACT_PERSON | PNO. A column rather than a Java enum: the
                -- realm has no Contact Person role to mirror and operations must be able to
                -- correct this without a redeploy.
                RE_ROLE          VARCHAR2(30)  NOT NULL,

                -- Inactive users are retained so historical reassignments still resolve to a name,
                -- but are never offered as a target. Deleting the row would leave the UST844
                -- report showing a bare user id.
                ACTIVE           NUMBER(1)     DEFAULT 1 NOT NULL,

                -- Flat, nullable label. There is no region hierarchy anywhere in the entity model,
                -- so candidate authorisation is by ENTITY_CODE alone; this is display /
                -- optional-narrowing only. Inventing a hierarchy would imply a scoping rule the
                -- server does not enforce.
                TERRITORY        VARCHAR2(100),

                CREATED_AT       TIMESTAMP(6),
                LAST_MODIFIED_AT TIMESTAMP(6),

                CONSTRAINT PK_ENTITY_USERS PRIMARY KEY (ID),
                CONSTRAINT UK_ENTITY_USER UNIQUE (USER_ID, ENTITY_CODE)
            )';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 5a. REASSIGNMENT_REQUESTS (UST839, UST840, UST842, UST843)
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'REASSIGNMENT_REQUESTS';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE REASSIGNMENT_REQUESTS (
                ID                          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                NODAL_OFFICER_RECORD_ID     NUMBER(19)    NOT NULL,

                -- Denormalised so the row survives the record being reassigned again.
                COMPLAINT_NUMBER            VARCHAR2(50)  NOT NULL,
                ENTITY_CODE                 VARCHAR2(50)  NOT NULL,

                FROM_USER_ID                VARCHAR2(200),
                TO_USER_ID                  VARCHAR2(200) NOT NULL,

                -- Names captured at request time, not resolved on read: an officer who later
                -- leaves must still appear by name in the audit trail.
                FROM_USER_NAME              VARCHAR2(200),
                TO_USER_NAME                VARCHAR2(200),

                -- IMMUTABLE (UST840). Mapped updatable = false in JPA, so no service, admin
                -- endpoint or bulk correction can rewrite it. A reassignment reason is what the
                -- PNO relied on when approving; if it could be edited afterwards the approval
                -- would attest to a rationale never actually reviewed. Corrections are appended to
                -- REASSIGNMENT_CLARIFICATIONS.
                REASON                      CLOB,

                -- PENDING | APPROVED | REJECTED | WITHDRAWN
                -- WITHDRAWN is distinct from REJECTED: withdrawing your own request is legitimate
                -- but is not an independent refusal, and conflating them would overstate the
                -- review that took place.
                STATUS                      VARCHAR2(20)  NOT NULL,

                REQUESTED_BY                VARCHAR2(200) NOT NULL,
                REQUESTED_BY_NAME           VARCHAR2(200),
                REQUESTED_AT                TIMESTAMP(6),

                DECIDED_BY                  VARCHAR2(200),
                DECIDED_AT                  TIMESTAMP(6),
                DECISION_COMMENT            CLOB,

                -- Destination officer''s workload snapshotted at request time. Recomputing at
                -- approval time would show the PNO a different number from the one the requester
                -- acted on.
                TO_USER_WORKLOAD_AT_REQUEST NUMBER(10),

                CONSTRAINT PK_REASSIGNMENT_REQUESTS PRIMARY KEY (ID)
            )';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 5b. REASSIGNMENT_CLARIFICATIONS — append-only (UST840)
--     This table is the reason the REASON column above can be immutable.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'REASSIGNMENT_CLARIFICATIONS';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE REASSIGNMENT_CLARIFICATIONS (
                ID                      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                REASSIGNMENT_REQUEST_ID NUMBER(19)    NOT NULL,
                NOTE                    CLOB,

                -- Attribution resolved server-side from RequestIdentity, never taken from the
                -- request body.
                ADDED_BY                VARCHAR2(200) NOT NULL,
                ADDED_BY_NAME           VARCHAR2(200),
                ADDED_BY_SIDE           VARCHAR2(10),
                ADDED_AT                TIMESTAMP(6),

                CONSTRAINT PK_REASSIGNMENT_CLARIF PRIMARY KEY (ID)
            )';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 5c. REASSIGNMENT_HISTORY — append-only record of movements that took effect (UST844)
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'REASSIGNMENT_HISTORY';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE REASSIGNMENT_HISTORY (
                ID                      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                NODAL_OFFICER_RECORD_ID NUMBER(19)    NOT NULL,
                COMPLAINT_NUMBER        VARCHAR2(50)  NOT NULL,
                ENTITY_CODE             VARCHAR2(50)  NOT NULL,

                FROM_USER_ID            VARCHAR2(200),
                FROM_USER_NAME          VARCHAR2(200),
                TO_USER_ID              VARCHAR2(200) NOT NULL,
                TO_USER_NAME            VARCHAR2(200),

                -- APPROVED_REQUEST | DIRECT
                TRIGGER_TYPE            VARCHAR2(30)  NOT NULL,

                -- NULL for a direct move, which has no request behind it.
                REASSIGNMENT_REQUEST_ID NUMBER(19),

                -- Copied from the request rather than joined, so the report reads without a join
                -- and stays correct if the request is later superseded.
                REASON                  CLOB,

                PERFORMED_BY            VARCHAR2(200) NOT NULL,
                PERFORMED_BY_NAME       VARCHAR2(200),
                REASSIGNED_AT           TIMESTAMP(6),

                CONSTRAINT PK_REASSIGNMENT_HISTORY PRIMARY KEY (ID)
            )';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. NOTIFICATION_DELIVERY_LOG — one append-only row per delivery attempt (UST845)
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'NOTIFICATION_DELIVERY_LOG';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE NOTIFICATION_DELIVERY_LOG (
                ID                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,

                -- Nullable by design: a failure that happened before the notification could be
                -- persisted still has to be recorded, and that is precisely the case worth
                -- logging.
                NOTIFICATION_ID          NUMBER(19),

                RECIPIENT_USER_ID        VARCHAR2(200) NOT NULL,

                -- Translation key of the notification, so the log is readable without re-deriving
                -- the text.
                NOTIFICATION_TYPE        VARCHAR2(200),

                -- IN_APP for now. A column rather than an assumption, so adding email needs no
                -- schema change.
                CHANNEL                  VARCHAR2(20)  NOT NULL,

                -- SENT | FAILED
                STATUS                   VARCHAR2(20)  NOT NULL,

                -- Truncated at the service boundary; a stack trace does not belong in an audit row.
                ERROR_MESSAGE            VARCHAR2(1000),
                RELATED_COMPLAINT_NUMBER VARCHAR2(50),
                ATTEMPTED_AT             TIMESTAMP(6),

                CONSTRAINT PK_NOTIF_DELIVERY_LOG PRIMARY KEY (ID)
            )';
    END IF;
END;
/

-- ───────────────────── Indexes for sections 4, 5 and 6 ─────────────────────
-- Oracle has no INDEX clause inside CREATE TABLE, so the MySQL inline indexes become separate
-- guarded CREATE INDEX statements. Names are the MySQL names uppercased.
DECLARE
    PROCEDURE add_idx(p_name VARCHAR2, p_ddl VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = p_name;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;
BEGIN
    -- ENTITY_USERS. UK_ENTITY_USER is backed by a unique index on (USER_ID, ENTITY_CODE), which
    -- already covers USER_ID as its leading column, so IDX_EU_USER_ID is largely redundant on
    -- Oracle. It is created anyway to keep the index set identical to the MySQL twin — dropping it
    -- here would make the two schemas diverge for a marginal saving.
    add_idx('IDX_EU_ENTITY_CODE',
            'CREATE INDEX IDX_EU_ENTITY_CODE ON ENTITY_USERS(ENTITY_CODE)');
    add_idx('IDX_EU_USER_ID',
            'CREATE INDEX IDX_EU_USER_ID ON ENTITY_USERS(USER_ID)');
    add_idx('IDX_EU_ENTITY_ACTIVE',
            'CREATE INDEX IDX_EU_ENTITY_ACTIVE ON ENTITY_USERS(ENTITY_CODE, ACTIVE)');
    add_idx('IDX_EU_ROLE',
            'CREATE INDEX IDX_EU_ROLE ON ENTITY_USERS(RE_ROLE)');

    -- REASSIGNMENT_REQUESTS
    add_idx('IDX_RR_STATUS',
            'CREATE INDEX IDX_RR_STATUS ON REASSIGNMENT_REQUESTS(STATUS)');
    add_idx('IDX_RR_ENTITY_STATUS',
            'CREATE INDEX IDX_RR_ENTITY_STATUS ON REASSIGNMENT_REQUESTS(ENTITY_CODE, STATUS)');
    add_idx('IDX_RR_REQUESTED_BY',
            'CREATE INDEX IDX_RR_REQUESTED_BY ON REASSIGNMENT_REQUESTS(REQUESTED_BY)');
    add_idx('IDX_RR_RECORD',
            'CREATE INDEX IDX_RR_RECORD ON REASSIGNMENT_REQUESTS(NODAL_OFFICER_RECORD_ID)');
    add_idx('IDX_RR_REQUESTED_AT',
            'CREATE INDEX IDX_RR_REQUESTED_AT ON REASSIGNMENT_REQUESTS(REQUESTED_AT)');

    -- REASSIGNMENT_CLARIFICATIONS
    add_idx('IDX_RC_REQUEST',
            'CREATE INDEX IDX_RC_REQUEST ON REASSIGNMENT_CLARIFICATIONS(REASSIGNMENT_REQUEST_ID)');
    add_idx('IDX_RC_ADDED_AT',
            'CREATE INDEX IDX_RC_ADDED_AT ON REASSIGNMENT_CLARIFICATIONS(ADDED_AT)');

    -- REASSIGNMENT_HISTORY. IDX_RH_ENTITY_AT serves the UST844 report, which is always
    -- entity-scoped and date-ranged; the single-column IDX_RH_ENTITY_CODE stays for the
    -- unbounded count.
    add_idx('IDX_RH_ENTITY_CODE',
            'CREATE INDEX IDX_RH_ENTITY_CODE ON REASSIGNMENT_HISTORY(ENTITY_CODE)');
    add_idx('IDX_RH_COMPLAINT',
            'CREATE INDEX IDX_RH_COMPLAINT ON REASSIGNMENT_HISTORY(COMPLAINT_NUMBER)');
    add_idx('IDX_RH_FROM_USER',
            'CREATE INDEX IDX_RH_FROM_USER ON REASSIGNMENT_HISTORY(FROM_USER_ID)');
    add_idx('IDX_RH_TO_USER',
            'CREATE INDEX IDX_RH_TO_USER ON REASSIGNMENT_HISTORY(TO_USER_ID)');
    add_idx('IDX_RH_REASSIGNED_AT',
            'CREATE INDEX IDX_RH_REASSIGNED_AT ON REASSIGNMENT_HISTORY(REASSIGNED_AT)');
    add_idx('IDX_RH_ENTITY_AT',
            'CREATE INDEX IDX_RH_ENTITY_AT ON REASSIGNMENT_HISTORY(ENTITY_CODE, REASSIGNED_AT)');

    -- NOTIFICATION_DELIVERY_LOG
    add_idx('IDX_NDL_NOTIFICATION',
            'CREATE INDEX IDX_NDL_NOTIFICATION ON NOTIFICATION_DELIVERY_LOG(NOTIFICATION_ID)');
    add_idx('IDX_NDL_RECIPIENT',
            'CREATE INDEX IDX_NDL_RECIPIENT ON NOTIFICATION_DELIVERY_LOG(RECIPIENT_USER_ID)');
    add_idx('IDX_NDL_STATUS',
            'CREATE INDEX IDX_NDL_STATUS ON NOTIFICATION_DELIVERY_LOG(STATUS)');
    add_idx('IDX_NDL_ATTEMPTED_AT',
            'CREATE INDEX IDX_NDL_ATTEMPTED_AT ON NOTIFICATION_DELIVERY_LOG(ATTEMPTED_AT)');
    add_idx('IDX_NDL_TYPE',
            'CREATE INDEX IDX_NDL_TYPE ON NOTIFICATION_DELIVERY_LOG(NOTIFICATION_TYPE)');
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. Configurable thresholds. No hardcoded values in code — all read via SystemConfigService.
--    Prefixed cms.reassign.* so they cannot collide with another session's keys.
--
--    The excluded-status list for the UST838 workload count lives in SYSTEM_CONFIG rather than
--    Java because this codebase already contains FOUR disagreeing hardcoded CLOSED_STATUSES lists
--    (WorkflowController:57, NotificationScheduledTasks:29, AppealWorkflowService:36,
--    AppealController:28); a fifth would guarantee the workload figure drifts from what the rest
--    of the system considers closed, with no way to correct it without a redeploy.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    PROCEDURE add_cfg(p_key VARCHAR2, p_val VARCHAR2, p_desc VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM SYSTEM_CONFIG WHERE CONFIG_KEY = p_key;
        IF v_exists = 0 THEN
            INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_BY, UPDATED_AT)
            VALUES (p_key, p_val, p_desc, 'V28_MIGRATION', SYSTIMESTAMP);
        END IF;
    END;
BEGIN
    add_cfg('cms.reassign.workload.excluded_statuses',
            'DRAFT,CLOSED,RESOLVED,REJECTED,WITHDRAWN,ADJUDICATED,CONCILIATED,ORDER_PASSED,NON_MAINTAINABLE',
            'Record statuses excluded from the RE nodal officer workload count — drafts and closed work (UST838)');
    add_cfg('cms.reassign.bulk.max_records', '50',
            'Maximum records permitted in one bulk reassignment or bulk approval action (UST839, UST843)');
    add_cfg('cms.reassign.page_size.default', '20',
            'Default page size for reassignment request lists (UST842, UST843)');
    add_cfg('cms.reassign.page_size.max', '100',
            'Upper bound on a client-requested page size, so a caller cannot request an unbounded page');
    add_cfg('cms.reassign.reason.min_length', '10',
            'Minimum characters in a reassignment reason. The reason is immutable once submitted (UST840), so it must be substantive at entry.');
    -- When true (the default), even a PNO's own reassignment is queued as a request rather than
    -- applied immediately. Defaulting to true is the conservative choice: it keeps a two-step
    -- record for every movement until an operator deliberately relaxes it.
    add_cfg('cms.reassign.require_pno_approval', 'true',
            'Whether a PNO-initiated reassignment still requires an explicit approval step (UST843)');
    COMMIT;
END;
/
