-- V29: AA foundation — Closure Clause Master, Appeal schema expansion, REOPENED support
-- Oracle version — twin of MySQL V31. Oracle numbering runs behind MySQL by convention; the two
-- directories are not in step and each takes its own next free number.
--
-- Context: the Appellate Authority module could not implement its own user stories.
--
--   1. CLOSURE_CLAUSE_MASTER is new. The closure-clause vocabulary was a hardcoded List<Map> inside
--      WorkflowController.getClosureClauses, so a Scheme amendment required a code release — and the
--      appeal path never read it anyway. Classification (APPEAL vs REPRESENTATION) was taken from a
--      request parameter defaulting to 'APPEAL', which meant the browser decided a citizen's
--      statutory recourse.
--
--      Appealability is PARTY-DEPENDENT, hence two flag columns rather than one. Per the RBI ruling:
--      a complainant may appeal a closure under 15(1)(a) or 15(1)(b); a regulated entity may appeal
--      only under 15(1)(b). Everything else is a representation. This SUPERSEDES the old hardcoded
--      list, which also marked 16(2)(c)-(f) 'appellable' — a flag no code ever read.
--
--      Only RBIOS_2021 is seeded. RBIOS 2026 clause numbers are deliberately NOT invented: they are
--      pending RBI confirmation, and a guessed clause number in a citizen-facing closure letter is a
--      legal defect. The table is scheme-versioned and date-bounded so 2026 arrives as data, and a
--      complaint is always judged under the Scheme in force when it was created.
--
--   2. APPEALS gains the Register-milestone intake fields, provenance (CREATED_BY, ROUTED_BY,
--      PUT_UP_TO) and entity linkage. Without CREATED_BY the 'Created By Me' view is impossible;
--      without ROUTED_BY_USER_ID every 'send back to the ORIGINAL officer' story is unimplementable,
--      because send-back currently round-robins to a random holder of the role.
--
--   3. APPEAL_TIMELINE gains FIELD_NAME/OLD_VALUE/NEW_VALUE so a classification override records what
--      actually changed. The timeline could only say 'status went X to Y'.
--
--   4. APPEAL_ATTACHMENTS is new. Appeal documents were written as COMPLAINT_ATTACHMENTS rows with
--      the appeal number in the complaint-number column.
--
--   5. COMPLAINTS.REOPENED_AT plus an index on WORKFLOW_STAGE. 'Closed or reopened' could not be
--      expressed as a status filter: reopen is recorded only as WORKFLOW_STAGE='REOPENED'.
--
-- Re-running is safe: every DDL is guarded on USER_TABLES / USER_TAB_COLUMNS / USER_INDEXES and
-- every seed on a COUNT(*).

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. CLOSURE_CLAUSE_MASTER
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'CLOSURE_CLAUSE_MASTER';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE CLOSURE_CLAUSE_MASTER (
                ID                        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                SCHEME_VERSION            VARCHAR2(20)  NOT NULL,
                CLAUSE_CODE               VARCHAR2(40)  NOT NULL,
                LABEL                     VARCHAR2(300) NOT NULL,
                LABEL_KEY                 VARCHAR2(160),
                CATEGORY                  VARCHAR2(40)  NOT NULL,
                APPEALABLE_BY_COMPLAINANT NUMBER(1)     DEFAULT 0 NOT NULL,
                APPEALABLE_BY_ENTITY      NUMBER(1)     DEFAULT 0 NOT NULL,
                RESTRICTED_TO_ROLES       VARCHAR2(300),
                EFFECTIVE_FROM            DATE,
                EFFECTIVE_TO              DATE,
                ACTIVE                    NUMBER(1)     DEFAULT 1 NOT NULL,
                CREATED_AT                TIMESTAMP(6),
                UPDATED_AT                TIMESTAMP(6),
                CONSTRAINT PK_CLOSURE_CLAUSE_MASTER PRIMARY KEY (ID),
                -- One row per clause per scheme version: a duplicate would make a legal
                -- determination ambiguous, which must be impossible rather than merely unlikely.
                CONSTRAINT UK_CCM_SCHEME_CLAUSE UNIQUE (SCHEME_VERSION, CLAUSE_CODE)
            )';
    END IF;
END;
/

DECLARE
    PROCEDURE add_index(p_index VARCHAR2, p_table VARCHAR2, p_cols VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE 'CREATE INDEX ' || p_index || ' ON ' || p_table || ' (' || p_cols || ')';
        END IF;
    END;
BEGIN
    add_index('IDX_CCM_SCHEME', 'CLOSURE_CLAUSE_MASTER', 'SCHEME_VERSION');
    add_index('IDX_CCM_ACTIVE', 'CLOSURE_CLAUSE_MASTER', 'ACTIVE');
END;
/

-- RBIOS 2021 clauses. Seeded here as well as in ClosureClauseMasterSeeder so a database restored
-- without an application boot still classifies correctly.
DECLARE
    TYPE t_clause IS RECORD (
        code       VARCHAR2(40),
        label      VARCHAR2(300),
        label_key  VARCHAR2(160),
        category   VARCHAR2(40),
        by_compl   NUMBER,
        by_entity  NUMBER,
        roles      VARCHAR2(300)
    );
    TYPE t_clauses IS TABLE OF t_clause;
    v_rows   t_clauses;
    v_exists NUMBER;
    v_scheme CONSTANT VARCHAR2(20) := 'RBIOS_2021';
    v_omb    CONSTANT VARCHAR2(300) := 'OMBUDSMAN,RBIO_ADMIN,ADMIN';
BEGIN
    v_rows := t_clauses(
        t_clause('15(1)(a)', 'Award - full relief granted',                         'clause.15_1_a', 'AWARD',            1, 0, v_omb),
        t_clause('15(1)(b)', 'Award - partial relief with compensation',            'clause.15_1_b', 'AWARD',            1, 1, v_omb),
        t_clause('16(1)',    'Resolved to the satisfaction of the complainant',     'clause.16_1',   'RESOLUTION',       0, 0, NULL),
        t_clause('16(2)(a)', 'Not maintainable - time barred',                      'clause.16_2_a', 'NON_MAINTAINABLE', 0, 0, NULL),
        t_clause('16(2)(b)', 'Not maintainable - frivolous or vexatious',           'clause.16_2_b', 'NON_MAINTAINABLE', 0, 0, NULL),
        t_clause('16(2)(c)', 'Not maintainable - sub-judice',                       'clause.16_2_c', 'NON_MAINTAINABLE', 0, 0, v_omb),
        t_clause('16(2)(d)', 'Not maintainable - outside jurisdiction',             'clause.16_2_d', 'NON_MAINTAINABLE', 0, 0, v_omb),
        t_clause('16(2)(e)', 'Not maintainable - already settled by RBI',           'clause.16_2_e', 'NON_MAINTAINABLE', 0, 0, v_omb),
        t_clause('16(2)(f)', 'Not maintainable - covered by another dispute mechanism', 'clause.16_2_f', 'NON_MAINTAINABLE', 0, 0, v_omb),
        t_clause('16(2)(g)', 'Not maintainable - anonymous complaint',              'clause.16_2_g', 'NON_MAINTAINABLE', 0, 0, NULL),
        t_clause('16(2)(h)', 'Not maintainable - insufficient information',         'clause.16_2_h', 'NON_MAINTAINABLE', 0, 0, NULL),
        t_clause('16(3)',    'Closed - complainant not responding',                 'clause.16_3',   'CLOSURE',          0, 0, NULL),
        t_clause('16(4)',    'Closed - matter settled between the parties',         'clause.16_4',   'CLOSURE',          0, 0, NULL)
    );

    FOR i IN 1 .. v_rows.COUNT LOOP
        SELECT COUNT(*) INTO v_exists FROM CLOSURE_CLAUSE_MASTER
         WHERE SCHEME_VERSION = v_scheme AND CLAUSE_CODE = v_rows(i).code;
        IF v_exists = 0 THEN
            INSERT INTO CLOSURE_CLAUSE_MASTER
                (SCHEME_VERSION, CLAUSE_CODE, LABEL, LABEL_KEY, CATEGORY,
                 APPEALABLE_BY_COMPLAINANT, APPEALABLE_BY_ENTITY, RESTRICTED_TO_ROLES,
                 ACTIVE, CREATED_AT, UPDATED_AT)
            VALUES (v_scheme, v_rows(i).code, v_rows(i).label, v_rows(i).label_key, v_rows(i).category,
                    v_rows(i).by_compl, v_rows(i).by_entity, v_rows(i).roles,
                    1, SYSTIMESTAMP, SYSTIMESTAMP);
        END IF;
    END LOOP;
    COMMIT;
END;
/

-- Corrective UPDATEs, scoped BY CLAUSE CODE. The seeder is insert-if-absent, so a database seeded
-- before the party-dependent ruling would still carry a single-flag interpretation.
UPDATE CLOSURE_CLAUSE_MASTER
   SET APPEALABLE_BY_COMPLAINANT = 1, APPEALABLE_BY_ENTITY = 0, UPDATED_AT = SYSTIMESTAMP
 WHERE SCHEME_VERSION = 'RBIOS_2021' AND CLAUSE_CODE = '15(1)(a)'
   AND (APPEALABLE_BY_COMPLAINANT <> 1 OR APPEALABLE_BY_ENTITY <> 0);

UPDATE CLOSURE_CLAUSE_MASTER
   SET APPEALABLE_BY_COMPLAINANT = 1, APPEALABLE_BY_ENTITY = 1, UPDATED_AT = SYSTIMESTAMP
 WHERE SCHEME_VERSION = 'RBIOS_2021' AND CLAUSE_CODE = '15(1)(b)'
   AND (APPEALABLE_BY_COMPLAINANT <> 1 OR APPEALABLE_BY_ENTITY <> 1);

UPDATE CLOSURE_CLAUSE_MASTER
   SET APPEALABLE_BY_COMPLAINANT = 0, APPEALABLE_BY_ENTITY = 0, UPDATED_AT = SYSTIMESTAMP
 WHERE SCHEME_VERSION = 'RBIOS_2021'
   AND CLAUSE_CODE NOT IN ('15(1)(a)', '15(1)(b)')
   AND (APPEALABLE_BY_COMPLAINANT <> 0 OR APPEALABLE_BY_ENTITY <> 0);
COMMIT;

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. APPEALS / 3. APPEAL_TIMELINE / 5. COMPLAINTS — guarded column adds
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    PROCEDURE add_col(p_table VARCHAR2, p_name VARCHAR2, p_type VARCHAR2) IS
        v_tab NUMBER;
        v_col NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_tab FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_tab = 0 THEN
            RETURN;
        END IF;
        SELECT COUNT(*) INTO v_col FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_name;
        IF v_col = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD ' || p_name || ' ' || p_type;
        END IF;
    END;
BEGIN
    -- Classification override audit
    add_col('APPEALS', 'CLASSIFICATION_OVERRIDDEN',      'NUMBER(1) DEFAULT 0');
    add_col('APPEALS', 'CLASSIFICATION_OVERRIDE_REASON', 'VARCHAR2(1000)');
    add_col('APPEALS', 'CLASSIFICATION_OVERRIDDEN_BY',   'VARCHAR2(200)');
    add_col('APPEALS', 'CLASSIFICATION_OVERRIDDEN_AT',   'TIMESTAMP(6)');

    add_col('APPEALS', 'CLOSURE_CLAUSE',                 'VARCHAR2(40)');

    -- Provenance. NULL on historical rows: they genuinely have no recorded creator, and inventing
    -- one would be worse than an honest blank in the 'Created By Me' view.
    add_col('APPEALS', 'CREATED_BY',                     'VARCHAR2(200)');
    add_col('APPEALS', 'CREATED_BY_ROLE',                'VARCHAR2(50)');
    add_col('APPEALS', 'ROUTED_BY_USER_ID',              'VARCHAR2(200)');
    add_col('APPEALS', 'ROUTED_BY_ROLE',                 'VARCHAR2(50)');
    add_col('APPEALS', 'PUT_UP_TO_USER_ID',              'VARCHAR2(200)');

    -- Entity linkage
    add_col('APPEALS', 'ENTITY_CODE',                    'VARCHAR2(100)');
    add_col('APPEALS', 'RESOLVED_PNO_USER_ID',           'VARCHAR2(200)');

    -- Register-milestone intake
    add_col('APPEALS', 'APPEAL_FILED_BY',                'VARCHAR2(30)');
    add_col('APPEALS', 'SOURCE_OF_APPEAL',               'VARCHAR2(60)');
    add_col('APPEALS', 'MODE_OF_RECEIPT',                'VARCHAR2(30)');
    add_col('APPEALS', 'APPELLANT_ADDRESS1',             'VARCHAR2(300)');
    add_col('APPEALS', 'APPELLANT_ADDRESS2',             'VARCHAR2(300)');
    add_col('APPEALS', 'APPELLANT_CITY',                 'VARCHAR2(100)');
    add_col('APPEALS', 'APPELLANT_DISTRICT',             'VARCHAR2(100)');
    add_col('APPEALS', 'APPELLANT_STATE',                'VARCHAR2(100)');
    add_col('APPEALS', 'APPELLANT_COUNTRY',              'VARCHAR2(100)');
    add_col('APPEALS', 'APPELLANT_PINCODE',              'VARCHAR2(10)');
    add_col('APPEALS', 'CATEGORY_ID',                    'NUMBER(19)');
    add_col('APPEALS', 'ENTITY_NAME',                    'VARCHAR2(300)');
    add_col('APPEALS', 'ENTITY_REGION',                  'VARCHAR2(100)');
    add_col('APPEALS', 'ENTITY_CATEGORY',                'VARCHAR2(100)');
    add_col('APPEALS', 'ENTITY_BRANCH',                  'VARCHAR2(200)');
    add_col('APPEALS', 'BSR_IFSC_CODE',                  'VARCHAR2(40)');
    add_col('APPEALS', 'ACCOUNT_NUMBER',                 'VARCHAR2(60)');
    add_col('APPEALS', 'CARD_NUMBER',                    'VARCHAR2(60)');
    add_col('APPEALS', 'NODAL_OFFICER_NAME',             'VARCHAR2(200)');
    -- Nullable, not DEFAULT 0: 'not yet answered' and 'answered No' are different, and the Register
    -- milestone must be able to block on an unanswered mandatory checkbox.
    add_col('APPEALS', 'IS_COMPLAINANT_ADVOCATE',        'NUMBER(1)');
    add_col('APPEALS', 'HAS_RELATED_COURT_TRIAL',        'NUMBER(1)');

    -- Regulated-entity sign-off for PNO-created appeals
    add_col('APPEALS', 'ED_APPROVAL_GIVEN',              'NUMBER(1)');
    add_col('APPEALS', 'ED_APPROVAL_DATE',               'TIMESTAMP(6)');
    add_col('APPEALS', 'ED_APPROVAL_COMMENTS',           'VARCHAR2(2000)');

    -- Field-level audit on the timeline
    add_col('APPEAL_TIMELINE', 'FIELD_NAME',             'VARCHAR2(60)');
    add_col('APPEAL_TIMELINE', 'OLD_VALUE',              'CLOB');
    add_col('APPEAL_TIMELINE', 'NEW_VALUE',              'CLOB');

    -- Reopen timestamp on complaints
    add_col('COMPLAINTS', 'REOPENED_AT',                 'TIMESTAMP(6)');
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. APPEAL_ATTACHMENTS
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'APPEAL_ATTACHMENTS';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE APPEAL_ATTACHMENTS (
                ID              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                APPEAL_NUMBER   VARCHAR2(50)   NOT NULL,
                FILE_NAME       VARCHAR2(400)  NOT NULL,
                CONTENT_TYPE    VARCHAR2(100),
                FILE_SIZE       NUMBER(19),
                STORAGE_PATH    VARCHAR2(1000) NOT NULL,
                DOCUMENT_TYPE   VARCHAR2(40),
                SOURCE_DRAFT_ID VARCHAR2(60),
                UPLOADED_BY     VARCHAR2(200),
                UPLOADED_AT     TIMESTAMP(6),
                CONSTRAINT PK_APPEAL_ATTACHMENTS PRIMARY KEY (ID)
            )';
    END IF;
END;
/

DECLARE
    PROCEDURE add_index(p_index VARCHAR2, p_table VARCHAR2, p_cols VARCHAR2) IS
        v_tab NUMBER;
        v_idx NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_tab FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_tab = 0 THEN
            RETURN;
        END IF;
        SELECT COUNT(*) INTO v_idx FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_idx = 0 THEN
            EXECUTE IMMEDIATE 'CREATE INDEX ' || p_index || ' ON ' || p_table || ' (' || p_cols || ')';
        END IF;
    END;
BEGIN
    add_index('IDX_APPEAL_ATT_NUMBER',        'APPEAL_ATTACHMENTS', 'APPEAL_NUMBER');
    add_index('IDX_APPEAL_ATT_DRAFT',         'APPEAL_ATTACHMENTS', 'SOURCE_DRAFT_ID');
    add_index('IDX_APPEAL_CLASSIFICATION',    'APPEALS',            'CLASSIFICATION_TYPE');
    add_index('IDX_APPEAL_CREATED_BY',        'APPEALS',            'CREATED_BY');
    add_index('IDX_APPEAL_ENTITY_CODE',       'APPEALS',            'ENTITY_CODE');
    -- Reopen is recorded as WORKFLOW_STAGE='REOPENED', so the AA parent search filters on it.
    add_index('IDX_COMPLAINT_WORKFLOW_STAGE', 'COMPLAINTS',         'WORKFLOW_STAGE');
    add_index('IDX_COMPLAINT_CLOSURE_CLAUSE', 'COMPLAINTS',         'CLOSURE_CLAUSE');
END;
/

-- Backfill from the CEPC/RBIO reopen path so existing reopened complaints are findable.
DECLARE
    v_col NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_col FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'LAST_REOPENED_AT';
    IF v_col > 0 THEN
        EXECUTE IMMEDIATE 'UPDATE COMPLAINTS SET REOPENED_AT = LAST_REOPENED_AT
                            WHERE REOPENED_AT IS NULL AND LAST_REOPENED_AT IS NOT NULL';
        COMMIT;
    END IF;
END;
/
