-- V34: AA parent-complaint search — RBIO office column, Ground-of-Complaint master, search indexes
-- Oracle version. MySQL twin: database/V36__aa_parent_search_office_and_ground.sql
--
-- See the MySQL twin's header for the full rationale. In short:
--
--   1. COMPLAINTS.RBIO_OFFICE_CODE is new. The originating office is encoded inside the complaint
--      number (N{FY:6}{office:3}{seq:6}); substringing that in a WHERE clause is unindexable and
--      mis-parses every other number format. THE BACKFILL IS DELIBERATELY PARTIAL — only N-format
--      numbers carry an office at all, and the parsed code is validated against OFFICE_CODE_MASTER, so
--      a mis-parse leaves NULL instead of inventing a territorial jurisdiction on a citizen's
--      complaint. Jurisdiction decides which Ombudsman may lawfully hear an appeal.
--
--   2. GROUND_OF_COMPLAINT_MASTER is new, seeded from the existing RB-IOS 2021 complaint-category
--      vocabulary. No Scheme clause number is invented; a ground is an operational grouping, not a
--      statutory citation. RBIOS_2021 only.
--
--   3. Indexes on COMPLAINT_PHONE / NAME / ENTITY_CODE / REOPENED_AT, which the AA search filters on
--      and which were unindexed.
--
-- Re-running is safe: guarded on USER_TAB_COLUMNS / USER_INDEXES / USER_TABLES, and every seed is
-- guarded by an existence check.

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. GROUND_OF_COMPLAINT_MASTER
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'GROUND_OF_COMPLAINT_MASTER';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE GROUND_OF_COMPLAINT_MASTER (
                ID             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                GROUND_CODE    VARCHAR2(60)  NOT NULL,
                LABEL          VARCHAR2(300) NOT NULL,
                LABEL_KEY      VARCHAR2(160),
                SCHEME_VERSION VARCHAR2(20)  NOT NULL,
                SORT_ORDER     NUMBER(10),
                ACTIVE         NUMBER(1)     DEFAULT 1 NOT NULL,
                EFFECTIVE_FROM DATE,
                EFFECTIVE_TO   DATE,
                CREATED_AT     TIMESTAMP(6),
                UPDATED_AT     TIMESTAMP(6),
                CONSTRAINT PK_GROUND_OF_COMPLAINT PRIMARY KEY (ID),
                CONSTRAINT UQ_GROUND_SCHEME_CODE UNIQUE (SCHEME_VERSION, GROUND_CODE)
            )';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. COMPLAINTS — office + ground columns
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    PROCEDURE add_col(p_table VARCHAR2, p_col VARCHAR2, p_type VARCHAR2) IS
        v_tab NUMBER;
        v_col NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_tab FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_tab = 0 THEN
            RETURN;
        END IF;
        SELECT COUNT(*) INTO v_col FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_col;
        IF v_col = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD ' || p_col || ' ' || p_type;
        END IF;
    END;
BEGIN
    add_col('COMPLAINTS', 'RBIO_OFFICE_CODE',       'VARCHAR2(10)');
    add_col('COMPLAINTS', 'GROUND_OF_COMPLAINT_ID', 'NUMBER(19)');
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. Indexes
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    PROCEDURE add_index(p_index VARCHAR2, p_table VARCHAR2, p_cols VARCHAR2) IS
        v_tab NUMBER;
        v_idx NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_tab FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_tab = 0 THEN
            RETURN;
        END IF;
        SELECT COUNT(*) INTO v_idx FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_idx = 0 THEN
            EXECUTE IMMEDIATE 'CREATE INDEX ' || p_index || ' ON ' || p_table || ' (' || p_cols || ')';
        END IF;
    END;
BEGIN
    add_index('IDX_GROUND_ACTIVE',            'GROUND_OF_COMPLAINT_MASTER', 'ACTIVE');
    add_index('IDX_GROUND_SCHEME',            'GROUND_OF_COMPLAINT_MASTER', 'SCHEME_VERSION');
    add_index('IDX_COMPLAINT_RBIO_OFFICE',    'COMPLAINTS', 'RBIO_OFFICE_CODE');
    add_index('IDX_COMPLAINT_GROUND',         'COMPLAINTS', 'GROUND_OF_COMPLAINT_ID');
    add_index('IDX_COMPLAINT_PHONE',          'COMPLAINTS', 'COMPLAINANT_PHONE');
    add_index('IDX_COMPLAINT_NAME',           'COMPLAINTS', 'COMPLAINANT_NAME');
    add_index('IDX_COMPLAINT_ENTITY_CODE',    'COMPLAINTS', 'ENTITY_CODE');
    add_index('IDX_COMPLAINT_REOPENED_AT',    'COMPLAINTS', 'REOPENED_AT');
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. Seed grounds (RBIOS_2021 only)
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    PROCEDURE seed_ground(p_code VARCHAR2, p_label VARCHAR2, p_key VARCHAR2, p_sort NUMBER) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM GROUND_OF_COMPLAINT_MASTER
         WHERE SCHEME_VERSION = 'RBIOS_2021' AND GROUND_CODE = p_code;
        IF v_exists = 0 THEN
            INSERT INTO GROUND_OF_COMPLAINT_MASTER
                (GROUND_CODE, LABEL, LABEL_KEY, SCHEME_VERSION, SORT_ORDER, ACTIVE,
                 EFFECTIVE_FROM, CREATED_AT, UPDATED_AT)
            VALUES (p_code, p_label, p_key, 'RBIOS_2021', p_sort, 1,
                    DATE '2021-11-12', SYSTIMESTAMP, SYSTIMESTAMP);
        END IF;
    END;
BEGIN
    seed_ground('ATM_DEBIT_CARD',      'ATM / Debit Card',      'aa.ground.atm_debit_card',      1);
    seed_ground('CREDIT_CARD',         'Credit Card',           'aa.ground.credit_card',         2);
    seed_ground('INTERNET_BANKING',    'Internet Banking',      'aa.ground.internet_banking',    3);
    seed_ground('MOBILE_BANKING_UPI',  'Mobile Banking / UPI',  'aa.ground.mobile_banking_upi',  4);
    seed_ground('LOAN_ADVANCES',       'Loan / Advances',       'aa.ground.loan_advances',       5);
    seed_ground('DEPOSIT_ACCOUNTS',    'Deposit Accounts',      'aa.ground.deposit_accounts',    6);
    seed_ground('PENSION',             'Pension',               'aa.ground.pension',             7);
    seed_ground('REMITTANCE_TRANSFER', 'Remittance / Transfer', 'aa.ground.remittance_transfer', 8);
    seed_ground('INSURANCE',           'Insurance',             'aa.ground.insurance',           9);
    seed_ground('OTHERS',              'Others',                'aa.ground.others',              99);
    COMMIT;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. Office backfill — N-format numbers only, validated against OFFICE_CODE_MASTER
-- ═══════════════════════════════════════════════════════════════════════════
-- Oracle has no REGEXP in the MySQL sense here; TRANSLATE-based digit checks keep this portable and
-- avoid a function-based index requirement. A parsed code absent from OFFICE_CODE_MASTER stays NULL.
DECLARE
    v_col NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_col FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'RBIO_OFFICE_CODE';
    IF v_col > 0 THEN
        UPDATE COMPLAINTS c
           SET RBIO_OFFICE_CODE = (
                   SELECT o.OFFICE_CODE FROM OFFICE_CODE_MASTER o
                    WHERE o.OFFICE_CODE = SUBSTR(c.COMPLAINT_NUMBER, 8, 3)
                      AND o.IS_ACTIVE = 1
                      AND ROWNUM = 1)
         WHERE c.RBIO_OFFICE_CODE IS NULL
           AND c.COMPLAINT_NUMBER LIKE 'N%'
           AND LENGTH(c.COMPLAINT_NUMBER) = 16
           AND TRANSLATE(SUBSTR(c.COMPLAINT_NUMBER, 2, 9), '0123456789', '9999999999') = '999999999'
           AND EXISTS (SELECT 1 FROM OFFICE_CODE_MASTER o2
                        WHERE o2.OFFICE_CODE = SUBSTR(c.COMPLAINT_NUMBER, 8, 3)
                          AND o2.IS_ACTIVE = 1);
        COMMIT;
    END IF;
END;
/
