-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V44 — AA assignment engine: placement records, audit trail, officer skills, stable pointer
--
-- Session S2C. Oracle counterpart of MySQL V46. Re-runnable: guarded through USER_TABLES /
-- USER_TAB_COLUMNS / USER_INDEXES.
--
-- Oracle numbering runs behind MySQL by convention; the two directories are not in step and each takes
-- its own next free number.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. AA_ASSIGNMENT_RECORD — one row per placement of an appeal with an officer
--
-- A row per placement rather than a column on APPEALS. The engine needs to know when a placement
-- happened, whether the assignee has opened it, whether it has been escalated, and whether it counts
-- against their threshold; keeping history means a reassignment does not erase who held it before.
-- Exactly one row per appeal should have RELEASED_AT NULL — that is the current holder.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'AA_ASSIGNMENT_RECORD';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE AA_ASSIGNMENT_RECORD (
                ID               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                APPEAL_NUMBER    VARCHAR2(50)  NOT NULL,
                ASSIGNED_USER_ID VARCHAR2(200) NOT NULL,
                ROLE_GROUP       VARCHAR2(100) NOT NULL,
                OUTCOME          VARCHAR2(40)  NOT NULL,
                THRESHOLD_EXEMPT NUMBER(1)     DEFAULT 0 NOT NULL,
                ASSIGNED_BY      VARCHAR2(200),
                ASSIGNED_AT      TIMESTAMP(6)  NOT NULL,
                CLAIMED_AT       TIMESTAMP(6),
                ESCALATED_AT     TIMESTAMP(6),
                RELEASED_AT      TIMESTAMP(6),
                CONSTRAINT PK_AA_ASSIGNMENT_RECORD PRIMARY KEY (ID)
            )';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. AA_ASSIGNMENT_AUDIT — actor + timestamp + reason for every mutation of shared state
--
-- Not CONFIG_AUDIT_LOG, which has no reason column. Threshold edits, activation changes, manual
-- assignments and above-threshold placements all need to record WHY.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'AA_ASSIGNMENT_AUDIT';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE AA_ASSIGNMENT_AUDIT (
                ID                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                ACTION            VARCHAR2(40)   NOT NULL,
                SUBJECT_USER_ID   VARCHAR2(200),
                ROLE_GROUP        VARCHAR2(100),
                APPEAL_NUMBER     VARCHAR2(50),
                FIELD_NAME        VARCHAR2(60),
                OLD_VALUE         VARCHAR2(500),
                NEW_VALUE         VARCHAR2(500),
                REASON            VARCHAR2(1000),
                PERFORMED_BY      VARCHAR2(200)  NOT NULL,
                PERFORMED_BY_ROLE VARCHAR2(50),
                PERFORMED_AT      TIMESTAMP(6)   NOT NULL,
                CONSTRAINT PK_AA_ASSIGNMENT_AUDIT PRIMARY KEY (ID)
            )';
    END IF;
END;
/

DECLARE
    PROCEDURE add_index(p_index VARCHAR2, p_table VARCHAR2, p_cols VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE 'CREATE INDEX ' || p_index || ' ON ' || p_table || ' (' || p_cols || ')';
        END IF;
    END;
BEGIN
    add_index('IDX_AAAR_APPEAL',    'AA_ASSIGNMENT_RECORD', 'APPEAL_NUMBER');
    add_index('IDX_AAAR_HOLDER',    'AA_ASSIGNMENT_RECORD', 'ASSIGNED_USER_ID, RELEASED_AT');
    add_index('IDX_AAAR_UNCLAIMED', 'AA_ASSIGNMENT_RECORD', 'RELEASED_AT, CLAIMED_AT, ASSIGNED_AT');
    add_index('IDX_AAA_AUDIT_ACTION',  'AA_ASSIGNMENT_AUDIT', 'ACTION');
    add_index('IDX_AAA_AUDIT_SUBJECT', 'AA_ASSIGNMENT_AUDIT', 'SUBJECT_USER_ID');
    add_index('IDX_AAA_AUDIT_AT',      'AA_ASSIGNMENT_AUDIT', 'PERFORMED_AT');
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 3+4. WF_OFFICER_POOL skills, and a pointer that identifies an officer not a position
--
-- LAST_ASSIGNED_INDEX is left untouched: cms-workflow-service still uses it for the CRPC/RBIO/CEPC
-- pools. It cannot serve AA because it was applied modulo a list re-sorted by workload on every call,
-- so a stored position meant a different officer each time. A user id survives a re-sort and a restart.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    PROCEDURE add_column(p_table VARCHAR2, p_name VARCHAR2, p_type VARCHAR2) IS
        v_tab NUMBER;
        v_col NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_tab FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_tab = 0 THEN
            RETURN;
        END IF;
        SELECT COUNT(*) INTO v_col FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_name;
        IF v_col = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD ' || p_name || ' ' || p_type;
        END IF;
    END;
BEGIN
    add_column('WF_OFFICER_POOL',       'SKILL_LANGUAGES',       'VARCHAR2(200)');
    add_column('WF_ASSIGNMENT_COUNTER', 'LAST_ASSIGNED_USER_ID', 'VARCHAR2(255)');
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. SYSTEM_CONFIG — assignment tunables (the "Preference Master")
--
-- There is no PREFERENCE_MASTER table in this schema; SYSTEM_CONFIG is the established typed, cached,
-- auditable config store.
--
-- grace_allowance defaults to 0: without an explicit operator decision, an exhausted pool must leave
-- work unassigned and visible rather than silently pushing officers past a threshold.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    PROCEDURE seed_config(p_key VARCHAR2, p_value VARCHAR2, p_desc VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM SYSTEM_CONFIG WHERE CONFIG_KEY = p_key;
        IF v_exists = 0 THEN
            INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_BY, UPDATED_AT)
            VALUES (p_key, p_value, p_desc, 'V44', SYSTIMESTAMP);
        END IF;
    END;
BEGIN
    seed_config('cms.aa.assignment.grace_allowance', '0',
        'Records an AA officer may exceed their threshold by when the pool is exhausted. 0 disables.');
    seed_config('cms.aa.assignment.auto_rebalance', 'false',
        'Whether lowering a threshold rebalances held records automatically, or waits for an admin.');
    seed_config('cms.aa.escalation.unclaimed_backoff_minutes', '2880',
        'Minutes an assigned draft may sit unclaimed before the AA Admin is alerted. Default 48h.');
    seed_config('cms.aa.escalation.enabled', 'true',
        'Master switch for the unclaimed-draft escalation sweep.');
    seed_config('cms.aa.reassign.require_admin_approval', 'true',
        'Whether an AA reassignment request needs admin approval, or is auto-approved on raise.');
    COMMIT;
END;
/
