-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V45 — AA reassignment requests (story 11). Oracle counterpart of MySQL V47.
--
-- Session S2C. Re-runnable via USER_TABLES / USER_INDEXES guards.
--
-- A separate table from REASSIGNMENT_REQUESTS rather than a widening of it: that table requires
-- NODAL_OFFICER_RECORD_ID and ENTITY_CODE, both NOT NULL and both meaningless for an appeal, and the RE
-- flows depend on its current shape.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'AA_REASSIGNMENT_REQUEST';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE AA_REASSIGNMENT_REQUEST (
                ID                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                APPEAL_NUMBER       VARCHAR2(50)   NOT NULL,
                ROLE_GROUP          VARCHAR2(100),
                FROM_USER_ID        VARCHAR2(200)  NOT NULL,
                TO_USER_ID          VARCHAR2(200),
                REASON              VARCHAR2(1000) NOT NULL,
                STATUS              VARCHAR2(20)   NOT NULL,
                REQUESTED_BY        VARCHAR2(200)  NOT NULL,
                REQUESTED_BY_ROLE   VARCHAR2(50),
                REQUESTED_AT        TIMESTAMP(6)   NOT NULL,
                DECIDED_BY          VARCHAR2(200),
                DECIDED_AT          TIMESTAMP(6),
                DECISION_COMMENT    VARCHAR2(1000),
                RESOLVED_TO_USER_ID VARCHAR2(200),
                AUTO_APPROVED       NUMBER(1)      DEFAULT 0 NOT NULL,
                CONSTRAINT PK_AA_REASSIGNMENT_REQUEST PRIMARY KEY (ID)
            )';
    END IF;
END;
/

DECLARE
    PROCEDURE add_index(p_index VARCHAR2, p_table VARCHAR2, p_cols VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE 'CREATE INDEX ' || p_index || ' ON ' || p_table || ' (' || p_cols || ')';
        END IF;
    END;
BEGIN
    add_index('IDX_AARR_STATUS',       'AA_REASSIGNMENT_REQUEST', 'STATUS');
    add_index('IDX_AARR_APPEAL',       'AA_REASSIGNMENT_REQUEST', 'APPEAL_NUMBER');
    add_index('IDX_AARR_REQUESTED_BY', 'AA_REASSIGNMENT_REQUEST', 'REQUESTED_BY');
END;
/
