-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V52 — AA hearing history, immutable order revisions, and the citizen-notice outbox
--
-- Session S3C. Oracle counterpart of MySQL V54. Re-runnable: guarded through USER_TABLES /
-- USER_INDEXES / USER_CONSTRAINTS in anonymous PL/SQL blocks.
--
-- Oracle numbering runs behind MySQL by convention; the two directories are not in step and each
-- takes its own next free number.
--
-- Prod/SIT runs ddl-auto=validate, so this script is the ONLY thing that creates these tables there.
-- The column set must match the JPA mappings exactly or the context fails to start.
--
-- WHY THESE THREE TABLES EXIST
--
--   APPEAL_HEARING    — append-only hearing history. APPEALS.HEARING_DATE / HEARING_VENUE were
--                       overwritten in place by SCHEDULE_HEARING, so a reschedule destroyed the fact
--                       that an earlier date had ever been fixed and notified to the parties. For a
--                       statutory hearing that is an audit failure. A superseded row is only STAMPED
--                       (SUPERSEDED_AT / SUPERSEDED_BY_ID), never rewritten; the operative hearing is
--                       the one row with SUPERSEDED_AT IS NULL.
--
--   APPEAL_ORDER      — immutable order revisions. PASS_ORDER wrote APPEALS.ORDER_* in place with no
--                       terminal guard, so a re-POST silently replaced the outcome, summary, amount
--                       and date of an order that had already ISSUED. An issued order is a legal
--                       instrument. A correction APPENDS revision N+1 with SUPERSEDES_ORDER_ID and a
--                       mandatory CORRECTION_REASON.
--
--   AA_CITIZEN_NOTICE — a notice OUTBOX, not a send log. cms-backend has NO email or SMS gateway at
--                       all, so a notice is recorded as a PENDING OBLIGATION and nothing in Phase 1
--                       ever marks it SENT. No screen can then truthfully claim delivery.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. APPEAL_HEARING — one row per hearing EVENT (SCHEDULED/RESCHEDULED/ADJOURNED/COMPLETED/CANCELLED)
--
-- Every hearing particular is updatable=false on the entity; only SUPERSEDED_AT / SUPERSEDED_BY_ID
-- are writable, so JPA itself refuses to rewrite the date or venue a party was notified about. The
-- outcome of a hearing is recorded by APPENDING a COMPLETED/ADJOURNED row. PRESIDING_OFFICER is
-- stored per event rather than read off the appeal, because the appeal's assignee can change after a
-- listing and the double-booking check must reflect who was actually listed at the time.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'APPEAL_HEARING';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE APPEAL_HEARING (
                ID                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                APPEAL_NUMBER     VARCHAR2(50)   NOT NULL,
                SEQUENCE_NO       NUMBER(10)     NOT NULL,
                EVENT_TYPE        VARCHAR2(20)   NOT NULL,
                HEARING_DATE      TIMESTAMP(6)   NOT NULL,
                HEARING_VENUE     VARCHAR2(500),
                HEARING_MODE      VARCHAR2(20),
                PRESIDING_OFFICER VARCHAR2(200),
                OUTCOME           VARCHAR2(40),
                OUTCOME_REMARKS   VARCHAR2(2000),
                REASON            VARCHAR2(1000),
                SUPERSEDED_AT     TIMESTAMP(6),
                SUPERSEDED_BY_ID  NUMBER(19),
                PERFORMED_BY      VARCHAR2(200)  NOT NULL,
                PERFORMED_BY_ROLE VARCHAR2(50),
                PERFORMED_AT      TIMESTAMP(6)   NOT NULL,
                CONSTRAINT PK_APPEAL_HEARING PRIMARY KEY (ID)
            )';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. APPEAL_ORDER — one row per order REVISION
--
-- ED_APPROVAL_GIVEN / ED_APPROVAL_BY / ED_APPROVAL_AT are COPIED onto the order as they stood when it
-- issued, not read live off the appeal: the appeal's approval columns can be re-registered, but what
-- approved THIS order cannot change afterwards. CLAUSE_CODE is validated against
-- CLOSURE_CLAUSE_MASTER at the service boundary rather than being free text.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'APPEAL_ORDER';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE APPEAL_ORDER (
                ID                     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                APPEAL_NUMBER          VARCHAR2(50)   NOT NULL,
                REVISION_NO            NUMBER(10)     NOT NULL,
                SUPERSEDES_ORDER_ID    NUMBER(19),
                CORRECTION_REASON      VARCHAR2(1000),
                OUTCOME                VARCHAR2(30)   NOT NULL,
                ORDER_SUMMARY          CLOB           NOT NULL,
                AWARD_AMOUNT           NUMBER(15,2),
                CLAUSE_CODE            VARCHAR2(40),
                GROUND                 VARCHAR2(300),
                ISSUING_AUTHORITY      VARCHAR2(200)  NOT NULL,
                ISSUING_AUTHORITY_ROLE VARCHAR2(50),
                ORDER_DATE             TIMESTAMP(6)   NOT NULL,
                ED_APPROVAL_GIVEN      NUMBER(1),
                ED_APPROVAL_BY         VARCHAR2(200),
                ED_APPROVAL_AT         TIMESTAMP(6),
                SUPERSEDED_AT          TIMESTAMP(6),
                SUPERSEDED_BY_ID       NUMBER(19),
                PERFORMED_BY           VARCHAR2(200)  NOT NULL,
                PERFORMED_BY_ROLE      VARCHAR2(50),
                PERFORMED_AT           TIMESTAMP(6)   NOT NULL,
                CONSTRAINT PK_APPEAL_ORDER PRIMARY KEY (ID)
            )';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. AA_CITIZEN_NOTICE — outbox of notices OWED, one row per recipient per event
--
-- MESSAGE_KEY holds a translation key, not rendered English: the citizen's locale is unknown when the
-- obligation arises, so the text is resolved at dispatch and no statutory wording is frozen into the
-- row. ATTEMPT_COUNT / LAST_ERROR / NEXT_ATTEMPT_AT exist now so the eventual gateway is a plain
-- dispatcher over this table and needs no schema change.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'AA_CITIZEN_NOTICE';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE AA_CITIZEN_NOTICE (
                ID              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                APPEAL_NUMBER   VARCHAR2(50)   NOT NULL,
                EVENT_CODE      VARCHAR2(60)   NOT NULL,
                RECIPIENT_ROLE  VARCHAR2(30)   NOT NULL,
                RECIPIENT_NAME  VARCHAR2(200),
                RECIPIENT_EMAIL VARCHAR2(200),
                RECIPIENT_PHONE VARCHAR2(30),
                CHANNEL         VARCHAR2(20)   NOT NULL,
                MESSAGE_KEY     VARCHAR2(200)  NOT NULL,
                MESSAGE_PARAMS  CLOB,
                STATUS          VARCHAR2(20)   NOT NULL,
                DEDUPE_KEY      VARCHAR2(100)  NOT NULL,
                ATTEMPT_COUNT   NUMBER(10)     NOT NULL,
                LAST_ERROR      VARCHAR2(1000),
                NEXT_ATTEMPT_AT TIMESTAMP(6),
                DISPATCHED_AT   TIMESTAMP(6),
                CREATED_BY      VARCHAR2(200)  NOT NULL,
                CREATED_AT      TIMESTAMP(6)   NOT NULL,
                UPDATED_AT      TIMESTAMP(6),
                CONSTRAINT PK_AA_CITIZEN_NOTICE PRIMARY KEY (ID)
            )';
    END IF;
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. Indexes — every @Index declared on the three entities
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    PROCEDURE add_index(p_index VARCHAR2, p_table VARCHAR2, p_cols VARCHAR2) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE 'CREATE INDEX ' || p_index || ' ON ' || p_table || ' (' || p_cols || ')';
        END IF;
    END;
BEGIN
    add_index('IDX_AH_APPEAL',       'APPEAL_HEARING', 'APPEAL_NUMBER');
    add_index('IDX_AH_ACTIVE',       'APPEAL_HEARING', 'APPEAL_NUMBER, SUPERSEDED_AT');
    add_index('IDX_AH_OFFICER_DATE', 'APPEAL_HEARING', 'PRESIDING_OFFICER, HEARING_DATE');
    add_index('IDX_AH_PERFORMED_AT', 'APPEAL_HEARING', 'PERFORMED_AT');

    add_index('IDX_AO_APPEAL',     'APPEAL_ORDER', 'APPEAL_NUMBER');
    add_index('IDX_AO_OPERATIVE',  'APPEAL_ORDER', 'APPEAL_NUMBER, SUPERSEDED_AT');
    add_index('IDX_AO_ORDER_DATE', 'APPEAL_ORDER', 'ORDER_DATE');

    add_index('IDX_ACN_APPEAL',   'AA_CITIZEN_NOTICE', 'APPEAL_NUMBER');
    add_index('IDX_ACN_STATUS',   'AA_CITIZEN_NOTICE', 'STATUS');
    add_index('IDX_ACN_DISPATCH', 'AA_CITIZEN_NOTICE', 'STATUS, NEXT_ATTEMPT_AT');
    -- Declared by @Index on the entity. Created even though UK_ACN_EVENT_RECIPIENT below covers the
    -- same leading columns, so the schema matches the mapping literally.
    add_index('IDX_ACN_DEDUPE',   'AA_CITIZEN_NOTICE',
              'APPEAL_NUMBER, EVENT_CODE, RECIPIENT_ROLE, DEDUPE_KEY');
END;
/

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. UK_ACN_EVENT_RECIPIENT — LOAD-BEARING idempotency guarantee
--
-- The reminder sweep runs on every pod and there is NO distributed lock, so two pods can decide to
-- record the same notice in the same second. Idempotency therefore has to be enforced by the
-- database, not by application code: the second INSERT must be REJECTED. Do not drop this constraint
-- to "fix" a unique-violation error — that error is the guarantee working.
--
-- Guarded on USER_CONSTRAINTS (not USER_INDEXES): Oracle names the backing index after the
-- constraint, so checking either alone is not reliable if a bare index of the same name pre-exists.
-- ═══════════════════════════════════════════════════════════════════════════
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_NAME = 'UK_ACN_EVENT_RECIPIENT';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE AA_CITIZEN_NOTICE ADD CONSTRAINT UK_ACN_EVENT_RECIPIENT
                UNIQUE (APPEAL_NUMBER, EVENT_CODE, RECIPIENT_ROLE, DEDUPE_KEY)';
    END IF;
    COMMIT;
END;
/
