-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V55 — RBIO_STATUS_MASTER + per-role visibility. Oracle counterpart of MySQL V57 (Wave 0).
--
-- Re-runnable: every DDL is wrapped so that ORA-00955 (name already used) and ORA-01430 (column
-- already present) are swallowed, which is this tree's idiom for idempotent Oracle DDL.
--
-- See MySQL V57 for the full rationale. The load-bearing point, repeated because it is the thing most
-- likely to be "tidied" away: FILTER_KIND distinguishes STATUS (a value COMPLAINTS.status takes) from
-- QUEUE (status + assigned_role) from SCOPE (a predicate on the CALLER, e.g. "Assigned to Me"). The
-- ~25 backlog "statuses" are a mix of all three, and a SCOPE row has no LEGACY_VALUE and never appears
-- in COMPLAINTS.status — querying WHERE status='ALL' would silently return an empty grid.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

DECLARE
    PROCEDURE ddl(p_sql VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
    EXCEPTION
        -- 00955 object exists, 01430 column exists, 01408 index exists, 02275 FK exists
        WHEN OTHERS THEN
            IF SQLCODE IN (-955, -1430, -1408, -2275) THEN NULL; ELSE RAISE; END IF;
    END;
BEGIN
    ddl('CREATE TABLE RBIO_STATUS_MASTER (
            STATUS_CODE        VARCHAR2(50)  NOT NULL,
            LEGACY_VALUE       VARCHAR2(30),
            FILTER_KIND        VARCHAR2(10)  DEFAULT ''STATUS'' NOT NULL,
            LABEL_EN           VARCHAR2(150) NOT NULL,
            TRANSLATION_KEY    VARCHAR2(150),
            MILESTONE_CODE     VARCHAR2(30),
            QUEUE_ROLE         VARCHAR2(50),
            IS_CLOSED          CHAR(1)       DEFAULT ''N'' NOT NULL,
            IS_TERMINAL        CHAR(1)       DEFAULT ''N'' NOT NULL,
            IS_CITIZEN_VISIBLE CHAR(1)       DEFAULT ''N'' NOT NULL,
            DISPLAY_ORDER      NUMBER(10)    DEFAULT 999 NOT NULL,
            IS_ACTIVE          CHAR(1)       DEFAULT ''Y'' NOT NULL,
            SCHEME_VERSION     VARCHAR2(20)  DEFAULT ''RBIOS_2021'' NOT NULL,
            CREATED_AT         TIMESTAMP(6),
            CONSTRAINT PK_RBIO_STATUS_MASTER PRIMARY KEY (STATUS_CODE)
         )');
    ddl('CREATE INDEX IDX_RBIO_STATUS_LEGACY ON RBIO_STATUS_MASTER (LEGACY_VALUE)');
    ddl('CREATE INDEX IDX_RBIO_STATUS_KIND ON RBIO_STATUS_MASTER (FILTER_KIND, DISPLAY_ORDER)');

    ddl('CREATE TABLE RBIO_STATUS_ROLE_VISIBILITY (
            ID            NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
            STATUS_CODE   VARCHAR2(50) NOT NULL,
            ROLE_NAME     VARCHAR2(50) NOT NULL,
            DISPLAY_ORDER NUMBER(10)   DEFAULT 999 NOT NULL,
            IS_DEFAULT    CHAR(1)      DEFAULT ''N'' NOT NULL,
            CONSTRAINT PK_RBIO_STATUS_ROLE_VIS PRIMARY KEY (ID),
            CONSTRAINT UK_RBIO_STATUS_ROLE UNIQUE (STATUS_CODE, ROLE_NAME)
         )');
    ddl('CREATE INDEX IDX_RBIO_STATUS_VIS_ROLE ON RBIO_STATUS_ROLE_VISIBILITY (ROLE_NAME, DISPLAY_ORDER)');

    COMMIT;
END;
/
