-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V56 — RBIO_MILESTONE_MASTER + RBIO_WORKFLOW_TRANSITION + COMPLAINTS columns.
--       Oracle counterpart of MySQL V58 (Wave 0).
--
-- Re-runnable via the same swallow-if-exists idiom as V55.
--
-- See MySQL V58 for the full rationale. Two points that must not be "corrected":
--   * Transition ROWS are seeded by RbioWorkflowTransitionSeeder (@Order(21)), not by this file.
--     There is no Flyway in this tree, so an unapplied migration is normal; rows in SQL would mean an
--     unseeded database has an EMPTY transition table and a completely dead RBIO workflow, where the
--     switch it replaces always worked. Sessions S1-S7 also add rows, and one shared .sql file would
--     silently lose their work.
--   * NULL TO_STATUS means "status unchanged" (SCHEDULE_MEETING, ISSUE_NOTICE_13_1 move only the
--     stage), NOT "unconfigured". Treating NULL as unconfigured would blank the status.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

DECLARE
    PROCEDURE ddl(p_sql VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE IN (-955, -1430, -1408, -2275) THEN NULL; ELSE RAISE; END IF;
    END;

    PROCEDURE seed_milestone(p_code VARCHAR2, p_label VARCHAR2, p_key VARCHAR2, p_order NUMBER) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists FROM RBIO_MILESTONE_MASTER WHERE MILESTONE_CODE = p_code;
        IF v_exists = 0 THEN
            INSERT INTO RBIO_MILESTONE_MASTER (MILESTONE_CODE, LABEL_EN, TRANSLATION_KEY, DISPLAY_ORDER, IS_ACTIVE)
            VALUES (p_code, p_label, p_key, p_order, 'Y');
        END IF;
    END;
BEGIN
    ddl('CREATE TABLE RBIO_MILESTONE_MASTER (
            MILESTONE_CODE  VARCHAR2(30)  NOT NULL,
            LABEL_EN        VARCHAR2(150) NOT NULL,
            TRANSLATION_KEY VARCHAR2(150),
            DISPLAY_ORDER   NUMBER(10)    DEFAULT 999 NOT NULL,
            IS_ACTIVE       CHAR(1)       DEFAULT ''Y'' NOT NULL,
            CONSTRAINT PK_RBIO_MILESTONE_MASTER PRIMARY KEY (MILESTONE_CODE)
         )');

    ddl('CREATE TABLE RBIO_WORKFLOW_TRANSITION (
            ID               NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
            ACTION_CODE      VARCHAR2(50) NOT NULL,
            ROLE_NAME        VARCHAR2(50) NOT NULL,
            FROM_STATUS      VARCHAR2(30),
            TO_STATUS        VARCHAR2(30),
            TO_STAGE         VARCHAR2(50),
            TO_MILESTONE     VARCHAR2(30),
            ASSIGN_TO_ROLE   VARCHAR2(50),
            ASSIGN_STRATEGY  VARCHAR2(20),
            REQUIRES_COMMENT CHAR(1)      DEFAULT ''N'' NOT NULL,
            REQUIRED_PARAMS  VARCHAR2(255),
            IS_TERMINAL      CHAR(1)      DEFAULT ''N'' NOT NULL,
            SIDE_EFFECT      VARCHAR2(50),
            SLA_STAGE        VARCHAR2(50),
            CLOSURE_CAUSE    VARCHAR2(50),
            DISPLAY_ORDER    NUMBER(10)   DEFAULT 999 NOT NULL,
            IS_ACTIVE        CHAR(1)      DEFAULT ''Y'' NOT NULL,
            SCHEME_VERSION   VARCHAR2(20) DEFAULT ''RBIOS_2021'' NOT NULL,
            OWNED_BY         VARCHAR2(20),
            CONSTRAINT PK_RBIO_WORKFLOW_TRANSITION PRIMARY KEY (ID),
            CONSTRAINT UK_RBIO_TRANSITION UNIQUE (ACTION_CODE, ROLE_NAME, FROM_STATUS)
         )');
    ddl('CREATE INDEX IDX_RBIO_TRANS_LOOKUP ON RBIO_WORKFLOW_TRANSITION (ACTION_CODE, ROLE_NAME, IS_ACTIVE)');
    ddl('CREATE INDEX IDX_RBIO_TRANS_ROLE ON RBIO_WORKFLOW_TRANSITION (ROLE_NAME, IS_ACTIVE)');

    -- Both NULLABLE. ddl-auto never drops a column, so a NOT NULL here would be permanent for every
    -- other session and would break their inserts. record_version is NULL on legacy rows; Hibernate
    -- initialises a null @Version on first write, so no backfill UPDATE is needed.
    ddl('ALTER TABLE COMPLAINTS ADD (MILESTONE VARCHAR2(30) NULL)');
    ddl('ALTER TABLE COMPLAINTS ADD (RECORD_VERSION NUMBER(19) DEFAULT 0 NULL)');
    ddl('CREATE INDEX IDX_COMPLAINT_MILESTONE ON COMPLAINTS (MILESTONE)');

    -- Backfill. The entity maps record_version as a PRIMITIVE long because Hibernate does NOT lazily
    -- initialise a null @Version — it reads null and increments it, which failed EVERY write to a
    -- pre-existing complaint. This makes the stored data agree so the version is never null in the DB.
    EXECUTE IMMEDIATE 'UPDATE COMPLAINTS SET RECORD_VERSION = 0 WHERE RECORD_VERSION IS NULL';

    -- The DEFAULT above only applies when THIS script created the column. Where `ddl-auto: update`
    -- created it first from the entity there is no default, so any INSERT omitting the column writes
    -- NULL, Hibernate reads NULL into a primitive `long`, and the request fails with
    --   Null value was assigned to a property [Complaint.recordVersion] of primitive type (setter)
    -- Observed on MySQL as 76 AA E2E failures caused solely by fixtures that omit the column.
    -- Applying the default unconditionally makes the column behave identically however it was created.
    ddl('ALTER TABLE COMPLAINTS MODIFY (RECORD_VERSION DEFAULT 0)');

    seed_milestone('REGISTER',       'Register',       'rbio.milestone.register',       1);
    seed_milestone('ASSESSMENT',     'Assessment',     'rbio.milestone.assessment',     2);
    seed_milestone('CONCILIATION',   'Conciliation',   'rbio.milestone.conciliation',   3);
    seed_milestone('FORWARD',        'Forward',        'rbio.milestone.forward',        4);
    seed_milestone('FINAL_DECISION', 'Final Decision', 'rbio.milestone.final_decision', 5);

    COMMIT;
END;
/
