-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V69 — S3: RBIO ladder case-file tables + COMPLAINTS columns.
--       Oracle counterpart of MySQL V71.
--
-- Re-runnable via the same swallow-if-exists idiom as V55/V56: -955 (name already used), -1430 (column
-- already exists), -1408 (index already exists), -2275 (constraint already exists).
--
-- See MySQL V71 for the full rationale. Three points that must not be "corrected":
--   * ALL new columns are NULLABLE. Schema comes from ddl-auto on a database shared by seven sessions
--     and ddl-auto never reverts, so a NOT NULL here is permanent for everyone.
--   * RELEASED_AT NULL means "holds the file now". The previous-holder query keys on
--     RELEASED_AT IS NOT NULL, which is what stops a send-back resolving to the CURRENT holder — i.e. a
--     file "sent back" to the officer who just sent it.
--   * The six-entity cap is enforced in RbioAdditionalEntityService, not by a constraint here. A row
--     limit is not expressible as a column constraint, and the browser-only version that existed before
--     was bypassed by any direct POST.
--
-- The workflow action ROWS are seeded by RbioLadderTransitionSeeder (@Order 32), not by this file, for
-- the reason V56 states: there is no Flyway here, so an unapplied migration is a normal occurrence.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

DECLARE
    PROCEDURE ddl(p_sql VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE IN (-955, -1430, -1408, -2275) THEN NULL; ELSE RAISE; END IF;
    END;
BEGIN
    -- ═══ 1. Custody trail ═══
    ddl('CREATE TABLE RBIO_CASE_ASSIGNMENT_HISTORY (
            ID                 NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
            COMPLAINT_NUMBER   VARCHAR2(50)  NOT NULL,
            ROLE_NAME          VARCHAR2(50)  NOT NULL,
            OFFICER_ID         VARCHAR2(100) NOT NULL,
            ASSIGNED_BY_ACTION VARCHAR2(50),
            ASSIGNED_BY        VARCHAR2(100),
            ASSIGNED_AT        TIMESTAMP     NOT NULL,
            RELEASED_AT        TIMESTAMP,
            CONSTRAINT PK_RBIO_CASE_ASSIGN_HIST PRIMARY KEY (ID)
         )');
    ddl('CREATE INDEX IDX_RBIO_CAH_COMPLAINT ON RBIO_CASE_ASSIGNMENT_HISTORY (COMPLAINT_NUMBER)');
    ddl('CREATE INDEX IDX_RBIO_CAH_LOOKUP ON RBIO_CASE_ASSIGNMENT_HISTORY (COMPLAINT_NUMBER, ROLE_NAME, RELEASED_AT)');

    -- ═══ 2. Additional entities (max six, enforced in the service) ═══
    ddl('CREATE TABLE RBIO_ADDITIONAL_ENTITY (
            ID                  NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
            COMPLAINT_NUMBER    VARCHAR2(50)  NOT NULL,
            ENTITY_NAME         VARCHAR2(200) NOT NULL,
            ENTITY_BRANCH       VARCHAR2(200),
            ENTITY_TYPE         VARCHAR2(100),
            ENTITY_CATEGORY     VARCHAR2(100),
            REGULATED_ENTITY_ID NUMBER(19),
            CREATED_BY          VARCHAR2(100),
            CREATED_BY_ROLE     VARCHAR2(50),
            CREATED_AT          TIMESTAMP     NOT NULL,
            CONSTRAINT PK_RBIO_ADDITIONAL_ENTITY PRIMARY KEY (ID)
         )');
    ddl('CREATE INDEX IDX_RBIO_ADDL_ENTITY_CN ON RBIO_ADDITIONAL_ENTITY (COMPLAINT_NUMBER)');

    -- ═══ 3. Field-level override history, append-only ═══
    ddl('CREATE TABLE RBIO_ACTION_OVERRIDE (
            ID                 NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
            COMPLAINT_NUMBER   VARCHAR2(50)  NOT NULL,
            FIELD_NAME         VARCHAR2(100) NOT NULL,
            OLD_VALUE          VARCHAR2(500),
            NEW_VALUE          VARCHAR2(500),
            OVERRIDDEN_BY      VARCHAR2(100),
            OVERRIDDEN_BY_ROLE VARCHAR2(50),
            OVERRIDDEN_AT      TIMESTAMP     NOT NULL,
            CONSTRAINT PK_RBIO_ACTION_OVERRIDE PRIMARY KEY (ID)
         )');
    ddl('CREATE INDEX IDX_RBIO_OVERRIDE_CN ON RBIO_ACTION_OVERRIDE (COMPLAINT_NUMBER)');

    -- ═══ 4. Legal case — one per complaint ═══
    -- COMPLAINT_NUMBER is UNIQUE because "is this matter before a court" has one answer at a time, and
    -- the statutory sub-judice guard depends on that uniqueness.
    ddl('CREATE TABLE RBIO_LEGAL_CASE (
            ID                NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
            COMPLAINT_NUMBER  VARCHAR2(50)   NOT NULL,
            CASE_NUMBER       VARCHAR2(100)  NOT NULL,
            COURT_NAME        VARCHAR2(200)  NOT NULL,
            CASE_STATUS       VARCHAR2(50),
            FILING_DATE       DATE,
            NEXT_HEARING_DATE DATE,
            REMARKS           VARCHAR2(2000),
            CREATED_BY        VARCHAR2(100),
            CREATED_AT        TIMESTAMP,
            UPDATED_BY        VARCHAR2(100),
            UPDATED_AT        TIMESTAMP,
            CONSTRAINT PK_RBIO_LEGAL_CASE PRIMARY KEY (ID),
            CONSTRAINT UK_RBIO_LEGAL_CASE_CN UNIQUE (COMPLAINT_NUMBER)
         )');

    -- ═══ 5. COMPLAINTS — five new nullable columns ═══
    -- DEPUTY_DECISION is separate from MAINTAINABILITY_DETERMINATION on purpose: a complaint can be
    -- maintainable AND rejected on its merits, so one column could not express both outcomes.
    ddl('ALTER TABLE COMPLAINTS ADD (DEPUTY_DECISION      VARCHAR2(30))');
    ddl('ALTER TABLE COMPLAINTS ADD (REGULATORY_BODY_NAME VARCHAR2(200))');
    ddl('ALTER TABLE COMPLAINTS ADD (ADVISORY_COMPLIED_AT TIMESTAMP)');
    ddl('ALTER TABLE COMPLAINTS ADD (REOPEN_REASON        VARCHAR2(50))');
    ddl('ALTER TABLE COMPLAINTS ADD (REOPEN_JUSTIFICATION CLOB)');
END;
/
