-- ============================================================
-- RBI CMS 2.0 — V6 ALTER TABLE Migration
-- Date: 2026-07-29
-- Scope: New columns added to COMPLAINTS and EMAIL_DRAFTS
--        since V5 (2026-07-24)
-- Safe to run multiple times (checks before adding)
-- ============================================================

-- ============================================================
-- COMPLAINTS TABLE — New closure and tracking columns
-- ============================================================

-- Add CUSTOM_CLOSURE_TEXT if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'CUSTOM_CLOSURE_TEXT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE COMPLAINTS ADD CUSTOM_CLOSURE_TEXT VARCHAR2(2000)';
    END IF;
END;
/

-- Add CLOSURE_LETTER_SENT_AT if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'CLOSURE_LETTER_SENT_AT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE COMPLAINTS ADD CLOSURE_LETTER_SENT_AT TIMESTAMP(6)';
    END IF;
END;
/

-- Add CLOSURE_CLAUSE if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'CLOSURE_CLAUSE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE COMPLAINTS ADD CLOSURE_CLAUSE VARCHAR2(100)';
    END IF;
END;
/

-- Add CLOSURE_AUTHORITY_NAME if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'CLOSURE_AUTHORITY_NAME';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE COMPLAINTS ADD CLOSURE_AUTHORITY_NAME VARCHAR2(200)';
    END IF;
END;
/

-- Add CLOSURE_AUTHORITY_DESIGNATION if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'CLOSURE_AUTHORITY_DESIGNATION';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE COMPLAINTS ADD CLOSURE_AUTHORITY_DESIGNATION VARCHAR2(200)';
    END IF;
END;
/

-- Add RE_RESPONSE_DEADLINE if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'RE_RESPONSE_DEADLINE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE COMPLAINTS ADD RE_RESPONSE_DEADLINE DATE';
    END IF;
END;
/

-- Add LAST_STATUS_CHANGE_DATE if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'COMPLAINTS' AND COLUMN_NAME = 'LAST_STATUS_CHANGE_DATE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE COMPLAINTS ADD LAST_STATUS_CHANGE_DATE TIMESTAMP(6)';
    END IF;
END;
/

-- ============================================================
-- EMAIL_DRAFTS TABLE — New workflow columns
-- ============================================================

-- Add SCHEME_VERSION if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'EMAIL_DRAFTS' AND COLUMN_NAME = 'SCHEME_VERSION';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_DRAFTS ADD SCHEME_VERSION VARCHAR2(20)';
    END IF;
END;
/

-- Add CLOSURE_CLAUSE if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'EMAIL_DRAFTS' AND COLUMN_NAME = 'CLOSURE_CLAUSE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_DRAFTS ADD CLOSURE_CLAUSE VARCHAR2(50)';
    END IF;
END;
/

-- Add AUTO_CLOSURE_RESPONSES_JSON if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'EMAIL_DRAFTS' AND COLUMN_NAME = 'AUTO_CLOSURE_RESPONSES_JSON';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_DRAFTS ADD AUTO_CLOSURE_RESPONSES_JSON CLOB';
    END IF;
END;
/

-- Add SUB_JUDICE if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'EMAIL_DRAFTS' AND COLUMN_NAME = 'SUB_JUDICE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_DRAFTS ADD SUB_JUDICE NUMBER(1) DEFAULT 0';
    END IF;
END;
/

-- Add NOT_A_COMPLAINT_REASON if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'EMAIL_DRAFTS' AND COLUMN_NAME = 'NOT_A_COMPLAINT_REASON';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_DRAFTS ADD NOT_A_COMPLAINT_REASON VARCHAR2(100)';
    END IF;
END;
/

-- Add NOT_A_COMPLAINT_OTHERS_REASON if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'EMAIL_DRAFTS' AND COLUMN_NAME = 'NOT_A_COMPLAINT_OTHERS_REASON';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_DRAFTS ADD NOT_A_COMPLAINT_OTHERS_REASON CLOB';
    END IF;
END;
/

-- Add SUGGESTION_DEPARTMENT if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'EMAIL_DRAFTS' AND COLUMN_NAME = 'SUGGESTION_DEPARTMENT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_DRAFTS ADD SUGGESTION_DEPARTMENT VARCHAR2(100)';
    END IF;
END;
/

-- Add SUGGESTION_NATURE if not exists
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'EMAIL_DRAFTS' AND COLUMN_NAME = 'SUGGESTION_NATURE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_DRAFTS ADD SUGGESTION_NATURE VARCHAR2(200)';
    END IF;
END;
/

COMMIT;

-- ============================================================
-- VERIFICATION
-- ============================================================
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME IN ('COMPLAINTS', 'EMAIL_DRAFTS')
AND COLUMN_NAME IN (
    'CUSTOM_CLOSURE_TEXT', 'CLOSURE_LETTER_SENT_AT', 'CLOSURE_CLAUSE',
    'CLOSURE_AUTHORITY_NAME', 'CLOSURE_AUTHORITY_DESIGNATION',
    'RE_RESPONSE_DEADLINE', 'LAST_STATUS_CHANGE_DATE',
    'SCHEME_VERSION', 'AUTO_CLOSURE_RESPONSES_JSON', 'SUB_JUDICE',
    'NOT_A_COMPLAINT_REASON', 'NOT_A_COMPLAINT_OTHERS_REASON',
    'SUGGESTION_DEPARTMENT', 'SUGGESTION_NATURE'
)
ORDER BY TABLE_NAME, COLUMN_NAME;
