-- ============================================================
-- V71 — OFFICE_THRESHOLD_CONFIG: re-key to OFFICE_CODE_MASTER and seed all 24 offices
-- Session S3 (UST464-467, UST755). Oracle counterpart of MySQL V73.
-- ============================================================
--
-- See database/V73__office_threshold_by_office_code.sql for the full rationale. In brief:
--
--   * OFFICE_THRESHOLD_CONFIG was keyed on five synthetic ids ('RBIO-MUM', 'RBIO-DEL', 'RBIO-CHN',
--     'RBIO-KOL', 'CEPC') that covered four of the twenty-four real ombudsman offices and had NO
--     join key to OMBUDSMAN_OFFICE_MASTER, which is keyed by name and has no code column.
--     It is re-keyed here onto OFFICE_CODE_MASTER.OFFICE_CODE — the only stable short code in the
--     schema, and already the value carried on COMPLAINTS.RBIO_OFFICE_CODE.
--
--   * MAX_THRESHOLD is a uniform placeholder read from SYSTEM_CONFIG
--     ('office.threshold.default_max') because no authoritative per-office RBI capacity figure
--     exists in this repo. A guessed per-office cap would divert a citizen's complaint away from
--     its lawful territorial office. Uniform-and-explainable beats invented-and-plausible.
--
-- ORACLE-SPECIFIC NOTE: OMBUDSMAN_OFFICE_MASTER has NO Oracle DDL anywhere in database/oracle/
-- (verified: zero hits). That is a PRE-EXISTING schema drift, not something introduced here. The
-- seed below is therefore written to degrade safely: if the table is absent the office seed simply
-- inserts nothing rather than failing the migration, and the CEPC row plus the config keys still
-- land. The office rows then arrive from the MySQL side or from a later Oracle DDL for that master.
-- This is called out in the batch report as an outstanding item rather than silently patched here,
-- because creating a 24-row territorial-jurisdiction master for Oracle is a data-authority
-- decision, not a mechanical port.
--
-- Re-running is safe: Oracle has no ADD COLUMN IF NOT EXISTS, so DDL is guarded on
-- USER_TAB_COLUMNS / USER_TABLES / USER_INDEXES and every seed is INSERT ... WHERE NOT EXISTS.
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- 1. Table + index, guarded
-- ─────────────────────────────────────────────────────────────
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'OFFICE_THRESHOLD_CONFIG';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE OFFICE_THRESHOLD_CONFIG (
                ID                      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                OFFICE_ID               VARCHAR2(50) NOT NULL,
                OFFICE_NAME             VARCHAR2(200) NOT NULL,
                DEPARTMENT              VARCHAR2(20) NOT NULL,
                MAX_THRESHOLD           NUMBER(10) DEFAULT 100 NOT NULL,
                CURRENT_COUNT           NUMBER(10) DEFAULT 0 NOT NULL,
                OVERFLOW_SEQUENCE_ORDER NUMBER(10) DEFAULT 0 NOT NULL,
                OVERFLOW_TARGET_OFFICE  VARCHAR2(50),
                ACTIVE                  NUMBER(1) DEFAULT 1 NOT NULL,
                UPDATED_BY              VARCHAR2(100),
                UPDATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
                CONSTRAINT UQ_OFFICE_THRESHOLD_OFFICE_ID UNIQUE (OFFICE_ID)
            )';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_OFC_THRESH_DEPT_ORDER';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_OFC_THRESH_DEPT_ORDER ON OFFICE_THRESHOLD_CONFIG '
                       || '(DEPARTMENT, ACTIVE, OVERFLOW_SEQUENCE_ORDER)';
    END IF;
END;
/

-- ─────────────────────────────────────────────────────────────
-- 2. Config keys (admin-tunable, no restart — SYSTEM_CONFIG is uncached)
-- ─────────────────────────────────────────────────────────────
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_BY, UPDATED_AT)
SELECT 'office.threshold.default_max', '500',
       'Default per-office concurrent complaint capacity before overflow. Placeholder pending RBI capacity data.',
       'V71_migration', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYSTEM_CONFIG WHERE CONFIG_KEY = 'office.threshold.default_max');

INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_BY, UPDATED_AT)
SELECT 'office.threshold.enforcement_enabled', 'true',
       'When false, routeToOffice records the office but never diverts to an overflow office.',
       'V71_migration', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYSTEM_CONFIG WHERE CONFIG_KEY = 'office.threshold.enforcement_enabled');

-- ─────────────────────────────────────────────────────────────
-- 3. Retire the synthetic office ids (deactivate, never delete — preserves history)
-- ─────────────────────────────────────────────────────────────
UPDATE OFFICE_THRESHOLD_CONFIG
   SET ACTIVE = 0, UPDATED_BY = 'V71_migration', UPDATED_AT = SYSTIMESTAMP
 WHERE OFFICE_ID IN ('RBIO-MUM', 'RBIO-DEL', 'RBIO-CHN', 'RBIO-KOL');

-- ─────────────────────────────────────────────────────────────
-- 4. Seed one capacity row per real ombudsman office, keyed by OFFICE_CODE
-- ─────────────────────────────────────────────────────────────
-- Guarded on the presence of OMBUDSMAN_OFFICE_MASTER (see header note): absent master => no office
-- rows, rather than a failed migration.
DECLARE
    v_has_oom NUMBER;
    v_has_ocm NUMBER;
    v_default VARCHAR2(50);
BEGIN
    SELECT COUNT(*) INTO v_has_oom FROM USER_TABLES WHERE TABLE_NAME = 'OMBUDSMAN_OFFICE_MASTER';
    SELECT COUNT(*) INTO v_has_ocm FROM USER_TABLES WHERE TABLE_NAME = 'OFFICE_CODE_MASTER';

    BEGIN
        SELECT CONFIG_VALUE INTO v_default FROM SYSTEM_CONFIG
         WHERE CONFIG_KEY = 'office.threshold.default_max';
    EXCEPTION WHEN NO_DATA_FOUND THEN v_default := '500';
    END;

    IF v_has_oom > 0 AND v_has_ocm > 0 THEN
        EXECUTE IMMEDIATE '
            INSERT INTO OFFICE_THRESHOLD_CONFIG
                (OFFICE_ID, OFFICE_NAME, DEPARTMENT, MAX_THRESHOLD, CURRENT_COUNT,
                 OVERFLOW_SEQUENCE_ORDER, OVERFLOW_TARGET_OFFICE, ACTIVE, UPDATED_BY, UPDATED_AT)
            SELECT ocm.OFFICE_CODE,
                   oom.OFFICE_NAME,
                   ''RBIO'',
                   TO_NUMBER(:1),
                   0,
                   TO_NUMBER(ocm.OFFICE_CODE),
                   NULL,
                   1,
                   ''V71_migration'',
                   SYSTIMESTAMP
              FROM OMBUDSMAN_OFFICE_MASTER oom
              JOIN OFFICE_CODE_MASTER ocm
                ON REPLACE(UPPER(ocm.OFFICE_NAME), ''-'', '' '') = REPLACE(UPPER(oom.OFFICE_NAME), ''-'', '' '')
               AND ocm.IS_ACTIVE = 1
             WHERE oom.IS_ACTIVE = 1
               AND NOT EXISTS (SELECT 1 FROM OFFICE_THRESHOLD_CONFIG t WHERE t.OFFICE_ID = ocm.OFFICE_CODE)'
        USING v_default;
    END IF;
END;
/

-- CEPC is a department, not a territorial office — its own single row.
INSERT INTO OFFICE_THRESHOLD_CONFIG
    (OFFICE_ID, OFFICE_NAME, DEPARTMENT, MAX_THRESHOLD, CURRENT_COUNT,
     OVERFLOW_SEQUENCE_ORDER, OVERFLOW_TARGET_OFFICE, ACTIVE, UPDATED_BY, UPDATED_AT)
SELECT 'CEPC', 'CEPC', 'CEPC',
       TO_NUMBER(NVL((SELECT CONFIG_VALUE FROM SYSTEM_CONFIG
                       WHERE CONFIG_KEY = 'office.threshold.default_max'), '500')),
       0, 1, NULL, 1, 'V71_migration', SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM OFFICE_THRESHOLD_CONFIG WHERE OFFICE_ID = 'CEPC');

-- ─────────────────────────────────────────────────────────────
-- 5. Overflow chain — each RBIO office overflows to the next by sequence order
-- ─────────────────────────────────────────────────────────────
-- Highest-ordered office keeps NULL = "end of chain", which the service treats as all-full rather
-- than looping.
UPDATE OFFICE_THRESHOLD_CONFIG t
   SET t.OVERFLOW_TARGET_OFFICE = (
        SELECT nxt.OFFICE_ID FROM (
            SELECT n.OFFICE_ID,
                   ROW_NUMBER() OVER (ORDER BY n.OVERFLOW_SEQUENCE_ORDER ASC) rn
              FROM OFFICE_THRESHOLD_CONFIG n
             WHERE n.DEPARTMENT = t.DEPARTMENT
               AND n.ACTIVE = 1
               AND n.OVERFLOW_SEQUENCE_ORDER > t.OVERFLOW_SEQUENCE_ORDER
        ) nxt WHERE nxt.rn = 1),
       t.UPDATED_BY = 'V71_migration',
       t.UPDATED_AT = SYSTIMESTAMP
 WHERE t.DEPARTMENT = 'RBIO'
   AND t.ACTIVE = 1
   AND t.OVERFLOW_TARGET_OFFICE IS NULL
   AND EXISTS (SELECT 1 FROM OFFICE_THRESHOLD_CONFIG n
                WHERE n.DEPARTMENT = t.DEPARTMENT
                  AND n.ACTIVE = 1
                  AND n.OVERFLOW_SEQUENCE_ORDER > t.OVERFLOW_SEQUENCE_ORDER);

COMMIT;
