-- V7: Phase 1 UST changes — withdrawal fields, appeal delay, feedback, FAQ, system config
-- Oracle version

-- ═══ COMPLAINTS: withdrawal fields ═══
ALTER TABLE COMPLAINTS ADD (
    withdrawal_reason VARCHAR2(500),
    withdrawal_date TIMESTAMP,
    withdrawn_by VARCHAR2(200)
);

-- ═══ APPEALS: reason for delay (31-60 day window) ═══
ALTER TABLE APPEALS ADD reason_for_delay VARCHAR2(500);

-- ═══ COMPLAINT_FEEDBACK ═══
CREATE TABLE COMPLAINT_FEEDBACK (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_number VARCHAR2(50) NOT NULL,
    overall_rating NUMBER(1) NOT NULL,
    ease_of_filing NUMBER(1) NOT NULL,
    timeliness_rating NUMBER(1),
    communication_rating NUMBER(1),
    satisfaction_rating NUMBER(1),
    grievance_redress_time NUMBER(1) NOT NULL,
    source_of_information VARCHAR2(100) NOT NULL,
    source_other_text VARCHAR2(500),
    cms_portal_awareness VARCHAR2(50) NOT NULL,
    feedback_text VARCHAR2(500),
    suggestions VARCHAR2(500),
    complainant_phone VARCHAR2(20),
    office_code VARCHAR2(20),
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_feedback_complaint UNIQUE (complaint_number)
);

CREATE INDEX idx_feedback_complaint ON COMPLAINT_FEEDBACK (complaint_number);
CREATE INDEX idx_feedback_phone ON COMPLAINT_FEEDBACK (complainant_phone);
CREATE INDEX idx_feedback_office ON COMPLAINT_FEEDBACK (office_code);

-- ═══ FAQ ═══
CREATE TABLE FAQ (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_key VARCHAR2(200) NOT NULL,
    answer_key VARCHAR2(200) NOT NULL,
    category VARCHAR2(100),
    sort_order NUMBER DEFAULT 0 NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX idx_faq_category ON FAQ (category);
CREATE INDEX idx_faq_sort ON FAQ (sort_order);

INSERT ALL
    INTO FAQ (question_key, answer_key, category, sort_order, is_active, created_at, updated_at) VALUES ('faq.q1.question', 'faq.q1.answer', 'GENERAL', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP)
    INTO FAQ (question_key, answer_key, category, sort_order, is_active, created_at, updated_at) VALUES ('faq.q2.question', 'faq.q2.answer', 'GENERAL', 2, 1, SYSTIMESTAMP, SYSTIMESTAMP)
    INTO FAQ (question_key, answer_key, category, sort_order, is_active, created_at, updated_at) VALUES ('faq.q3.question', 'faq.q3.answer', 'GENERAL', 3, 1, SYSTIMESTAMP, SYSTIMESTAMP)
    INTO FAQ (question_key, answer_key, category, sort_order, is_active, created_at, updated_at) VALUES ('faq.q4.question', 'faq.q4.answer', 'FILING', 4, 1, SYSTIMESTAMP, SYSTIMESTAMP)
    INTO FAQ (question_key, answer_key, category, sort_order, is_active, created_at, updated_at) VALUES ('faq.q5.question', 'faq.q5.answer', 'FILING', 5, 1, SYSTIMESTAMP, SYSTIMESTAMP)
    INTO FAQ (question_key, answer_key, category, sort_order, is_active, created_at, updated_at) VALUES ('faq.q6.question', 'faq.q6.answer', 'TRACKING', 6, 1, SYSTIMESTAMP, SYSTIMESTAMP)
    INTO FAQ (question_key, answer_key, category, sort_order, is_active, created_at, updated_at) VALUES ('faq.q7.question', 'faq.q7.answer', 'TRACKING', 7, 1, SYSTIMESTAMP, SYSTIMESTAMP)
    INTO FAQ (question_key, answer_key, category, sort_order, is_active, created_at, updated_at) VALUES ('faq.q8.question', 'faq.q8.answer', 'APPEAL', 8, 1, SYSTIMESTAMP, SYSTIMESTAMP)
    INTO FAQ (question_key, answer_key, category, sort_order, is_active, created_at, updated_at) VALUES ('faq.q9.question', 'faq.q9.answer', 'APPEAL', 9, 1, SYSTIMESTAMP, SYSTIMESTAMP)
    INTO FAQ (question_key, answer_key, category, sort_order, is_active, created_at, updated_at) VALUES ('faq.q10.question', 'faq.q10.answer', 'WITHDRAWAL', 10, 1, SYSTIMESTAMP, SYSTIMESTAMP)
SELECT 1 FROM DUAL;

-- ═══ SYSTEM_CONFIG ═══
CREATE TABLE SYSTEM_CONFIG (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR2(100) NOT NULL,
    config_value VARCHAR2(500) NOT NULL,
    description VARCHAR2(500),
    updated_by VARCHAR2(200),
    updated_at TIMESTAMP,
    CONSTRAINT uk_config_key UNIQUE (config_key)
);

INSERT ALL
    INTO SYSTEM_CONFIG (config_key, config_value, description, updated_at) VALUES ('timeline.complaint.filing_window_days', '365', 'Maximum days after incident to file a complaint', SYSTIMESTAMP)
    INTO SYSTEM_CONFIG (config_key, config_value, description, updated_at) VALUES ('timeline.appeal.filing_window_days', '30', 'Days after closure to file an appeal without delay reason', SYSTIMESTAMP)
    INTO SYSTEM_CONFIG (config_key, config_value, description, updated_at) VALUES ('timeline.appeal.extended_window_days', '60', 'Days after closure to file an appeal with delay reason', SYSTIMESTAMP)
    INTO SYSTEM_CONFIG (config_key, config_value, description, updated_at) VALUES ('timeline.re.response_deadline_days', '15', 'Days for RE to respond to a forwarded complaint', SYSTIMESTAMP)
    INTO SYSTEM_CONFIG (config_key, config_value, description, updated_at) VALUES ('timeline.sla.default_resolution_days', '30', 'Default SLA for complaint resolution', SYSTIMESTAMP)
SELECT 1 FROM DUAL;

-- ═══ CONFIG_AUDIT_LOG ═══
CREATE TABLE CONFIG_AUDIT_LOG (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR2(100) NOT NULL,
    old_value VARCHAR2(500),
    new_value VARCHAR2(500),
    changed_by VARCHAR2(200) NOT NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_config_audit_key ON CONFIG_AUDIT_LOG (config_key);
CREATE INDEX idx_config_audit_date ON CONFIG_AUDIT_LOG (changed_at);
