-- V80: ENTITY_OFFICE_NODAL_OFFICER — (regulated entity + Ombudsman office) → NO/PNO (UST773)
-- Oracle version (mirrors database/V82__entity_office_nodal_officer.sql;
-- the two directories' V-numbers are not in sync)
--
-- ═══ CONTRACT FOR THE ADMIN CRUD SCREEN ═══
-- This table is owned jointly: the resolver (NodalOfficerResolver) reads it, and the Ombudsman admin
-- maintenance screen owns create/update/deactivate of whole rows. Anything building against it must hold
-- to the following, because the resolver's correctness depends on all four points.
--
--   1. LOOKUP KEY IS ENTITY_NAME_NORMALIZED, NOT ENTITY_NAME.
--      COMPLAINTS.ENTITY_CODE stores entity *names* ("State Bank of India"), not short codes, and
--      REGULATED_ENTITIES has no code column. ENTITY_NAME_NORMALIZED must always be written as
--      RegulatedEntity.normalize(ENTITY_NAME) — uppercase, punctuation stripped, whitespace collapsed.
--      The resolver matches it with EQUALITY ONLY, never LIKE. This is the whole safety property: a fuzzy
--      match here would hand one bank's Nodal Officer contacts to a complaint filed against a different
--      bank, which is a cross-entity data leak, not a cosmetic bug. If the screen writes ENTITY_NAME
--      without recomputing ENTITY_NAME_NORMALIZED, the row becomes unreachable and every complaint for
--      that entity silently falls through to the Ombudsman Admin.
--
--   2. PROCESSING_OFFICE IS NULLABLE AND NULL IS MEANINGFUL.
--      NULL means "this contact set serves every office for this entity" — the national-desk case, so a
--      small entity needs one row rather than twenty-two. A non-NULL value must be the office name in
--      OFFICE_CODE_MASTER.OFFICE_NAME form ("Mumbai I", "New Delhi I"), which is what
--      ComplaintNumberGeneratorService.resolveOfficeName returns and what the workflow layer passes as
--      targetOffice. Office CODES ('013') will not match and must not be stored here.
--
--   3. RESOLUTION ORDER IS (entity, office) → (entity, NULL) → REGULATED_ENTITIES → PNO → Ombudsman Admin.
--      A row whose NODAL_OFFICER_NAME is blank does NOT stop the ladder; the resolver treats it as absent
--      and keeps going. So blanking a name is not a way to block resolution — deactivate the row instead.
--
--   4. DEACTIVATE, DO NOT DELETE. ACTIVE = 0 is excluded from resolution. NODAL_OFFICER_RECORDS rows
--      already created keep the contacts they copied, so deactivating here changes future resolutions
--      only; it does not retro-edit complaints already in flight.
--
-- Seeded empty on purpose. Inventing NO/PNO contacts for real banks would put fabricated names and email
-- addresses in front of officers who would then write to them; the rows must come from the admin screen.

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'ENTITY_OFFICE_NODAL_OFFICER';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE ENTITY_OFFICE_NODAL_OFFICER (
                ID                        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ENTITY_NAME               VARCHAR2(300) NOT NULL,
                ENTITY_NAME_NORMALIZED    VARCHAR2(300) NOT NULL,
                PROCESSING_OFFICE         VARCHAR2(100),
                NODAL_OFFICER_NAME        VARCHAR2(200),
                NODAL_OFFICER_DESIGNATION VARCHAR2(100),
                NODAL_OFFICER_EMAIL       VARCHAR2(200),
                NODAL_OFFICER_PHONE       VARCHAR2(20),
                PNO_NAME                  VARCHAR2(200),
                PNO_EMAIL                 VARCHAR2(200),
                PNO_PHONE                 VARCHAR2(20),
                ACTIVE                    NUMBER(1) DEFAULT 1 NOT NULL,
                CREATED_BY                VARCHAR2(100),
                CREATED_AT                TIMESTAMP,
                UPDATED_AT                TIMESTAMP
            )';
    END IF;

    -- One contact set per (entity, office). Without it, two racing admin edits leave two rows and the
    -- resolver's findFirst picks whichever the optimiser returns — so which officer receives the complaint
    -- would depend on row order, and would change between runs.
    --
    -- Oracle treats NULLs as distinct in a unique constraint, so this does NOT constrain the entity-wide
    -- (PROCESSING_OFFICE IS NULL) rows to one per entity. That is a known, accepted limit: the resolver
    -- uses findFirst for the NULL-office lookup, so a duplicate national row degrades to "an arbitrary one
    -- of two identical desks" rather than an error. Enforcing it would need a sentinel value, and a column
    -- that exists only to satisfy an index is not worth the confusion it causes operators.
    SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'UK_EONO_ENTITY_OFFICE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ENTITY_OFFICE_NODAL_OFFICER '
                       || 'ADD CONSTRAINT UK_EONO_ENTITY_OFFICE '
                       || 'UNIQUE (ENTITY_NAME_NORMALIZED, PROCESSING_OFFICE)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_EONO_ENTITY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_EONO_ENTITY ON ENTITY_OFFICE_NODAL_OFFICER(ENTITY_NAME_NORMALIZED)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_EONO_OFFICE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_EONO_OFFICE ON ENTITY_OFFICE_NODAL_OFFICER(PROCESSING_OFFICE)';
    END IF;
END;
/
