-- ============================================================
-- V82 — Per-office assignment strategy and its mappings
-- Session S3 (UST468-472). Oracle counterpart of MySQL V84.
-- ============================================================
--
-- See database/V84__office_assignment_strategy.sql for the full rationale. In brief:
--
--   * Each Ombudsman office chooses exactly ONE assignment logic — ROUND_ROBIN, ENTITY_MAPPING or
--     CATEGORY_MAPPING (UST468). Nothing like this existed: the only "strategy" was a global env var
--     read by no Java code, and cms-assignment-service has no entities or endpoints at all.
--   * Two tables, because the SELECTION (which logic) and the DATA (which subject to which officer)
--     have different lifecycles: switching strategies must not destroy the mappings.
--   * UQ_OAS_OFFICE enforces "one active logic per office" in the database. Two rows for one office is
--     a state the domain cannot answer — whichever the query returned first would decide, so one
--     complaint could route differently on two pods.
--   * office_id is OFFICE_CODE_MASTER.OFFICE_CODE, matching COMPLAINTS.RBIO_OFFICE_CODE and
--     OFFICE_THRESHOLD_CONFIG. Office NAMES are not used: the two masters disagree on them.
--   * Entity subject keys are NORMALISED names (upper case, punctuation stripped) because
--     REGULATED_ENTITIES has no code column and the complaint carries a free-text name. A raw name
--     would miss on any punctuation difference, and a missed mapping silently falls back to the
--     Ombudsman Admin.
--   * No seed data: every office starts unconfigured, which the resolver treats as ROUND_ROBIN, so this
--     migration changes no behaviour until a Super Admin opts an office in. Seeding would mean inventing
--     which officer handles which bank.
--
-- Re-running is safe: Oracle has no CREATE TABLE IF NOT EXISTS, so all DDL is guarded on USER_TABLES /
-- USER_INDEXES inside PL/SQL.
-- ============================================================

DECLARE
    PROCEDURE ddl_if_absent(p_kind VARCHAR2, p_name VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        IF p_kind = 'TABLE' THEN
            SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = p_name;
        ELSE
            SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = p_name;
        END IF;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;
BEGIN
    -- 1. The strategy selection: one row per office.
    ddl_if_absent('TABLE', 'OFFICE_ASSIGNMENT_STRATEGY', '
        CREATE TABLE OFFICE_ASSIGNMENT_STRATEGY (
            ID          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            OFFICE_ID   VARCHAR2(20)  NOT NULL,
            STRATEGY    VARCHAR2(30)  DEFAULT ''ROUND_ROBIN'' NOT NULL,
            ROLE_GROUP  VARCHAR2(50)  DEFAULT ''RBIO_OFFICER'' NOT NULL,
            UPDATED_BY  VARCHAR2(100),
            REASON      VARCHAR2(500),
            UPDATED_AT  TIMESTAMP(6),
            CONSTRAINT UQ_OAS_OFFICE UNIQUE (OFFICE_ID)
        )');
    ddl_if_absent('INDEX', 'IDX_OAS_STRATEGY',
        'CREATE INDEX IDX_OAS_STRATEGY ON OFFICE_ASSIGNMENT_STRATEGY (STRATEGY)');

    -- 2. The mapping data: subject -> officer, per office.
    ddl_if_absent('TABLE', 'OFFICE_ASSIGNMENT_MAPPING', '
        CREATE TABLE OFFICE_ASSIGNMENT_MAPPING (
            ID                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            OFFICE_ID         VARCHAR2(20)  NOT NULL,
            MAPPING_TYPE      VARCHAR2(20)  NOT NULL,
            SUBJECT_KEY       VARCHAR2(250) NOT NULL,
            SUBJECT_LABEL     VARCHAR2(250),
            TARGET_OFFICER_ID VARCHAR2(200) NOT NULL,
            ACTIVE            NUMBER(1)     DEFAULT 1 NOT NULL,
            UPDATED_BY        VARCHAR2(100),
            UPDATED_AT        TIMESTAMP(6),
            CONSTRAINT UQ_OAM_OFFICE_TYPE_SUBJECT UNIQUE (OFFICE_ID, MAPPING_TYPE, SUBJECT_KEY)
        )');
    -- The resolver's hot path.
    ddl_if_absent('INDEX', 'IDX_OAM_LOOKUP',
        'CREATE INDEX IDX_OAM_LOOKUP ON OFFICE_ASSIGNMENT_MAPPING '
        || '(OFFICE_ID, MAPPING_TYPE, SUBJECT_KEY, ACTIVE)');
    -- Supports "which subjects does this officer hold?", needed before deactivating them.
    ddl_if_absent('INDEX', 'IDX_OAM_OFFICER',
        'CREATE INDEX IDX_OAM_OFFICER ON OFFICE_ASSIGNMENT_MAPPING (TARGET_OFFICER_ID)');

    COMMIT;
END;
/
