-- ============================================================
-- V85 — RBIO staff profile: designation, office posting, leave dates, closure eligibility
-- Session S1 (UST443-448, UST451-455, UST629-631)
-- Oracle counterpart of MySQL V87. The two directories' V-numbers are NOT in sync.
-- ============================================================
--
-- WHY THIS TABLE HAS TO EXIST
--
--   There is no RBIO staff master anywhere in this system. Identity lives in Keycloak, and the only
--   officer-shaped table is cms-workflow-service's WF_OFFICER_POOL (nine columns: USER_ID, DISPLAY_NAME,
--   ROLE_GROUP, REGIONAL_OFFICE, IS_ACTIVE, IS_ON_LEAVE, CURRENT_WORKLOAD, MAX_WORKLOAD). Four things
--   the stories require have nowhere to live: designation (UST443/444), a real office FK for territory
--   scoping (UST440 — REGIONAL_OFFICE is free text with no FK), leave FROM/TO dates (UST447/448/451 —
--   leave is a bare boolean with no dates and no record of who set it), and reviewer closure
--   eligibility (UST629-631, zero occurrences repo-wide before this).
--
--   Keycloak user attributes were the alternative and are rejected deliberately: attribute writes are a
--   read-modify-write of the whole user, so concurrent sessions lose each other's updates, and
--   Keycloak 26's unmanagedAttributePolicy silently drops unknown attributes. A statutory permission
--   flag must not depend on that.
--
-- WHY IT DOES NOT DUPLICATE WF_OFFICER_POOL
--
--   This is a PROFILE keyed on the Keycloak user id, not a second assignment pool. Workload and the
--   round-robin pointer stay in WF_OFFICER_POOL, owned by another session. Duplicating IS_ON_LEAVE here
--   would create two answers to "is this officer on leave" — the same divergence that made the RE
--   response window wrong in two services simultaneously. IS_ON_LEAVE stays authoritative in
--   WF_OFFICER_POOL; this table adds the DATES and the attribution the boolean cannot carry.
--
-- NUMBER(1) is used for the CHAR flags' Oracle equivalent only where the entity maps a boolean;
-- CLOSURE_ELIGIBLE and IS_ACTIVE stay CHAR(1)'Y'/'N' to match the RBIO_STATUS_MASTER convention
-- already established in this schema.
--
-- Everything is guarded on USER_TABLES / USER_TAB_COLUMNS / USER_INDEXES so a re-run is safe. Wave 2
-- replays these against a clean database, and that replay is the only proof this SQL matches what
-- Hibernate's ddl-auto actually created.
-- ============================================================

DECLARE
    PROCEDURE add_table(p_table VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_index(p_index VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_constraint(p_constraint VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = p_constraint;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_config(p_key VARCHAR2, p_value VARCHAR2, p_description VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM SYSTEM_CONFIG WHERE CONFIG_KEY = p_key;
        IF v_count = 0 THEN
            INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_BY, UPDATED_AT)
            VALUES (p_key, p_value, p_description, 'V85_migration', SYSTIMESTAMP);
        END IF;
    END;
BEGIN
    -- ─────────────────────────────────────────────────────────
    -- 1. The profile table
    -- ─────────────────────────────────────────────────────────
    add_table('RBIO_STAFF_PROFILE', '
        CREATE TABLE RBIO_STAFF_PROFILE (
            ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
            USER_ID             VARCHAR2(200)  NOT NULL,
            DISPLAY_NAME        VARCHAR2(250),
            EMAIL               VARCHAR2(250),
            DESIGNATION         VARCHAR2(150),
            OFFICE_CODE         VARCHAR2(10),
            PRIMARY_ROLE        VARCHAR2(50),
            LEAVE_FROM_DATE     DATE,
            LEAVE_TO_DATE       DATE,
            LEAVE_SET_BY        VARCHAR2(200),
            LEAVE_SET_AT        TIMESTAMP,
            CLOSURE_ELIGIBLE    CHAR(1)        DEFAULT ''N'' NOT NULL,
            IS_ACTIVE           CHAR(1)        DEFAULT ''Y'' NOT NULL,
            CREATED_BY          VARCHAR2(200),
            CREATED_AT          TIMESTAMP,
            UPDATED_BY          VARCHAR2(200),
            UPDATED_AT          TIMESTAMP,
            CONSTRAINT PK_RBIO_STAFF_PROFILE PRIMARY KEY (ID)
        )');

    -- One profile per Keycloak user. This is the multi-pod guard: two concurrent "create user" requests
    -- for the same username cannot both land, whatever the application checked first.
    add_constraint('UK_RSP_USER_UNIQUE',
        'ALTER TABLE RBIO_STAFF_PROFILE ADD CONSTRAINT UK_RSP_USER_UNIQUE UNIQUE (USER_ID)');

    add_index('IDX_RSP_OFFICE',
        'CREATE INDEX IDX_RSP_OFFICE ON RBIO_STAFF_PROFILE (OFFICE_CODE)');
    add_index('IDX_RSP_ROLE',
        'CREATE INDEX IDX_RSP_ROLE ON RBIO_STAFF_PROFILE (PRIMARY_ROLE)');
    add_index('IDX_RSP_CLOSURE',
        'CREATE INDEX IDX_RSP_CLOSURE ON RBIO_STAFF_PROFILE (CLOSURE_ELIGIBLE)');

    -- ─────────────────────────────────────────────────────────
    -- 2. Audit of staff-administration actions
    -- ─────────────────────────────────────────────────────────
    -- UST452-455 and UST630 require an audit entry per reassignment and per closure-eligibility change,
    -- naming old owner, new owner, acting user and timestamp. No existing table can carry it:
    -- AUDIT_LOG.COMPLAINT_NUMBER is NOT NULL so it cannot represent a user-scoped change,
    -- AA_ASSIGNMENT_AUDIT is AA-namespaced with an APPEAL_NUMBER column, and CONFIG_AUDIT_LOG has six
    -- columns and no description.
    --
    -- PERFORMED_BY is resolved from the JWT by the service, never from the request body.
    add_table('RBIO_STAFF_AUDIT', '
        CREATE TABLE RBIO_STAFF_AUDIT (
            ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
            ACTION              VARCHAR2(50)   NOT NULL,
            SUBJECT_USER_ID     VARCHAR2(200),
            COMPLAINT_NUMBER    VARCHAR2(50),
            OLD_VALUE           VARCHAR2(500),
            NEW_VALUE           VARCHAR2(500),
            FIELD_NAME          VARCHAR2(60),
            DESCRIPTION         VARCHAR2(1000),
            REASON              VARCHAR2(1000),
            PERFORMED_BY        VARCHAR2(200)  NOT NULL,
            PERFORMED_BY_ROLE   VARCHAR2(50),
            PERFORMED_AT        TIMESTAMP      NOT NULL,
            CONSTRAINT PK_RBIO_STAFF_AUDIT PRIMARY KEY (ID)
        )');

    add_index('IDX_RSA_SUBJECT',
        'CREATE INDEX IDX_RSA_SUBJECT ON RBIO_STAFF_AUDIT (SUBJECT_USER_ID)');
    add_index('IDX_RSA_ACTION',
        'CREATE INDEX IDX_RSA_ACTION ON RBIO_STAFF_AUDIT (ACTION)');
    add_index('IDX_RSA_AT',
        'CREATE INDEX IDX_RSA_AT ON RBIO_STAFF_AUDIT (PERFORMED_AT)');
    add_index('IDX_RSA_COMPLAINT',
        'CREATE INDEX IDX_RSA_COMPLAINT ON RBIO_STAFF_AUDIT (COMPLAINT_NUMBER)');

    -- ─────────────────────────────────────────────────────────
    -- 3. Configuration
    -- ─────────────────────────────────────────────────────────
    -- 50 matches the existing cms.reassign.bulk.max_records cap so the two bulk paths do not disagree
    -- about what "too many" means.
    add_config('rbio.staff.bulk.max_records', '50',
        'Maximum staff accounts a single bulk activate/leave/closure-eligibility action may affect');

    add_config('rbio.staff.closure_eligibility.default', 'N',
        'Closure-eligibility flag applied to a newly created Reviewer account (UST629). N per the story.');

    COMMIT;
END;
/
