-- ============================================================
-- V89 — COMMUNICATION_OUTBOX + configurable RBIO compensation caps
-- Session S4 (UST504-509, 520, 541-542, 549, 757, 763-764, 506)
-- Oracle counterpart of MySQL V91. The two directories' V-numbers are NOT in sync.
-- ============================================================
--
-- The rationale is recorded in full in the MySQL counterpart (database/V91). In brief:
--
-- PART 1 — COMMUNICATION_OUTBOX. Outbound closure communication had no durable record. The CEPC
--   auto-dispatch path generated letter bytes, discarded them, stamped CLOSURE_LETTER_SENT_AT and logged,
--   so the database recorded "sent" for a message never handed to any transport; SMS was a log-only TODO.
--   Persisting intent first and dispatching later keeps the obligation alive across a gateway outage and
--   separates "failed to decide to communicate" from "failed to deliver". BODY and SMS_TEXT hold the
--   RESOLVED text as evidence, because a template edited later must not change what the system says it
--   told a citizen earlier. SENT=1 means the transport accepted the message, NOT that anyone received it —
--   the only adapter today delivers nothing.
--
-- PART 2 — Compensation caps move from private static final constants into SYSTEM_CONFIG. Seeded to
--   exactly the values the code already used, so this migration cannot change an award outcome; amending a
--   statutory figure becomes a one-row UPDATE instead of a release. Follows the precedent of
--   V54__aa_order_statutory_guards.sql.
--
-- Everything is guarded on USER_TABLES / USER_INDEXES so a re-run is safe. Wave 2 replays this against a
-- clean database, and that replay is the only proof this SQL matches what Hibernate's ddl-auto created.
-- ============================================================

DECLARE
    PROCEDURE add_table(p_table VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_index(p_index VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE seed_config(p_key VARCHAR2, p_value VARCHAR2, p_desc VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM SYSTEM_CONFIG WHERE CONFIG_KEY = p_key;
        IF v_count = 0 THEN
            INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_BY, UPDATED_AT)
            VALUES (p_key, p_value, p_desc, 'V89', SYSTIMESTAMP);
        END IF;
    END;
BEGIN
    add_table('COMMUNICATION_OUTBOX', '
        CREATE TABLE COMMUNICATION_OUTBOX (
            ID                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
            COMMUNICATION_TYPE VARCHAR2(60)  NOT NULL,
            CHANNEL            VARCHAR2(20)  NOT NULL,
            TEMPLATE_ID        NUMBER(19),
            RECIPIENT          VARCHAR2(320) NOT NULL,
            SENDER             VARCHAR2(320),
            SUBJECT            VARCHAR2(500),
            BODY               CLOB,
            SMS_TEXT           VARCHAR2(1000),
            LANGUAGE           VARCHAR2(10),
            RELATED_REFERENCE  VARCHAR2(50),
            SENT               NUMBER(1) DEFAULT 0 NOT NULL,
            SENT_AT            TIMESTAMP(6),
            ATTEMPT_COUNT      NUMBER(10) DEFAULT 0 NOT NULL,
            LAST_ERROR         VARCHAR2(1000),
            CREATED_AT         TIMESTAMP(6),
            CONSTRAINT PK_COMMUNICATION_OUTBOX PRIMARY KEY (ID)
        )');

    -- The sender's queue predicate; without it the drain full-scans a table that only ever grows.
    add_index('IDX_COMM_OUTBOX_SENT',
              'CREATE INDEX IDX_COMM_OUTBOX_SENT ON COMMUNICATION_OUTBOX(SENT)');

    -- "What was this complainant told, and when" — the audit question this table exists to answer.
    add_index('IDX_COMM_OUTBOX_COMPLAINT',
              'CREATE INDEX IDX_COMM_OUTBOX_COMPLAINT ON COMMUNICATION_OUTBOX(RELATED_REFERENCE)');

    add_index('IDX_COMM_OUTBOX_CHANNEL',
              'CREATE INDEX IDX_COMM_OUTBOX_CHANNEL ON COMMUNICATION_OUTBOX(CHANNEL)');

    add_index('IDX_COMM_OUTBOX_CREATED',
              'CREATE INDEX IDX_COMM_OUTBOX_CREATED ON COMMUNICATION_OUTBOX(CREATED_AT)');

    -- Values identical to the previously hardcoded constants: behaviour-neutral by construction.
    seed_config('cms.rbio.compensation.max_consequential_loss', '3000000',
                'RBIO cap on consequential-loss compensation (rupees). Seeded to the value previously hardcoded in RbioCompensationService; provenance unverified, see V54.');
    seed_config('cms.rbio.compensation.max_time_harassment', '300000',
                'RBIO cap on time/mental-agony/harassment compensation (rupees). Seeded to the previously hardcoded value; provenance unverified.');
    -- Deliberately NOT the sum of the two caps above; the 3300000 total in CompensationPrecedentService
    -- was the outlier and has been removed.
    seed_config('cms.rbio.compensation.max_combined', '3000000',
                'RBIO cap on combined compensation (rupees). Deliberately equal to the consequential-loss cap, not the sum of the component caps.');
    seed_config('cms.rbio.compensation.band_low_upto', '100000',
                'Upper bound of the LOW compensation reporting band (rupees).');
    seed_config('cms.rbio.compensation.band_medium_upto', '1000000',
                'Upper bound of the MEDIUM compensation reporting band (rupees).');
    seed_config('cms.rbio.compensation.band_high_upto', '2000000',
                'Upper bound of the HIGH compensation reporting band (rupees). Anything above is MAXIMUM.');
END;
/
