-- ============================================================
-- V90 — closure communication gate, IMPLEADED_PARTY, award/advisory dates
-- Session S4 (UST504-509, 520, 536-538, 543-546, 548, 576, 757, 762-764, 767)
-- Oracle counterpart of MySQL V92. The two directories' V-numbers are NOT in sync.
-- ============================================================
--
-- Full rationale is recorded in the MySQL counterpart (database/V92). In brief:
--
-- DATE_OF_SENDING — the closure dialog POSTed this on every closure and the server never read it; a grep
--   of cms-backend for "dateOfSending" returned nothing, so it was silently discarded and the signed letter
--   never left the browser. Any direct API call therefore closed a complaint with no letter, no send date
--   and no email to the complainant. Write-once in the service, because UST757/763 require it to be
--   non-editable once recorded.
--
-- AWARD_PASSED_DATE — distinct from ADJUDICATION_DATE, which is written by both ADJUDICATION_AWARD and
--   ADJUDICATION_REJECT and so cannot identify an award. The implemented / not-implemented / lapse dates
--   did not exist anywhere in the repository.
--
-- ADVISORY_TEXT / ADVISORY_ISSUED_AT — already declared in this directory (V4/V5) but missing from the
--   MySQL side; repeated here as guarded no-ops so both dialects stay in step.
--
-- IMPLEADED_PARTY — impleading only appended to a CSV column, which cannot carry per-party Nodal Officer
--   contacts, clause, compensation or completeness state, and discarded the PARTY_TYPE the UI collected.
--   The CSV column is deliberately retained for existing readers.
--
-- The closure-gate switches are seeded 'false' (unenforced), following V54__aa_order_statutory_guards.sql.
--   Arming them changes citizen-facing legal behaviour and is a one-row UPDATE after sign-off, so this
--   migration is behaviour-neutral and cannot break go-live.
--
-- Everything is guarded on USER_TABLES / USER_TAB_COLUMNS / USER_INDEXES so a re-run is safe, and every new
-- column is NULLABLE as required on a shared ddl-auto database.
-- ============================================================

DECLARE
    PROCEDURE add_table(p_table VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_column(p_table VARCHAR2, p_column VARCHAR2, p_sql VARCHAR2) IS
        v_tab NUMBER;
        v_col NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_tab FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_tab = 0 THEN
            RETURN;
        END IF;
        SELECT COUNT(*) INTO v_col FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_column;
        IF v_col = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_index(p_index VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE seed_config(p_key VARCHAR2, p_value VARCHAR2, p_desc VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM SYSTEM_CONFIG WHERE CONFIG_KEY = p_key;
        IF v_count = 0 THEN
            INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_BY, UPDATED_AT)
            VALUES (p_key, p_value, p_desc, 'V90', SYSTIMESTAMP);
        END IF;
    END;
BEGIN
    add_column('COMPLAINTS', 'DATE_OF_SENDING',
               'ALTER TABLE COMPLAINTS ADD (DATE_OF_SENDING DATE)');
    add_column('COMPLAINTS', 'AWARD_PASSED_DATE',
               'ALTER TABLE COMPLAINTS ADD (AWARD_PASSED_DATE DATE)');
    add_column('COMPLAINTS', 'AWARD_IMPLEMENTED_DATE',
               'ALTER TABLE COMPLAINTS ADD (AWARD_IMPLEMENTED_DATE DATE)');
    add_column('COMPLAINTS', 'AWARD_NOT_IMPLEMENTED_DATE',
               'ALTER TABLE COMPLAINTS ADD (AWARD_NOT_IMPLEMENTED_DATE DATE)');
    add_column('COMPLAINTS', 'AWARD_LAPSE_DATE',
               'ALTER TABLE COMPLAINTS ADD (AWARD_LAPSE_DATE DATE)');

    -- Present since V4/V5 in this directory; guarded so this is a no-op here but keeps both dialects aligned.
    add_column('COMPLAINTS', 'ADVISORY_TEXT',
               'ALTER TABLE COMPLAINTS ADD (ADVISORY_TEXT CLOB)');
    add_column('COMPLAINTS', 'ADVISORY_ISSUED_AT',
               'ALTER TABLE COMPLAINTS ADD (ADVISORY_ISSUED_AT TIMESTAMP(6))');

    add_table('IMPLEADED_PARTY', '
        CREATE TABLE IMPLEADED_PARTY (
            ID                      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
            COMPLAINT_NUMBER        VARCHAR2(50)  NOT NULL,
            PARTY_NAME              VARCHAR2(200) NOT NULL,
            PARTY_TYPE              VARCHAR2(100),
            REGULATED_ENTITY_ID     NUMBER(19),
            NODAL_OFFICER_RECORD_ID NUMBER(19),
            DATA_STATUS             VARCHAR2(40)  NOT NULL,
            CLOSURE_CLAUSE          VARCHAR2(40),
            COMPENSATION_AMOUNT     NUMBER(15,2),
            IMPLEAD_REASON          VARCHAR2(1000),
            IMPLEADED_BY            VARCHAR2(200),
            IMPLEADED_BY_ROLE       VARCHAR2(100),
            IMPLEADED_AT            TIMESTAMP(6),
            CONSTRAINT PK_IMPLEADED_PARTY PRIMARY KEY (ID)
        )');

    add_index('IDX_IMPLEAD_COMPLAINT',
              'CREATE INDEX IDX_IMPLEAD_COMPLAINT ON IMPLEADED_PARTY(COMPLAINT_NUMBER)');
    -- The closure gate queries on status, so it must not full-scan.
    add_index('IDX_IMPLEAD_STATUS',
              'CREATE INDEX IDX_IMPLEAD_STATUS ON IMPLEADED_PARTY(DATA_STATUS)');

    seed_config('cms.rbio.closure.require_send_date', 'false',
                'When true, an RBIO closure is refused until the Date of Sending of the closure letter is recorded (UST509). Seeded false: arming changes citizen-facing legal behaviour and needs sign-off.');
    seed_config('cms.rbio.closure.require_signed_letter', 'false',
                'When true, an RBIO closure is refused until an attachment with documentType=SIGNED_LETTER exists (UST507-508). Seeded false pending sign-off.');
    seed_config('cms.rbio.closure.require_complainant_email', 'false',
                'When true, a direct RBIO closure is refused when the complainant has no email address, routing back via Facilitation/Rejection or Decision instead (UST549, UST764). Seeded false pending sign-off.');
    seed_config('cms.communication.outbox.dispatch_enabled', 'true',
                'When true, the communication outbox scheduler drains queued email/SMS. Defaults TRUE, unlike the statutory guards: a queued closure communication never drained is an obligation silently unmet, and the transport is a no-op adapter until a real gateway is configured.');
END;
/
