-- ============================================================
-- V93 — Conciliation meetings as an append-only history, with participants
-- Session S5 (UST496-503, 643-651). Oracle counterpart of MySQL V95.
-- ============================================================
--
-- See database/V95__rbio_meeting_history.sql for the full rationale. In brief:
--
--   * Meeting particulars had two homes: COMPLAINTS.CONCILIATION_DATE (a single scalar) and the free
--     text of a COMPLAINT_TIMELINE row. Both are overwritten by the next schedule, so "the meeting was
--     moved twice" and "the meeting was always on this date" were the same stored fact — which UST502-503
--     ("PREVIOUS meeting details RETAINED") cannot be built on.
--   * In practice nothing was persisted at all: the side effect read `meetingDate` while the only client
--     sent `hearingDate`, so CONCILIATION_DATE stayed NULL after every schedule.
--   * RBIO_MEETING is append-only, modelled on APPEAL_HEARING: superseding a row stamps SUPERSEDED_AT /
--     SUPERSEDED_BY_ID on it, a LINKAGE and never a rewrite. The operative meeting is the one row per
--     complaint with SUPERSEDED_AT IS NULL; an outcome is recorded by APPENDING a COMPLETED row.
--   * The meeting itself happens OUTSIDE the application (UST501), so there is no attendance/join column:
--     PARTICIPANT_CONFIRMED is an officer's assertion, not something the system observes.
--   * MEETING_DATE and MEETING_TIME are separate because both are independently mandatory (UST496) and a
--     single timestamp cannot express "date supplied, time missing".
--   * The six-entity cap (UST498) is NOT re-implemented here — RbioAdditionalEntityService owns it.
--   * BLOCKS_MEETING is a flag on the status master, not a from-status enumeration, because the
--     requirement is a NOT-IN: enumerating "every status except six" would silently omit any status a
--     later session adds.
--
-- All columns nullable except the identifying ones (shared ddl-auto database). Nothing is backfilled:
-- inventing a meeting history would assert meetings that never happened.
--
-- Re-running is safe: guarded on USER_TABLES / USER_TAB_COLUMNS / USER_INDEXES.
-- ============================================================

DECLARE
    PROCEDURE add_table(p_table VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_column(p_table VARCHAR2, p_column VARCHAR2, p_definition VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_column;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_column || ' ' || p_definition || ')';
        END IF;
    END;

    PROCEDURE add_index(p_index VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;
BEGIN
    -- ── 1. The meeting event history ──
    add_table('RBIO_MEETING',
        'CREATE TABLE RBIO_MEETING ('
        || ' ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
        || ' COMPLAINT_NUMBER VARCHAR2(50) NOT NULL,'
        || ' SEQUENCE_NO NUMBER(10),'
        || ' EVENT_TYPE VARCHAR2(20) NOT NULL,'
        || ' MEETING_DATE DATE,'
        || ' MEETING_TIME VARCHAR2(10),'
        || ' PARTICIPANTS VARCHAR2(20),'
        || ' MEETING_MODE VARCHAR2(20),'
        || ' MEETING_VENUE VARCHAR2(500),'
        || ' RESCHEDULE_REASON VARCHAR2(1000),'
        || ' ENTITY_ACCEPTED CHAR(1),'
        || ' MINUTES_OF_MEETING CLOB,'
        || ' SUPERSEDED_AT TIMESTAMP,'
        || ' SUPERSEDED_BY_ID NUMBER,'
        || ' PERFORMED_BY VARCHAR2(200),'
        || ' PERFORMED_BY_ROLE VARCHAR2(50),'
        || ' PERFORMED_AT TIMESTAMP,'
        || ' CREATED_AT TIMESTAMP)');

    add_index('IDX_RBIO_MEETING_COMPLAINT',
        'CREATE INDEX IDX_RBIO_MEETING_COMPLAINT ON RBIO_MEETING (COMPLAINT_NUMBER)');
    add_index('IDX_RBIO_MEETING_ACTIVE',
        'CREATE INDEX IDX_RBIO_MEETING_ACTIVE ON RBIO_MEETING (COMPLAINT_NUMBER, SUPERSEDED_AT)');
    add_index('IDX_RBIO_MEETING_DATE',
        'CREATE INDEX IDX_RBIO_MEETING_DATE ON RBIO_MEETING (MEETING_DATE)');

    -- ── 2. Additional entity participants (UST498) ──
    -- PARTICIPANT_CONFIRMED is what "displays all confirmed attendee entities" reads: an invitee is not
    -- an attendee, and conflating them would let the MOM letter assert attendance nobody confirmed.
    add_table('RBIO_MEETING_PARTICIPANT',
        'CREATE TABLE RBIO_MEETING_PARTICIPANT ('
        || ' ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
        || ' MEETING_ID NUMBER,'
        || ' COMPLAINT_NUMBER VARCHAR2(50) NOT NULL,'
        || ' PARTICIPANT_TYPE VARCHAR2(20),'
        || ' PARTICIPANT_NAME VARCHAR2(250) NOT NULL,'
        || ' ENTITY_CODE VARCHAR2(50),'
        || ' PARTICIPANT_EMAIL VARCHAR2(320),'
        || ' PARTICIPANT_CONFIRMED CHAR(1),'
        || ' ADDED_BY VARCHAR2(200),'
        || ' CREATED_AT TIMESTAMP)');

    add_index('IDX_RBIO_MTG_PART_MEETING',
        'CREATE INDEX IDX_RBIO_MTG_PART_MEETING ON RBIO_MEETING_PARTICIPANT (MEETING_ID)');
    add_index('IDX_RBIO_MTG_PART_COMPLAINT',
        'CREATE INDEX IDX_RBIO_MTG_PART_COMPLAINT ON RBIO_MEETING_PARTICIPANT (COMPLAINT_NUMBER)');

    -- ── 3. Which statuses forbid a meeting (UST497, 643, 646, 649) ──
    add_column('RBIO_STATUS_MASTER', 'BLOCKS_MEETING', 'CHAR(1)');

    -- Set by STATUS_CODE, never by label: labels are localised and an English match finds none of the
    -- translated rows.
    UPDATE RBIO_STATUS_MASTER
       SET BLOCKS_MEETING = 'Y'
     WHERE STATUS_CODE IN ('ADVISORY_COMPLIED', 'SETTLED', 'WITHDRAWN',
                           'REJECTED', 'AWARD_PASSED', 'OMBUDSMAN_DECISION');

    -- Explicitly allowed rather than left NULL, so the server can tell "not configured" from "allowed"
    -- and fail closed on the former.
    UPDATE RBIO_STATUS_MASTER
       SET BLOCKS_MEETING = 'N'
     WHERE BLOCKS_MEETING IS NULL;

    add_index('IDX_RBIO_STATUS_BLOCKS_MTG',
        'CREATE INDEX IDX_RBIO_STATUS_BLOCKS_MTG ON RBIO_STATUS_MASTER (BLOCKS_MEETING)');

    COMMIT;
END;
/

-- ─────────────────────────────────────────────────────────────
-- 4. The MOM letter template (UST500, 644, 647, 650)
-- ─────────────────────────────────────────────────────────────
-- Reuses the CommunicationTemplate mechanism S4's closure letters use rather than adding a second letter
-- pipeline. NOTE THE DOUBLE BRACES: CommunicationTemplateService compiles Pattern "\{\{(\w+)}}", so the
-- single-brace {placeholders} used by the legacy V5 seed rows never substitute — a letter built that way
-- reaches the citizen with literal {complaintNumber} in it.
--
-- SCHEME NAME. 'Reserve Bank - Integrated Ombudsman Scheme, 2021' is correct and current. No
-- '(as amended 2026)' text appears here: that amendment does not exist, and asserting it in a document a
-- citizen relies on to compute an appeal window is a legal-text defect.
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM COMMUNICATION_TEMPLATES
     WHERE TRIGGER_CONDITION = 'MEETING_MINUTES';

    IF v_count = 0 THEN
        INSERT INTO COMMUNICATION_TEMPLATES
            (TEMPLATE_NAME, MODE, TRIGGER_CONDITION, SCHEME_VERSION, SUBJECT_TEMPLATE, BODY_TEMPLATE,
             DESCRIPTION, CATEGORY, ACTIVE, CREATED_BY, CREATED_AT, UPDATED_AT)
        VALUES ('Minutes of Meeting', 'LETTER', 'MEETING_MINUTES', 'BOTH',
            'Minutes of Meeting - Complaint {{complaintNumber}}',
            '<p>Reserve Bank of India - Office of the Ombudsman</p>'
            || '<p><b>MINUTES OF MEETING</b></p>'
            || '<p>Complaint Number: {{complaintNumber}}<br/>'
            || 'Complainant: {{complainantName}}<br/>'
            || 'Regulated Entity: {{entityName}}</p>'
            || '<p>Meeting Date: {{meetingDate}}<br/>'
            || 'Meeting Time: {{meetingTime}}<br/>'
            || 'Mode: {{meetingMode}}<br/>'
            || 'Venue: {{meetingVenue}}</p>'
            || '<p>Participants: {{participants}}</p>'
            || '<p>Attendees confirmed: {{confirmedParticipants}}</p>'
            || '<p><b>Minutes</b></p><p>{{minutesOfMeeting}}</p>'
            || '<p>Entity acceptance of the settlement discussed: {{entityAccepted}}</p>'
            || '<p>Recorded by: {{performedBy}} ({{performedByRole}})<br/>'
            || 'Recorded on: {{recordedAt}}</p>'
            || '<p>Issued under the Reserve Bank - Integrated Ombudsman Scheme, 2021.</p>',
            'Minutes of Meeting letter for an RBIO conciliation meeting (UST500). Rendered by MinutesOfMeetingLetterService through the shared CommunicationTemplate pipeline.',
            'MEETING', 1, 'V93_migration', SYSTIMESTAMP, SYSTIMESTAMP);
    END IF;

    COMMIT;
END;
/
