-- ============================================================
-- V96 — Report access roles + the report column registry
-- Session S7 (UST613, UST615, UST669, UST670)
-- Oracle counterpart of MySQL V98. The two directories' V-numbers are NOT in sync.
--
-- NOTE ON V-NUMBERING: this session was allotted Oracle V89-V93, but V89/V90/V93/V94/V95 were
-- already taken on disk by parallel sessions. V96-V100 is the next free block in this tree.
--
-- Rationale for both tables is documented at length in the MySQL counterpart (database/V98). The
-- two points that bear repeating because they are security-relevant:
--
--   1. REPORT_ACCESS_ROLE's ABSENCE currently GRANTS permission. The Angular screen swallows the
--      404 from the missing endpoint (report-builder.component.ts:247) and its canExport computed
--      then falls through to `return true`. So "no rows" reads as "everyone may export", behind a
--      reassuring "No access roles configured" empty state.
--   2. REPORT_COLUMN_REGISTRY seeds only the ELEVEN columns that demonstrably exist. UST613 asks
--      for 62, each mapped per the "BRD Format and Logic Sheet", and that sheet is NOT in this
--      repository. The mechanism is built so the remaining columns are INSERTs, not Java edits;
--      inventing 52 column definitions would be fabricating a regulator-facing specification.
--
-- Everything is guarded on USER_TABLES / USER_INDEXES / USER_CONSTRAINTS so a re-run is safe.
-- ============================================================

DECLARE
    PROCEDURE add_table(p_table VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_index(p_index VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_access_role(p_type VARCHAR2, p_role VARCHAR2,
                              p_view VARCHAR2, p_export VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM REPORT_ACCESS_ROLE
         WHERE REPORT_TYPE = p_type AND ROLE_NAME = p_role;
        IF v_count = 0 THEN
            INSERT INTO REPORT_ACCESS_ROLE
                (REPORT_TYPE, ROLE_NAME, CAN_VIEW, CAN_EXPORT, CREATED_BY, CREATED_AT)
            VALUES (p_type, p_role, p_view, p_export, 'V96_MIGRATION', SYSTIMESTAMP);
        END IF;
    END;

    PROCEDURE add_column_def(p_key VARCHAR2, p_field VARCHAR2, p_path VARCHAR2,
                             p_type VARCHAR2, p_order NUMBER) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM REPORT_COLUMN_REGISTRY WHERE COLUMN_KEY = p_key;
        IF v_count = 0 THEN
            INSERT INTO REPORT_COLUMN_REGISTRY
                (COLUMN_KEY, FIELD_NAME, JPA_PATH, VALUE_TYPE, DISPLAY_ORDER, IS_DEFAULT, IS_ACTIVE)
            VALUES (p_key, p_field, p_path, p_type, p_order, 'Y', 'Y');
        END IF;
    END;
BEGIN
    -- ─────────────────────────────────────────────────────────
    -- 1. REPORT_ACCESS_ROLE
    -- ─────────────────────────────────────────────────────────
    add_table('REPORT_ACCESS_ROLE', '
        CREATE TABLE REPORT_ACCESS_ROLE (
            ID          NUMBER GENERATED BY DEFAULT AS IDENTITY,
            REPORT_TYPE VARCHAR2(50)  NOT NULL,
            ROLE_NAME   VARCHAR2(50)  NOT NULL,
            CAN_VIEW    CHAR(1)       DEFAULT ''Y'' NOT NULL,
            CAN_EXPORT  CHAR(1)       DEFAULT ''N'' NOT NULL,
            CREATED_BY  VARCHAR2(200),
            CREATED_AT  TIMESTAMP,
            UPDATED_BY  VARCHAR2(200),
            UPDATED_AT  TIMESTAMP,
            CONSTRAINT PK_REPORT_ACCESS_ROLE PRIMARY KEY (ID),
            CONSTRAINT UK_REPORT_ACCESS_ROLE UNIQUE (REPORT_TYPE, ROLE_NAME)
        )');

    add_index('IDX_REPORT_ACCESS_ROLE_NAME',
        'CREATE INDEX IDX_REPORT_ACCESS_ROLE_NAME ON REPORT_ACCESS_ROLE (ROLE_NAME)');

    -- UST615/669 role list. CAN_EXPORT='N' encodes "view-only" for CEPD Admin and AA Admin exactly
    -- as the stories word it. AA_SECRETARIAT is a DISTINCT row from AA_ADMIN with full view+export,
    -- per UST669's explicit statement that the two are not the same actor.
    --
    -- FLAGGED, NOT RESOLVED: UST615 lists Secretary as a report viewer while UST655 (session S3)
    -- removes Secretary as an assignment target. Those may well both be intended — "may view
    -- reports" and "may be assigned complaints" are different capabilities — but the apparent
    -- contradiction is for the product owner, not for this migration. Seeding it as DATA means
    -- changing the answer is an UPDATE rather than a release.
    add_access_role('ALL', 'ADMIN',                 'Y', 'Y');
    add_access_role('ALL', 'RBIO_ADMIN',            'Y', 'Y');
    add_access_role('ALL', 'RBIO_OMBUDSMAN',        'Y', 'Y');
    add_access_role('ALL', 'RBIO_DEPUTY_OMBUDSMAN', 'Y', 'Y');
    add_access_role('ALL', 'RBIO_SECRETARY',        'Y', 'Y');
    add_access_role('ALL', 'AA_SECRETARIAT',        'Y', 'Y');
    add_access_role('ALL', 'CEPD_ADMIN',            'Y', 'N');
    add_access_role('ALL', 'AA_ADMIN',              'Y', 'N');

    -- ─────────────────────────────────────────────────────────
    -- 2. REPORT_COLUMN_REGISTRY
    -- ─────────────────────────────────────────────────────────
    add_table('REPORT_COLUMN_REGISTRY', '
        CREATE TABLE REPORT_COLUMN_REGISTRY (
            ID            NUMBER GENERATED BY DEFAULT AS IDENTITY,
            COLUMN_KEY    VARCHAR2(80)  NOT NULL,
            FIELD_NAME    VARCHAR2(120) NOT NULL,
            JPA_PATH      VARCHAR2(120) NOT NULL,
            VALUE_TYPE    VARCHAR2(20)  DEFAULT ''STRING'' NOT NULL,
            DISPLAY_ORDER NUMBER        DEFAULT 999 NOT NULL,
            IS_DEFAULT    CHAR(1)       DEFAULT ''Y'' NOT NULL,
            IS_ACTIVE     CHAR(1)       DEFAULT ''Y'' NOT NULL,
            CONSTRAINT PK_REPORT_COLUMN_REGISTRY PRIMARY KEY (ID),
            CONSTRAINT UK_REPORT_COLUMN_KEY UNIQUE (COLUMN_KEY)
        )');

    add_index('IDX_REPORT_COLUMN_ORDER',
        'CREATE INDEX IDX_REPORT_COLUMN_ORDER ON REPORT_COLUMN_REGISTRY (DISPLAY_ORDER)');

    -- A faithful transcription of the ten columns QueryCompiler.executeList emits today, in its
    -- existing LinkedHashMap insertion order (which IS the UI column order, since the frontend
    -- derives headers from Object.keys of the first row). Transcribing rather than redesigning is
    -- what makes the switch to registry-driven projection verifiable: output must not change.
    --
    -- FIELD_NAME values are provisional labels, NOT BRD Field Names — the BRD sheet is absent.
    add_column_def('complaintNumber', 'Complaint Number',      'complaintNumber', 'STRING',    10);
    add_column_def('subject',         'Subject',               'subject',         'STRING',    20);
    add_column_def('status',          'Status',                'status',          'STRING',    30);
    add_column_def('priority',        'Priority',              'priority',        'STRING',    40);
    add_column_def('department',      'Department',            'department',      'STRING',    50);
    add_column_def('entityCode',      'Regulated Entity Code', 'entityCode',      'STRING',    60);
    add_column_def('createdAt',       'Created On',            'createdAt',       'DATETIME',  70);
    add_column_def('filedAt',         'Filed On',              'filedAt',         'DATETIME',  80);
    add_column_def('resolvedAt',      'Resolved On',           'resolvedAt',      'DATETIME',  90);
    -- closedAt was filterable (closedDate -> closedAt in QueryCompiler.FIELD_MAPPING) but never
    -- projected, so a user could filter on a closure date they could not then see. UST672 requires
    -- the Complaint-Closed-On filter to work, and a column the report cannot display makes that
    -- unverifiable by inspection.
    add_column_def('closedAt',        'Complaint Closed On',   'closedAt',        'DATETIME',  95);
    add_column_def('triageSignal',    'Triage Signal',         'triageSignal',    'STRING',   100);
END;
/
