-- ============================================================
-- V97 — Staff draft ownership, the autosave interval, and edit presence
-- Session S7 (UST673, UST674, UST675)
-- Oracle counterpart of MySQL V99. The two directories' V-numbers are NOT in sync.
--
-- Full rationale is in the MySQL counterpart (database/V99). The three decisions worth restating:
--
--   1. STAFF_DRAFT is a NEW table, not a reuse of EMAIL_DRAFTS. EMAIL_DRAFTS is an email-intake
--      record with ~60 intake-specific columns, keyed to an inbound message. Three of the five
--      UST674 milestones (Conciliation, Forward, Final Decision) have no inbound email and so have
--      no row to update. Separately, the Register milestone's existing "save draft" does not save a
--      draft at all: WorkflowController.java:338 overrides the client's status:'DRAFT' to "assigned",
--      applies an SLA clock and writes a CREATED timeline row.
--
--   2. OWNER_USER_ID is written from the resolved JWT identity, NEVER from a request field. The
--      existing draft listing takes its owner as a client-supplied query parameter and returns
--      EVERY draft in the system when that parameter is omitted
--      (EmailSyndicationApiController.java:451). "Visible only to the user who saved it" cannot be
--      built on a filter the caller chooses.
--
--   3. There is deliberately NO lock table. COMPLAINT_EDIT_PRESENCE is ADVISORY: it powers the
--      UST675 warning so a second user learns on OPEN rather than after typing, and it never blocks
--      a save. Enforcement is the @Version optimistic check that Wave 0 already merged
--      (Complaint.java:135-138 record_version) surfaced as 409 by GlobalExceptionHandler:225-237.
--      A lease would be a SECOND answer to "may I save", and it would need an expiry — an expiry
--      short enough to be safe is short enough to fire mid-edit, turning a concurrency problem into
--      silent data loss. Because presence is advisory, a stale row is harmless.
--
-- Guarded on USER_TABLES / USER_INDEXES / SYSTEM_CONFIG so a re-run is safe.
-- ============================================================

DECLARE
    PROCEDURE add_table(p_table VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = p_table;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_index(p_index VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = p_index;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;

    PROCEDURE add_config(p_key VARCHAR2, p_value VARCHAR2, p_description VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM SYSTEM_CONFIG WHERE CONFIG_KEY = p_key;
        IF v_count = 0 THEN
            INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_BY, UPDATED_AT)
            VALUES (p_key, p_value, p_description, 'V97_MIGRATION', SYSTIMESTAMP);
        END IF;
    END;
BEGIN
    -- ─────────────────────────────────────────────────────────
    -- 1. STAFF_DRAFT
    -- ─────────────────────────────────────────────────────────
    -- COMPLAINT_NUMBER is nullable because the REGISTER milestone has no complaint yet. Oracle, like
    -- MySQL, treats NULLs as distinct in a UNIQUE constraint, so REGISTER drafts are not constrained
    -- by UK_STAFF_DRAFT_OWNER_MILESTONE; that path is keyed by owner alone in application code.
    add_table('STAFF_DRAFT', '
        CREATE TABLE STAFF_DRAFT (
            ID               NUMBER GENERATED BY DEFAULT AS IDENTITY,
            MILESTONE        VARCHAR2(30)  NOT NULL,
            OWNER_USER_ID    VARCHAR2(200) NOT NULL,
            COMPLAINT_NUMBER VARCHAR2(50),
            FORM_DATA_JSON   CLOB          NOT NULL,
            DRAFT_STATUS     VARCHAR2(20)  DEFAULT ''DRAFT''  NOT NULL,
            SAVE_SOURCE      VARCHAR2(20)  DEFAULT ''MANUAL'' NOT NULL,
            CREATED_AT       TIMESTAMP,
            UPDATED_AT       TIMESTAMP,
            CONSTRAINT PK_STAFF_DRAFT PRIMARY KEY (ID),
            CONSTRAINT UK_STAFF_DRAFT_OWNER_MS UNIQUE (MILESTONE, OWNER_USER_ID, COMPLAINT_NUMBER)
        )');

    add_index('IDX_STAFF_DRAFT_OWNER',
        'CREATE INDEX IDX_STAFF_DRAFT_OWNER ON STAFF_DRAFT (OWNER_USER_ID)');
    add_index('IDX_STAFF_DRAFT_COMPLAINT',
        'CREATE INDEX IDX_STAFF_DRAFT_COMPLAINT ON STAFF_DRAFT (COMPLAINT_NUMBER)');

    -- ─────────────────────────────────────────────────────────
    -- 2. COMPLAINT_EDIT_PRESENCE — advisory only, never blocks a save
    -- ─────────────────────────────────────────────────────────
    add_table('COMPLAINT_EDIT_PRESENCE', '
        CREATE TABLE COMPLAINT_EDIT_PRESENCE (
            ID               NUMBER GENERATED BY DEFAULT AS IDENTITY,
            COMPLAINT_NUMBER VARCHAR2(50)  NOT NULL,
            USER_ID          VARCHAR2(200) NOT NULL,
            DISPLAY_NAME     VARCHAR2(250),
            HEARTBEAT_AT     TIMESTAMP     NOT NULL,
            CONSTRAINT PK_COMPLAINT_EDIT_PRESENCE PRIMARY KEY (ID),
            CONSTRAINT UK_EDIT_PRESENCE UNIQUE (COMPLAINT_NUMBER, USER_ID)
        )');

    add_index('IDX_EDIT_PRESENCE_HEARTBEAT',
        'CREATE INDEX IDX_EDIT_PRESENCE_HEARTBEAT ON COMPLAINT_EDIT_PRESENCE (HEARTBEAT_AT)');

    -- ─────────────────────────────────────────────────────────
    -- 3. SYSTEM_CONFIG rows
    -- ─────────────────────────────────────────────────────────
    -- Read through SystemConfigService.getInt — typed, 30s TTL local cache, logged fallback.
    -- Deliberately NOT TimelineConfigService, which rejects keys not prefixed "timeline.", is
    -- uncached, returns String, and whose default map yields "30" for ANY unknown key. A
    -- wrong-but-plausible interval is the worst failure mode for a timer.
    add_config('cms.draft.autosave_interval_seconds', '120',
        'Staff form auto-save interval in seconds (UST673). 0 disables auto-save entirely.');
    add_config('cms.draft.edit_presence_stale_seconds', '90',
        'Seconds after which an edit-presence heartbeat is treated as stale and no longer warned about (UST675).');
    add_config('cms.reports.max_date_range_days', '365',
        'Maximum report date-range span in days; a longer range is auto-capped from the From Date (UST617/671).');
    add_config('cms.reports.min_date_range_days', '1',
        'Minimum report date-range span in days; a shorter range is rejected (UST617/671).');
    add_config('cms.reports.max_in_values', '100',
        'Maximum comma-separated values accepted for the IN operator (UST618).');
END;
/
