-- V9: ELIGIBILITY_QUESTION_MASTER (UST-public / D14)
-- Oracle version
--
-- Context: the citizen filing wizard's maintainability questions, their block rules and their
-- Scheme clause references were hardcoded in the Angular component
-- (file-complaint.component.ts eligibilityQuestions[]). A Scheme amendment therefore needed a
-- frontend release, and the hardcoded text had already drifted — it cited
-- "Integrated Ombudsman Scheme, 2026" for clauses that belong to the 2021 Scheme.
--
-- Rows are seeded by EligibilityQuestionMasterSeeder (insert-if-absent on
-- scheme_version + question_key) so operator edits made through the master survive a restart.
-- Served to the portal by GET /api/v1/eligibility/questions.
--
-- Mirrors the AUTO_CLOSURE_QUESTIONS shape (see V5__complete_ddl_dml.sql).

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES
     WHERE TABLE_NAME = 'ELIGIBILITY_QUESTION_MASTER';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE ELIGIBILITY_QUESTION_MASTER (
                ID                      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                SCHEME_VERSION          VARCHAR2(20) NOT NULL,
                APPLICABLE_ENTITY_TYPE  VARCHAR2(20) NOT NULL,
                QUESTION_NUMBER         NUMBER(10) NOT NULL,
                QUESTION_KEY            VARCHAR2(60) NOT NULL,
                QUESTION_TYPE           VARCHAR2(20) NOT NULL,
                QUESTION_TEXT           CLOB NOT NULL,
                TRANSLATION_KEY         VARCHAR2(120),
                BLOCK_ON                VARCHAR2(20),
                BLOCK_MESSAGE           CLOB,
                BLOCK_MESSAGE_KEY       VARCHAR2(120),
                CLAUSE_REFERENCE        VARCHAR2(100),
                NON_MAINTAINABLE        NUMBER(1) DEFAULT 0,
                SIMPLIFIED_TEXT         CLOB,
                SIMPLIFIED_TEXT_KEY     VARCHAR2(120),
                INLINE_SUB_QUESTION     NUMBER(1) DEFAULT 0,
                ACTIVE                  NUMBER(1) DEFAULT 1,
                CREATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
                UPDATED_AT              TIMESTAMP(6) DEFAULT SYSTIMESTAMP
            )';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_EQM_SCHEME';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_EQM_SCHEME ON ELIGIBILITY_QUESTION_MASTER(SCHEME_VERSION)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_EQM_ENTITY_TYPE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_EQM_ENTITY_TYPE ON ELIGIBILITY_QUESTION_MASTER(APPLICABLE_ENTITY_TYPE)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_EQM_KEY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_EQM_KEY ON ELIGIBILITY_QUESTION_MASTER(QUESTION_KEY)';
    END IF;
END;
/

-- ═══ Correct the Scheme year in already-seeded translations ═══
-- The seeders are insert-if-absent, so environments seeded before this migration still hold
-- "Integrated Ombudsman Scheme, 2026" for clauses that belong to the 2021 Scheme. Citizens are
-- shown this text verbatim when a complaint is closed as non-maintainable, so it must be corrected
-- in place rather than only in the seeder defaults.
--
-- Scoped by key code, not by the English phrase: the localized rows are in native scripts, so no
-- English substring matches them. Bengali also stores the year in Bengali numerals, which an ASCII
-- '2026' replacement would silently skip -- UNISTR is used so the literal survives any client charset.
-- VALUE / DEFAULT_VALUE are CLOB, so DBMS_LOB.SUBSTR is used to hand a VARCHAR2 to REPLACE.
UPDATE TRANSLATIONS t
   SET t.VALUE = TO_CLOB(REPLACE(REPLACE(DBMS_LOB.SUBSTR(t.VALUE, 32767, 1),
                                         '2026', '2021'),
                                 UNISTR('\09E8\09E6\09E8\09EC'), UNISTR('\09E8\09E6\09E8\09E7')))
 WHERE t.VALUE IS NOT NULL
   AND EXISTS (SELECT 1 FROM TRANSLATION_KEYS k
                WHERE k.ID = t.TRANSLATION_KEY_ID
                  AND k.CODE IN ('eligibility.block_not_filed', 'eligibility.passed_message',
                                 'home.ct_regulated'));

UPDATE TRANSLATION_KEYS k
   SET k.DEFAULT_VALUE = TO_CLOB(REPLACE(REPLACE(DBMS_LOB.SUBSTR(k.DEFAULT_VALUE, 32767, 1),
                                                 '2026', '2021'),
                                         UNISTR('\09E8\09E6\09E8\09EC'), UNISTR('\09E8\09E6\09E8\09E7')))
 WHERE k.CODE IN ('eligibility.block_not_filed', 'eligibility.passed_message', 'home.ct_regulated')
   AND k.DEFAULT_VALUE IS NOT NULL;

COMMIT;
/
